idris-lang/Idris2

libs/base/System/Directory.idr
support/c/idris_directory.c

I noticed it was missing while I was trying to fix the problem with paths starting with `~`

Add rmDir to System.Directory

---

src/Utils/String.idr

Small REPL test:
Dual of edwinb/Idris2#388

Refactor Utils.String.stripQuotes to avoid double reversion on Strings

---

.gitignore

These files were generated when I ran
make bootstrap SCHEME=chez
make install
make test IDRIS2_BOOT=idris2sh

Ignoring autogenerated bootstrap/test files

---

src/Idris/Package.idr

Silence annoying errors like 'No such file or directory' if there are no files/directoris to delete

Silence 'idris2 --clean idris2.ipkg' errors

---

libs/base/Data/List.idr
libs/contrib/System/Path.idr
libs/contrib/Text/Parser.idr
libs/contrib/contrib.ipkg

Add a cross-platform path helper, which handles different formats depending on the platform. It can also be used to append paths, to update the extension and to extract the parent directory.
Hopefully, it can be used to self-host idris2 and, as a result, improves robustness on different platforms.
Some necessary list functions are added all together.

Add System.Path

---

libs/network/Network/FFI.idr
libs/network/Network/Socket.idr
libs/network/Network/Socket/Data.idr
libs/network/Network/Socket/Raw.idr
libs/network/network.ipkg

Mostly tedious rebinding.
There's a slight wiggle in `Network.Socket.Data`, where this module also calls (at one point sneakily) foreign functions. I repeated the binding of the three functions it calls locally (without exporting them).

libs/network: Port FFI calls from deprecated interface to `%foreign` pragma

---

libs/contrib/System/Path.idr

> Separate is often misspelled as seperate, a word that has no meaning and is simply a misspelling:
https://www.grammarly.com/blog/separate-seperate/
Noticed when looking at latest merges. Thank you!

Fix typo seperate -> separate in System/Path.idr

---

src/Core/Hash.idr

File locations end up in module interface hashes, triggering unnecessary rebuilds. This patch ignores `DN` layers in hashes to prevent this behaviour.
Everything else, such as the `Show` instance for names, should be unaffected.
Fixes #95.

Exclude `DN` from `Hashable Name`

---

support/gambit/support.scm

I have noticed this function being defined in Chez [support.ss](https://github.com/idris-lang/Idris2/blob/master/support/chez/support.ss) and Racket [support.rkt](https://github.com/idris-lang/Idris2/blob/master/support/racket/support.rkt#L1) support files but not in Gambit.
Also as it is called in
```
File: src/Compiler/Scheme/Common.idr
405:18:      = pure $ "(blodwen-os)"
```
Thought it may be useful to add it.
on OSX, Windows (mingw32) and Ubuntu (WSL)
I have also created this spreadsheet to see difference between different scheme files
https://docs.google.com/spreadsheets/d/1lLd-6OuOLVntq7AR6Ecr0CXDUBzFQj3iZxjlYw3Up4k/edit#gid=0
and may try to fill some gaps as exercise :)
Thank you!

Define blodwen-os in Gambit support.scm

---

CHANGELOG.md
docs/source/tutorial/modules.rst
src/Core/Binary.idr
src/Idris/Desugar.idr
src/Idris/Parser.idr
src/Idris/Resugar.idr
src/Idris/Syntax.idr
src/TTImp/Elab/Ambiguity.idr
src/TTImp/Elab/Check.idr
src/TTImp/Elab/Term.idr
src/TTImp/TTImp.idr
tests/Main.idr
tests/idris2/with003/Main.idr
tests/idris2/with003/expected
tests/idris2/with003/input
tests/idris2/with003/run

In https://github.com/edwinb/Idris2-boot/pull/308, we talked about restricting disambiguation for better error messages. (See that pull request for a motivating example.)
While some aspects of the original proposal were controversial, it seems that most people were okay with notation like `with Prelude.(>>=) do ...`. This pull request is a port of the [original implementation](https://github.com/edwinb/Idris2-boot/pull/359).
This patch adds new syntax `with NS.name <term>` and `with [NS.name1, NS.name2, ...] <term>` to determine disambiguation for the specified names in `<term>` without search.
The names given need not be _fully_ qualified, so `with Vect.Nil` will work for `Data.Vect.Nil`, as long as that's the only possible disambiguation, and you can even say `with Nil []` if there's …

`with` expressions for name disambiguation

---

.github/workflows/ci-ubuntu.yml
README.md

The latest commits broke bootstrapping on Linux, even though we have CI using Travis already that should detect this problem.
This CR adds a bootstrap build for Ubuntu using GitHub actions, similarly to the ones we have for windows. This hopes to achieve more stable and faster feedback on builds and their problems.
The proposed action shows the current build failure, as shown here: https://github.com/wchresta/Idris2/runs/702631251
The current Travis build for the same commit is currently stuck: https://travis-ci.org/github/idris-lang/Idris2/builds/690433878
This will not fix the build failure for Linux but rather make the failure obvious through (hopefully) better CI. We can leave both builds in, Travis and GitHub, and observe which works better for us. Eventually, we'll want to get rid …

Add GitHub CI action that bootstraps on Ubuntu

---

.github/workflows/ci-ubuntu-bootstrap-racket.yml
.github/workflows/ci-ubuntu-bootstrap-scheme.yml
.travis.yml
README.md

* Remove Travis as described in #127
This adds a CI build for bootstrapping `racket` on Ubuntu and drops builds for Travis.

Add CI for bootstrapping via racket

---

.github/workflows/ci-ubuntu-racket.yml
.github/workflows/ci-ubuntu.yml
.github/workflows/ci-windows.yml
README.md

Link them to the respective workflow page.
Rename to be more consistent.
Turns out that the name in the link on the README doesn't matter, so leave it blank.

Shorten names on CI icons

---

libs/prelude/Prelude.idr

This allows proofs to use erased arguments: 
```
data Split : List a -> List a -> List a -> Type where
Nil   : Split [] [] []
ConsR : Split xs ls rs -> Split (x::xs)     ls (x::rs)
ConsL : Split xs ls rs -> Split (x::xs) (x::ls)    rs
splitRInv : Split xs [] rs -> xs = rs
splitRInv  Nil          = Refl
splitRInv (ConsR {x} s) = cong (Prelude.(::) x) $ splitRInv s
```
Without `0` on `f` this produces `x is not accessible in this context` on the last line.

Erase function argument of cong

---

support/c/idris_support.c
support/c/windows/win_utils.c
support/c/windows/win_utils.h

This eliminates a dependency on libwinpthread-l that has been documented to cause confusion when it's absent. An alternative would be to always copy it around when we build. But as we only use nanosleep from there it is much better to eliminate that function on windows.
It's possible to do a bit better with a lot more work, but people will just have to make do with millisecond resolution.

Remove dependency on pthreads on Windows

---

docs/source/reference/records.rst
idris2.ipkg
idris2api.ipkg
src/Core/Core.idr
src/Idris/IDEMode/Parser.idr
src/Idris/Package.idr
src/Idris/Parser.idr
src/Idris/ProcessIdr.idr
src/Idris/REPL.idr
src/Parser/Lexer/Common.idr
src/Parser/Lexer/Package.idr
src/Parser/Lexer/Source.idr
src/Parser/Package.idr
src/Parser/Rule/Package.idr
src/Parser/Rule/Source.idr
src/Parser/Source.idr
src/Parser/Support.idr
src/TTImp/Parser.idr
src/Text/Parser/Core.idr
src/Utils/String.idr

This has two commits, the first one refactors SourceToken a bit and the second one implements an (unpolished) Package Lexer/Parser and refactors Idris/Package.idr to use this new Lexer/Parser.
Feedback is appreciated. First part is #89.
One pro is that package names can now have dashes in their name UwU
There are many organizational and consistency changes, one of the more important ones being `Literal` being rename `StringLit` to correspond with `CharLit`, `IntegerLit`, `DoubleLit` and extracting more common code to Parser/Lexer/Common.
`ParseError tok` was renamed `ParsingError tok` and `ParseError` was refactored to `ParseError tok` to accept a token type.

Split Source and Package Parser (Part 2)

---

Makefile
bootstrap-rkt.sh
bootstrap.sh

* Refactor bootstrap and bootstrap-rkt scripts
* Move the execution of the test phase after bootstrapping from bootstrap
scripts into the Makefile. This allows separate execution of build
and test seperately.
* Fixes #125

Split bootstrap into separate build and test stage

---

.github/workflows/ci-macos.yml
.github/workflows/ci-ubuntu.yml
.github/workflows/ci-windows.yml
config.mk

The github actions latest windows image contains msys2 so use that.
Also use gcc that comes with thatm to save downloading clang.
Skip Racket as it's slow enough already.

Run the self-hosting step in CI

---

docs/source/tutorial/typesfuns.rst

In the intial code listing we currently have "x = 42" but in following listings "x == 9 * 9 + 13" and "x == 8 * 8 + 30" return true.

Possible copy-paste mistake in typesfuns.rst

---

src/Idris/CommandLine.idr
src/Idris/Package.idr
tests/Main.idr
tests/idris2/pkg003/Main.idr
tests/idris2/pkg003/expected
tests/idris2/pkg003/run
tests/idris2/pkg003/testpkg.ipkg

As it was in Idris1 being able to override *some*, or introduce new, options to an Idris IPKG is beneficial. For example, generate code for multiple codegens from a single source.
This PR is the beginning of adding this ability to Idris2. I have fixed some other minor issues with how Idris handle's IPKG files as well.
I will get round to this as and when I can. This PR is there to let people know something is being done.

Allow cli given option overriding for ipkg cmds

---

libs/base/Data/Fin.idr
libs/base/Data/List/Views.idr
libs/base/Data/Nat/Views.idr
libs/base/System.idr
libs/contrib/Data/String/Extra.idr
libs/contrib/Language/JSON/String/Lexer.idr
libs/contrib/System/Path.idr
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Gambit.idr
src/Compiler/Scheme/Racket.idr
src/Core/Binary.idr
src/Core/Core.idr
src/Core/LinearCheck.idr
src/Core/Metadata.idr
src/Core/TTC.idr
src/Core/Unify.idr
src/Data/ANameMap.idr
src/Idris/Error.idr
src/Idris/IDEMode/REPL.idr
src/Idris/Main.idr
src/Idris/Package.idr
src/Idris/ProcessIdr.idr
src/Idris/REPL.idr
src/Idris/SetOptions.idr
src/TTImp/ProcessType.idr
src/Yaffle/Main.idr
tests/idris2/coverage005/Cover.idr
tests/idris2/import002/expected
tests/idris2/reg003/expected
tests/typedd-book/chapter14/Hangman.idr

This was taking too long, and adding too many things, because it was
going too deep in the name of having everything accessible at the REPL
and for the compiler. So, it's done a bit differently now, only chasing
everything on a "full" load (i.e., final load at the REPL)
This has some effects:
+ As systems get bigger, load time gets better (on my machine, checking
Idris.Main now takes 52s from scratch, down from 76s)
+ You might find import errors that you didn't previously get, because
things were being imported that shouldn't have been. The new way is
correct!
An unfortunate effect is that sometimes you end up getting "undefined
name" errors even if you didn't explicitly use the name, because
sometimes a module uses a name from another module in a type, which then
gets exported, and …

Fix import loading

---

src/Utils/Path.idr

This wouldn't have got caught since the merge that caused the problem
was checked before I pushed the patch that made import work right! So
hopefully this'll sort it.

Add missing import

---

src/Core/Core.idr
src/Idris/Error.idr
src/Idris/Main.idr
src/Idris/Package.idr
src/Idris/REPLOpts.idr

Otherwise they need to be relative to know where the root of the module
tree is, so report an error with absolute paths in other cases.

Allow absolute paths in --find-ipkg

---

libs/contrib/System/Path.idr
src/Core/Core.idr
src/Core/Directory.idr
src/Idris/Error.idr
src/Idris/Main.idr
src/Idris/ModTree.idr
src/Idris/Package.idr
src/Idris/ProcessIdr.idr
src/Idris/REPLOpts.idr
src/Utils/Path.idr
src/Yaffle/Main.idr

Based on https://github.com/idris-lang/Idris2/pull/200
This allows absolute input file in any situation.
And since System.Path is out of sync with Utils.Path, I copied the src/Utils/Path.idr to contrib.

Make pathToNS handle absolute path

---

docs/source/typedd/typedd.rst
libs/base/Control/App.idr
libs/base/Data/IOArray.idr
libs/base/System/Clock.idr
libs/contrib/System/Path.idr
libs/contrib/Text/Lexer/Core.idr
src/Algebra/ZeroOneOmega.idr
src/Idris/Error.idr
src/TTImp/Elab/Case.idr
src/TTImp/ProcessData.idr
src/TTImp/ProcessRecord.idr
src/TTImp/ProcessType.idr
src/TTImp/Utils.idr
src/Utils/Path.idr
tests/idris2/basic003/Ambig2.idr
tests/idris2/basic003/expected
tests/idris2/coverage008/expected
tests/idris2/perf004/bigdpair.idr
tests/idris2/real002/Control/App.idr
tests/idris2/reg008/Vending.idr
tests/ttimp/basic005/Ambig.yaff
tests/ttimp/basic006/Ambig.yaff
tests/typedd-book/chapter11/ArithCmdDo.idr
tests/typedd-book/chapter12/ArithState.idr
tests/typedd-book/chapter13/StackIO.idr
tests/typedd-book/chapter13/Vending.idr
tests/typedd-book/chapter14/Hangman.idr

Can't export a type which refers to a private name. This has caught a
couple of visibility errors in the libraries, code and tests, so they've
been updated too.

Add visibility rules on types

---

src/Core/Directory.idr
src/Idris/Package.idr

This makes vim mode work again.
I don't know a good way to test this, since it involves dealing with
absolute paths. If anyone has the bash skills to get this working in a
pkg test, please do...

findIpkg needs to set working directory

---

src/TTImp/ProcessDef.idr
tests/Main.idr
tests/idris2/coverage010/casetot.idr
tests/idris2/coverage010/expected
tests/idris2/coverage010/run

If we don't do this, we don't look inside case blocks to check they
cover, and so we might miss coverage errors in nested case blocks.
Fixes #202

Calculate compile time references even in case

---

idris2.ipkg
libs/base/Language/Reflection.idr
libs/base/Language/Reflection/TT.idr
libs/base/Language/Reflection/TTImp.idr
src/Core/Options.idr
src/Core/Reflect.idr
src/Idris/Parser.idr
src/Parser/Lexer/Source.idr
src/TTImp/Elab/RunElab.idr
src/TTImp/Elab/Term.idr
src/TTImp/Reflect.idr
tests/Main.idr
tests/idris2/reflection002/expected
tests/idris2/reflection002/input
tests/idris2/reflection002/power.idr
tests/idris2/reflection002/run

The entire documentation is in the `Language.Reflection` part of `base`, and tests `idris2/reflection00x`.
So far, you can run elaborator scripts inside term elaboration. The scripts can inspect the goal, construct terms for checking, and do various bits of basic logging according to the overall elaborator log level. Terms can be quoted, and you can unquote terms inside quoted terms.
This already gives you what is essentially "template Idris", and you can probably do some quite interesting proof automation already, with some effort, by inspecting the goal and trying to construct a term accordingly.
One warning though: everything might change! So it's hidden behind an extension flag.

Initial steps to elaborator reflection

---

src/Compiler/Scheme/Gambit.idr
support/c/idris_file.c

I tried to play with Idris on ios and the easiest way for it is Gambit backend and it worked great :)
But I found that Gambit backend didn't support callbacks in ffi so I added it.
Not sure if I should add tests for gambit backend. Locally I tested it on the example from the docs:
```
%foreign (libsmall "applyFn")
prim_applyFn : String -> Int -> (String -> Int -> String) -> PrimIO String
applyFn : String -> Int -> (String -> Int -> String) -> IO String
applyFn c i f = primIO $ prim_applyFn c i f
```
I also added #include <sys/time.h> to satisfy xcode.
It seems relevant to all BSD systems.
In xcode the option -Wno-error-implicit-function-declaration is enabled. So the following error occured:
"Idris2/support/c/idris_file.c:76:13: Missing '#include <sys/time.h>'; declaration of 'select' …

Gambit ffi callbacks

---

INSTALL.md
config.mk
support/c/Makefile
support/c/windows/win_utils.c

`GetSystemTimePreciseAsFileTime ` was introduced in Windows 8. On earlier Windows systems, it might compile (with a newer SDK), but the result dll cannot be loaded. For these systems, use `GetSystemTimeAsFileTime ` instead.

Try to load libidris2_support on older Windows

---

src/Core/Reflect.idr
src/TTImp/Elab/RunElab.idr
tests/idris2/reflection003/expected

PiInfo was reflected wrongly. Also there is a more useful behaviour for genSym - instead of just checking the name doesn't exist globally, use the name supply which unification uses, which will give a completely new name.

Reflection fixes

---

libs/base/Language/Reflection.idr
src/Core/TT.idr
src/TTImp/Elab/RunElab.idr
src/TTImp/Unelab.idr

Get the names of local variables. and add the ability to look up their
types.
When we get a reflected TTImp, either checking the Goal or looking up a
type, it's not impossible that there'll be some repeated binder names,
so also make sure binders are unique relative to the current context.
Ideally we'd also rename things in the environment to guarantee that all
names are unique, but we don't yet.
(This would be much easier if reflected terms were typed such that they
were well scoped, but that would also make reflection harder to use.)

A couple more elab reflection primitives

---

libs/base/Language/Reflection.idr
src/TTImp/Elab/RunElab.idr
tests/Main.idr
tests/idris2/reflection002/expected
tests/idris2/reflection002/input
tests/idris2/reflection002/power.idr
tests/idris2/reflection003/expected
tests/idris2/reflection003/refprims.idr
tests/idris2/reflection004/refdecl.idr
tests/idris2/reflection005/expected
tests/idris2/reflection006/refleq.idr
tests/idris2/reflection007/NatExpr.idr
tests/idris2/reflection007/expected
tests/idris2/reflection007/input
tests/idris2/reflection007/run

So the type of Elab now gives the expected type that's being elaborated
to, meaning that we can run 'check' in the middle of scripts and use the
result.

In reflection, check now takes a concrete type

---

src/Core/CaseBuilder.idr
src/Core/Env.idr
src/Core/Normalise.idr
tests/Main.idr
tests/idris2/reg021/case.idr
tests/idris2/reg021/expected
tests/idris2/reg021/run

This is quite fiddly as it the blocks might be in different contexts so
we need to keep track of which variables correspond in the scrutinees of
the blocks. Once that's done, check the terms at the leaves convert,
then check the corresponding variables convert.
This may not be perfect yet, because we only look at case scrutinees to
find correspondence. It might also be a bit slower than it could be, but
at least these checks are quite rare.
Fixes #208 and maybe some others?

Look inside case blocks in conversion check

---

src/Core/Normalise.idr
tests/Main.idr
tests/idris2/reg023/boom.idr
tests/idris2/reg023/expected
tests/idris2/reg023/run

Another one from the "stop trying to be clever" files :). Instead of a
continuation for fallthrough in the evaluator, be explicit about whether
there's a result, no match, or evaluation is stuck.
Fixes #70

More explicitness in evaluator return type

---

libs/base/Language/Reflection/TT.idr
src/Core/Reflect.idr

These arise in interface declarations (to give a nicer way of displaying
auto generated names) and for record fields.

Reflect 'display names' and record field names

---

src/Core/Directory.idr
src/Core/Termination.idr
src/Idris/Desugar.idr
tests/Main.idr

* Productivity checker wasn't looking under case, now it does
* Free standing case blocks assumed to return (), as in Idris 1

Case block improvements

---

src/Compiler/CompileExpr.idr
src/Core/CaseTree.idr
src/Core/CompileExpr.idr
src/Core/TT.idr

There are three functions; `Core.TT.thin`, `Core.CaseTree.thinTree`, and `Core.CompileExpr.thin`; which duplicate much of the code of `Core.TT.insertNames`, `Core.CaseTree.insertCaseNames`, and `Core.CompileExpr.insertNames`.
This PR removes them, and replaces their (very infrequent) use by equivalent uses of `insertNames`.
I'm not sure how much you try to keep a stable module API, but this would be a breaking change.  If that's something that's important, I can add short wrapper functions in place of the originals:
```idris
%inline
export
thin : {outer, inner : _} ->
(n : Name) -> Term (outer ++ inner) -> Term (outer ++ n :: inner)
thin n t = insertNames [n] t
```

Remove redundant thin functions and replace with insertNames

---

INSTALL.md

and improve formatting in terminal.
Why:
This may help people prevent or resolve following issues
when running `make bootstrap SCHEME=chez`
- missing clang
```
make: clang: Command not found
make[1]: Entering directory 'support/c'
make[1]: clang: Command not found
```
- missing Chez thread support
```
Compiling idris2_app/idris2-boot.ss with output to idris2_app/idris2-boot.so
Exception: attempt to reference unbound identifier
make-thread-parameter at line 171, char 30 of idris2_app/idris2-boot.ss
```
`$ less INSTALL.md` before:
`$ less INSTALL.md` after:

Add additional information on requirements in INSTALL.md

---

tests/idris2/reflection003/expected

Clash in a reflection test due to conflicting merges. I'd like to find a
way to make the internally generated numbers not matter here (and
elsewhere) but I don't see an obvious way.

Update test output

---

src/Core/Context.idr
src/Core/Options.idr
src/Idris/Desugar.idr
src/Idris/Parser.idr
src/Idris/Syntax.idr
src/TTImp/Elab/App.idr

By default, the search depth for auto implicit arguments is limited to 50. In some cases, it may be reasonable to manually extend this limit for a specific file or portion of a file.
This patch adds a `%auto_implicit_depth n` pragma that overrides the default limit.
For example, this trivial code fails, because the autosearch cannot construct a LTE value deeper than 50:
```
consumeBoundedNat : (x : Nat) -> LTE x 255 => ()
consumeBoundedNat x = ()
testSearch : ()
testSearch = consumeBoundedNat 100
-- Fails with:
-- Can't find an implementation for LTE 100 255
```
Adding `%auto_implicit_depth 256` on top of testSearch declaration leads to a correct typecheck with reasonable compile times, in this particular case. To revert to the default depth it suffices to write `%auto_implicit_depth 50`. …

Added auto_implicit_depth pragma

---

docs/source/ffi/ffi.rst
libs/prelude/PrimIO.idr
src/Compiler/CompileExpr.idr
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Common.idr
src/Compiler/Scheme/Racket.idr
src/Core/CompileExpr.idr
src/Core/TTC.idr
support/chez/support.ss
support/racket/support.rkt
tests/Main.idr
tests/chez/chez022/Makefile
tests/chez/chez022/expected
tests/chez/chez022/input
tests/chez/chez022/mkalloc.c
tests/chez/chez022/run
tests/chez/chez022/usealloc.idr
tests/idris2/coverage008/expected
tests/idris2/coverage010/expected

This involves new primitives GCPtr and GCAnyPtr which are pointer types that have finalisers attached. The finalisers are run when the associated pointer goes out of scope, or at the end (so there's now an explicit call to the GC at the end).
In the test, I am assuming that the GC will only be called once, right at the end. Otherwise, the output isn't guaranteed to be deterministic! Let's see how this assumption holds...
I expect it'll be easy enough to add to the Gambit back end, but I'll wait for a patch for that.

Add finalisers to Chez and Racket back ends

---

tests/Main.idr

The current approach has the wrong boolean test.
When the command executed cleanly it will return 0.
A non-zero answer implies that `git diff` errored.

Fix test reporting when in interactive mode.

---

src/Idris/IDEMode/REPL.idr
tests/ideMode/ideMode001/dummy.ipkg
tests/ideMode/ideMode003/dummy.ipkg

This takes the responsibility of finding the ipkg away from IDE mode, which seems sensible given that we can do it ourselves. If there isn't one, it'll load from the local directory as always.
(I won't merge this immediately - please shout if it's likely to break anything. I think it's a better way to go, though, in the end.)

In IDE mode, look for a ipkg file before loading

---

src/Text/Literate.idr
tests/Main.idr
tests/idris2/literate013/Lit.lidr
tests/idris2/literate013/expected
tests/idris2/literate013/run

The tokenizer for literate modes was incorrectly detecting code lines within the text. 
Code line deliminators should only be at the start of a line.
This PR fixes that by ensuring tokenizers consume whole lines at a time. We also allow for empty code lines..
This commit partially addresses  #211.
No performance improvements are made, and the hidden bird style remains.

Improved parsing for literate modes.

---

docs/source/typedd/typedd.rst

The `rest` argument must be made explicit. Related to
https://github.com/idris-lang/Idris2/issues/253.

Add some comments about `TakeN` in chapter 10.

---

support/c/idris_buffer.c
support/c/idris_buffer.h

I saw that they were missing binary mode, but they aren't used anyway, so remove them rather than fix.

Remove unused functions from idris_buffer.c

---

libs/base/Data/Nat.idr

Having unsolved holes in a 'core' library unneccessarily pollutes the list of holes shown to the user.
Thus, having unfilled holes in a 'core' library is not right.
These constructs can be re-added once the holes have been filled in.

Remove unsolved holes from `base`.

---

libs/network/Network/Socket.idr

We have tried to use the recvAll functionality in the Network.Socket library from the contrib package.
It seems that when it runs recursively into the recv on an empty buffer, it is blocking and not receiving the clean exit (Left 0) signal, thus running infinitely and never returning.
We propose a solution to this issue that instead of waiting for a Left 0 signal, the function runs recursively until then buffer size is smaller than the reading size that it is trying to achieve.

Added fix to recvAll that doesn't use signal (Left 0)

---

libs/base/Control/App/FileIO.idr
support/c/idris_file.c
support/c/idris_file.h
tests/Main.idr
tests/chez/chez023/File.idr
tests/chez/chez023/expected
tests/chez/chez023/input
tests/chez/chez023/run

* Add ` fGetChars`, `fGetChar`, `fPutStrLn` to `FileIO`
* Make `withFile` close the file after performing the operations
* Fix `fGetChars` by renaming `idris_readChars` to `idris2_readChars`
* Add a simple test case for `Control.App.FileIO`
Can we rename `fGetStr` to `fGetLine` for consistency or is there a reason for the different name? Thanks :)

Extend Control.App.FileIO

---

libs/base/System.idr
support/c/idris_support.c
support/c/windows/win_utils.c
support/c/windows/win_utils.h
tests/Main.idr
tests/chez/chez024/Envy.idr
tests/chez/chez024/expected
tests/chez/chez024/input
tests/chez/chez024/run

prim__unsetenv was set to the wrong function and there was no windows implementation. Added a test.
Using setenv is bad practice anyhow, but if we have it it should work.

Fix setenv and unsetenv

---

src/Compiler/Scheme/Racket.idr
src/Idris/IDEMode/Commands.idr
src/Utils/Hex.idr

The motivation for this change is to remove the usage of FFI in the `Idris.IDEMode.Commands.hex` function so that code generators have one less thing to worry about.
This change is covered by the `ideModeNNN` tests.
Notes about the changes in this pull request:
- Changed `Utils.Hex.asHex` to be a total function. Before one could supply a negative integer and it would loop forever. There was also an edge case where calling `asHex 0` would result in an empty string (instead of `"0"`).
- Moved `Compiler.Scheme.Racket.showRacketChar.pad` to `Utils.Hex` because it is used in two places.
- Renamed `sendLine` to `sendStr` because it doesn't send a newline.

Replace FFI implementation of 'hex' function with a plain Idris version

---

Makefile
docs/source/backends/custom.rst

When building from a clean state `src/IdrisPaths.idr` must be generated first
before installing `idris2api.ipkg`.

Fix 'install-api' makefile target

---

docs/source/reference/literate.rst
src/Parser/Unlit.idr

In the CommonMark section of the reference for literate Idris, it says that both `.md` files and `.markdown` files are treated as Org-Mode style literate Idris.  I believe this should say CommonMark style.
When looking at the source to back this up, however, I saw that it only interprets `.md` files as CommonMark-style literate Idris files, and doesn't allow `.markdown` files.
This PR fixes both of these.

Make reference and source agree about literate markdown

---

libs/base/Data/Bool.idr
tests/idris2/coverage010/expected

This function may be useful when using `decEq` for `Bool`s with `with` where previously `with ... proof` was used, e.g.:
```idris
f : X -> Y
f x with (decEq whatever True)
| Yes p = rewrite p in ...
| No n = rewrite notTrueIsFalse n in ...
```
(where previously we were used to write
```idris
f : X -> Y
f x with (whatever) proof p
| True = rewrite p in ...
| False = rewrite p in ...
```
)

Function mapping `Not (x=True)` to `x=False` was added for `Bool`s

---

src/Compiler/VMCode.idr

For constructors which don't have a tag (so case matching needs to be done based on the `Name`), the `Name` information is correctly carried over into the `CASE` instructions (in form of an `Either Int Name`), but is lost when converting the ANF `ACon` to a VMCode `MKCON`.
For reference, the current conversion from ANF to VMCode `CASE` looks like this:
```idris
toVMConAlt (MkAConAlt n (Just tag) args code)
= (Left tag, projectArgs 0 args ++ toVM t res code)
toVMConAlt (MkAConAlt n Nothing args code)
= (Right n, projectArgs 0 args ++ toVM t res code)
```
This commit slightly changes the constructor for the `MKCON` instruction to match the type of the `CASE` alternatives and changes the conversion from ANF to keep the original constructor name. As before, backends still need to do the …

VMCODE: Carry over required type names for named constructors without a tag

---

src/Core/Context.idr
src/TTImp/ProcessData.idr

We do this when elaborating the data type, but not when adding the
individual constructors, so weren't catching the case of repeated
constructors within the same type. Fixes #338

Check consructor names are not defined

---

CHANGELOG.md
src/Idris/Parser.idr
src/Idris/ProcessIdr.idr
src/Idris/REPL.idr
src/Idris/Syntax.idr
src/Parser/Rule/Source.idr
tests/Main.idr
tests/idris2/interpreter003/expected
tests/idris2/interpreter003/input
tests/idris2/interpreter003/run

Implemented a `:module <module>` command to load a module during a REPL session.

Module command to import module in REPL

---

CHANGELOG.md
docs/source/backends/custom.rst
src/Compiler/Common.idr
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Gambit.idr
src/Compiler/Scheme/Racket.idr
src/Core/Context.idr
src/Core/Directory.idr
src/Core/Options.idr
src/Idris/CommandLine.idr
src/Idris/Driver.idr
src/Idris/Main.idr
src/Idris/Package.idr
src/Idris/SetOptions.idr
tests/Main.idr
tests/chez/chez026/Dummy.idr
tests/chez/chez026/dummy.ipkg
tests/chez/chez026/expected
tests/chez/chez026/run
tests/idris2/pkg003/expected

This pull request contains more changes than I originally intended:
1. Adds `--build-dir` and `--output-dir` and corresponding fields in the package description (See more detailed description below)
2. Adds `--source-dir` to match the existing `sourcedir` field in the package description (See overview at the bottom)
3. Renamed `dir_prefix` to `prefix_dir` to match the other names in the record
4. Fixes a bug regarding the `main` field in the package description (Previously it always used `Main` as the namespace)
5. Silences the compilation message when compiling Chez programs: `compiling <path>/print_hello.ss with output to <path>/print_hello.so`
- I should probably emphasize that by silencing this message, there might be cases where you will miss seeing this message, for example when …

Allow overriding build and output directory

---

libs/contrib/Data/List/TailRec.idr
libs/contrib/Syntax/PreorderReasoning.idr

Change the poor-man's preorder reasoning in `contrib` to use slightly faster data structures, following [Agda](https://github.com/agda/agda-stdlib/issues/622).
Since only the `TailRec` ursive version of `Data.List` seems to use these proofs, hopefully it'll be ok to change this now.

Fancy preorder reasoning

---

libs/base/System/File.idr
libs/network/Network/FFI.idr

Minor correctness fixes.
In particular: Importing fgetc and listen indirectly via support seems not to create issues on Linux (5.6.16, Glibc 2.31, x86_64, with Racket 7.4), and presumably other platforms but prevents building on OpenBSD 6.7 (x86_64 with Racket 7.7) due to linkage issues.
I haven't committed updated bootstrap code in case special vetting is required. It seems that the bootstrap is less frequently updated.
Anyone wishing to benefit from this fix before the bootstrap is updated should build with this PR on a working platform (eg. Linux) then copy across the source tree and rebuild. Alternatively (for Racket, say) in bootstrap/idris2_app/idris2.rkt: substitute the lines
(define-libidris2_support fgetc (_fun _pointer -> _int))
with
(define-libc fgetc (_fun _pointer -> _int)) …

Import fgetc and listen from libc rather than support libs

---

src/Idris/Resugar.idr
tests/idris2/with003/expected

This addresses the case where you'd see an error of:
```
Ambiguous elaboration at:
r <- pure []
Possible correct results:
[]
[]
[]
```
By changing it to:
```
Possible correct results:
Main.Nil
PrimIO.Nil
Prelude.Nil
```

reduce sugar in confusing error messages

---

src/Idris/Parser.idr
tests/Main.idr
tests/idris2/namespace001/Dup.idr
tests/idris2/namespace001/Scope.idr
tests/idris2/namespace001/expected
tests/idris2/namespace001/run

The namespace parser was not requiring a minimum indentation and instead
based its indentation on the following line, which meant that a line like:
```
namespace Foo
foodef : Int
```
placed `foodef` into namespace `Foo` instead of the module's top level.
And so made it unclear when a namespace ends.

change namespace parser to have minimum indentation

---

CHANGELOG.md
docs/source/ffi/ffi.rst
docs/source/tutorial/interfaces.rst
libs/base/Control/App.idr
libs/base/Data/IOArray.idr
libs/base/Data/IORef.idr
libs/base/Data/Ref.idr
libs/base/System.idr
libs/base/System/Directory.idr
libs/base/System/File.idr
libs/base/System/REPL.idr
libs/contrib/Debug/Buffer.idr
libs/contrib/System/Random.idr
libs/network/Network/Socket.idr
libs/network/Network/Socket/Data.idr
libs/network/Network/Socket/Raw.idr
libs/prelude/Prelude.idr
libs/prelude/PrimIO.idr
tests/chez/chez010/CB.idr
tests/idris2/coverage008/expected
tests/idris2/coverage010/expected
tests/idris2/real002/Control/App.idr
tests/idris2/with003/Main.idr
tests/idris2/with003/expected
tests/idris2/with003/input

Also updates the Prelude and some base libraries to use HasIO rather than using IO directly. This is a draft, since it hasn't covered all the libraries yet (and some need a bit more thought, especially the concurrency primitives) and the documentation needs updating, especially FFI.
My main motivation is that whenever I experiment with some new abstraction for effects or linearity, I need to lift all the primitive IO operations somehow, and I wouldn't have to if they were in an appropriate interface. `HasIO` is basically like `MonadIO` from Haskell. My hope is that if everything lives in `HasIO` then we'll all get in the habit of adding primitives this way rather than putting them directly in `IO`!
* Is there a better name than `HasIO`? I'm not especially attached to it (but I don't like …

HasIO interface for IO actions

---

libs/base/System/Concurrency/Raw.idr
libs/prelude/PrimIO.idr
support/chez/support.ss
support/racket/support.rkt

Conditional variables with timeout in Chez didn't work, so changed to a
consistent meaning of the timeout (microseconds). Also fix linearity of
unsafePerformIO.

Small concurrency fixes

---

src/TTImp/Unelab.idr
tests/idris2/reflection003/expected

unelabBinder was losing information for the purpose of displaying names nicely. This is typically wanted but when working with elabortation it's useful to have all the information you can get.  
Things like record field names would be lost when querying with GetType but are now retained.

change how unelabBinder shows names

---

src/Core/Binary.idr

Locally all of the tests fail with error like: `Error in TTC file: TTC data is in an older format, file: ["Prelude"], expected version: 34, actual version: 33`.
From this description it's hard to find out what's the actual file path, what should I clean to make Idris rebuild something that is cached.
Now the error is: `Error in TTC file: TTC data is in an older format, file: /Users/nga/.idris2/idris2-0.2.0/prelude/Prelude.ttc, expected version: 34, actual version: 33`.

Better TTC data is in an older format message

---

libs/contrib/Data/String/Interpolation.idr
libs/contrib/contrib.ipkg

Apparently the concrete syntax is controversial ("{apples}"
vs. "$oranges"), so I'm just adding a simple DYI version until we
agree on a concrete syntax
Some people wrote about it at [some lengths](https://en.wikipedia.org/wiki/String_interpolation), and note that you should probably sanitize any user-given string substitute.

Add a simple DYI f-string / string interpolation library

---

libs/base/Data/Vect.idr

Change the `len` to be irrelevant, as it's uniquely determined by
matching on the input vector

Export the `lengthCorrect` proof, as users might want to use it

---

libs/contrib/Control/Monad/Syntax.idr
libs/contrib/contrib.ipkg

Add the kleisli operators to contrib:
```idris
(>=>) : Monad m => (a -> m b) -> (b -> m c) -> (a -> m c)
(<=<) : Monad m => (b -> m c) -> (a -> m b) -> (a -> m c)
(=<<) : Monad m => (a -> m b) -> m a -> m b
```

Add Kleisli arrow operators to contrib

---

src/Core/Binary.idr
src/Idris/Elab/Implementation.idr
src/Idris/Elab/Interface.idr
src/Idris/Syntax.idr
src/TTImp/Utils.idr
tests/Main.idr
tests/idris2/reg026/Meh.idr
tests/idris2/reg026/expected
tests/idris2/reg026/run

We need to make sure they are inferred again when elaborating methods, so substitute in a _ in method types before substituting in the explicit parameters.
In future, it might (probably will) also be useful to allow giving the implicit parameters explicitly when defining implementations.
Fixes #374

Record implicit parameters of interfaces

---

Makefile

I think it make sense to let the install commands in the `Makefile` only perform installation, similar to `install-idris2`.
In the case of `make install-libs` which runs `idris2 --install <ipkg>`, it will rebuild any changed modules anyway. So calling `idris2 --build <ipkg>` first is just duplicate work. On my computer it takes about 5 seconds to run `make install-libs`. When I remove the dependency on `libs`, the command takes about half the time.

Avoid traversing all Idris modules twice when installing

---

src/Core/Unify.idr
tests/Main.idr
tests/idris2/reg028/Test.idr
tests/idris2/reg028/expected
tests/idris2/reg028/run

'convert' doesn't solve holes, so might reject things that are solvable.
This can be an issue when resolving interfaces, because we were using
convert for arguments of the invertible holes that arise when trying to
resolve them. Fixes #66.

Use 'unify' rather than 'convert' if possible

---

CHANGELOG.md
libs/contrib/Control/ANSI.idr
libs/contrib/Control/ANSI/CSI.idr
libs/contrib/Control/ANSI/SGR.idr
libs/contrib/contrib.ipkg

Adds a module for ANSI codes in contrib. The API is a bit barebone, but supports both coloring and cursor/screen control.
This module will be useful when (soon) I will work on syntax highlightning and colorful error messages in the REPL.

Adds ANSI codes support in contrib

---

libs/contrib/Data/List/Equalities.idr
libs/contrib/Data/List/Palindrome.idr

Existing in the `contrib` library `snoc`'s injectivity property was named as a congruence for some reason, this PR fixes it.

List's `snoc` injectivity property was renamed approporiately.

---

libs/base/Data/Vect.idr
tests/idris2/coverage010/expected

This PR changes `Data.Vect.::` to be a linear constructor, like its `List` counterpart.
It further modifies many of the linear functions in `Data.Vect` to be annotated as such.
However, it falls short of making *everthing* that could be linear linear: higher-order functions remain nonlinear, to retain their use with nonlinear arguments.
I believe that although it adds some complexity, this change makes it overall conceptually simpler and much less surprising: one would expect that a function `{0 a : Type} -> (1 xs : Vect 4 a) -> Vect 3 a` would be impossible to write, but without this change, it's as easy as `tail`.  The goal of this change is to make `Vect` behave more "normally" wrt linearity.

Make Data.Vect linear

---

libs/base/Data/List.idr

I have managed to track down the reason why not enough computation was
happening on the idris2 branch of tparsec to get the STLC example running.
We use these two functions at the type level but they are not publically exported.
It turns out that by simply asking for the type of `test` in the repl, I would
not get the top-level type I had declared but rather the one Idris inferred: a 
big expression clearly stuck on `mapMaybe`, and then on `head'`.
Having to make some functions `public` in the main repo on a per-project
basis does not seem like a tractable solution.

[ fix ] make some exports public

---

src/Idris/CommandLine.idr
src/Idris/SetOptions.idr

The flag takes a natural number as argument
It would be ideal to generalise the argument parser to be able
to parse any argument of any type, but right now we only add
`RequiredNat` as a new flag option.

Add support for --log flag

---

CHANGELOG.md
docs/source/tutorial/interfaces.rst
docs/source/tutorial/modules.rst
libs/prelude/Prelude.idr
src/Core/Binary.idr
src/Core/Context.idr
src/Core/Name.idr
src/Data/ANameMap.idr
src/Idris/Desugar.idr
src/Idris/Elab/Implementation.idr
src/Idris/Elab/Interface.idr
src/Idris/Parser.idr
src/Idris/ProcessIdr.idr
src/Idris/REPL.idr
src/Idris/Syntax.idr
src/TTImp/ProcessData.idr
src/TTImp/ProcessType.idr
src/TTImp/Unelab.idr
src/TTImp/Utils.idr
tests/Main.idr
tests/idris2/basic041/QDo.idr
tests/idris2/basic041/expected
tests/idris2/basic041/run
tests/idris2/import005/As.idr
tests/idris2/import005/Test.idr
tests/idris2/import005/expected
tests/idris2/import005/input
tests/idris2/import005/run

All somehow related, so coming in one PR:
* `import X as Y` now works, aliasing the names exported by X to the namespace Y (including dealing with nested namespaces properly)
* The `Prelude` is now all available via the namespace `Prelude` even though it's split into multiple modules (so now we can go further with separating it more, as it probably should be)
* Removed the restriction that exported names can't refer to private names, because it doesn't seem to achieve anything useful. It was there in an effort to speed up importing, but that's no longer necessary (and it never worked in Idris 1 anyway)
* Added qualified do, where `Namespace.do` introduces a `do` block desugared via `Namespace.(>>=)`, inspired by a similar feature in Purescript

A variety of namespace and import goodies

---

libs/contrib/Control/Algebra.idr
libs/contrib/Control/Algebra/Laws.idr
libs/contrib/contrib.ipkg

This PR ports over some Algebra stuff from Idris 1. It is mostly similar: the interfaces are split into syntactic versions and verified versions. The latter are named like `VMonoid` etc. That can be changed, but I think it's the most ergonomic name.
Many of the theorems are stated but not proved. They can all be proved in Idris 1 [1], but the proofs don't work here. I would expect them all to work. There seem to be a few different bugs involved, but I don't understand the details.
[1] See https://github.com/idris-lang/Idris-dev/blob/master/libs/contrib/Control/Algebra/Laws.idr and https://github.com/idris-lang/Idris-dev/pull/4848

Add Algebra interfaces and laws

---

libs/base/Language/Reflection/TTImp.idr
tests/idris2/reflection004/refdecl.idr

I'm probably doing something wrong in the test (I must admit I don't have much experience and it's been a long time since I've played with Idris), feel free to request changes (if I define `axes` as a subroutine of `mkPoint` by using `where`, the totality checker will complain but maybe it's unrelated?).
If I `declare [ mkPoint 4 ]`, I'll get `Main.(.z) is already defined` which seems about right but I couldn't figure out if there is a way to properly namespace fields (adding `NS [type, "Main"]` doesn't help, any idea?).

Fix MkRecord signature

---

src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Gambit.idr
src/Compiler/Scheme/Racket.idr

* `@generated` is a marked used by Phabricator to mark generated files,
any other marker would do
* it's easier to explore source tree when it's clear which files are sources
and which are generated

Insert @generated marker into generated Scheme files

---

libs/prelude/Prelude.idr

Being tail-recursive doesn't matter that much for Chez Scheme with its (seemingly?) unbounded call stack. But when targeting a runtime with a smaller stack / bounded call stack size, it's one less thing to worry about.

Make Prelude.unpack tail-recursive

---

src/Compiler/Scheme/Common.idr
src/Core/Binary.idr
src/Core/Context.idr
src/Core/Name.idr
src/Core/UnifyState.idr
src/TTImp/Elab/Case.idr
src/TTImp/ProcessDef.idr
tests/idris2/coverage008/expected
tests/idris2/coverage010/expected

The Int represented the resolved name, but this isn't guaranteed to be
up to date after reloading and, worse, it doesn't display helpfully. I'm
bored of updating the tests which fail as a result!
This also fixes #407, which is about displaying the wrong name after
reloading the ttc.

Use a String, not an Int, for case/with names

---

docs/source/tutorial/modules.rst

It seems that `public` is forgotten between `import` and `as` ;-) I checked!

Tiny doc fix about combination of `import public` and `import .. as`

---

support/c/idris_directory.h

More of a hotfix. this was clearly not used anywhere before, so one'd either have to think about tests to make sure this kind of thing doesn't happen again, or if it's not needed remove it.

Fix forward declaration of idris_closeDir

---

src/Idris/Error.idr

In using local builds of idris2 I often forget that there's a build dir containing TTC files and lose time to thinking something other than "you last compiled this with a previous version of idris2" is wrong.  This just adds to the error message.

Add comment about TTC files in TTC error

---

libs/base/System/File.idr

This didn't cause a problem before as it was likely just ignored by the C
function. According to Edwin the extra argument is a leftover from when this
was a pure scheme call.

Remove a superflousy declared argument to idris2_openFile

---

src/TTImp/Elab/Record.idr
tests/Main.idr
tests/idris2/reg032/expected
tests/idris2/reg032/recupdate.idr
tests/idris2/reg032/run

Unless an explicit update is given

Leave implicit record fields alone on update

---

src/Compiler/LambdaLift.idr

PR #416 removed the unique index from `show` for `CaseBlock` and `WithBlock`, which is great for tests. But as a result, LambdaLift generates non-unique names, as it uses `show Name` by default to generate names for lifted lambdas. This commit explicitly includes the Case/With block index in the generated name to guarantee that it's unique.

Make sure names derived from case and with blocks get unique names during LambdaLifting

---

CHANGELOG.md
docs/source/backends/index.rst
docs/source/backends/javascript.rst
src/Compiler/ES/ES.idr

This name was removed in a recent patch, leading to a small conflict.
Also added a note to the CHANGELOG and a placeholder in the docs.
(Without a typo in the changelog this time...)

Update JS code generator to remove RF

---

src/Idris/Package.idr

This was broken in #425, because Idris2-boot hasn't implemented the
fix for #116

Fix bootstrap

---

libs/prelude/Prelude.idr
tests/idris2/reflection003/expected

Noticed this seemed to be missing. If there's a reason this wasn't included, feel free to ignore.

Add `Ord` implementation for `Either`

---

src/Idris/CommandLine.idr
src/Idris/Package.idr

```
$ time idris2 --build idris2.ipkg
________________________________________________________
Executed in   46,90 secs   fish           external 
usr time   44,26 secs  118,00 micros   44,26 secs 
sys time    2,46 secs  498,00 micros    2,46 secs 
$ time idris2 --checkpkg idris2.pkg
________________________________________________________
Executed in    1,68 secs   fish           external 
usr time  1482,77 millis  132,00 micros  1482,64 millis 
sys time  147,89 millis  591,00 micros  147,30 millis 
```
I find this command very helpful for some workflows.

Add command line option to typecheck package without codegen

---

libs/base/Data/Nat.idr

I assume these were copied directly from the Idris 1 libraries, where
there was an %access directive that we don't have any more.

Data.Nat proofs should be exported

---

docs/source/implementation/overview.rst

`%auto_implicits` has been renamed to `%unbound_implicits`. See https://github.com/edwinb/Idris2-boot/commit/c725d374884232ae20e076466e33bc0ac28b2537

Update reference to %auto_implicits in implementation notes

---

libs/base/Data/Vect.idr

`deleteAt` required access to the vector length, which can be problematic when you want to ensure that the length is erased at compile time.

Remove dependency to Vector length in deleteAt

---

src/Idris/Package.idr
tests/idris2/pkg003/expected

Seems like useful addition to ease packaging debugging.

Allow to override log level with package options

---

libs/contrib/Text/Parser.idr

Previously, the following code would run forever, or at least until it had eaten all my RAM.   Making `between` appropriately lazy fixes it.
(It has what I assume is the same behavior in Idris 1, where it segfaults in what is likely a stack overflow.  However, switching to a lazy `between` did not fix it like in Idris 2.)
```idris
import Text.Parser
openParen : Grammar Char True Char
openParen = terminal "wanted (" $ \x => if x == '(' then Just '(' else Nothing
closeParen : Grammar Char True Char
closeParen = terminal "wanted )" $ \x => if x == ')' then Just ')' else Nothing
otherChar : Grammar Char True Char
otherChar = terminal "did not want ()" $ \x => if x `elem` ['(',')'] then Nothing else Just x
data Tree = Leaf Char
| Branch (List Tree)
mutual
thingsInParens : Grammar Char True …
```

Make Text.Parser.between lazy

---

docs/source/updates/updates.rst

I think this is a spelling mistake.

fix typo: "lowercase later" to "lowercase letter"

---

libs/base/Language/Reflection.idr
src/Core/LinearCheck.idr
src/TTImp/Elab/RunElab.idr
tests/Main.idr
tests/idris2/reflection002/expected
tests/idris2/reflection002/power.idr
tests/idris2/reflection009/expected
tests/idris2/reflection009/perf.idr
tests/idris2/reflection009/run

In a 'Bind', normalise the result of the first action, rather than
quoting the HNF. This improves performance since the HNF could be quite
big when quoted back.
Ideally, we wouldn't have to quote and unquote here, and we can probably
achieve this by tinkering with the evaluator.
This has an unfortunate effect on the reflection002 test, in that the
"typed template Idris" example now evaluates too much. But, I think the
overall performance is too important for the primary motivation
behind elaborator reflection. I will return to this!

Improve elaborator reflection performance

---

src/Core/Coverage.idr
src/TTImp/ProcessDef.idr
tests/Main.idr
tests/idris2/coverage010/casetot.idr
tests/idris2/coverage010/expected
tests/idris2/reg033/DerivingEq.idr
tests/idris2/reg033/expected
tests/idris2/reg033/run
tests/idris2/reg033/test.idr

...until the definition is complete. This is necessary since sometimes
information outside the case block can help resolve interfaces, and in
the simplest case, we might just have delayed resolving a default
Integer. It turns out this was also an obscure bug waiting to happen
with coverage checking of nested case blocks (so there's a test update
there too).
Fixes #443

Delay building references for case blocks

---

libs/base/Data/Morphisms.idr

If `(~>)` isn't publicly exported, the type checker doesn't know that `Mor` constructs something of type `~>`.

Export `(~>)` publicly.

---

src/Core/Context.idr
src/Core/Options.idr
src/Idris/CommandLine.idr
src/Idris/IDEMode/Commands.idr
src/Idris/IDEMode/REPL.idr
src/Idris/Parser.idr
src/Idris/REPL.idr
src/Idris/SetOptions.idr
src/Idris/Syntax.idr

It sends a codegen directive to the current codegen. It's useful
for sending options you don't want to hard code in the source. Examples
include enabling profiling or setting a target.

Add `--directive` cli option

---

samples/ffi/Small.idr
samples/ffi/Struct.idr
samples/ffi/smallc.c

This (very) small PR adds some documentation and clarification around a sample that I was quite confused by when initially looking around at the source for Idris2. Specifically, it adds some documentation specifying that the *user* must build `libsmallc.so`[1], and changes the name of the `.so` in `Small.idr` and `Struct.idr` to better reflect the convention of `X.c` producing `libX.so`. 
[1] Although this might seem obvious, it tripped me up somewhat, as Idris 2's build process generates a file called `small.so` when compiling `Small.idr`. This, however, isn't a shared object, but (as far as I can tell) compiled scheme code, and aside from a "cannot find shared object..." error, there is no other indication that the user should build the correct `.so` themselves. Moreover, as the (old) …

Document samples/ffi, and change name of .so to better suit convention. 

---

src/Core/CaseBuilder.idr

Add a missing explicit case to Core/CaseBuilder.idr: `headEq` to allow for matching on pi-types as per Edwin.
Code that fails before the fix:
https://gist.github.com/donovancrichton/2838abd65c12dbf0dc01806ac8eafb0f
Has been tested to work after the fix.
See: https://functionalprogramming.slack.com/archives/C043A0KTY/p1595633177089900

Added explicit case to headEq to allow matching on Pi Types.

---

libs/base/Data/Either.idr
libs/base/Decidable/Equality.idr
libs/prelude/Prelude/EqOrd.idr

For Void and Either
This is because I ended up using them elsewhere, so why not include them in the stdlib.
Also expose left/rightInjective functions, as are used in the DecEq proofs.

Add various instances from stdlib interfaces (Eq, Ord, DecEq)

---

src/Core/Context.idr
src/Idris/REPL.idr
src/TTImp/Interactive/CaseSplit.idr
src/TTImp/Interactive/ExprSearch.idr
src/TTImp/Interactive/GenerateDef.idr
src/Yaffle/REPL.idr
tests/idris2/interactive005/IEdit.idr
tests/idris2/interactive005/expected
tests/idris2/interactive005/input

Rather than returning a complete list of results, return a pair of the
first result, and a continuation. The continuation explains how to
continue the search if the given result is deemed unacceptable (either
on encountering an error somewhere, or just if the caller wants the next
result).
This means we don't search needlessly if we're only looking for the
first result. Fixes #228

Reorganise expression search

---

libs/prelude/Prelude/Show.idr

I'm currently duplicating it in my own project, and it would be nicer to just use the standard library version.

Make showParens public

---

CHANGELOG.md
src/Idris/REPL.idr
src/Idris/REPLOpts.idr
src/Idris/Resugar.idr
src/TTImp/Interactive/CaseSplit.idr
src/TTImp/Interactive/ExprSearch.idr
src/TTImp/Interactive/GenerateDef.idr
src/Yaffle/REPL.idr
tests/Main.idr
tests/idris2/basic016/expected
tests/idris2/basic019/expected
tests/idris2/basic023/expected
tests/idris2/interactive009/expected
tests/idris2/interactive011/expected
tests/idris2/interactive016/Cont.idr
tests/idris2/interactive016/expected
tests/idris2/interactive016/input
tests/idris2/interactive016/run
tests/idris2/interactive017/RLE.idr
tests/idris2/interactive017/expected
tests/idris2/interactive017/input
tests/idris2/interactive017/run
tests/idris2/literate006/expected
tests/idris2/literate008/expected
tests/idris2/pkg005/expected

This has involved quite a bit of reorganisation and some improvements in
resugaring so that the results look nice. In summary:
* Expression search now gives back a RawImp rather than a checked term,
which allows it to include case expressions
* Case with one pattern is resugared to a destructuring let
* Some name generation issues address in function generation
We look at intermediate results for local variables which are functions
that return a concrete type, or recursive calls that return a single
constructor type. In these cases, we:
* let bind the local variable/recursive call
* generate a new definition for the scope, as a 'case' function
When we recursively generate the definition, it's a bit more restricted
so as not to explode the search space. We only take the first result, we …

Look at intermediate results in program search

---

src/Idris/Parser.idr
src/Parser/Rule/Source.idr
tests/Main.idr
tests/idris2/perf005/Lambda.idr
tests/idris2/perf005/expected
tests/idris2/perf005/run

As it was, there was significant backtracking for big expressions,
getting to the end, not finding a **, so having to try again for
application expressions. Fixes #532

Refactor grammar for dependent pairs

---

libs/prelude/Prelude/IO.idr

`getChar, putChar` reads/writes exactly one byte from/to stdio
`putChar` writes exactly one byte
`putCharLn` writes the whole codepoint + \n
I think that should be pointed out more vigorously as their behaviour currently is confusing

Inconsistent std IO

---

libs/contrib/Syntax/PreorderReasoning.idr

Fix the `contrib:Syntax.PreorderReasoning` error from #536 (there's still a bug in idris that `PreorderReasning` no longer exposes).
Correct the dependency in `FastDerivation` to use the RHS in `step`
Try to avoid shadowing `y` in the LHS of `Calc`
I've pushed this through frex, too, if that's a measure for anything

Fix Preorder reasoning 

---

src/Core/Unify.idr
tests/Main.idr
tests/idris2/reg034/expected
tests/idris2/reg034/run
tests/idris2/reg034/void.idr

As it was, it could break if the argument was repeated more than twice.
When checking dot patterns, we need to check that no further holes are
solved, and that the pattern variable doesn't unify with some other
pattern variable, but if it had already made progress (either for a good
or bad reason) we missed this. Fixes #536

Fix repeated argument check

---

libs/contrib/Syntax/PreorderReasoning.idr

For lack of a better place, I've put it in `Syntax.PreorderReasoning`
These equations are natural in equational reasoning, but less so when
rewriting, so that's why it's there

contrib: Add a 2-holed congruence function

---

src/Idris/Driver.idr
src/Idris/ProcessIdr.idr
src/Idris/REPL.idr

The timings flag (`--timing`) displays various timing information during the entire compilation process.
This is useful when performing adhoc profiling of the compiler.
However, the information is a mixture of timestamps and relative progress.
The information is inherently nested, and such nesting is not immediatly clear in the output.
This can be confusing.
This minor changes nests the timing information on output so that when aligned one can see the timestamps at the highest level, and progress during the elaboration stage.

Makes timing output more intuative to read.

---

libs/contrib/Data/String/BuildExpressionParser.idr
libs/contrib/Data/String/Parser.idr
libs/contrib/Data/String/Parser/Expression.idr
libs/contrib/contrib.ipkg
tests/Main.idr
tests/chez/chez028/ExpressionParser.idr
tests/chez/chez028/expected
tests/chez/chez028/input
tests/chez/chez028/run

Idris port of haskell's [`BuildExpressionParser`](https://hackage.haskell.org/package/parsec-3.1.13.0/docs/Text-Parsec-Expr.html). I figured with the parser combinators in contrib this might be a useful addition, but I'm not sure what the rules are for what ends up in contrib so feel free to close this PR if it's not relevant.
Also this is my first attempt at idris2, so I may have gotten a lot of stuff wrong, and I may have gone overboard with the `public export`s. The test seems reasonable but could probably be improved upon, plus I had to add a few combinators just to test (`natural`, `token`...) which maybe don't belong in the test file. Open to any feedback on how to improve this anyway.

Add BuildExpressionParser to contrib

---

libs/base/Control/Monad/State.idr

It requires a slightly more convoluted implementation, because of `liftIO`'s linear type.
It might make sense to export a linear `io_map : (a -> b) -> (1 _ : IO a) -> IO b` from `PrimIO`, similarly to `io_bind` -- it would make things like this a little nicer to write.

Implement HasIO for StateT

---

src/Compiler/CompileExpr.idr
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Gambit.idr
src/Compiler/Scheme/Racket.idr
src/Core/Binary.idr
src/Core/CompileExpr.idr
src/Core/TTC.idr

This should fix #549, as well as other potential problems caused by Bits8, Bits16 and Bits64 being treated as Bits32 for foreign functions.
Needs a review by someone who understands the bigger picture, particularly in relation to `TTC.idr` as it is entirely unclear to me what that does.

Split CFUnsigned into 8/16/32/64 bits versions

---

libs/prelude/Prelude/Ops.idr
src/Core/Normalise.idr
tests/Main.idr
tests/prelude/reg001/expected
tests/prelude/reg001/fixity.idr
tests/prelude/reg001/run

(&&) traditionally has higher precedence than (||).
Note that this commit requires to bootstrap again.

Restore Bool operators precedence

---

INSTALL.md

I encountered a difficult-to-diagnose error while bootstrapping Idris 2, and these instructions fixed it for me.

Add instructions about thread support in Chez Scheme to INSTALL.md

---

src/Idris/Driver.idr
src/Utils/Term.idr
support/c/idris_term.c
support/c/idris_term.h

Even if the windows 10 terminal has support for ansi escape codes, it still needs some convincing before actually working.
As I cannot, at the moment, test on windows system, before merging, can someone confirm that indeed on windows 10 colors work automatically with this fix?

Windows color fix

---

src/Idris/IDEMode/REPL.idr

emacs's idris-mode seems to hang without a response

Make IDEMode respond after executing a `consolewidth` instruction

---

src/Idris/SetOptions.idr

At least on Emacs this fixes the following warning:
```
Warning from Idris:    / // __  / ___/ / ___/   __/ /     Version 0.2.1-
error in process filter: open-network-stream: make client process failed: Connection refused, :name, Idris IDE support, :buffer, *idris-connection*, :host, 127.0.0.1, :service, 310, :nowait, nil, :tls-parameters, nil
error in process filter: make client process failed: Connection refused, :name, Idris IDE support, :buffer, *idris-connection*, :host, 127.0.0.1, :service, 310, :nowait, nil, :tls-parameters, nil
```

Suppress banner when running with --ide-mode-socket option

---

libs/prelude/PrimIO.idr
support/c/idris_support.c
support/c/idris_support.h

This will enable us to get null pointers in Idris2 so that we can pass
them on to other c methods. This is useful when creating FFI bindings
for other libraries that expect optional null pointers to be passed into
the arguments.
For example, the samples/FFI-readline code uses
nullString, a similar method to get a null pointer in Idris2.
https://github.com/idris-lang/Idris2/blob/3d53c2874b4dcfe8ca4b6687b384be261faf74d4/samples/FFI-readline/readline_glue/idris_readline.c#L32-L34
Note: I tried to implement a generic getNullPtr via
```idris
%foreign "C:idris2_getNull,libidris2_support"
export
prim__getNullPtr : Ptr t
```
But I kept getting an error saying:
`Uncaught error: PrimIO.idr:95:1--97:25:Can't pass argument of type Type  to foreign function`
So I just implemented one specific for …

add prim__getNullAnyPtr and prim__castPtr

---

tests/idris2/basic044/expected
tests/idris2/basic044/run

All of these internal names are making the output fragile. This
cleanup should allow us to only have to update the golden file
when there is a genuinely interesting change.

[ test ] cleanup basic044

---

libs/base/Data/Strings.idr
src/Compiler/ES/ES.idr
support/chez/support.ss
support/gambit/support.scm
support/racket/support.rkt

`Data.Strings.fastAppend` was a `schemeCall`; this patch makes it a foreign call, so it can be implemented on non-Scheme backends.

Make fastAppend a foreign call

---

libs/base/Data/List.idr
libs/base/Data/Nat.idr
libs/base/Data/Stream.idr
src/Compiler/Inline.idr
src/Compiler/LambdaLift.idr
src/Compiler/Scheme/Gambit.idr
src/Core/AutoSearch.idr
src/Core/CaseBuilder.idr
src/Core/CaseTree.idr
src/Core/CompileExpr.idr
src/Core/Coverage.idr
src/Core/Env.idr
src/Core/Normalise.idr
src/Core/TT.idr
src/Idris/Error.idr
src/TTImp/Elab.idr
src/TTImp/Elab/ImplicitBind.idr
src/TTImp/Elab/Rewrite.idr
src/TTImp/Interactive/ExprSearch.idr
src/TTImp/ProcessDef.idr
src/TTImp/Unelab.idr

Main change
===========
The main change is to the type of functions dealing with an untouched
segment of the local scope. e.g.
```idris
weak : {outer, vars : _} -> (ns : List Name) ->
tm (outer ++ inner) -> tm (outer ++ ns ++ inner)
```
Instead we now write
```idris
weak : SizeOf outer -> SizeOf ns -> tm (outer ++ inner) -> tm (outer ++ ns ++ inner)
```
meaning that we do not need the values of `outer`, `inner` and `ns`
at runtime. Instead we only demand a `SizeOf outer` and `SizeOf ns`
which are essentially a `Nat` each together with an (erased) proof
that the list in question is of that length.
Other modifications
===================
Quadratic behaviour
-------------------
A side effect of this refactor is the removal of two sources of
quadratic behaviour. They typically arise in a …

[ refactor ] suggested during SPLV 

---

src/Idris/Parser.idr
tests/Main.idr
tests/idris2/record007/Fld.idr
tests/idris2/record007/expected
tests/idris2/record007/input
tests/idris2/record007/run

I wanted to add a test case with a record that contains nothing but an implicit
auto field to #607 but it was not implemented. So I thought I would fix that.
Love that this was basically just a matter of adding syntax for it! :relaxed:

[ new ] allow `auto` fields in records

---

src/Idris/Parser.idr
tests/idris2/basic041/QDo.idr
tests/idris2/basic041/expected

[ fix #616 ] Namespaces are stored in reverse order

---

src/Parser/Lexer/Source.idr
src/Text/Lexer.idr
tests/idris2/reg020/expected
tests/idris2/reg020/matchlits.idr

Written via "0b" in the manner of other literals. e.g. 0b111001 = 57
useful precursor to other bits things in the works

add binary literals

---

src/Compiler/ES/ES.idr
src/Compiler/ES/Imperative.idr
src/Compiler/ES/ImperativeAst.idr

So backends based on it can expose a simpler FFI.

Preserve foreign declaration types in `Compiler.ES.ImperativeAst`

---

libs/base/Data/Nat.idr
libs/base/Data/Nat/Order.idr
libs/contrib/Data/HVect.idr

[ #597 ] Constructor injectivity proofs don't have to match on their arguments, so they might as well take them at quantity 0. This PR cleans up a couple of places in the libraries where an injectivity proof named its arguments explicitly but left them at multiplicity `ω`.

[re #597] make constructor injectivity proofs use 0 multiplicity

---

src/Core/Context.idr
src/TTImp/Interactive/GenerateDef.idr
src/TTImp/ProcessDecls.idr
src/TTImp/ProcessDef.idr
tests/Main.idr
tests/idris2/total010/PartialWith.idr
tests/idris2/total010/expected
tests/idris2/total010/run

Auxiliary functions introduced in elaboration (e.g., through case splits and with clauses) now
have the same totality annotation as the function they're defined in.
Moved auxiliary function `findSetTotal` into `Context.idr` since it's
now used by `ProcessDef.idr` too.
Added a totality requirement argument to `checkClause` so that the
with-clause case could propagate it to the functions it generates in
elaboration.
Dyanmically rebind the default totality annotation in rhs elaboration 
in pattern matches to the current function's totality annotation, 
restoring the previous default afterwards.
When synthesizing clauses, allow synthesised clauses to be
partial.
It's an arbitrary choice, the other choice can be the default
option. But if the place in which we're synthesising has a non-default …

Fix bug #654

---

docs/source/ffi/ffi.rst
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Gambit.idr
src/Compiler/Scheme/Racket.idr
src/Core/Core.idr
src/Idris/Error.idr
src/Idris/SetOptions.idr
tests/Main.idr
tests/chez/chez031/Specifiers.idr
tests/chez/chez031/expected
tests/chez/chez031/input
tests/chez/chez031/run

There's some missing flexibility in how foreign specifiers can be used with scheme that is addressed here with minimal changes to how scheme specifiers are read. This opens up uses for users that they otherwise would have had to modify the compiler's support files to accomplish.

add ability to target scheme flavor in foreign specifiers

---

libs/base/Data/Rel.idr
libs/base/Decidable/Decidable.idr
libs/contrib/Data/Fun/Extra.idr
libs/contrib/Data/Void.idr
libs/contrib/Decidable/Decidable/Extra.idr
libs/contrib/Decidable/Order/Strict.idr
libs/contrib/contrib.ipkg

Expose some `private` function in libs/base that I needed, and seem like
their visibility was forgotten
I'd appreciate a code review, especially to tell me I'm
re-implementing something that's already elsewhere in the library
Mostly extending existing functionality:
* `Data/Void.idr`: add some utility functions for manipulating absurdity.
* `Decidable/Decidable/Extra.idr`: add support for double negation elimination in decidable relations
* `Data/Fun/Extra.idr`:
+ add `application` (total and partil) for n-ary functions
+ add (slightly) dependent versions of these operations
+ add n-ary function precomposition
* `Decidable/Order/Strict.idr`: a strict preorder is what you get when
you remove the diagonal from a pre-order. For example, `<` is the
associated preorder for `<=` over `Nat`. …

 [contrib] Add misc libraries to contrib

---

docs/source/typedd/typedd.rst
libs/base/Control/Monad/State.idr
src/Idris/Elab/Implementation.idr
tests/typedd-book/chapter12/TreeLabelState.idr

Nipping this historical artifact in the bud before it roots. It's quite often useful to be able to `map` directly to the result of a StateT computation and due to how Functor works this is made harder when the tuple is `(a,state)` vs `(state,a)`
Specifically that `map f (x,y)` applies `f` to `y`.
It's also rare that a person's `state` argument takes up more space than their `StateT s a` argument in `runState`. e.g.
```
foo = runState (do multiline
statet
thing)
thestartingstate
```
and so one has to immediately decide if it's worth the extra parens and formatting involved or if they should take the time to pull out `multiline_statet_thing` into a separate definition.
Let's avoid this hassle by providing the state upfront instead and allowing users to write their bulkier code where it will …

State param order

---

libs/base/Control/Monad/Reader.idr

following up on the change made in #671 
To encourage people to order arguments in this manner going forward.

change runReader's to take state first to allow easier use

---

src/Idris/IDEMode/Parser.idr
tests/Main.idr
tests/ideMode/ideMode004/expected
tests/ideMode/ideMode004/input
tests/ideMode/ideMode004/run

Escaped characters sent via idris-mode were not being converted cleanly, resulting in errors.
This PR fixes the issue.
Before this fix:
```
$ build/exec/idris2 --ide-mode
000018(:protocol-version 2 0)
00001C((:interpret "\"Test\"") 32)
0000d8(:return (:error "Parse error at line 1:1:
Expected 'case', 'if', 'do', application or operator expression (next tokens: [symbol \\, Unrecognised \", identifier Test, symbol \\, Unrecognised \", end of input])") 32)
^CFailed to read a character
```
After this fix:
```
$ build/exec/idris2 --ide-mode
000018(:protocol-version 2 0)
00001C((:interpret "\"Test\"") 32)
000021(:return (:ok "\"Test\"" ()) 32)
^DAlas the file is done, aborting
```

Fix ide mode repl not converting escaped characters

---

src/TTImp/Elab/RunElab.idr
src/TTImp/ProcessRunElab.idr
tests/idris2/reflection001/expected
tests/idris2/reflection001/quote.idr

The check was present for %runElab in the RHS but not if you used as declaration. See #672.

Added missing extension check on top-level %runElab

---

src/Idris/Parser.idr
tests/Main.idr
tests/idris2/basic046/TupleSections.idr
tests/idris2/basic046/expected
tests/idris2/basic046/input
tests/idris2/basic046/run

The commented out test is aspirational: we should be able to do the same for `DPair`.
Ideally we should also be able to arbitrarily interleave `,` and `**`.

Adding a whole bunch of tuple sections

---

src/Idris/Parser.idr
tests/Main.idr
tests/idris2/interface017/Tricho.idr
tests/idris2/interface017/TwoNum.idr
tests/idris2/interface017/expected
tests/idris2/interface017/run

Coming back to the code that motivated the work on #680 
I got annoyed I could not write
```idris
interface T (a : Type) (lt, eq : a -> a -> Type)
```
like in other telescopes but would be forced to write
```idris
interface T (a : Type) (lt : a -> a -> Type) (eq : a -> a -> Type)
```
instead

[ new ] comma-separated interface parameters

---

libs/prelude/Prelude/EqOrd.idr
libs/prelude/Prelude/Interfaces.idr

useful items for applying multiple predicates, e.g.
sortBy (comparing length <+> compare)
To sort some lists elements by length and then lexographically

add Semigroup for Ordering and a -> b

---

libs/base/Data/Nat.idr

So we could use it for type-level division.
Means changing it and its auxiliary function from `export partial` to
`public export total`

[minor] Make `base/Data.Nat.divNatNZ` compile-time reducible

---

libs/base/Data/Either.idr
libs/base/Data/List.idr
libs/base/Data/List1.idr
libs/base/Data/Strings.idr
libs/base/Decidable/Equality.idr
libs/contrib/Data/List/TailRec.idr
libs/network/Network/Socket/Data.idr
src/Compiler/Scheme/Chez.idr
src/Core/Core.idr
src/Core/Hash.idr
src/Core/Name/Namespace.idr
src/Core/Options/Log.idr
src/Core/Reflect.idr
src/Idris/Parser.idr
src/Parser/Lexer/Source.idr
src/Utils/Binary.idr
tests/Main.idr
tests/chez/chez020/Popen.idr

The constructor for `List1` was named `(::)` so that we could write `[x,y,z]`
for List1 literals. However that means that every `[x,y,z]` or (`x :: xs`)
is ambiguous (it could be either a `List` or a `List1`) and can only be
disambiguated if there is a type annotation around.
This is really annoying because if we apply an overloaded function to
one such expression (e.g. `show [x,y,z]`) then we need to manually
disambiguate!
Similarly, `toList` is a `Foldable` method and having it overloaded with
List1's function to forget a `List1` back into a `List` is really
annoying.

[ breaking ] remove List1 related ambiguities

---

libs/prelude/PrimIO.idr
src/Compiler/ES/ES.idr
tests/idris2/basic044/expected
tests/idris2/with003/expected

The PR #690 reminded me about `FArgList`, which is not needed anymore (since #595).

Remove FArgList

---

support/chez/support.ss
support/gambit/support.scm
support/racket/support.rkt
tests/Main.idr
tests/idris2/interpreter004/expected
tests/idris2/interpreter004/input
tests/idris2/interpreter004/run

Numbers in Scheme have an internal flag: exact/inexact.
This fix flags numbers outputted from `floor` when casting between `String` and `Int` as exact.
Fixes `cast {to = Int} "12.3"` reducing to `12.0` (internally)
I have tested it on my machine with Chez as a backend. I can't properly install Racket for some reason.
So if someone reading this has Racket in working order, could you please check this ?
Not sure how to write a test in such case, as the fix only concerns the internal representation, nor that a test is really needed.

Fix String->Int cast on Scheme backends

---

libs/base/Language/Reflection/TTImp.idr

Addresses https://github.com/idris-lang/Idris2/issues/625
I wasn't sure which the right choice was so you can cherrypick dd128f2 to address this by changing `ForeignFn : List String -> FnOpt` to `ForeignFn : List TTImp -> FnOpt` to match the RawImp, or the PR as a whole can be taken to fix this issue while keeping `libs/base/Language/Reflection/TTImp.idr` as `ForeignFn : List String -> FnOpt`

Fix how reify treats ForeignFn

---

src/Idris/Desugar.idr
src/TTImp/BindImplicits.idr
src/TTImp/TTImp.idr
tests/idris2/basic032/Idiom.idr
tests/idris2/basic032/Idiom2.idr
tests/idris2/basic032/expected
tests/idris2/basic032/run

Things like (,) () aren't straightforward IVar's but are IAlternative's
which present options about how the term should resolve. [| |] was not
accounting for this.
Addressing #676

fix idiom brackets to account for IAlternative

---

src/Text/Lexer.idr

introduced in #619 but wasn't actually doing anything
this wasn't doing anything anyway as it's first handled while
escaping in src/Parser/Support.idr and ends up clashing with \b
This doesn't affect being able to write `0b10101`, only `'\b10101'` which it wasn't doing anyway

revert binary character literal

---

src/Compiler/Scheme/Chez.idr

So that we prefer the local support lib before others in the path.

Put the appdir first in LD_LIBRARY_PATH

---

src/Compiler/ES/Imperative.idr
tests/Main.idr
tests/node/idiom001/Main.idr
tests/node/idiom001/expected
tests/node/idiom001/input
tests/node/idiom001/run

Since the imperative form has no nesting of scopes.
Fixes #643

[ fix #643 ] Make `NmLet` names unique in `Compiler.ES.Imperative`

---

libs/prelude/Prelude/Interfaces.idr
libs/prelude/Prelude/Ops.idr

This mirrors Haskell's `(>>)` operator, for sequencing computations while discarding intermediate results. I realise that adding things to the prelude shouldn't be taken lightly, however in conversation with @edwinb we've agreed that this seems like a sensible place to put this function.

Add (>>) operator

---

src/Core/Core.idr
src/Idris/Driver.idr
src/Idris/SetOptions.idr
tests/chez/chez031/Specifiers.idr
tests/chez/chez031/expected
tests/chez/chez031/run

Missed a case in #663 which is covered now by checking for exceptions where postOptions is used

add specifier check for cli compilation

---

libs/contrib/Syntax/PreorderReasoning.idr

Refactor the DIY equational reasoning library to be a bit more like
the generic pre-order reasoning library:
Change the `...` notation into a constructor for a new `Step` datatype.
This seems to help idris disambiguate between the two kinds of
reasoning when they're used in the same file (e.g., frex).

preorder reasoning: introduce a `Step` datatype

---

libs/network/Network/Socket/Data.idr
support/c/idris_net.c
support/c/idris_net.h

The current implementation of `ToCode SocketFamily` uses hardcoded constants, which are correct on Linux but not all correct on other systems (though I've only checked OpenBSD, as that's what I have to hand). For portability's sake, it would be a better idea to read the magic constants from the definitions in the system C library, so we don't need to special case every platform we want Idris to run on. I've implemented this by adding some getter functions to the C runtime support library (one for each constant we want to know about) and then calling the appropriate getter to decode each symbolic constant on the Idris side.

Retrieve network address family preprocessor constants from C runtime code

---

src/Idris/IDEMode/REPL.idr

This patch simply forces a flush on the IDE mode first message sent on the standard output (the port of the socket). Note that all comunication on the socket are flushed on message basis, which seems reasonable since the IDE mode is meant to be used in a "conversational" manner. While trying to implement a vim plugin based upon the IDE mode instead of the `--client` CLI argument, we encountered two difficulties:
1. The buffered messages on the stdout (if not using sockets or just for the first message) where not read asynchronously on each message, and required some additional options (in particular that the stdout pipe must be a pseudo-terminal, which is problematic on non-unix). Flushing solved the issue.
2. When spawning a new idris2 ide mode instance there is no reliable way of …

Flush stdout in IDE mode first message

---

src/Core/Context.idr
src/TTImp/Interactive/CaseSplit.idr

The problem is that if the function is defined in a submodule, then the current namespace (accessed by calling getNS) differs from the function namespace, therefore it is not considered visible by TTImp.Elab.App.checkVisibleNS

Fixes Issue #74. 

---

libs/contrib/Data/String/Parser.idr
tests/chez/chez027/StringParser.idr
tests/chez/chez027/expected

The combinators are mostly those found in [Lightyear](https://github.com/ziman/lightyear) that I was missing when porting a parser to `Data.String.Parser`. I'm not sure that I implemented `requireFailure` 100% correctly, so would be best to take a close look at that.
This also changes the return type of `char` and `string`. They previously returned `()`, they now return `Char` and `String` repectively. I can change it back if this is not desired behaviour, but this seems to be the normal return type for `char` and `string` as found in [Lightyear](https://github.com/ziman/lightyear/blob/master/Lightyear/Char.idr#L23), [attoparsec](http://hackage.haskell.org/package/attoparsec-0.8.1.0/docs/Data-Attoparsec-Char8.html#v:char) and [parsec](https://hackage.haskell.org/package/parsec-3.1.11/docs/ …

Add extra parsers

---

libs/contrib/System/Future.idr
libs/contrib/contrib.ipkg
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Common.idr
src/Compiler/Scheme/Racket.idr
support/chez/support.ss
support/racket/support.rkt
tests/Main.idr
tests/chez/concurrency001/Futures.idr
tests/chez/concurrency001/expected
tests/chez/concurrency001/run

This is a simple Chez implementation of a Future Primitive; Since many systems are multicore this might be a good low hanging fruit in improving the Idris2 Compiler Performance.
The idea of adopting Future as a threading primitive rather than a Thread is to facilitate parallelism in the case of pure functions. (Since it makes returning values from a thread easier without needing to worry about mutation/synchronization or other interproccess communication techniques) This is implemented as an OS Thread per future in Chez. So for the time being it is intended to launch tasks in parallel that currently take some time. (Parsing for example)

Implement Futures as a Parallelism Primitive

---

libs/base/Data/Fin.idr
libs/base/Data/List.idr
libs/base/Decidable/Equality.idr
libs/base/Decidable/Equality/Core.idr
libs/base/base.ipkg

This PR is somewhat controversial because for addition of simple function, well-known and commonly used `Decidable.Equality` module was split on two parts. However, this split does not influence on regular users of this module.
This split was done to avoid circular dependency of module imports since `Decidable.Equality` imports lots of `Data.*` modules for those types that are defined in the `prelude`, thus preventing, e.g. using `Data.Fin` module in the `Data.List` one.

Suggestion of alternative list index function

---

src/Idris/Parser.idr
tests/Main.idr
tests/idris2/basic050/Ilc.idr
tests/idris2/basic050/expected
tests/idris2/basic050/input
tests/idris2/basic050/run

You can use lambda functions without parenthesis and `$`-operator as the last argument:
```idris
f : (Int -> Bool) -> Int
il : Int
il = f \x => x > 0
```
But at the moment you can't do this for the lambda case.
```idris
lc : Int
lc = f $ \case 0 => True ; _ => False -- ok
ilc : Int
ilc = f \case 0 => True; _ => False -- does not parse
```
This PR fixes this.

Have lambda-case available everywhere lambda is

---

src/Idris/Elab/Interface.idr
tests/Main.idr
tests/idris2/reg035/Implicit.idr
tests/idris2/reg035/expected
tests/idris2/reg035/run

The interface constraint variable `__con` was added after all implicit
variables before during interface elaboration, resulting in the variable
being unavailable in implicit arguments to interface methods.
For example, when type-checking
interface A where
x : Nat
f : {pf : x = 0} -> ()
the type-checker would complain with
Error: While processing type of f. Undefined name __con.
, whereas
interface A where
x : Nat
f : (pf : x = 0) -> ()
would type-check just fine.
Note that the first example still doesn't type-check, but that's because
of another error.
**Remark**: This fixes #658.

Auto-implicit `__con` now added before implicits.

---

docs/source/reference/literate.rst
src/Parser/Unlit.idr
tests/idris2/literate011/IEdit.md
tests/idris2/literate013/LitTeX.tex
tests/idris2/literate013/expected
tests/idris2/literate013/run

+ Expanded the documentation on how to use literate modes.
+ Added invisible code blocks in Markdown using specially tagged comment blocks: ``.
+ Fixed OrgMode specificaton to recognise comment blocks properly.
+ Extended Literate support to include LaTeX.

Fixed docs and improved Literate mode. 

---

docs/source/updates/updates.rst

With the original indent the beginning of the sentence is parsed as a named itemization.

Tiny fix of the formatting in the recently added documentation.

---

libs/base/Control/Monad/Either.idr
libs/base/Data/List1.idr
libs/base/Data/Vect.idr
libs/contrib/Data/SortedMap.idr
libs/contrib/Data/SortedSet.idr
libs/prelude/Prelude/Interfaces.idr
libs/prelude/Prelude/Types.idr
tests/typedd-book/chapter07/Tree.idr

Adding functions `null` for Foldable structures and `isNullString` to test whether the structure / string is empty, respectively.

[ new ] null method in Foldable

---

libs/base/Data/List.idr
libs/base/Data/List/Quantifiers.idr
libs/contrib/Data/List/Lazy.idr

There are a lot of functions for usual lists but almost no for lazy lists. I propose to add several functions for lazy lists in `contrib`, especially for their creation and cutting.
Also, I propose to add one function to `Data.List` in `base` and to add `%default total` there.

Some functions, mostly for lazy lists

---

src/Idris/Pretty.idr

Fixes the extra newlines described in https://github.com/meraymond2/idris-vscode/issues/23

If the width terminal is zero make it Unbounded

---

src/Core/AutoSearch.idr
tests/Main.idr
tests/idris2/interface021/LocalHint.idr
tests/idris2/interface021/expected
tests/idris2/interface021/run

Local hints need to reduce (just like global hints do) so we expand
their definition to the lifted name before applying them.
We're identifying the global hints by knowing that the binder name is a
nested function name. This is a bit of hack, and it'd probably be better
to record that information in the binder instead, but that's a more
substantial change than I want to do right now.

Treat local hints differently in auto search

---

INSTALL.md
src/Core/Core.idr
src/Core/Hash.idr
src/Core/Name/Namespace.idr
src/Core/Options/Log.idr
src/Core/Reflect.idr
src/Idris/Elab/Implementation.idr
src/Parser/Lexer/Source.idr
src/TTImp/Elab/App.idr
src/TTImp/Impossible.idr
src/Text/Lexer/Core.idr
src/Utils/Binary.idr

For compatibility with previous library verions, so that we can build with 0.2.1(+patches) as well as bootstrapping.

Compatibility fixes

---

src/Idris/REPL.idr
src/Idris/Syntax.idr

Add `:!` from Idris 1 to the REPL. Only tested on macOS.

Add :! to REPL

---

.github/workflows/ci-buildprevious.yml

Specifically, at the moment, to build from Idris 0.2.2 (which is not yet released, but is basically 0.2.1 plus a few bits that are needed to build the latest version). I suggest we keep this at the earliest version known to work, though there is also no need to be shy about increasing the minimum requirements when we need to.
This CI action skips the tests - it's just about knowing whether the APIs are still up to date.
I'll release 0.2.2 soon, then 0.3.0 not long after, after checking over the latest PRs.

Add CI action to build from older version

---

src/Idris/REPL.idr
tests/Main.idr
tests/idris2/interpreter006/expected
tests/idris2/interpreter006/input
tests/idris2/interpreter006/run

Implement `it` in the REPL. Since this is in the contributions wanted and is easy to implement, I figured I would add it. I would be willing to try improve `:let` and add `:unlet` if that is wanted, but I would need to know if and how the behavior should be different from Idris 1 before I start. I'm not entirely sure if I did this right, but it works.

Add it to REPL

---

libs/contrib/Text/Parser.idr

`count` currenty only returns lists with unknown length:
```idris
mutual
private
count1 : (q : Quantity) ->
(p : Grammar tok True a) ->
Grammar tok True (List a)
count1 q p = do x <- p
seq (count q p)
(\xs => pure (x :: xs))
||| Parse `p`, repeated as specified by `q`, returning the list of values.
export
count : (q : Quantity) ->
(p : Grammar tok True a) ->
Grammar tok (isSucc (min q)) (List a)
count (Qty Z Nothing) p = many p
count (Qty Z (Just Z)) _ = pure []
count (Qty Z (Just (S max))) p = option [] $ count1 (atMost max) p
count (Qty (S min) Nothing) p = count1 (atLeast min) p
count (Qty (S min) (Just Z)) _ = fail "Quantity out of order"
count (Qty (S min) (Just (S max))) p = count1 (between min max) p
```
I don't think idris can figure out the length later on, so either we give a …

Add `countExactly` to Text.Parser in libs/contrib to return a Vect

---

docs/source/faq/faq.rst
docs/source/tutorial/interactive.rst

This PR adds some documentation about how one can get command history in the Idris2 repl by using the rlwrap utility.

Add rlwrap information to docs

---

libs/base/Data/Vect.idr

Snoc adds an element at the end of the vector. The main use case
is to get the expected type signature
`Vect n a -> a -> Vect (S n) a` instead of
`Vect n a -> a -> Vect (n + 1) a` which you get by using `++ [x]`
I've needed this a lot lately, `List` already has `snoc` so I thought
`Vect` should get it too

Add `snoc` to Data.Vect

---

tests/typedd-book/chapter02/Generic.idr

Seemed like the doubling functions had incorrect function definitions, so I changed them such that they actually double their inputs instead of squaring them.

test: Change function definitions in "Generic.idr".

---

libs/prelude/Prelude/Interfaces.idr
libs/prelude/Prelude/Types.idr
tests/idris2/total006/Total.idr
tests/idris2/total006/expected
tests/idris2/total006/input

I've needed this function a lot lately so I thought other people might
need it too.
I've placed it in `Types` because it cannot live in `Interfaces`. Indeed,
since the return type is `Nat` it would require importing `Types` making
the imports circular. Another solution would have been to add it to `base`
rather than `prelude` but I could not find a suitable place for it. Finally,
another solution would have been to place it in `Interfaces` and have it 
depend on the `Num` interface and return a member of `Num` rather than
`Nat` but that meant worse inference and inaccurate semantics since the
count can never be negative.

Add count to prelude

---

libs/base/Data/Fin/Order.idr

I was trying to make use of Data.Fin.Order and realized that the code was not exported. I've added "public export" to the types and functions in Data.Fin.Order.
Let me know if you think any of them should be export instead of public export.

Add public export to types/functions in Data.Fin.Order

---

libs/base/Data/Stream.idr

`head` for `Stream` is exported both from `Prelude.Types` and `Data.Stream`. This PR removes the export from `Data.Stream`.

deleted 'head' from Data.Stream

---

src/Idris/IDEMode/Commands.idr
src/Idris/IDEMode/REPL.idr
src/Idris/IDEMode/SyntaxHighlight.idr
src/Idris/REPLOpts.idr
tests/ideMode/ideMode001/expected
tests/ideMode/ideMode001/input
tests/ideMode/ideMode001/input2

Fixed a simple issue where some IDE mode messages where not using the pretty printing options and added a IDE mode exclusive options (not available as a command-line option) to enable/disable syntax output when loading files. Even simple files with few definitions can generate a great amount of messages on the line, and some client may not need those messages.

IDEMode syntax option and fixed output

---

libs/base/Data/DPair.idr

We have `curry` and `uncurry` for non-dependent pairs, however, similar functions for dependent pairs sometimes are useful. In particular, I run into a usefulness when defining an isomorphism between two-argument dependently typed function and a function that returns a dependent pair.
Technically, this PR depends on #922 ~and if you look to diff, you'll see a combined diff of #922 and of actual addition of currying functions. But if #922 is not accepted but we're okay with this PR, it can be rebased and slightly changed to work on `master`~.

Currying functions for dependent pairs were added

---

libs/base/Data/DPair.idr
libs/base/Data/List/Quantifiers.idr

In some cases it's convenient to have a proof-carrying type of list elements. Suggested functions provide a way of converting between library way of expressing some property on the list level and a way of proof-carrying list elements (and vice-versa).
Technically, this PR depends on #928 and this PR's diff contains its diff too, so the only significant changes are in `Data.List.Quantifiers` module. However obviously it's possible to implement the suggested functions with similar but local definitions in case when general approach from #928 is undesired.

Functions for converting between list-level universal quantification and elementwise one

---

Makefile

Took some time for me to figure that out.

Print warning `make test` does not invoke `make`

---

libs/base/Control/Monad/Either.idr

This fixes an issue in the Foldable implementation of EitherT that came up during the writing of MaybeT (#909).

fixed bug in Foldable of EitherT

---

libs/base/Control/Monad/Either.idr
libs/base/Control/Monad/Maybe.idr
libs/base/base.ipkg
libs/prelude/Prelude/Basics.idr

This adds MaybeT to base. The implementation was based on the one of EitherT. Note: As far as I can see, this was not in Idris1 but neither was EitherT, so I thought it should be fine if I put this in base.

added MaybeT monad transformer to base

---

idris2api.ipkg
src/Compiler/ES/Node.idr
src/Compiler/RefC/RefC.idr
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Gambit.idr
src/Compiler/Scheme/Racket.idr
src/Idris/CommandLine.idr
src/Idris/Driver.idr
src/Idris/Env.idr

Until yesterday I did not know Idris2 accesses environment variables.
Mentioning them in `--help` would educate other users.
Not all descriptions make sense, I tried my best to guess them.
Output is: [link](https://gist.github.com/stepancheg/7d1dff344a0dd35b9d07fb4a417ecb32).

idris2 --help now prints env variables used by the compiler

---

libs/contrib/Test/Golden.idr
tests/Lib.idr
tests/Main.idr
tests/chez/concurrency001/Futures.idr

This executes all tests in a single test-suite concurrently, there were several refactors to avoid output being mangled between different test-units and changeDir was removed since several systems have a per-process working directory rather than a per-thread/future working directory.
test-suits are still executed sequentially.
In my system total test time went down from 148 seconds to 35 seconds. (A 76% decrease in test time)
```
________________________________________________________
Executed in   34.56 secs   fish           external 
usr time  376.58 secs    0.00 micros  376.58 secs 
sys time   57.88 secs  345.00 micros   57.88 secs 
```
vs
```
________________________________________________________
Executed in  147.41 secs   fish           external 
usr time  123.86 secs  264.00 …
```

Execute tests concurrently

---

src/TTImp/TTImp.idr
tests/Main.idr
tests/idris2/reg036/Test.idr
tests/idris2/reg036/expected
tests/idris2/reg036/run

The function `TTImp.TTImp.implicitsAs` is changed so that implicit
arguments that come after explicit ones that are not given are no longer
added. This fixes #67.
The reasoning behind this is that the former behaviour---of adding all
missing implicits---makes `implicitsAs` return malformed terms in
certain cases where the underlying function type has implicit arguments
that come after explicit ones. For example, the interface declaration
interface Foo a where
bar : a -> {auto ok : ()} -> a
and the function declaration
foo : Void -> {auto ok : ()} -> Void
foo = ?foo_hole
result in the errors
ok is not a valid argument in bar
and
ok is not a valid argument in foo
respectively, because the auto-implicit is added during elaboration. For
instance, in the second example the left hand side of …

Don't add implicits after non-given explicits.

---

.ecrc
.github/workflows/ci-super-linter.yml

Example run with error:
[here](https://github.com/stepancheg/Idris2/runs/1718861440?check_suite_focus=true)
The downside is super-linter runs for 3 minutes. But that's probably expected
since the linter is [provided by GitHub](https://github.com/github/super-linter).
Two days ago when I submitted #931 I did not know super-linter exists.

Replace lint.py with super-linter

---

INSTALL.md

When trying to perform a self-hosting build, it will fail if you're not using `scheme`. This PR updates the docs with a command that succeeds when using `racket`.

adds command for self-hosting when using racket

---

bootstrap/idris2-boot

Before this commit the error was:
```
bootstrap/idris2-boot: line 15: --script: command not found
```

Explicitly handle empty SCHEME env var in bootstrap/idris2-boot

---

libs/base/Data/Nat.idr

I encountered a lack of this export in idris-lang/idris2#945
We might want to export more of these helpers as `public export`

libs: mark Data.Nat.lteAddRight as public export

---

libs/base/Data/List.idr
libs/contrib/Data/List/Palindrome.idr
libs/contrib/Data/List/Reverse.idr

There's probably an argument for not adding this directly to `base`, but when I first needed it I was a bit surprised it wasn't already in `base`, so here I am suggesting we add it.
This does overlap with `reverseReverseId` currently living in `contrib`, but that version is built up from other properties defined inside `contrib`'s `Data.List.Reverse` whereas this version only requires definitions currently in `Data.List`; an additional argument for inclusion in `base` is that this definition is not as clean (best I have figured) without access to `revOnto` which is not exported from `Data.List` so I ended up copying `revOnto` out of `base` just to create a proof that `reverse` is involutory in my own project.

Add proof that list reverse is involutive.

---

.github/linters/.ecrc

* `.ecrc` was in incorrect directory
* add another option for extra precaution
Tested on [this job](https://github.com/stepancheg/Idris2/runs/1742739559?check_suite_focus=true).

Disable indents check (properly this time)

---

libs/contrib/System/Console/GetOpt.idr
libs/contrib/contrib.ipkg

This adds an Idris2 port of the corresponding Haskell module [GetOpt](http://hackage.haskell.org/package/base-4.14.1.0/docs/System-Console-GetOpt.html) as discussed in #935.
Note: Since this uses its own implementation of `unzip3` internally, we probably should wait with merging this until after #972 is merged.

added System.Console.GetOpt to contrib

---

libs/base/Data/List.idr
libs/base/Data/List1.idr
libs/base/Data/Stream.idr

Unfortunately, I wasn't just able to reuse `Data.List.zip*/unzip*` on `Data.List1`'s tail due to the circular
module dependency error as `Data.List` already depends on `Data.List1`

Add zip*/unzip* for List1

---

libs/prelude/Prelude/Basics.idr
libs/prelude/Prelude/Ops.idr

After getting familiar with different kinds of function compositions, especially with the blackbird operator, I find myself using such things in almost every second module in my projects.
Blackbird operator is an operator similar to `(.)` but having a two-argument function on the right. It is convenient when combining a two-argument function and some post-processing. For example, instead of
```idris
f ls rs = unlines (zipWith (\l, r => map toUpper (trim (max l r))) ls rs)
-- or --
f ls rs = unlines $ zipWith (\l, r => map toUpper $ trim $ max l r) ls rs
```
you can write
```idris
f = unlines .: zipWith (map toUpper .: trim .: max)
```
which reads better, for those who are familiar with `(.:)` and its similarity to `(.)`.
This pattern of combining a two-argument and single-argument …

The blackbird operator (in the variant of `.:`) was added

---

src/Compiler/Scheme/Common.idr

Looks like it was just missing. The Int->Bits64 and Integer->Bits64
cases are identical, so casting back can also be identical.
I ran into this in some binary parsing code.

Add missing Bits64->Int cast

---

src/TTImp/ProcessType.idr
tests/idris2/interface019/expected

We can't just assume that a hint added in an empty environment is a global hint, because a top level definition might still have no local variables.

Local hints shouldn't be accessible globally

---

libs/base/Control/App.idr

Took me some time to figure out that `Void` means `IO`.
Express that knowledge more explicitly.

Control.App: use new type instead of Void as marker for I/O

---

.github/linters/.ecrc

Those files are part of tests and hold what should be the output of the
compiler. If they are included in the linting, warnings will be emitted
when one of the tests in which the compiler outputs a line with trailing
whitespace is edited, which is not desirable.
I ran into this in (#998): The output of the test interpreter/003 changed,
and I updated the "expected" file accordingly, but the linter issued a
warning due to a space character that the REPL outputs in that
sequence of interactions, while the character can't be removed without
breaking the test.

Exclude "expected" files from linting

---

libs/contrib/Test/Golden.idr
tests/Lib.idr

Adding support for C backend requirement in the test suite just like I
did when adding a test in #848.

[ contrib ] support for C backend

---

src/Idris/IDEMode/Parser.idr
src/Libraries/Utils/String.idr
src/Parser/Lexer/Source.idr
src/Parser/Rule/Source.idr
src/Parser/Support.idr
tests/Main.idr
tests/idris2/basic053/RawString.idr
tests/idris2/basic053/expected
tests/idris2/basic053/run

This PR proposed a new simple syntax for raw string, aka, the string literal with no escape.
For example, a template string that contains lots of quotes can be written in:
```idris
template : String
template = #"[project]
name: "project"
version: "0.1.0"
[deps]
"semver" = 0.2
"#
```
before:
```idris
template : String
template =  "[project]\n"
++ "name: \"project\"\n"
++ "version: \"0.1.0\"\n"
++ "\n"
++ "[deps]\n"
++ "\"semver\" = 0.2\n"
```

Support raw string

---

.editorconfig

Do not trim trailing whitespaces in `expected` files.
Some on them have trailing whitespaces: `rg ' $' -g expected`
reports 26 files.

editorconfig: trailing whitespaces in expected

---

.github/workflows/ci-super-linter.yml

Use the same trigger as in the rest of jobs.
Before submitting a PR, commit is pushed to a private branch where
the jobs are executed. Super-linter should be executed in these
jobs as well to get signal about linting issue before submitting a
PR, to reduce noise to PR reviewers.

Run super-linter in all branches

---

Makefile
tests/Makefile

At the moment we try to run the test suite even if the executable
does not even exist.

[ test ] check IDRIS2 exists & is executable

---

docs/source/tutorial/starting.rst

Doc linter now shows this as a warning in each PR

A tiny doc fix: heading line was not long enough.

---

libs/base/Data/IOArray.idr

There seems to be no apparent reason why this function hasn't been updated to MonadIO and later to HasIO with everything else, I'm guessing it was missed by accident.

Update IOArray.fromList to use HasIO

---

src/Compiler/RefC/RefC.idr
tests/Main.idr
tests/refc/refc002/RecordProjection.idr
tests/refc/refc002/expected
tests/refc/refc002/run

Fixes records (specifically '.' syntax) being unsupported with refc backend.

[ new ] support record projections in refc backend

---

libs/prelude/Prelude/Interfaces.idr

`Prelude` seems like a sensible spot for those instances.
Tell me if that needs changing.

Add named instances for functor & applicative composition

---

libs/contrib/Syntax/PreorderReasoning.idr
libs/contrib/Syntax/PreorderReasoning/Generic.idr

Small change to the multiplicity of the PreorderReasoning syntax. The implicit arguments were declared with omega multiplicity instead of zero leading to errors like this one:
```idris
foo : {0 a : Nat} -> a = a
foo = Calc $
|~ a
~~ a ...(Refl)
```
Which produced the following error:
```Error: While processing right hand side of foo. a is not accessible in this context.```
This change should align PreorderReasoning with the rewrite syntax which allows the use of zero arguments.

Change PreorderReasoning arguments to 0

---

libs/base/Decidable/Equality/Core.idr

This function is a complementary to existing function `decEqSelfIsYes` showing `decEq x x = Yes _`. I find the new function to be useful in places near to where the existing one is used.

A function from `Not (x = y)` to `decEq x y = No _` was added

---

libs/base/Data/Fun.idr
libs/base/Data/List/Views.idr
libs/base/Data/Nat/Order.idr
libs/base/Data/Stream.idr
libs/base/Data/Vect.idr
libs/base/Decidable/Equality/Core.idr
libs/contrib/Data/Nat/Factor.idr
libs/contrib/Data/Telescope/Segment.idr
libs/contrib/Data/Vect/Sort.idr
libs/contrib/Decidable/Decidable/Extra.idr
libs/contrib/Decidable/Order/Strict.idr
libs/contrib/System/Random.idr
libs/contrib/Text/Lexer.idr
libs/contrib/Text/Lexer/Core.idr
libs/contrib/Text/Parser.idr

Some useless matches of implicit arguments were removed (seemingly, left after porting from Idris 1). Useless `$`'s were removed where (arguably) they didn't give anything to readability. Identation was nicened in couple of places (while leaving it as it was in all the other places).
Changed code is mosly equivalent to the former except for two added `0`'s to `NonEmpty` auto arguments.

[base, contrib] Some cleanup

---

src/Idris/IDEMode/REPL.idr
src/Idris/REPL.idr

To match `:cd` command that accepts a double-quoted string

Use double quotes to display the current working directory

---

src/Core/Directory.idr

For some codegens it is useful to get access to the filename of a supporting data file instead of just the content of that file. For example, this is needed in the case where a subcommand is invoked which expects a path to the support file as argument.
This PR splits the "finding" and "reading" of the data file and exports both. The existing `readDataFile` function works the same as before and thus should not impact any existing code.

Extract findDataFile code from readDataFile and export it

---

libs/prelude/Prelude/Types.idr

`countFrom` must be made public accidentally:
* it is defined in the ranges section of the file, not stream section
* it is used only in `Range` implementation
* the same function `iterate` is defined in `Data.Stream`
```
countFrom start next
```
is the same as
```
iterate next start
```

Hide countFrom function from prelude

---

.github/linters/.ecrc
.github/workflows/ci-super-linter.yml
libs/base/System/File.idr
support/c/idris_file.c
support/c/idris_file.h
support/js/support_system_file.js
tests/Main.idr
tests/base/system_file001/ReadFilePage.idr
tests/base/system_file001/expected
tests/base/system_file001/input
tests/base/system_file001/run
tests/base/system_file001/test.txt

It's useful to be able to read files in within total code. I figured if I was adding a concept of fuel, I may as well add an efficient way to offset the start of the read operation.
I added tests (and caught a bug in my initial pass at the JS helper implementation so I am glad I did). As far as I could tell, this was the first base library test added.

Add a total way of reading files in.

---

libs/base/System/File.idr

As a fast follow to my previous PR that merged today:
I went to use `withFile` in `writeFile` and realized `withFile` could be made more ergonomic. More often than not (really, just about always), the thing you want to do with a successfully opened file can itself fail so I updated the signature of the `onOpen` function to allow for errors and things got a whole lot nicer.
Note that `withFile` was totally new as of today, so I don't feel bad about breaking it immediately. I do feel a bit embarrassed though 😊.

withFile & writeFile cleanup

---

libs/contrib/Data/String/Position.idr
libs/contrib/contrib.ipkg

This is an alternative to using `fastUnpack` and `fastPack` to work
on lists of characters.
Using this to refactor the lexer and benchmarking the resulting
compiler on building idris2 shows it's 3 to 5s slower than the
current implementation that goes via `List Char`.
This may be backend-dependent so I still push this to contrib,
with the plan of running further benchmarks in the future.

[ contrib ] Positions in strings

---

src/Idris/Parser.idr
tests/Main.idr
tests/idris2/basic044/Term.idr
tests/idris2/basic044/Vec.idr
tests/idris2/interactive028/expected
tests/idris2/interactive028/input
tests/idris2/interactive028/run
tests/idris2/positivity002/Issue660.idr
tests/idris2/positivity003/Issue660.idr
tests/idris2/with003/expected

(as well as in type signatures now that I know how to do that)
Also taking this opportunity to fix the historical mistake of parsing
`logging` arguments as qualified names (which meant you couldn't use
reserved keywords like `"with"` as logging topics...)

[ re #1087 ] Better error messages in the REPL

---

libs/contrib/Test/Golden.idr
tests/Lib.idr

I discovered that the prompt for updating expected values did not work when the expected file was not found -- it just asked for "y/n" and then immediately exited without an opportunity to choose!
It turned out is was just an indentation bug causing the required code for reading in a response to only get run under one of the two paths.

fix Golden so that prompt is run after both paths where expected and actual outputs don't match.

---

libs/base/Language/Reflection/TT.idr

Added some brief comments describing the nature of `FilePos` and `MkFC` in `Language.Reflection.TT.idr`.
(Please yell out if these aren't correct!)

Added comment descriptions for FC and FilePos.

---

libs/base/Data/Zippable.idr

Since `(a, b, c)` is the same as `(a, (b, c))`, this allows for chaining `zip` in a nice-looking way:
```idris
zipFour : List a -> List b -> List c -> List d -> List (a,b,c,d)
zipFour x y z w = x `zip` y `zip` z `zip` w
```
I chose `infixr 6`, since that seemed reasonable enough to me, but I'm open to suggestions for a better precedence.

Make `zip` usable infix 

---

libs/base/Data/DPair.idr

This allows transform e.g. proof-carrying easier. For instance, instead of writing something like
```idris
let Element a b = fn x in Element (S a) (LTESucc b)
```
we could write
```idris
bimap S LTESucc $ fn x
```
which seems to read better.

[base] `bimap` functions were added for dependent pairs.

---

libs/base/Control/App.idr

App1 is not a monad, and was missed in the change to desugaring of non-binding sequences.
This fixes that.

Give App1 implementation of (>>)

---

libs/base/Language/Reflection/TTImp.idr
src/Core/CaseBuilder.idr
src/Core/Core.idr
src/Core/Coverage.idr
src/Core/TT.idr
src/TTImp/Elab/App.idr
src/TTImp/Elab/Dot.idr
src/TTImp/Reflect.idr
tests/Main.idr
tests/idris2/casetree001/IsS.idr
tests/idris2/casetree001/Issue762.idr
tests/idris2/casetree001/expected
tests/idris2/casetree001/run
tests/idris2/error014/expected

Make sure that any under-applied constructor on the LHS is forced
by another pattern somewhere.
Do NOT split on a pattern just because it is constructor-headed:
start by making sure that the pattern is fully applied.
This is valid for both type and data constructors!

[ fix #762 ] Different case tree building strategy

---

libs/prelude/Prelude/Ops.idr

After `>>` started to be widely used for monads, is was added as `infixl 1`, but the older (and unused) definition as `infixl 7` left in the same file. Let's remove unused and immidiately overridden definition of `infixl 7` (also with undefined elsewhere `<<` operator).

[ prelude ] Strange definition of different priorities for a single operator was removed

---

CHANGELOG.md
docs/source/reference/envvars.rst
src/Core/Context.idr
src/Core/Options.idr
src/Idris/Driver.idr
src/Idris/Env.idr
src/Idris/SetOptions.idr

Whenever we look for things in some default places, we should give the option to look in other places. I expect some package managers will find this useful.
Also added the list of recognised environment variables to the docs.

Add IDRIS2_PACKAGE_PATH environment variable

---

support/c/idris_directory.c

Change the support code for directory creation so that it sets all
permission bits (ugo=rwx). The process's currently active umask will be
subtracted from these permissions, which leads to the result that (for a
standard umask of "022") directories are created with a mode of "0755".
So by default, directories created with `prim__createDir` are now also
group-executable and other-executable by default.
Previous behaviour was to create the directories readable for group and
other, but not executable (mode "744"), and thus inaccessible to anyone
except the owner.

Better default permissions for created directories

---

libs/base/Data/List.idr
libs/base/Data/List1.idr
libs/base/Data/Stream.idr
libs/base/Data/Vect.idr

Rewriting rules for `index i (zipWith ...)` were added for `Vect` and `Stream`.
Also, implementations of `Zippable` were made to be publicly exported (actually, some of them were originally `public export` and were dispublished when introducing `Zippable`).

[ base ] A property of interaction between `zipWith` and `index`

---

libs/contrib/Data/Fin/Extra.idr

Actually, zero quantity of the bound argument can be done with `weakenLTE` too, in case when the type of the argument would be changed from `LTE` to `LT`, i.e. if signature would be strengthened a bit, but I'm not sure whether it should be done.

[contrib] Existing `natToFinLTE` was reimplemented to have zero-quantity for `LT` argument

---

docs/source/reference/envvars.rst

New github linter found this and warns in every PR

[ doc ] Orphaned `todo` block was removed

---

src/Core/UnifyState.idr
src/Idris/ProcessIdr.idr
src/TTImp/Elab.idr
tests/Main.idr
tests/idris2/reg037/Test.idr
tests/idris2/reg037/expected
tests/idris2/reg037/run

Fixes #1140 - when checking holes were solved, we checked all of them,
but there may still be some open if there's a local definition.

Check current holes only at end of elaboration

---

src/Core/UnifyState.idr
src/TTImp/Elab/Delayed.idr
tests/Main.idr
tests/idris2/interface024/EH.idr
tests/idris2/interface024/expected
tests/idris2/interface024/run

We might not have set up search problems yet when delaying an elaborator, so we need to know what the local hints were at the point of delay.

Record local hints in delayed elaborators

---

libs/base/Data/List.idr
libs/contrib/Data/Elem/Extra.idr

Some lemmas that show appending doesn't impact on a proof that
an element is a member of a List.

[ new ] Lemmas: append preserves List membership.

---

docs/source/reference/overloadedlit.rst
docs/source/reference/packages.rst
docs/source/updates/updates.rst

I tried to use the new (great) facility of `depends` subdirectory and found that it's not clear from the documentation that subdirectories in the `depends` folder should point to a directory with TTC files, not to one with an appropriate `ipkg`-file. I tried to clarify gthis in the documentation.

[ doc ] Documentation of package lookup was clarified a bit

---

libs/contrib/Data/SortedMap.idr
libs/contrib/Data/SortedSet.idr

This just adds some missing implementations. In case of `Eq` instances, this goes via `toList`, so two sorted maps with different `Ord` implementations might still be considered equal if they return their key-value-pairs in the same order.

[new] Additional Eq and Show implementations for SortedMap and Set

---

libs/contrib/Data/List/AtIndex.idr
libs/contrib/Data/OpenUnion.idr

The previous approach could only work with type families. This
should be fully generic. Potential users of the previous scheme
can change `Union ts v` to `Union ($ v) ts`.

[ refactor ] generalise open union machinery

---

libs/base/Data/DPair.idr

Since `Subset` is highly useful as a refinement type (especially when working with primitives), it is convenient to have implementations for the core interfaces `Eq`, `Ord` and `Show`. The `Show` implementation replaces the erased invariant with an underscore.

[ new ] Interface implementations for Subset

---

src/Core/AutoSearch.idr

The function `searchLocalHints` introduced in #878 was never used in code, probably due to a typo.
At the same time the test case from that PR has been passing the type-checker.
Since `searchLocalHints` was the only logical novelty of that PR, we can revert it, eliminating the dead code.
The work of properly reducing local hints during auto-search that was supposed to be done by `searchLocalHints` is already done elsewhere, presumably in `TTImp.Elab.Check.searchVar`, by inserting the local definitions into the local environment as (reducible) `let` binders.

Revert #878 (the test stays put)

---

src/Idris/Resugar.idr
tests/idris2/linear002/Door.idr
tests/idris2/linear002/expected

Previously constructors which clashed with some builtin constructors
would get resugared incorrectly. `Nil` and `::` still get resugared
outside of the builtin namespace, allowing list syntax for different
types.
The linear002 test now expects and uses Unit explicitly, rather than
relying on this behaviour.
Fixes #634

Namespace checks for resugaring

---

libs/contrib/Data/Validated.idr
libs/contrib/contrib.ipkg

This is, in fact, an error-accumulating flavor of `Either`.
It is intended to be used for applicative data creation (e.g. with idiom brackets like `[| MkData validatedF1 validatedF2 ... validatedFn |]`) where each component can be checked and as a result no failed checks should lost.
This kind of structures is usually named `Validation` or `Validated` and I chose the latter because 1) to my feeling the first one describes a process rather than a processed data 2) we already have a module named `Validation` (in `Control`) describing composable effectful processes of validation.

`Validated` data structure was added

---

libs/contrib/Data/Validated.idr

A confusing thing: PR #1098 was checked as OK with CI some time ago, before the changes in the standard library. Then, the signature of the `Alternative` changed but CI wasn't rerun, thus this was merged and failing in the `master` now.
This fixes it.
I decided to repeat the implementation in order to get an advantage of the second lazy argument to be not evaluated when the first one is `Valid`

[ fix ] Change one implementation according to recent lib change

---

src/Core/Binary.idr
src/Core/Context.idr
src/Core/Options.idr
src/Core/TTC.idr
src/Idris/Desugar.idr
src/Idris/Parser.idr
src/Idris/Syntax.idr
src/TTImp/Elab/Ambiguity.idr
tests/Main.idr
tests/idris2/basic056/DoubleLit.idr
tests/idris2/basic056/expected
tests/idris2/basic056/input
tests/idris2/basic056/run

So far, there seems to be no way to overload floating point literals. I thought they might be useful, so this PR adds a new `%doubleLit` pragma. I added a test case and it seems to work OK, but I still might have overlooked something, so please review carefully.

[ new ] Support overloaded floating point literals

---

src/Core/Context.idr
src/Core/TT.idr
src/Idris/REPL.idr

* allow non-Pi types as search targets
* do not return defs whose type is `Erased`
* do not return private definitions

[ fix #1193 ] Fine tune REPL's typesearch

---

src/Idris/IDEMode/Holes.idr
src/TTImp/BindImplicits.idr
src/TTImp/Elab/ImplicitBind.idr
src/TTImp/Elab/Local.idr
src/TTImp/ProcessDef.idr
src/TTImp/TTImp.idr
tests/Main.idr
tests/idris2/interactive020/expected
tests/idris2/interactive029/Issue834.idr
tests/idris2/interactive029/expected
tests/idris2/interactive029/input
tests/idris2/interactive029/run

When we are considering a local definition, the elaborated type has an
extra telescope of explicit arguments that correspond to the variables
bound in the parent function.
These get in the way of the work done by `implicitsAs` which makes us
miss out on some implicit arguments that ought to have been automatically
bound. #834 was but a symptom of this much deeper problem.

[ fix #834 ] Fix implicitsAs for local definitions 

---

libs/base/Data/Fin.idr
libs/base/Data/Vect.idr

All the other `DecEq` implementations already are `public export` and this gives us an ability to use `decEq` in type-level expressions and those expressions to be reduced when needed. We lack this now for `Fin`s and `Vect`s.

[ base ] DecEq implementations of Fin and Vect were exported publicly

---

src/Idris/Parser.idr
src/Libraries/Text/Parser/Core.idr
src/Parser/Rule/Source.idr
tests/Main.idr
tests/idris2/perror008/Issue710a.idr
tests/idris2/perror008/Issue710b.idr
tests/idris2/perror008/Issue710c.idr
tests/idris2/perror008/Issue710d.idr
tests/idris2/perror008/Issue710e.idr
tests/idris2/perror008/Issue710f.idr
tests/idris2/perror008/expected
tests/idris2/perror008/run

Given we keep getting tripped up by this, here we go:
* Namespaces
* Data names
* Record names
* Data constructor names (except for operators)
* Record constructor names (except for operators)
* Interface constructor names (except for operators)

[ fix #710 ] Enforce assumptions about capitalised idents

---

libs/contrib/Data/Fun/Graph.idr
src/Core/Binary.idr
src/Core/TT.idr
src/Core/Unify.idr
src/Idris/Desugar.idr
src/Idris/Elab/Implementation.idr
src/Idris/Elab/Interface.idr
src/Idris/Parser.idr
src/Idris/Pretty.idr
src/Idris/REPL.idr
src/Idris/Resugar.idr
src/Idris/Syntax.idr
src/Parser/Lexer/Source.idr
src/TTImp/Elab/Case.idr
src/TTImp/Elab/Quote.idr
src/TTImp/Interactive/GenerateDef.idr
src/TTImp/Parser.idr
src/TTImp/ProcessDef.idr
src/TTImp/Reflect.idr
src/TTImp/TTImp.idr
src/TTImp/Utils.idr
tests/Main.idr
tests/idris2/perror004/expected
tests/idris2/with005/Issue893.idr
tests/idris2/with005/WithProof.idr
tests/idris2/with005/expected
tests/idris2/with005/run

All the scoping-related work is isolated in `bindWithArgs` so hopefully
it won't be too much work to extend this to multiwith.
Had to fix an unrelated bug in `Core.Unify` to get this through!

[ fix #893 ] `proof` gadget for `with` clauses

---

src/Idris/Parser.idr
src/Parser/Rule/Source.idr
tests/Main.idr
tests/idris2/basic058/DataTypeOp.idr
tests/idris2/basic058/DataTypeProj.idr
tests/idris2/basic058/expected
tests/idris2/basic058/run

#1207 made less ambiguity but I think it was too restrictive. Previously, we were able to define our `data` named as operators and this was handy for custom type-level relations. #1207 restricted us to use only letter names for that. I suggest to relax this and to add an ability to define data types as operators, as it was possible before.
Originally, I invented and used analogue to `opNonNS` but without ability of projections, but later I found that the current interfaces are allowed to be named (besides all) as projections. Thus for consistency, I made data types to have the same rules as data constructors.
So, only `data` and `record`s are affected, but test were added for `interface`s too, just to fix the status quo.

Restore the ability for data types to be operators

---

src/Core/Directory.idr
src/Idris/Driver.idr
src/Idris/ModTree.idr
src/Idris/Parser.idr
src/Idris/ProcessIdr.idr
src/Parser/Rule/Source.idr
src/Parser/Source.idr
src/Parser/Support.idr
tests/chez/chez031/expected
tests/idris2/import004/expected
tests/idris2/perror008/Issue1224a.idr
tests/idris2/perror008/Issue1224b.idr
tests/idris2/perror008/expected
tests/idris2/perror008/run

Had to do a bit of digging to get nice error messages.
I have decided to not reject files with a lowercase name and no
`module` declaration. They are implicitly declared as a `Main`
module and you simply won't be able to import them.

[ fix #1224 ] moduleIdent must be capitalised 

---

libs/base/Data/List/Quantifiers.idr
libs/base/Data/Stream.idr
libs/contrib/Data/Path.idr
libs/contrib/contrib.ipkg

I've added `Data.Path` because I keep copypasting it around and it seems generic enough, also Agda has it in the stdlib.
Also, exported publicly `List.Elem.indexElem` (I needed to access its structure in a logrel proof) and simplified `Stream.nats`.

Add Path@contrib & small changes

---

libs/contrib/contrib.ipkg

Add a missing module to `contrib.ipkg`.

Add Data.Monoid.Exponentiation to contrib.ipkg

---

libs/base/Data/String.idr

I am working on an algorithm, which generates several tens of thousands lines of Idris2 code. Replacing all occurences of `unlines` with `fastUnlines` as presented in this PR, brought the running time down by two orders of magnitude (from > 50 s to < 0.5 s on my system). I therefore thought this might be useful for others as well.

[ performance ] add fastUnlines to base

---

Makefile

1. Fixes an error in stage2 of `make bootstrap-racket`. Reproducible if Chez is not available as 'scheme' and IDRIS2_CG is not exported in environment / not passed to make.
2. Use the same shell as Make, allowing it to be be overridden.

[ fix ] bootstrap-stage2: IDRIS2_CG not set correctly

---

libs/prelude/Builtin.idr
libs/prelude/Prelude/Ops.idr

Lower the precedence of `(===)` and `(~=~)` to match that of `==` (6). 
With the tuned precedence, arithmetic operators `(+)`, `(*)`, etc. behave as one would expect when combined with propositional equality. Examples of impacted expressions:
- `2 + 2 === 4` now parses as `(2 + 2) === 4`
- `2 :: Nil === [2]` now parses as `(2 :: Nil) === [2]`
- `[1, 2] ++ [3, 4] === [1, 2, 3, 4]` now parses as `([1, 2] ++ [3, 4]) === [1, 2, 3, 4]`
Also `(<+>)` is made to bind as tight as `(+)` (precedence 8).
None of the builtin operators seem to be negatively impacted by the change.

Tune precedence of (===), (~=~) and (<+>)

---

libs/base/Data/Nat.idr
libs/contrib/Data/Nat/Division.idr
libs/contrib/Data/Nat/Properties.idr

This has a much better behaviour with respect to proof search and
the coverage checker realising we don't need to consider the Z case
than the `Not (x = Z)` we used earlier.

[ refactor ] introduce NonZero

---

src/Compiler/RefC/RefC.idr

Use unicode escapes. Insert trailing doublequotes to terminate (otherwise hexchars will be considered part of escape)
What remains to do now is missing primitive functions.

Fix escaping in C backend

---

Makefile
src/Core/Context.idr
src/Core/Options.idr
src/Core/Unify.idr
src/Idris/Desugar.idr
src/Idris/Parser.idr
src/Idris/Syntax.idr

If they're big, they take a long time to instantiate, and if they
consist of a lot of functions, chances are that normalising them will
make them much smaller. This significantly improves type checking
performance for some programs with lots of type level computation going
on.
The threshold is set with %nf_metavar_threshold, but the default value
of 50 is probably fine. Set it to 0 to always normalise metavar
solutions, or something higher than 1000 to essentially never do it.
It's roughly a count of nodes in the typechecked syntax tree under the
first function application.

Add heuristic for when to normalise metavars

---

src/Core/LinearCheck.idr
tests/Main.idr
tests/idris2/reg039/dupdup.idr
tests/idris2/reg039/expected
tests/idris2/reg039/run

The scope should be checked at the same multiplicity as the enclosing expression.

Use correct multiplicity in scope of lets

---

README.md

At the moment readme badges point to ancient unupdated workflows and remain green even if the current `master` is failing. This PR updates those badges to point to the current workflows after their rework couple of months ago.

Update readme badges to point to the currently relevant workflows.

---

src/Idris/Package.idr

Currently, `idris2 -p contrib --build mypkg.ipkg` enters the REPL, while ` --build mypkg.ipkg -p contrib` fails with an error. This PR makes both instances fail.
I also priveledged some REPL options to silently pass through package commands like `--build`, so users can alias idris2 with `--no-banner --no-colour`.

Ignore some REPL options in package commands

---

libs/contrib/Control/Linear/LIO.idr
libs/network/Control/Linear/Network.idr

1) Fix a leak in `Control.Linear.Network.accept`, where it returns a `Res` with an unrestricted pair as its second component.
This bug is probably a consequence of removing multiplicity subtyping & tweaking default data type multiplicities to unrestricted throughout the code base.
2) Expose the socket errors to the user as they _are_ helpful when one of the operations on sockets fails.

Fix a linearity leak in network; expose error codes to the user

---

libs/test/Test/Golden.idr
src/Compiler/Common.idr
src/Compiler/ES/Node.idr
src/Compiler/Scheme/Chez.idr

Move pathLookup to Compiler.Common and use it on Node.

Use file extensions when looking for exes on windows

---

src/Idris/Package.idr

As noted in #1250, Idris can only handle one package command at a time. This PR allows multiple in sequence.

Multiple build commands

---

Makefile
tests/idris2/pkg002/run

Rather than tracking how far we are from the project root in the various
Makefile commands, it's much easier to reference the build target with
with an absolute path.
This was going to be a part of a bigger PR, but I ended up not needing it there.

Use absolute path to pass around Idris2 executable

---

libs/network/Network/FFI.idr
libs/network/Network/Socket/Raw.idr
support/c/idris_net.c
support/c/idris_net.h
tests/chez/chez014/Echo.idr
tests/chez/chez014/expected

This change adds logic to set up `sockaddr` correctly for connect and
bind, handles the `AF_UNIX` case for `getSockAddr` and adds a test for unix
sockets.
Mingw-w64 seems to be missing the `afunix.h` header even though windows does support unix sockets, so I've added the structure manually but I might be missing something. It looks like CI only builds windows but doesn't test it, should it be? Can add if so.

Fix issues with use of unix sockets

---

libs/contrib/contrib.ipkg

Add 3 missing modules to contrib.ipkg (`Data.Nat.Exponentiation`, `Data.Num.Exponentiation` and `Data.Rel.Complement`) and add tweak formatting to separate unrelated modules.

Add missing modules to contrib.ipkg

---

src/TTImp/ProcessDecls.idr
src/TTImp/ProcessDef.idr

This is a noisy update to the information reported by `--timing`. 
Recent work of mine has suggested bottlenecks with compilation are in the totality checker. The Issue tracker has seen related issues, for example see #1277. 
Although noisy, the output can be grepped away giving the structure in the logs.

Report time taken to check totality.

---

Makefile
nix/package.nix
nix/test.nix
tests/tests.ipkg

*As I understand the way Idris2 reads paths*, this solves #934.
All CI appears to run correctly and fail correctly, including the new (to us) `checkPhase` in Nix.
`make bootstrap-test` works as I expect, but I don't know how to make it fail without either a) deleting one of the packages I tell it to look for, or b) breaking a test case so `make test` also fails.
---
As a rough summary, currently, `make test` reads `~/.idris2/idris2-${VERSION}/` to see what packages are available, then imports packages preferentially through the local paths.
By setting IDRIS2_PREFIX to a dir containing symlinks to those files instead, we bypass the need to have packages installed. This allows us to run `make test` without having a `~/.idris2`, and lets us use nix for the full test suite*.
The `make …

Hermetic tests

---

idris2api.ipkg
src/Compiler/RefC/CC.idr
src/Compiler/RefC/RefC.idr

Expose the RefC code for compiling CC object files and executables, and add the option to compile them as libraries.
This should result in no behavioural changes to the RefC backend. I'm exposing these functions to enable other backends to make use of them, such as Python.
I wasn't able to run `make install-api` on `master`, so this branch is instead based off the most recent tag (`v0.3.0`). From a quick glance, it appears the only merge issues are a matter of `import`s, but I'm not able verify if any particular solution is correct.

Shared C codegen

---

libs/contrib/Data/String/Extra.idr
libs/contrib/Language/JSON/Data.idr
libs/contrib/Language/JSON/String/Tokens.idr
tests/Main.idr
tests/contrib/json_001/CharEncoding.idr
tests/contrib/json_001/expected
tests/contrib/json_001/input
tests/contrib/json_001/run

JSON encoding and decoding of escaped unicode characters in contrib is broken in several ways. Here's the fix plus a test.
As an aside: Whoever implemented the erroneous version was working under the assumption that the `Cast` implementation from `Int` to `String` would behave correctly for hexadecimal strings, i.e. that the following would hold: 
```idris
the Int (cast "0x2") = 2
```
This doesn't work, though. Whether this is yet another bug, I do not know.

[ fix ] broken unicode parsing in JSON

---

libs/contrib/Text/PrettyPrint/Prettyprinter/SimpleDocTree.idr
src/Libraries/Text/PrettyPrint/Prettyprinter/SimpleDocTree.idr

When flattening the `SimpleDocTree` created from a `SimpleDocStream`, the
first part of a concatenated doc is sometimes dropped, depending on the
result of the recursive call to `flatten`.
Can be reproduced by:
`idris2 -p idris2` (Same bug is in corresponding module in `contrib`):
```idris
:module Libraries.Text.PrettyPrint.Prettyprinter.Doc
:module Libraries.Text.PrettyPrint.Prettyprinter.SimpleDocTree
fromStream $ SText 5 "first" (SText 6 "second" SEmpty)
```
Current result: `STText 6 "second"`
Result after this fix: `STConcat [STText 5 "first", STText 6 "second"]`

PrettyPrint: Fix SimpleDocTree.fromStream dropping parts of documents

---

libs/prelude/Prelude/Cast.idr

Add an implementation for `Cast a a` for a more comfortable use of `Cast` interface in implementation of functions, independent of exact input type.

Add identity cast

---

src/Idris/Parser.idr
src/Idris/REPL.idr
src/Idris/Syntax.idr

`:ti` does the same thing as `:t`, but shows the type as if `showimplicits` were set. The value of `REPLOpt.ShowImplicits` is unchanged.
`:opts` shows the current values of the options that can be set or unset with `:set`/`:unset`. (This already existed in `REPLCmd.GetOpts`, idk why it just wasn't in `Parser.parserCommandsForHelp`.)
I can add to or change the names of the commands; I don't think `:t+` can be parsed, and I don't know if we also want a `:typei`?
Also fixed the spacing of the help message.

[ REPL ] Added commands :ti and :opts (#1241)

---

src/Idris/DocString.idr
tests/idris2/docs001/expected
tests/idris2/interactive030/expected

I noticed that e.g. List's (::) was not printed correctly in `:doc`
so here's a fix.

[ fix ] print infix operators with parens

---

src/Idris/REPL.idr

There was a typo (made by myself 😭) in `Idris.REPL.findInTree` which selects the best result while searching in the metadata `PosMap` of names, this led to some edge cases where it did not select the best answer.

Fix for wrong search results in the metadata name PosMap

---

idris2api.ipkg
src/Idris/REPL.idr

This creates an `inferAndNormalize` function in `Idris/REPL.idr` that, given an evaluation mode and a `PTerm`, produces the term's type, its normal form, and the resugared version of its normal form. The idea is that other REPL commands and IDE actions, like refining a hole, will likely need this information, so the functionality can be shared.

[ refactor ] type inference and evaluation for the REPL

---

CHANGELOG.md
docs/source/backends/index.rst
idris2.ipkg
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Racket.idr
src/Core/Options.idr
src/Idris/CommandLine.idr
src/Idris/IDEMode/REPL.idr
src/Idris/Parser.idr
src/Idris/REPL.idr
src/Idris/SetOptions.idr
src/Idris/Syntax.idr

If set, when compiling this generates an executable which generates
profiling data. Currently supported by Racket and Chez, other backends
silently ignore it.

Add --profile flag

---

libs/base/Data/String.idr
libs/prelude/Prelude/Types.idr
src/Core/Context.idr
src/Core/Context/Log.idr
src/Core/Normalise.idr
src/Core/Options.idr
src/Core/Options/Log.idr
src/Core/UnifyState.idr
src/Idris/SetOptions.idr
src/TTImp/TTImp.idr
tests/idris2/coverage015/expected

A couple of changes that make Idris typecheck faster, and will be useful in general:
* Use the `%transform` syntax to pick fast runtime versions of things where possible. This isn't documented properly yet (or, I think, at all) so I'll get to that later. It's basically rewrite rules of the form `%transform "label" lhs = rhs` where `lhs` is a function application with variable names, and `rhs` is what it rewrites to.
* Add a flag to check when any logging has been enabled, so we only have the overhead of checking the categories if we're actually logging. The above change does make logging faster, but this makes it cheaper still.
On my machine, checking the Idris 2 source (with `--check`) is now done in around 1m26 (down from 1m45) on the current code base.

A couple of optimisations

---

libs/contrib/Data/List/Lazy.idr
libs/prelude/Prelude/Interfaces.idr
tests/Main.idr
tests/idris2/lazy002/LazyFoldlM.idr
tests/idris2/lazy002/expected
tests/idris2/lazy002/input
tests/idris2/lazy002/run

Sometimes I find myself wanting to switch from usual to lazy lists and missing some functions.
Also, the usual implementation of `foldlM` through `foldl` is very bad for shortcutting monads used with the lazy list. That's why I suggest to move `foldlM` inside the `Foldable` interface to make an effective specialised implementation to be definable. A test for that is included.

[ contrib ] Some functions for lazy list + fix for `foldlM`

---

src/Compiler/LambdaLift.idr
src/Core/Core.idr
src/Idris/Package.idr

This is my attempt at dropping unused variables during the "LambdaLift" compilation phase, which reduced the generated "lifted defs" for at least one real-world example (Idris 2 itself) by about 35%.
Usage bookkeeping is currently done via a `Vect n Bool` but could theoretically be moved to an IOArray (all the usage tracking code is in `Core`). In practice it turns out not to matter that much, since lambda lifting takes only about 1 sec for all of Idris 2 (as opposed to 0.9 secs without the usage bookkeeping).

Lambdalift optimisation: drop unused variables from outer scopes

---

docs/source/tutorial/interfaces.rst

As of  #1095 do syntax desugars using both `>>=` and `>>`, and this wasn't mentioned in the docs.
Took me a little bit to notice that change when trying to use do syntax with something that had only implemented `>>=`.

Update docs to reflect usage of >> in do syntax

---

src/Idris/Doc/HTML.idr
support/docs/styles.css

This includes fixes for the layout (weird indentation and missing spaces) in WebKit based browsers (e.g. Chrome mentioned in #1367), and a small fix to correctly escape operator names and text included in docstrings.

Some tiny HTML doc fixes (including a fix for #1367)

---

src/Idris/Package.idr
tests/idris2/pkg003/expected

The `--directive` flag is generally used to pass extra arguments/options to the code generator, since the codegen can be overridden for pkg opts, this should be allowed as well.

Allow `--directive` command line flag combined with package options

---

src/Idris/Doc/HTML.idr
src/Idris/DocString.idr
support/docs/styles.css
tests/idris2/docs002/Doc.idr
tests/idris2/docs002/expected
tests/idris2/docs002/input

Data constructor docstrings where not wrapped in a `<dd>` tag, and therefore
where not indented correctly.
As a relict of the REPL output, several `<br>` tags where introduced,
where they are not needed or even permitted. This led to some spacing
issues (sometimes the docstring was closer to the next term than to the
one above that it actually described).
To counter the removed forced newlines, some extra margin is added below
each declaration.
As a side-effect, this also makes the W3 "Nu Html Checker" happy (at least for _some_ pages ;)

[ docs ] Improve HTML Output

---

src/Compiler/Common.idr
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Gambit.idr
src/Compiler/Scheme/Racket.idr

Instead of taking the first applicable string, the backends submit an
ordered list of preferred prefixes and get the first match.

Choose foreign string based on priority

---

src/Core/Context/Log.idr
src/Core/Core.idr
src/Core/Normalise.idr
src/Core/Options/Log.idr
src/Core/Unify.idr
src/Core/UnifyState.idr
src/Idris/IDEMode/Holes.idr
src/Idris/ProcessIdr.idr
src/TTImp/Elab/RunElab.idr
src/TTImp/ProcessTransform.idr
src/TTImp/TTImp.idr
src/TTImp/WithClause.idr

This adds a type level check to most log calls to make sure that only known logging topics are used. Exceptions are allowed when topics are coming from client code, for instance during elab reflection.
The list of logging topics is now provably exhaustive (see also discussion in #1397), but the topics are not yet documented, nor is there any functionality for pretty printing all known topics.

[ towards #1124 ] Statically enforced logging

---

libs/base/Language/Reflection.idr
libs/base/Language/Reflection/TT.idr
libs/base/Language/Reflection/TTImp.idr

As soon as I have a total function that uses `Elab`'s monadic stuff, it's sad that totality checker is unsatisfied.
The original implementations could be preserved but with totality assertions, so why not to inline it all to have an equivalent implementation that satisfies the totality checker?

[ totality ] Make `Language.Reflection` modules have `%default total`

---

src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Racket.idr
tests/Makefile
tests/base/system_info001/run

Just a few small changes are required to enable building and installing on FreeBSD. The code then passes all tests on my machine.
For successful bootstrapping, the bootstrap code would need to be updated as well (built by the new compiler version). I think this can be done in a later PR (or just the next release).
The most "invasive" thing of this PR is the special-casing of "libc" FFI for the Racket backend, as it changes the codegen on all OSs. But I'm quite convinced, that this is the correct thing to do, as stated by the Racket documentation ([The Racket Foreign Interface > Loading Foreign Libraries](https://docs.racket-lang.org/foreign/Loading_Foreign_Libraries.html#%28def._%28%28lib._ffi%2Funsafe..rkt%29._ffi-lib%29%29)) (emphasis mine):
> If path is #f, then the resulting …

Some small changes to get Idris 2 working on FreeBSD

---

src/Core/Normalise.idr
src/Core/Unify.idr
src/Core/UnifyState.idr
src/Core/Value.idr
src/Idris/ProcessIdr.idr
src/TTImp/Elab.idr
src/TTImp/ProcessDef.idr
tests/ttimp/basic003/expected
tests/ttimp/basic006/expected
tests/ttimp/coverage002/expected
tests/ttimp/eta001/expected
tests/ttimp/eta002/expected

We stored them as equations between terms, I think because terms are easy to re-evaluate with new information, and because I thought we might want to save them out. It's not usually a problem to do that. However... Going back and forth between terms and values can be expensive if we're stuck in the middle of a complicated unification problem, the like of which can turn up a lot if your types are complicated. So, we need to be able to handle this.
Now store the postponed problems as NF, rather than Term, and add a function to resume evaluating a NF with an updated context.

Store postponed unification problems as values

---

src/Core/CaseBuilder.idr
src/Core/Normalise.idr
src/Core/Unify.idr
src/Core/UnifyState.idr
src/Core/Value.idr
src/TTImp/Elab/App.idr

Actually one of them is more of an un-pessimisation, given the new way we store postponed unification problems. They are:
* reduce a few calls to ++ (tiny but I did it anyway)
* don't calculate blocked metavariable set, since it takes way longer than just resuming the problem with the new representation of postponed problems

A couple of small optimisations

---

src/Core/Unify.idr
src/TTImp/ProcessDef.idr

I assume `toFullNames` is injective?

[ perf ] Move unnecessary `toFullNames` calls under a `logC`

---

src/Core/Binary.idr
src/Core/TTC.idr
src/Libraries/Utils/Binary.idr

Write small integers out as 1 byte, not 8, at the cost of writing larger integers out in 9 bytes. Most integers fit in 1 byte, since it's string and list lengths from user-written code.

Substantial reduction in TTC size

---

src/Idris/Desugar.idr
tests/Main.idr
tests/idris2/error018/Issue1031-2.idr
tests/idris2/error018/Issue1031-3.idr
tests/idris2/error018/Issue1031-4.idr
tests/idris2/error018/Issue1031.idr
tests/idris2/error018/expected
tests/idris2/error018/run

Does not currently fix the fact that metavariables may be solved in the body of a
let-binding so the workaround using `.(_)` is unfortunately still accepted.

[ re #1031 ] Disallow `?` patterns on the LHS

---

src/Core/Context/Log.idr
src/Core/Normalise.idr
src/Core/Options/Log.idr
src/Core/UnifyState.idr
src/TTImp/TTImp.idr

Cleanup repeated code in `Core.Context.Log` and add functions to get if a specific log level is enabled.
This could be useful for backend authors, so external tools can be told how much to log.

[ cleanup ] logging

---

INSTALL.md
README.md
docs/source/tutorial/starting.rst
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/ChezSep.idr
src/Compiler/Scheme/Racket.idr
support/refc/prim.c
tests/chez/chez016/run

EDIT: 
In addition to #1418 remove `realpath` usage leftovers.
I left the `realpath` requirement in `INSTALL.md` so bootstrapped compiler could still work.

Remove realpath

---

src/Compiler/CompileExpr.idr
src/Compiler/RefC/RefC.idr
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Gambit.idr
src/Compiler/Scheme/Racket.idr
src/Core/Binary.idr
src/Core/CompileExpr.idr
src/Core/Hash.idr
src/Core/TTC.idr

As mentioned on [discord](https://discord.com/channels/827106007712661524/827109161857712128/844065173756837930) I'm not sure I used the correct type names in the Scheme backends and in the RefC backend these int types are not supported and fail with a crash.

[ FFI ] Support new IntX types in foreign function types

---

libs/base/System.idr
libs/base/System/Signal.idr
libs/base/base.ipkg
support/c/idris_signal.c
support/c/idris_signal.h
support/c/idris_support.c
support/c/idris_support.h
support/c/windows/win_utils.c
support/c/windows/win_utils.h
tests/Main.idr
tests/base/system_file001/ReadFilePage.idr
tests/base/system_info001/NumProcessors.idr
tests/base/system_signal001/IgnoreSignal.idr
tests/base/system_signal001/expected
tests/base/system_signal001/input
tests/base/system_signal001/run
tests/base/system_signal002/HandleSignal.idr
tests/base/system_signal002/expected
tests/base/system_signal002/input
tests/base/system_signal002/run
tests/base/system_signal003/DefaultSignal.idr
tests/base/system_signal003/expected
tests/base/system_signal003/input
tests/base/system_signal003/run
tests/base/system_signal004/HandleManySignals.idr
tests/base/system_signal004/expected
tests/base/system_signal004/input
tests/base/system_signal004/run

This adds some simple signal handling to the base library.
I chose to implement this as a collector that allows retrieving signals that have been sent to a process since the last time the process checked for signals. This allows Idris developers to handle signals as part of a run loop.
If someone else wants to expand the implementation to offer thread-based interrupt handlers, this PR's C code and Idris types representing the most common signals should offer a solid foundation.
I, for one, am excited to take this and implement graceful shutdown on `SIGINT` (Ctrl+C) for a couple of my utilities!

Simple signal handling

---

libs/base/Data/Fin.idr
libs/contrib/Data/Fin/Extra.idr

(And throw in a %transform rule to optimise coerce away at runtime)

[ fix #1453 ] rename cast -> coerce

---

tests/Makefile
tests/base/system_info001/run

Instead of checking environment names, it's simpler to call nproc and fallback to sysctl.
In the unlikely event both commands fail, is `threads ?= 1` a reasonable default?
---
The next step is to remove `brew install coreutils` from ci-macos-combined.yml, once the bootstrap is updated.

[ fix ] nproc missing for non-GNU systems

---

src/Core/Termination.idr
tests/Main.idr
tests/idris2/error013/expected
tests/idris2/perf007/Slooow.idr
tests/idris2/perf007/expected
tests/idris2/perf007/run
tests/ttimp/total002/expected

This saves a lot of unnecessary exploring of size change graphs, which can get over the top quite quickly if there's complex mutual
definitions, or even just a single function with an interesting variety of recursive calls.
Fixes #1365
Fixes #1277
Fixes #645
...although only the performance aspects. If there are other issues (e.g. things which are not total with a clear explanation of why they should be) then these probably need minimising differently, so best submitted in new issue reports.

Cache intermediate results in totality checking

---

src/Core/Context.idr

For LSP these functionality is helpful. When we have a way to
request all the names we known about, we can use the information
for different purposes, such as, suggesting names to fill the
holes, or creating document symbols map for a module.

[ feature ] Expose 'resolvedAs' and 'getSimilarNames'

---

libs/prelude/Prelude/Types.idr

A tiny functionally equivalent change

[ refactor ] Use `f <$> ...` instead of `pure f <*> ...` in traverses

---

src/TTImp/Elab/Ambiguity.idr

Check for lambdas when checking if a type might fit for an ambiguous name.

Small pruning fix

---

docs/source/tutorial/typesfuns.rst
docs/source/updates/updates.rst

I missed the original PR that adds this syntax and used to wondering what's it until #1485. Let's add some documentation about it.
UPD: A UFO flew and broke CI, thus rebased to restart it.

[ doc ] Some documentation on `:=` syntax of `let` bindings

---

support/refc/clock.c

The cast to float needs to happen before the division, otherwise integer
division will be performed, and as a result `CLOCKS_PER_NSEC` will
always be 0 if `CLOCKS_PER_SEC` < `NSEC_PER_SEC`.

[ fix ] Cast CLOCKS_PER_SEC to float before division

---

src/Core/Binary.idr
tests/idris2/import001/expected

Need to use the 8 byte version of Ints for the shortcut version of reading TTCs too, otherwise we'll read the wrong hash and build things unnecessarily.

Read import hashes correctly

---

src/Core/Normalise.idr
tests/Main.idr
tests/idris2/reg040/CoverBug.idr
tests/idris2/reg040/expected
tests/idris2/reg040/run

We need to fully evaluate, not just the public export names, otherwise we don't pattern match properly and potentially generate catch all patterns we don't mean.
Fixes #1537

Properly normalise constants on LHS

---

idris2api.ipkg
libs/base/Data/Fin.idr
libs/contrib/Data/Fin/Extra.idr
src/Libraries/Data/Fin.idr
src/TTImp/ProcessBuiltin.idr

If the bound can't be strengthened, the current bound is returned
as-is in Left. But the current bound is already available, so the
returned bound isn't needed. Just return Nothing in that case.

Return Maybe from strengthen

---

libs/base/Data/Vect.idr
support/c/idris_signal.c

Two unrelated commits -- I can drop (heh) the `drop` function from this PR if folks don't want it in base.

Add Vect drop function and fix bug with signal C code

---

support/c/idris_net.c

As documented in e.g. [sys_socket.h](https://man7.org/linux/man-pages/man0/sys_socket.h.0p.html), one should use `socketaddr_storage` as a layout compatible version of either `socketaddr_in` or `socketaddr_in6` when reading one from e.g. `getsockname`. Mainly silences a compiler warning, since no bad memory is actually currently read after wrongly casting to `socketaddr_in6*` in
https://github.com/idris-lang/Idris2/blob/aa94dd235115137d56193f0db82d4f297758ee40/support/c/idris_net.c#L174

Use socketaddr_storage in getsockname

---

CHANGELOG.md
src/Libraries/Text/Lexer.idr
src/Parser/Lexer/Source.idr
tests/Main.idr
tests/idris2/basic061/UnderscoredIntegerLiterals.idr
tests/idris2/basic061/expected
tests/idris2/basic061/input
tests/idris2/basic061/run

Underscores can be used as visual separators for digit grouping purposes in integer literals.
This can aid the readability of long literals, or literals whose value should clearly separate into parts, such as bytes or words in hexadecimal notation.
For instance: `10_000_000` is equivalent to `10000000` and `0b1111_0101_0000` is equivalent to `0b111101010000`.

Allow underscores in integer literals to aid readability

---

src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/ChezSep.idr
src/Core/Binary.idr
src/Core/Options.idr
src/Idris/CommandLine.idr
src/Idris/ModTree.idr
src/Idris/Package.idr
src/Idris/ProcessIdr.idr
src/Idris/SetOptions.idr
src/Libraries/Utils/Binary.idr
src/Libraries/Utils/String.idr
src/Yaffle/Main.idr
tests/idris2/import001/expected
tests/idris2/import001/run

Closes #1519
Fixes #23 (modification time is not stored but read from the filesystem)

[ new ] detect changes using `sha256` rather than timestamps

---

src/Idris/Package.idr

Added "Profile" as a flag that can be used when building a project.  Since, if you try to use :exec within a repl, the profile flag is ignored by the Chez backend, without this flag, and there is no "profile" setting available within the "ipkg" file, there is not way to turn profiling on with the Chez backend.

[ fix #1572 ] Add `--profile` to the list of allowed flags in an .ipkg

---

docs/source/backends/refc.rst
idris2api.ipkg
src/Compiler/RefC.idr
src/Compiler/RefC/RefC.idr
support/refc/runtime.c
support/refc/runtime.h

Add the ability add aditional FFI targets to the RefC backend. This allows backends that extend RefC to add their own FFIs (for example, Python FFIs in the Python backend).
I've also added some documentation on how to extend RefC, both on creating basic backends, and adding FFI support to those backends.

Add ability to extend RefC backend to create further backends

---

src/Compiler/Scheme/Chez.idr

The Gentoo Chez package and some versions of the Ubuntu package install Chez scheme as `/usr/bin/chezscheme` which requires manually setting the CHEZ environment variable.  Adding it to the search path makes it easier for these users.
Maybe there is a better solution but I think this is an okay temporary fix.
Closes: https://github.com/idris-lang/Idris2/issues/666

Add chezscheme binary to search path

---

flake.nix
nix/templates/pkg/flake.nix
nix/templates/pkgWithDeps/flake.nix

References:
- https://nix.dev/anti-patterns/language#unquoted-urls
- https://github.com/NixOS/rfcs/pull/45
- https://github.com/NixOS/rfcs/blob/master/rfcs/0045-deprecate-url-syntax.md

Nix: verbatim URLs are deprecated

---

src/Core/Context.idr
src/Core/Core.idr
src/Core/Normalise.idr
src/Core/Options.idr
src/Idris/Desugar.idr
src/Idris/Error.idr
src/Idris/Parser.idr
src/Idris/REPL.idr
src/Idris/Syntax.idr
src/TTImp/Interactive/ExprSearch.idr
tests/Main.idr
tests/idris2/interactive034/expected
tests/idris2/interactive034/input
tests/idris2/interactive034/run
tests/idris2/interactive034/timeout.idr
tests/idris2/interactive035/expected
tests/idris2/interactive035/input
tests/idris2/interactive035/run
tests/idris2/interactive035/unify.idr

Firstly, add a configurable timeout (via `%search_timeout`), defaulting to 1 second (or rather, 1000 milliseconds), after which it will stop searching for more solutions. We search for a batch then sort to find the best of the batch, but in some cases it can start exploring too much, in which case we need the timeout. Typically if it hasn't found a solution in a second, it's not going to find a good one anyway.
Secondly, if a hole already has a solution by unification, we should just give that. We nearly did, but it was rendered incorrectly.
This adds a simple timeout mechanism, in which we can start a timer and check whether it's gone over some threshold. It could be useful elsewhere, e.g. in checking whether ambiguity resolution is struggling (the current check for depth is clearly not …

A couple of expression search improvements

---

src/Core/Directory.idr
src/Idris/IDEMode/REPL.idr
src/Idris/REPL/Common.idr

1) Recover the path relative to the working directory when sending file contexts, arisen due to typechecking errors, via the idemode protocol.
Send that over instead of module identifiers. (This is expected behaviour on the idris2-mode side)
2) Send the absolute path to a found global name in the name-at command.

Reconcile FC and IDE mode

---

INSTALL.md
config.mk

Found this to be true in the process of trying to install Idris 2 into its own `git clone`d folder.
I initially tried `./.idris2`, but this led to the library files not being installed in the right places.

Add clarifying note re: PREFIX in config.mk

---

CHANGELOG.md
libs/contrib/Control/Algebra/Implementations.idr
libs/contrib/Control/Validation.idr
libs/contrib/Data/Bool/Algebra.idr
src/Idris/Elab/Implementation.idr
src/Idris/ProcessIdr.idr
tests/Main.idr
tests/idris2/interface001/IFace.idr
tests/idris2/interface001/IFace1.idr
tests/idris2/reg044/Methods.idr
tests/idris2/reg044/expected
tests/idris2/reg044/run

This was always the intended behaviour, but until now not implemented! This caught a couple of issues in contrib and a test.

Missing interface methods now cause an error

---

libs/base/System.idr
support/c/idris_system.c
support/c/idris_system.h
support/chez/support.ss
support/gambit/support.scm
support/racket/support.rkt

To be able to eventually refactor/extend `system` function: to be
able to specify a directory, environment variables, specify arguments
as array etc. Ideally it should be something like Rust
[`std::process::Command`](https://doc.rust-lang.org/std/process/struct.Command.html).

Route System.prim__system through C function

---

support/c/idris_signal.c

Support for simple signal handling was added in a0a417240e69a9951e92b57c8d7fb328e437c71d (CC: @mattpolzin). This commit also adds the `_simple_handler` function. It seems to me that this function is intended as a helper function which should only be visible in `idris_signal.c`, it is not used outside this file. For this purpose it is probably also marked as inline. However, the inline keyword does not require the compiler to actually inline the function. As such, the `_simple_handler` symbol may still be exported if the compiler doesn't inline the function.
On my system this seems to be the case and causes the following error during compilation of idris2:
Exception: (while loading libidris2_support.so) Error relocating Idris2-0.4.0/build/exec/idris2_app/libidris2_support.so: …

Make sure _simple_handler is not exported

---

samples/FFI-readline/readline_glue/idris_readline.h
support/c/getline.h
support/c/idris_directory.h
support/c/idris_file.h
support/c/idris_net.h
support/c/idris_signal.h
support/c/idris_support.h
support/c/idris_term.h
support/refc/buffer.h
support/refc/cBackend.h
support/refc/casts.h
support/refc/clock.h
support/refc/conCaseHelper.h
support/refc/datatypes.h
support/refc/mathFunctions.h
support/refc/memoryManagement.h
support/refc/prim.h
support/refc/runtime.h
support/refc/stringOps.h
tests/chez/chez013/struct.h

Pragma once is supported by all compilers for the last ten years.
Better use it instead of include guards (which use different styles
in different files).

Use pragma once instead of include guard

---

src/Idris/Elab/Implementation.idr

The error message was missing a space
eg
```
Missing methods in SizedBinary: toBinarySize,KnownSize
```
Now it has one.

[ error message ] include space in missing methods error

---

docs/source/typedd/typedd.rst

The `VList` view is now located there, mention it in the `typedd.rst`
The extra view for Vect I didn't find in idris2, so for that one see https://github.com/idris-lang/Idris2/pull/1624
Regard,

Add comment about import from the contrib library

---

src/Compiler/Common.idr

This allows users to inspect IRs without worrying about choosing the right codegen to actually generate the result.
This also allows vmcode to be dumped despite no builtin backends using it.

[ fix ] generate lower level IRs if the option to dump that use phase is selected

---

Release/mkdist.sh

Handy as they might be, they're not really complete yet, and it includes a large file that just makes the tarball twice as big as necessary.

Don't need benchmarks in the release

---

src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/Gambit.idr

I suspect this function is left there accidentally after FFI was
refactored.
These functions can mislead about how FFI works.
Note these functions are private (not exported) and not used.  Idris
compiler could emit a warning about such functions.

Delete tyspec functions

---

flake.nix
nix/package.nix

With this PR, after building from nix, `idris2 --version` works as expected if the git tree is clean. Otherwise, it claims the revision is "dirty".
#1507

[ fix ] Nix uses proper version

---

.github/workflows/ci-macos-combined.yml
.github/workflows/ci-nix.yml
.github/workflows/ci-quick-check.yml
.github/workflows/ci-sphinx.yml
.github/workflows/ci-ubuntu-combined.yml
.github/workflows/ci-windows.yml

Rather than launching all of the builds immediately, we first try
to make sure that the project builds.

[ actions ] add quick check step

---

flake.nix
nix/buildIdris.nix
nix/lib.nix

This allows for cross-flake testing of content-addressible nix derivations without affecting other users of the flake (which would be the cases if CA-drvs would be hard-coded upstream) and without losing the ability to quickly update to the latest idris2 version (which would happen if a fork of the repo would be used).
See also: https://discourse.nixos.org/t/content-addressed-nix-call-for-testers/12881
The flake can still be used as usual, but it will gain an output `overrideOptions`, which can be used like e.g.
```nix
let
idrisx = idris.overrideOptions {
config.contentAddressedByDefault = true;
};
in { ... }
```
Additonally, this tries to improve `buildIdris` a bit.

Nix: make nixpkgs options overridable

---

src/Idris/Desugar.idr
src/Idris/Doc/HTML.idr
src/Idris/Doc/String.idr

This PR fixes a few issues with docs for records:
* docstrings for field projections were missing when listing the docs for a record type and when looking up docs with the `:doc (.fieldName)` syntax
* in the HTML docs, all field projections were shown in one line, now they're correctly formatted
* in the HTML docs, all field names were wrapped in parentheses, now that happens only if their name is an operator

[ docs ] Record docs fixes

---

.gitattributes

The slightly modified `.gitattributes` helps GitHub's "linguist" to skip the generated bootstrap code when counting lines of code per language. After this change, GitHub shows the repo as 95.5% Idris, which is nice :)
It seems the change only becomes effective after a merge to master and then only after some additional delay (at least that was the case for my personal branch [cypheon/Idris2](https://github.com/cypheon/Idris2)).

[ vanity ] Mark bootstrap code as generated -> detect repo's main language as Idris

---

src/Idris/CommandLine.idr
src/Idris/Package.idr

If no package file is passed to a package command, happily default
to whatever is in the working directory as long as it contains a
single package file.

[ cli ] make package file optional

---

src/Core/Unify.idr

We inline some holes when solving them if they pose no risk to breaking sharing, since this can speed up a few things. But if the hole was originally a user name, we might want to refer to it, and inlining it means we can't since it won't be saved to disk.
This fixes an occasional issue with proof search on a name that is already solved by unification.

Don't inline holes that are user defined names

---

libs/base/Control/App.idr
tests/Main.idr
tests/base/control_app001/TestException.idr
tests/base/control_app001/expected
tests/base/control_app001/run

Convert `App.Control.Exception` interface to an alias to `HasErr`.
Probably `Exception` interface need to be deprecated or removed.
Note similar problem exists with `PrimIO` calling `PrimIO, Exception`,
also need to be fixed.
Fix this scenario:
```
throwBoth : Has [Exception String, Exception Int] es => App es ()
throwOne : Has [Exception Int] es => App es Int
throwOne {es} = handle {err = String} {e = es} throwBoth (\r => pure 1) (\e => pure 3)
```
With this commit it works, before this commit it failed with:
```
Error: While processing right hand side of throwOne. Can't find an implementation for Exception Int (String :: es).
TestException.idr:8:48--8:57
|
8 | throwOne {es} = handle {err = String} {e = es} throwBoth (\r => pure 1) (\e => pure 3)
| …
```

More reliable exception handling in Control.App

---

idris2api.ipkg
src/Compiler/Interpreter/VMCode.idr
src/Compiler/Separate.idr
src/Compiler/VMCode.idr
src/Core/Name/Namespace.idr
src/Core/Options.idr
src/Core/Options/Log.idr
src/Core/TTC.idr
src/Idris/ProcessIdr.idr
src/Libraries/Data/IntMap.idr
tests/Main.idr
tests/chez/chez031/expected
tests/vmcode/basic001/Test.idr
tests/vmcode/basic001/expected
tests/vmcode/basic001/run

See #1608 for context.
This PR includes the improvements to `VMCode`, namely:
- Include Foreign definitions in `VMDef`
- Only project arguments to constructors when they are used
- If a case statement has exactly one alternative and no default, then skip CASE instruction (speeds up record projections).

[ improvement ] VMCode

---

README.md

Github Action status are based on workflows, not jobs. When #1645 was
merged, it changed multiple workflows into 1 workflow with multiple
jobs. This meant several badges on the README were now linking to
workflows which don't exist. This change makes a badge for the new
single workflow which does exist.
While it would probably be better to have statuses per job, I think the
only way to achieve that would be with an extra action like
https://github.com/marketplace/actions/bring-your-own-badge. So I'll
just stick with this minor fix for now.

Update README status badges

---

src/Compiler/RefC/CC.idr

I was getting "The system cannot find the drive specified" when compiling any code with "--cg refc", with msys2, no additional environment variables set.
Tried two different PCs both with Windows 10 + fresh msys2 install.
The problem is that operator `</>` is infix 5 so we're regarding the concatenation of everything (including `cc`) on the left side of `</>` a path, which is not valid (when CC is not set to an absolute path), so we end up with an invalid path.

[fix] refc backend broken with msys2

---

src/Core/Primitives.idr

Compile time evaluation was not yet supported for all the new primops like `prim__xor_Integer`, for instance. After this, #983 can be closed.

[ new ] support compile time evaluation for new integer primops

---

Makefile
src/Compiler/Scheme/Chez.idr
tests/chez/chez033/run

Update Windows launch script.
Add back the current directory to source-directories (not needed for
this, but it's the default and it's better to keep load working as usual,
there's no risk as the new dir has priority).
Copy libs instead of linking when testing (linking has bad interactions
with admin privileges).

Enable incremental compilation on Windows.

---

libs/prelude/Prelude/IO.idr

The function is not used, and it is defined incorrectly.

Remove prim__getErrno from Prelude.IO

---

src/TTImp/ProcessDef.idr
tests/Main.idr
tests/idris2/reg045/expected
tests/idris2/reg045/run
tests/idris2/reg045/withparams.idr

The 'with' type and application need to treat the parameters with the same plicity, but the application has just always treated them as explicit since it never looked. It's easiest just to make them all explicit, since this isn't a user visible type. Fixes #1695.

Fix 'with' under implicit parameters

---

src/Libraries/Text/Parser/Core.idr
src/Parser/Support.idr
tests/idris2/interactive028/expected
tests/idris2/perf005/expected
tests/idris2/perror005/expected
tests/idris2/perror006/expected
tests/idris2/perror008/expected
tests/idris2/with003/expected
tests/idris2/with004/expected

I was generating good error ranges in #1703 only to see them thrown away
by the reporting mechanism!

[ cosmetic ] use the whole range when underlining the problem

---

idris2api.ipkg
src/Compiler/Common.idr
src/Compiler/Interpreter/VMCode.idr
src/Core/Context.idr
src/Libraries/Data/IOArray.idr
src/Libraries/Utils/Binary.idr

To be able to modify `Data.IOArray` as proposed in #1677.
Currently `Data.IOArray` cannot be modified because compiler need
to be built with previous compiler. This PR removes compiler
dependency on `Data.IOArray`.

Fork Data.IOArray into the compiler

---

src/Idris/IDEMode/REPL.idr

the returned structure is inline with what Emacs idris-mode expects, so this fix allows using `C-c C-e` on a hole and get it lifted as a toplevel definition

Fix returned sexp for make-lemma command result in IDE mode

---

.github/workflows/ci-idris2.yml
.gitignore
Makefile
bootstrap-stage1-chez.sh
bootstrap-stage1-racket.sh
bootstrap-stage2.sh

... instead of `bootstrap` which contains source files. Make it easier to understand
how build works, and in particular, which files are sources and
which files are generated.

Write files into bootstrap-build directory during bootstrap

---

libs/base/Language/Reflection/TT.idr
libs/base/Language/Reflection/TTImp.idr
src/Core/Reflect.idr
src/TTImp/Reflect.idr
tests/idris2/reflection004/refdecl.idr
tests/idris2/reflection010/expected
tests/idris2/reflection010/run

Due to recent changes, the reflected version of records and parameters block got out of sync with the compiler internals. Thanks to @Z-snails for finding the issue.

Fixed wrong reflection of records and parameters

---

support/c/idris_directory.c
support/c/idris_file.c
support/c/idris_memory.c
support/c/idris_net.c
support/c/idris_signal.c
support/c/idris_support.c
support/c/idris_util.c
support/c/idris_util.h

```
IDRIS2_VERIFY(cond, message_format, ...)
```
When condition is false, crash.
Used in native functions where correct error handling is hard or
not impossible.
For example, `malloc` rarely fails, but if it fails, better crash
with clear error message than spend time debugging null pointer
dereference.

IDRIS2_VERIFY macro

---

support/refc/casts.c
support/refc/datatypes.h
support/refc/memoryManagement.c
support/refc/memoryManagement.h
support/refc/prim.c
support/refc/stringOps.c

* remove `Value.payload` field
* `IDRIS2_NEW_VALUE` macro now allocates the size needed for the struct

In RefC, allocate the exact size of value subtype

---

support/refc/datatypes.h

It is not used.
Also change `buffer` field type to avoid confusion.

Remove Value_Buffer.len field

---

support/c/idris_signal.c
tests/base/system_signal004/HandleManySignals.idr

Operating system counter stores signals as flag set without counter.
So sending two signals to a process may result to one or two signal
handler invocation. Queueing signals inside Idris could give users
false sense of signals being are queue, while they are not.
In particular, test for signal could not work reliably for that
reason.
Also, practically we usually don't need have more than once signal
event.
This is follow-up to #1660. CC @mattpolzin

Replace per signal counter with per signal flag

---

libs/base/Language/Reflection/TT.idr

This was different to `Name` in `Core.Name`
Specifically `CaseBlock` and `WithBlock` had an `Int` instead of a `String`

[ fix ] `Name` in `Language.Reflection.TT`

---

.github/ISSUE_TEMPLATE/feature-requests-and-proposals.md

In concert with  #1722 I think it's time we update the template for creating new proposals and feature requests. 
The new template has the following formal:
- Summary
- Motivation
- Proposal
- Subsections about the proposal
- Alternatives
- Conclusion
This aims to reach three goals:
- Encourage more thoroughly researched proposals
- Impose a uniform format for proposal and new features
- Ease the access to information about new features

Update issue template for proposals

---

libs/test/Test/Golden.idr

Situation I just ran into that I found confusing:
```
Golden value differs from actual value.
Accept actual value as new golden value? [y/N]
N
Invalid answer.
```

[ Test ] allow 'N' as an acceptable response

---

CHANGELOG.md
docs/source/tutorial/typesfuns.rst

A CHANGELOG update, and a correction on data type names which has been wrong in the crash course for some time now!

A couple of documentation corrections

---

libs/prelude/Prelude/IO.idr

Since most functions work with `HasIO`, it is more convenient to
accept `HasIO` in `onCollect` and `onCollectAny`.

Accept HasIO in onCollect functions

---

libs/base/Data/String.idr
libs/contrib/Data/String/Extra.idr
libs/contrib/System/Console/GetOpt.idr
libs/contrib/Text/PrettyPrint/Prettyprinter/Doc.idr
libs/test/Test/Golden.idr
src/TTImp/Elab/Ambiguity.idr
tests/Main.idr
tests/base/data_string_lines001/Lines.idr
tests/base/data_string_lines001/expected
tests/base/data_string_lines001/input
tests/base/data_string_lines001/run
tests/base/data_string_unlines001/Unlines.idr
tests/base/data_string_unlines001/expected
tests/base/data_string_unlines001/input
tests/base/data_string_unlines001/run

There are several reasons to do that:
* a line in a text file is something which ends with newline,
and the last line is not special
* `unlines []` should be different from `unlines [""]`
* `unlines (a ++ b) = unlines a ++ unlines b`
* Haskell does it
I suspect this is what most users expect. And this is what virtually all other implementations do.

Change semantics of lines and unlines function to match Haskell and other languages

---

support/refc/buffer.c
support/refc/conCaseHelper.c
support/refc/memoryManagement.c
support/refc/prim.c
support/refc/refc_util.c
support/refc/refc_util.h
support/refc/runtime.c
support/refc/stringOps.c

Better crash explicitly than debug memory violation.
The most important part of this is in `Buffer` implementation.

Assertions in RefC runtime

---

docs/source/faq/faq.rst
src/Core/UnifyState.idr
src/TTImp/Elab.idr
src/TTImp/Elab/Ambiguity.idr
src/TTImp/Elab/Binders.idr
src/TTImp/Elab/Case.idr
src/TTImp/Elab/Delayed.idr
src/TTImp/Elab/ImplicitBind.idr
src/TTImp/Elab/Lazy.idr
src/TTImp/Elab/Record.idr
src/TTImp/Elab/Rewrite.idr
src/TTImp/Elab/RunElab.idr
tests/Main.idr
tests/idris2/reg048/expected
tests/idris2/reg048/inferror.idr
tests/idris2/reg048/run

Instead of having an arbitrary looking priority number, record explicit reasons for the delay, which helps order them sensibly when rerunning them. Mostly this allows us to choose which ones to rerun, where it helps, and helps order things to get better error messages.
Also run them for longer - keep going as long as some progress is being made, rather than giving up after one pass. There's no good reason to stop early.

Better ordering of delayed elaborators

---

.github/workflows/ci-idris2.yml

It's easier to follow Windows CI output this way.

Split Windows CI build into multiple steps

---

CHANGELOG.md
docs/source/reference/index.rst
docs/source/reference/strings.rst

#555, #1027, #1029 have been implemented, but the documentation and the changelog weren't updated at the same time. Documenting those feature is the last item in their todo list.
The features seem to work well except for #1755 and #1132 which are fairly innocuous.

Document string literals

---

libs/base/Data/Vect.idr

When I added `Vect.drop` and `Vect.drop'` I forgot to export them!

Make drop and drop' public exported from the vect module.

---

.github/workflows/ci-idris2.yml

Checking commit messages for instructions:
* `[ci: skip]` to skip all idris2 builds
* `[ci: ubuntu]` to build the ubuntu-based ones (same for `macos`, `windows`, `nix`)
* `[ci: chez]` to only build the chez-based ones (same for `racket`)
If `[ci: skip]` is not present then the resulting action is the *union* of all the tags so
a message containing both `[ci: windows]` and `[ci: racket]` will run all of the windows
tests as well as the racket ones on ubuntu & macos.

[ ci ] controlling builds via commit messages

---

libs/base/System/Directory.idr
libs/test/Test/Golden.idr
support/c/idris_directory.c
tests/Main.idr
tests/base/system_directory/ReadDir.idr
tests/base/system_directory/expected
tests/base/system_directory/input
tests/base/system_directory/run

`testInDir dir ...` lists all directories in `dir` which contains
`run` files, and such directories are considered tests.
This is done to make test addition/maintenance cheaper.
Convert some test directories to `testInDir`, but not all of them
because
* some directories are listed in several test groups
* other directories are have some tests disabled
This is on top of #1733.

Implement test discovery

---

libs/base/System/Directory.idr
support/c/idris_directory.c
tests/Main.idr
tests/base/system_directory/ReadDir.idr
tests/base/system_directory/expected
tests/base/system_directory/input
tests/base/system_directory/run

* add `nextDirEntry` which returns `Maybe String`, so `Nothing` on
the end of directory unlike `dirEntry` which returns unspecified error
on the end of directory
* `dirEntry` is deprecated now, but not removed because compiler depends on it
* native implementation of `dirEntry` is patched to explicitly reset `errno`
before the `readdir` call: without it end of directory and error were
indistinguishable
* test added

System.Directory.nextDirEntry

---

libs/base/System/Directory.idr
support/c/idris_directory.c
tests/Main.idr
tests/base/system_directory/ReadDir.idr
tests/base/system_directory/expected
tests/base/system_directory/input
tests/base/system_directory/run

These entries returned by `readdir` are legacy of Unix API, we don't
really need them. Most APIs do not return them (for example Java
`Files.newDirectoryStream` or Python `os.listdir`).
This is on top of #1731.

Skip dot and dot-dot in nextDirEntry

---

src/TTImp/Elab/Ambiguity.idr
src/TTImp/Elab/App.idr
src/TTImp/Elab/Delayed.idr
src/TTImp/Elab/Lazy.idr
src/TTImp/Elab/Record.idr
src/TTImp/Elab/Rewrite.idr
tests/Main.idr
tests/idris2/error018/expected
tests/idris2/reg049/expected
tests/idris2/reg049/lettype.idr
tests/idris2/reg049/run

In theory argument elaboration order doesn't matter, but in practice we
sometimes make choices for performance reasons, like helping with
disambiguation by knowing the target type.
This was kind of messy, now we can more clearly see what's going on.
Also, more importantly, it gives us a bit more control which we
sometimes need. For example, if we go choose to go right to left for
some performance heuristic it might turn out we don't have enough
information yet, in which case we need to delay and try again later.
Fixes #1743

A bit of refactoring of argument elaboration order

---

.github/workflows/ci-idris2.yml
.github/workflows/ci-lint.yml
.github/workflows/ci-sphinx.yml
.github/workflows/ci-super-linter.yml

Partially addresses https://github.com/idris-lang/Idris2/issues/1682.
This PR updates the only inward-facing references to `master` branches in this repository: those found in the CI configurations. Additionally, see the bottom of the PR description for a bit more context on this branch renaming (in addition to the above-linked Issue).
Until the `master` branch is renamed `main`, the super-linter will fail on this PR due to the fact that this PR changes the `DEFAULT_BRANCH` to `main` which is not a branch yet.
We _could_ create the `main` branch before deleting the `master` branch to sidestep the awkwardness of this PR being broken until the `main` branch is created, but I suggest we use GitHub's built-in branch renaming, as described below, because it will automatically update all PRs …

Set the stage for renaming the `master` branch to `main`.

---

docs/source/tutorial/packages.rst

Reference the --init option for creating package files in the tutorial documentation.

Document --init

---

src/Idris/SetOptions.idr

As mentioned on [discord](https://discord.com/channels/827106007712661524/834611018775789568/868145988508975195), TAB completion for Idris2 does not work for files but only for directories. This PR should fix the issue.

[ fix ] bash TAB completion for files

---

src/Compiler/CompileExpr.idr
src/Core/CompileExpr.idr
src/Core/Hash.idr
src/Core/TTC.idr
support/chez/support.ss

This is step 0 in a plan to use the scheme evaluator to evaluate Idris
expressions at compile time. As a proof of concept, I've got this
working for a toy language here: https://github.com/edwinb/SchemeEval
We won't be able to do anything interesting with this in Idris itself
until the next release because it involves updating the bootstrap code
and adding the ability to pass 'Integer' to foreign calls, which really
should have been allowed anyway since it's for a backend to decide what
it can cope with, not Idris itself.

Add ability to manipulate scheme objects

---

src/Idris/Desugar.idr

This fixes a bug where an interpolated string would
be wrapped in a `fromString` call
Fixes #1755

Remove `fromString` calls from interpolated strings

---

libs/base/Data/List1.idr
src/Core/Termination.idr
src/Libraries/Data/List1.idr
src/TTImp/Elab/Case.idr
tests/Main.idr
tests/idris2/total011/Issue1460.idr
tests/idris2/total011/Issue1782.idr
tests/idris2/total011/expected
tests/idris2/total011/run

I can't make sense of this code, it seems to try to convert the
case function corresponding to `let (a, b) = f n in ...` into a
different case function where `f n` and `(a, b)` have been unified.
But if `f n` is a bona fide stuck computation, there's no chance of
this happening.
Just turning this off solves the #1782 and only breaks one function
in the whole of the idris2 repo (I would have expected our current
termination oracle to be too weak to detect it as valid anyway!)
and one in frex (which, again, should not have been seen as terminating).

[ fix #1782 ] remove the case-specific code

---

INSTALL.md
docs/source/tutorial/starting.rst
tests/base/system_info001/run

`realpath` is no longer needed to run executables.

Remove all mentions of `realpath` from docs

---

libs/base/Control/WellFounded.idr
libs/base/Data/Nat/Order.idr

Turns out that `Smaller` and `LT` won't unify because
1. the instance Sized Nat is not publicly exported
2. Smaller, and LT are stuck until fully applied
The given changes make that go away.

[ cleanup ] various public export & cleanup

---

.github/workflows/ci-idris2.yml
libs/prelude/Prelude/Basics.idr

The previous definition means it won't reduce until it's applied to
4 arguments which may have detrimental effects: ``f `on` fst`` would
for instance stay blocked, with some implicit arguments of the form
`DPair a b`. This means that `b` appears in a negative position in
the expression which may lead to positivity checking rejecting a
datatype defined using `on`!
I have decided to leave `g` and `f` on the LHS because I expect `on`
to be used either:
1. partially applied to two arguments
2. in a section if only applied to 1 and sections get eta-expanded
by the parser so that's fine.
Also: add collie & frex to the CI

[ cleanup ] `on` is meant to be used with 2 arguments

---

libs/prelude/Prelude/Types.idr
tests/prelude/nat001/expected
tests/prelude/nat001/nats.idr
tests/prelude/nat001/run

Lists produced by `Range` instance of `Nat` differ from those produced for `Integer`. This creates a confusing inconsistency:
```
Main> rangeFromThenTo (the Nat 2) 3 2
[]
Main> rangeFromThenTo (the Integer 2) 3 2
[2]
```
The issue is fixed in favour of behaviour for `Integer`, which seems more natural. Additionally some tests for Range instance for `Nat` were added.

Fix bad range behaviour for Nat

---

src/Compiler/ES/Codegen.idr
tests/Main.idr
tests/node/node026/Fix1795.idr
tests/node/node026/expected
tests/node/node026/input
tests/node/node026/run

Fixes #1795
Currently this isn't very clever, and inserts an uneeded `break` after every `return`.

Add `break` in each case alt in js backend

---

INSTALL.md

The other day a bit of confusion came up in Discord over the fact that installing "gmp" was not working; it was because the dev library was needed instead.

Get a bit more specific about the GMP library requirement.

---

Makefile

This minor change to the Makefile allows overriding the version tag that is used to tack a GIT commit SHA onto the end of an Idris 2 version when Idris 2 is built from source.
Overriding that tag is not just for vanity. I am currently making nightly builds of Idris 2 without `git` installed by downloading the source code from GitHub; I'd like to `VERSION_TAG=nightly make` so that `idris2 --version` does not _look_ like it is telling me I am running version 0.4.0 stable instead of the HEAD of main.
I imagine that forks of Idris 2 that add compiler backends might also be interested in specifying a suffix (e.g. `0.4.0-erlang`).

Support explicitly setting a version tag during build.

---

flake.lock
flake.nix
nix/package.nix
src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/ChezSep.idr

Use Racket's Chez for non-x86_64-linux platforms in flake.nix.
The nix expression is taken from https://github.com/NixOS/nixpkgs/pull/131833.
It supports many more platforms, excerpt from the README:
> Supported platforms:
>
>     Windows: x86, x86_64
>     Mac OS: x86, x86_64, AArch64, PowerPC32
>     Linux: x86, x86_64, ARMv6, AArch64, PowerPC32
>     FreeBSD: x86, x86_64, ARMv6, AArch64, PowerPC32
>     OpenBSD: x86, x86_64, ARMv6, AArch64, PowerPC32
>     NetBSD: x86, x86_64, ARMv6, AArch64, PowerPC32
>     Solaris: x86, x86_64
>     Android: ARMv7, AArch64
>     iOS: AArch64
Link to the fork: https://github.com/racket/ChezScheme

flake.nix: Use Racket's Chez for non-x86_64-linux platforms (more platforms supported)

---

src/Core/Normalise.idr
src/Core/Unify.idr

This isn't always safe - we have to have also checked the type of the things we're converting - but in the place where it is safe it can be a pretty significant saving.

Skip forced arguments in conversion check

---

src/Idris/Desugar.idr
tests/Main.idr
tests/idris2/error020/Error.idr
tests/idris2/error020/expected
tests/idris2/error020/run

Produces a proper error message when the leftmost term in a function clause's pattern is not a function name. Fixes #1441

Fix error message for incorrect function patterns

---

libs/contrib/Data/Validated.idr

I found myself needing this and I really think that great standard interface suits well this data type.
Also, a tiny cleanup in the same module. One function have its arguments flipped to make easy to use it inside function application chains.

[ contrib ] Implementation of `Zippable` was added for `Validated`

---

CHANGELOG.md
src/Idris/CommandLine.idr
src/Idris/Driver.idr
src/Idris/SetOptions.idr

When I was deciding where to add the `ListPackages` option I noticed there were a few options handled in disparate places all having to do with directories so I relocated them under the existing `DirCommand` type.

Add a `--list-packages` command to the `idris2` executable

---

libs/base/Control/Monad/Error/Either.idr
libs/base/Control/Monad/Maybe.idr
libs/base/Control/Monad/RWS/CPS.idr
libs/base/Control/Monad/Reader/Reader.idr
libs/base/Control/Monad/State/State.idr
libs/base/Control/Monad/Writer/CPS.idr

There are three more-or-less independent changes, but all about transformers. All of them are in different commits and all can be considered independently if needed:
- the current implementation of `Alternative` for `ReaderT` requires `Monad` but it may not;
- some (hopefully) readability cleanup;
- the current signature of `Alternative` has its second argument lazy; however, the current implementations of `Alternative` for transformers do not treat it nicely, they force its second argument despite the underlying alternative/monad may not require its second argument; the fix is proposed.

[ base ] Relax requirements of `Alternative` of `ReaderT` + lazy `<|>` for transformers + cleanup

---

libs/base/Language/Reflection.idr
libs/base/Language/Reflection/TTImp.idr
src/TTImp/Elab/RunElab.idr

I sometimes find myself wanting to complain about a particular point of a user code inside my elaboration scripts. This PR adds such an ability while keeping the original behaviour unchanged.

[ elab ] Add an ability to fail elaboration script with a custom `FC`

---

libs/base/Data/Vect.idr

I think these implementations are very consistent to the ideology of other `Vect`'s instances.
Also, existing `Monad` instance was not exported at all, seems to be non-intended.

[ base ] Add semigroup and monoid instances for `Vect`

---

libs/contrib/Text/Bounded.idr

This looks like an oversight in #1808.

[ fix ] export Show instance for Bounds

---

libs/prelude/Prelude/Num.idr

This PR adds `%inline` pragmas to all `Neg`-implementations in `libs/prelude/Prelude/Num.idr`.

Inline Neg implementations

---

tests/Main.idr
tests/idris2/namespace002/Issue1313.idr
tests/idris2/namespace002/expected
tests/idris2/namespace002/run

This was fixed by, I believe, the addition of `withExtendedNS` in #1342

[ close #1313 ] test case

---

libs/prelude/Prelude/IO.idr

Just a tiny but useful addition. I didn't even realize this was missing.

[ new ] support prim__putStr in browser backend

---

src/Compiler/ES/Codegen.idr
support/js/support.js
tests/Main.idr
tests/node/fix1839/OS.idr
tests/node/fix1839/expected
tests/node/fix1839/input
tests/node/fix1839/run

Fixes #1839.
This fix removes the implementation of `prim__os` from the static Javascript preamble. After this, `prim__os` is only supported in the `node` backend but not the `javascript` backend. If people can show me a reliable and useful way to determine the OS in the browser, I'll happily add that as the new implementation of `prim__os` for the `javascript` backend.

[ fix ] fix #1839

---

libs/prelude/Prelude/Cast.idr

integerToNat is only equal to `believe_me` at runtime, not at compile
time. You'd believe it cannot be a problem given that the implementation
of `Cast` is not exported but the REPL reduces everything.

[ fix ] invalid Cast instances

---

src/Compiler/Scheme/Chez.idr
src/Compiler/Scheme/ChezSep.idr

On Racket, the Mac M1 target (AArch64) is known as `tarm64osx`. Currently, Idris2 does not account for this when looking for the `libc.(so/dylib)` shared object file. This does not cause the build to fail, and it actually takes a while for the error to surface (for me it only appeared when trying to run `idris2-lsp`, getting the error `Exception: (while loading libc.so) dlopen(libc.so, 2): image not found`).
This pull request simply addr `tarm64osx` to the `case`-statements selecting macOS-targets, overriding the default behaviour of defaulting to `libc.so`.

Support tarm64osx (AArch64, Apple M1) target

---

support/c/idris_directory.c

Remove DirInfo.error

---

libs/base/Data/List.idr

I've started to hesitate adding things like this to `base` because Idris 2 has survived _this long_ without them; but... list difference is really useful, right?
I guess I'll either sneak this in or get shot down and either way I'll survive 😄.

Add list difference to base Data.List module.

---

.github/workflows/ci-idris2.yml
Release/mkdist.sh

Since Travis CI is no longer used.

[ cleanup ] `mkdist.sh` script cleanup

---

CHANGELOG.md
docs/source/tutorial/views.rst
src/Idris/Parser.idr
src/Idris/Syntax.idr
tests/Main.idr
tests/idris2/with006/SparseWith.idr
tests/idris2/with006/expected
tests/idris2/with006/run

Rather than Agda's `...` we use the common symbol for "I don't care": `_`.

[ new ] ellipses for with patterns

---

idris2api.ipkg
src/Compiler/Common.idr
src/Compiler/CompileExpr.idr
src/Compiler/ES/Codegen.idr
src/Compiler/LambdaLift.idr
src/Compiler/Opts/CSE.idr
src/Core/Context.idr
src/Core/Options/Log.idr
src/Core/Ord.idr
src/Core/TTC.idr
support/js/support.js

This PR introduces a simple form of CSE as a means of whole program optimization, mainly to reduce duplicate object definitions introduced during autosearch (see also #1614). This has a beneficial impact on the size of generated executables (for instance, `idris2.ss` is reduced from 11M to 7.9M, the compiled chez binary `idris2.so` from 6.1M to 4.6M), especially so in pathological cases (the notorious `node/integers` test is reduced from around 700KB to 76KB!).
In addition, this gives rise to some performance improvements as well: On the JS backends, I converted zero-argument toplevel functions to lazily evaluated constants. This increase performance in my idris2-json and idris2-webidl tests by about 30%. The same might be possible on scheme backends as well, as there too zero-argument …

[ performance ] Common subexpression elimination

---

libs/base/Data/DPair.idr
libs/contrib/Data/SortedMap.idr
libs/contrib/Data/SortedMap/Dependent.idr
libs/contrib/contrib.ipkg

This is done by minimal changes inside the internal data structure: practically it was ready to hold dependently typed values. All was split into two modules because of backward-compatibility: all the code that was working with existing non-dependent `SortedMap` data type should work unchanged.
During the review, probably it's better to look at diff between the original `SortedMap` module and the new `SortedMap.Dependent`, in this case there are not so many differences, e.g. using
```
> git diff HEAD^:libs/contrib/Data/SortedMap.idr HEAD:libs/contrib/Data/SortedMap/Dependent.idr
```

[ contrib ] Make sorted map be able to store dependently typed values

---

src/Core/CaseBuilder.idr
tests/Main.idr
tests/idris2/reg050/expected
tests/idris2/reg050/loopy.idr
tests/idris2/reg050/run

If they don't, we can't turn them into patterns to match on, and we end up looping. Possibly we could throw a different and maybe more informative error instead of just making an unmatchable pattern.
Fixes #1895

Check primitives (fromInteger etc) reduce on LHS

---

flake.nix
nix/buildIdris.nix

While looking at https://github.com/ReplicaTest/REPLica/pull/62, I looked at this flake (I am no idris developer, yet) and think the flake could be more idiomatic/easier to use it if allowed to  pass attributes directly to `buildIdris` instead of the
convoluted `buildIdris (...).build.overrideAttrs(oldAttrs: {})`.

nix flake: make it more idiomatic

---

docs/source/reference/overloadedlit.rst
docs/source/reference/strings.rst

Some block codes in the docs are not rendered: the 'idris' language missed and somehow the rst compiler apparently discarded them instead of letting them withut syntax coloring.

code-blocks missing in the docs

---

libs/base/Data/Vect/AtIndex.idr
libs/base/Data/Vect/Index.idr
libs/base/base.ipkg

`Elem` proofs give existential quantification that a given element *is* in the list, but not where in the list it is!
Here we give a predicate that presents proof that a given index of a vector, given by a `Fin` instance, will return a certain element.
Two decidable decision procedures are presented:
1. Check that a given index points to the provided element in the presented vector.
2. Find the element at the given index in the presented vector.
Prompted by #1891.

[ base ] Indexing Vectors.

---

libs/base/System/File/Meta.idr
support/c/idris_file.c
support/c/idris_file.h
support/c/windows/win_utils.c
support/c/windows/win_utils.h

This feels a bit more robust (and subtly different) than checking whether the `$TERM` environment variable is set to "dumb". It also theoretically opens the door for an app to pipe data to non-`stdout` TTY handles that it opens.
I also swapped out uses of `fileno()` for `_fileno()` when in a Windows environment because the former is a deprecated alias of the latter.
If this PR gets merged, I will submit a (good first issue) follow-up ticket that after the next Idris 2 release we can start using this function either in addition to- or instead of checking for "dumb" terminals when determining if colors are supported in the Idris 2 compiler source code.

Add function that checks whether a file handle points to a TTY device.

---

src/Compiler/ES/Codegen.idr
support/js/support.js
tests/Main.idr
tests/node/stringcast/StringCast.idr
tests/node/stringcast/expected
tests/node/stringcast/input
tests/node/stringcast/run

On the Node backend, the following fails with an exception (the same code prints "0" with the default Chez backend):
```idris
main : IO ()
main = printLn $ cast {to = Integer} "end"
```
Likewise, the following version prints "NaN", while again printing "0" on Chez:
```idris
main : IO ()
main = printLn $ cast {to = Double} "end"
```
This PR adjusts the JS backends in such a way that they behave consistently w.r.t. to the default backend in the cases above. There might still be corner cases where the two backends differ, though.

[ fix ] String casts on js backends

---

libs/contrib/Data/Fin/Extra.idr

I don't have a good feel for when it's "good" or "bad" to publicly export a function.
This one is needed to prove properties about `invFin` which haven't yet been stated in the standard library.
Take for example the spec for `invFin` itself, which hasn't been there up until now.

`invFin`: `export` ~> `public export` and `invFinSpec`

---

libs/test/Test/Golden.idr
src/Compiler/Scheme/Chez.idr

According to repology, there are a few systems using `chez-scheme` as chez's name (including Alpine, Guix, Void, ASOC, Freebsd-ports, MacPorts, nix...)
https://repology.org/project/chez-scheme/versions
This small addition can eliminate time-wasting for those users. They will no longer have to change chez name or delegate with corresponding packagers.

Add chez-scheme to chez search path

---

src/Idris/Driver.idr
src/Idris/REPL/Common.idr
src/Idris/REPL/Opts.idr
src/Idris/SetOptions.idr

The change helps to avoid the most commonly found dumps of elaboration error messages to stdout when in
quiet mode. That in turn keeps us safe from critical LSP failures due to unexpected writes to stdout.

Thread the option of silencing output to stdout

---

src/Idris/Error.idr
tests/idris2/basic001/expected
tests/idris2/basic016/expected
tests/idris2/basic030/expected
tests/idris2/basic034/expected
tests/idris2/error001/expected
tests/idris2/error003/expected
tests/idris2/interface027/expected
tests/idris2/namespace002/expected
tests/idris2/perf005/expected
tests/idris2/record004/expected
tests/idris2/reflection001/expected
tests/idris2/reflection005/expected
tests/idris2/reg007/expected
tests/idris2/with003/expected

Made unifying error msg nicer. ex.:
```
Error: While processing right hand side of foo3. When unifying:
(Int, (String, (String, (Char, (Int, (String, Char))))))
and:
(Int, (String, (String, (Char, (Int, (Int, Char))))))
Mismatch between: String and Int.
```
vs:
```
Error: While processing right hand side of foo3. When unifying (Int, (String, (String, (Char, (Int, (String, Char)))))) and (Int, (String, (String, (Char, (Int, (Int, Char))))))
Mismatch between: String and Int.
```
Code below:
```
foo : (Int,String,String,Char,Int,Int,Char) -> ()
foo x = ()
foo2 : (Int,String,String,Char,Int,String,Char)
foo2 = (1,"foo","x",'c',5,"fee",'d')
foo3 : ()
foo3 = foo foo2
```

Made unifying error msg nicer.

---

libs/base/Language/Reflection.idr

This is effectively an equivalent change, but allows not have arguments, that are already known to the compiler, to be passed as runtime arguments in macro and reflection-level functions.

[ elab ] Erase `check` and `quote`'s main argument
