idris-lang/Idris2

- libs/test/Test/Golden.idr
This is a follow up for #1920. Unfortunately, it was not full enough -- there was another `system` call that had unquoted paths.
> [ fix ] Wrap paths in quotes for one more call for `system`

- Makefile
On some systems, `/bin/sh` is a symlink to a minimal shell (e.g. `dash`) that doesn't understand bashisms like `mkdir -p some_dir/{one,two,three}`.
> [ install ] Fix `install-libdocs` makefile target

- CHANGELOG.md
- src/Compiler/Inline.idr
In incremental mode we need to add the arity of a compiled definition to the hash, because if that changes, we need to rebuild the dependencies too to make sure the arity is correct at the call site
> Small fix for incremental compilation

- Release/CHECKLIST
We don't need this for bootstrapping, and it prevents building on older Chez, so we can just remove it. Also added a note to the release checklist.
> Remove __collect_safe from bootstrap chez

- src/Compiler/Common.idr
- src/Compiler/CompileExpr.idr
- src/Compiler/Opts/CSE.idr
The current CSE algorithm stores all closed sub-terms in their unmodified form in a `SortedMap`. This requires O(n^2) space w.r.t. term size and can lead to drastic amounts of memory consumption during CSE as mentioned on [discord](https://discord.com/channels/827106007712661524/827109190266257409/889134639480991764). @Z-snails had the idea to start the CSE analysis at the leaves, in which case it should be possible for the algorithm to consume a linear amount of space w.r.t. term size.
This PR adjusts the algorithm in such a way.
> [ performance ] CSE in linear space

- tests/idris2/pkg010/gen_expected.sh
- tests/idris2/pkg010/run
`$(pwd)` in the shell means running `pwd` but then there's code next to it that specially handles cygwin.
merge the two into one.
> [tests] fix idris2/pk010: make it more roboust

- Makefile
Without this change `install-libs` will not install the `.so` files, and consequentially the test `chez/chez033` fails with `Error: INTERNAL ERROR: Missing .so:Prelude/Cast.so` when it is run by an installed executable.
Also add a `test-installed` makefile target to run the tests with the installed executable.
> [build] fix install-libs target

- libs/contrib/Language/JSON/Data.idr
- tests/contrib/json_002/ShowJSON.idr
- tests/contrib/json_002/expected
- tests/contrib/json_002/input
- tests/contrib/json_002/run
- tests/contrib/json_003/CastJSON.idr
- tests/contrib/json_003/expected
- tests/contrib/json_003/input
- tests/contrib/json_003/run
Adds some `Cast` to `JSON` implementations for `()`, `Bool`, `Double`, `String`, and `List`s.
Also adds another `Show JSON` implementation, for displaying the `JSON` as represented in Idris code.
Tests added for all of the above, as well as the existing `Show JSON` implemtation, and the `JSON` `format` function.
> Add some JSON cast interfaces

- src/Core/Core.idr
- src/Idris/Error.idr
- src/TTImp/Elab/Ambiguity.idr
- src/TTImp/Elab/Check.idr
- tests/idris2/basic003/expected
- tests/idris2/basic049/expected
- tests/idris2/reg048/expected
- tests/idris2/with003/expected
We need to store the Context in errors at the point where the error occurs (or make sure the term has holes normalised before throwing the error), or we might get some nonsense in the message. There's still a couple of places in Error where we don't do this right. This fixes one of them, and improves a few messages in the process.
> Fix display of ambiguity errors

- libs/base/Data/Either.idr
IsRight and IsLeft types, like IsJust and IsYes.
I have used IsRight instead of IsJust to provide more meaningful error messages, when the value is a Left.
I have no particular use case for IsLeft, it is included for the sake of completeness.
> [base] add IsRight and IsLeft proofs to Data.Either

- libs/contrib/Data/String/Parser.idr
- tests/chez/chez027/StringParser.idr
- tests/chez/chez027/expected
Adds the `takeUntil` parser, which takes from the input until the "stop" string is found; and tests.
> Add takeUntil Data.String.Parser parser

- bootstrap/idris2-boot.sh
- bootstrap/idris2-rktboot.sh
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/ChezSep.idr
- src/Compiler/Scheme/Racket.idr
Hi,
After upgrading to macOS 12 (Monterey) I was unable to run the `idris2` executable that I had previously installed. Instead I was shown the following error:
```
Exception: (while loading libidris2_support.dylib) dlopen(libidris2_support.dylib, 0x0002): tried: 'libidris2_support.dylib' (no such file), '/usr/local/lib/libidris2_support.dylib' (no such file), '/usr/lib/libidris2_support.dylib' (no such file), '/Users/USER/Idris/Idris2-main/libidris2_support.dylib' (no such file), '/usr/local/lib/libidris2_support.dylib' (no such file), '/usr/lib/libidris2_support.dylib' (no such file)
```
Thanks to @ska80's clarification in INSTALL.md (commit [880981d](https://github.com/idris-lang/Idris2/commit/880981d5b4de57b55f762ef6b13a11ce17c5421d#diff-09b140a43ebfdd8dbec31ce72cafffd15164d2860fd39069 …
> [ fix ] loading of dylib on macOS Monterey

- libs/contrib/Data/List/Alternating.idr
- libs/contrib/Data/SortedMap.idr
- libs/prelude/Prelude/EqOrd.idr
- libs/prelude/Prelude/Interfaces.idr
- libs/prelude/Prelude/Show.idr
- src/Compiler/ANF.idr
- src/Compiler/LambdaLift.idr
- src/Compiler/VMCode.idr
- src/Core/Case/CaseBuilder.idr
- src/Core/Case/CaseTree.idr
- src/Core/CompileExpr.idr
- src/Core/Context/Context.idr
- src/Core/Core.idr
- src/Core/Metadata.idr
- src/Core/Ord.idr
- src/Core/TT.idr
- src/Core/Value.idr
- src/Idris/ModTree.idr
- src/Idris/Parser.idr
- src/Idris/Syntax.idr
- src/TTImp/Elab/Check.idr
- src/TTImp/Elab/Record.idr
- src/TTImp/Interactive/CaseSplit.idr
- src/TTImp/PartialEval.idr
- src/TTImp/TTImp.idr
- tests/idris2/docs001/expected
- tests/idris2/interactive030/expected
- tests/idris2/reg033/DerivingEq.idr
- tests/idris2/reg033/test.idr
The prelude interfaces that have default definitions for *all* of
their fields are declared total so that users are forced to think
about meeting the minimal requirements for an implementation to be
valid.
> [ re #2001 ] Make some prelude interfaces total

- support/chez/support.ss
Hi! This change allows one to bootstrap and run idris2 on Macs using an ARM version of Chez (See more info below).
Similar error as #2078, but in this case the error was caused by `System.os` returning the wrong OS.
```
Exception: (while loading libidris2_support.so) dlopen(libidris2_support.so, 0x0002): tried: '/Users/USER/Idris/Idris2-main/build/exec/idris2_app/libidris2_support.so' (no such file), '/libidris2_support.so' (no such file), 'libidris2_support.so' (no such file), '/usr/local/lib/libidris2_support.so' (no such file), '/usr/lib/libidris2_support.so' (no such file), '/Users/USER/Idris/Idris2-main/build/exec/idris2_app/libidris2_support.so' (no such file), '/libidris2_support.so' (no such file), '/Users/USER/Idris/Idris2-main/libs/prelude/libidris2_support.so' (no such file), …
```
> [ fix ] Detect OS as Darwin when running ARM version of Chez on a Mac

- src/Core/Normalise.idr
- src/TTImp/Elab/App.idr
While we do end up normalising it anyway on success, there might be things blocking it that make the intermediate terms very big, so only do it speculatively to see if it's quick.
> Only normalise a search goal if it's fast

- libs/base/Data/List.idr
- tests/idris2/reg047/QualifiedDoBang.idr
Adds the `List` singleton function. Honestly, I'm suprised it's not already in `base`.
We could use `pure` instead, but that's not always the semantic meaning we try to get across. Further, the presence of `singleton` for a variety of list-like types, but not `List` itself, could be confusing.
> Add List singleton function

- src/Core/Binary.idr
Bump TTC version. It's been 10 days and a number of commits since the last TTC version bump, so I'd argue it's worth applying this bump right after the TTC changes for `%nomangle` instead of pretending the version of TTC from 10 days ago and this one are the same.
> bump TTC version for nomangle additions.

- libs/contrib/Data/List/Alternating.idr
- tests/contrib/list_alternating/AlternatingList.idr
- tests/contrib/list_alternating/expected
Adds the Alternating List `fst` and `snd` functions, which take the sublists of alternating lists corresponding to the odd and even elements, respectively. Named for consistency with the `Bi...` interfaces, and by analogy with `Pair`.
That is, `fst` and `snd` are the obvious non-trivial functions of type:
```idris
fst : Odd a b -> List a
snd : Odd a b -> List b
```
Also adds tests for these functions.
> Add Alternating List fst and snd functions

- docs/source/tutorial/starting.rst
I've figured out the genesis of the warning introduced at #1775. Sphinx (and, thus Github) requires every `rst` file to be either included using `.. include::` or included through table of contents (`toctree`) or explicitly orphaned. `windows.rst` does not conform to any of these.
What we can do is to include it as hidden into the `starting.rst` document, an addition to which `windows.rst` actually is. Unfortunately, you cannot add a `toctree` item between existing sections, only above them. So, if this PR is applied, `toctree` (table of contents on the left) starts looking like this:
i.e., prerequisites for windows are listed before the general prerequisites.
If you add a `toctree` directive to the "Prerequisites" section (not to the upper "Installing from Source", as it is in this PR), …
> [ doc ] Fix a complain of not being in a toctree

- libs/base/Data/List1.idr
Following up from https://github.com/idris-lang/Idris2/pull/2125
I wanted to implement lengthMap for List1 but idris2 couldn't simplify the expression because the List1.length function isn't public export.
```
lengthMap : (xs : List1 a) -> length (map f xs) = length xs
lengthMap (head ::: tail) = ?lengthMap_rhs_1
```
Here `lengthMap_rhs_1 : length (f head ::: map f tail) = length (head ::: tail)`
> make Data.List1.length public

- src/Idris/Doc/HTML.idr
In this pull request, the declaration code in the HTML document generated by `--mkdoc` option will be changed to be enclosed in `<code>`.
This should improve the semantic meaning of the generated HTML markup.
The "declaration part" here means the area shown in the screenshot below:
* A very similar past example was found in Rustdoc.
* Issue: [rustdoc, when I use google translate, that translate the doc as well as the code.](https://github.com/rust-lang/rust/issues/88020)
* Pull request: [[rustdoc] Wrap code blocks in `<code>` tag](https://github.com/rust-lang/rust/pull/88093)
> [ mkdoc ] Wrap declaration part in <code> tag

- src/Idris/Syntax.idr
- src/TTImp/Reflect.idr
- tests/Main.idr
- tests/idris2/reflection013/WithUnambig.idr
- tests/idris2/reflection013/expected
- tests/idris2/reflection013/run
+ also a cleanup and a cosmetic fix that do not worth their own PRs
This fixes a bug of unability to use `with <Constructor> <expression>` expressions under quotes (see added test for particular example).
> [ fix ] Use right reflection constructor name for unambiguing with

- src/Core/Binary.idr
- src/Idris/IDEMode/CaseSplit.idr
- src/Idris/IDEMode/Parser.idr
- src/Idris/Parser.idr
- src/Idris/ProcessIdr.idr
- src/Idris/Syntax.idr
- src/Parser/Rule/Source.idr
- src/Parser/Source.idr
- src/TTImp/Interactive/ExprSearch.idr
- src/TTImp/Interactive/GenerateDef.idr
- src/TTImp/Interactive/MakeLemma.idr
- src/TTImp/Utils.idr
- tests/idris2/interactive002/expected
- tests/idris2/interactive003/expected
- tests/idris2/interactive009/expected
- tests/idris2/interactive013/expected
- tests/idris2/interactive036/expected
- tests/idris2/interactive039/expected
- tests/idris2/literate001/expected
- tests/idris2/literate002/expected
- tests/idris2/literate006/expected
- tests/idris2/literate012/expected
- tests/idris2/literate016/expected
- tests/idris2/params003/expected
Once again breaking off a smaller subcomponent that probably works to minimise the diff.
As long as hole names are kept sufficiently different from that of toplevel functions by the user,
this should at least guarantee we don't generate clashes by ensuring we never have duplicated
hole names.
> [ re #1852 ] Partial fix without the Hole UN refactoring

- libs/base/Control/Function.idr
- libs/base/Data/Either.idr
- libs/base/Data/Fin.idr
- libs/base/Data/List/Elem.idr
- libs/base/Data/List1.idr
- libs/base/Data/Maybe.idr
- libs/base/Data/Nat.idr
- libs/base/Data/SnocList/Elem.idr
- libs/base/Data/Vect.idr
- libs/base/Decidable/Equality.idr
- libs/base/base.ipkg
- libs/contrib/Data/Container.idr
- libs/contrib/Data/Nat/Equational.idr
- libs/contrib/Data/Nat/Factor.idr
- src/Core/TT.idr
Add an `Injective` interface in `base` that you can call with `injective` or with `inj f` where `f` is the function over which the injection happens.
This is a copy of @nickdrozd 's PR with my commits added at the end, the preivous PR is here: #1761
> Injective interface and its implementations

- src/TTImp/ProcessRecord.idr
- tests/Main.idr
- tests/idris2/record012/Issue2065.idr
- tests/idris2/record012/expected
- tests/idris2/record012/run
This should fix issue #2065 (turning off prefix record projections ruins dependent records), and hopefully not change anything else.
> [ fix #2065 ] Use postfix projections if prefix ones are off

- src/Libraries/Text/Lexer/Core.idr
- src/Parser/Lexer/Source.idr
- tests/Main.idr
- tests/idris2/basic066/comment.idr
- tests/idris2/basic066/expected
- tests/idris2/basic066/run
- tests/idris2/basic067/expected
- tests/idris2/basic067/input
- tests/idris2/basic067/run
- tests/idris2/basic067/unclosed1.idr
- tests/idris2/basic067/unclosed2.idr
- tests/idris2/basic067/unclosed3.idr
This implementes request #2098: allow source files ending with unclosed comment blocks.
> [ fix #2098 ] Allow unclosed comment blocks

- support/c/idris_file.c
Other BSDs probably need this too but I've only tested on OpenBSD.
> Fix compilation on OpenBSD

- libs/base/Data/Fin.idr
- tests/base/data_fin001/expected
- tests/base/data_fin001/fromInteger.idr
- tests/base/data_fin001/run
- tests/idris2/basic042/expected
This PR fixes #2032 while being minimally invasive.
An example of the problem this is fixing is that following program typechecks very slowly (linear in the value of the constant):
```
import Data.Fin
addMillion : Int -> Int
addMillion x = 1000000 + x
```
The cause of the problem that even though `Data.Fin.fromInteger` is not called by this program, the typechecker tries to unify its type with the hole representing the type of `fromInteger` inserted before that literal constant. 
`Data.Fin.fromInteger` had the following type before this PR:
```
fromInteger : (x : Integer) -> {n : Nat} -> {auto 0 prf : So (fromInteger x < n)} -> Fin n
```
The problem is that `fromInteger x : Nat` in the proof obligation converts 1,000,000 to an unary `Nat` during typechecking, before finally rejecting it. …
> [ fix #2032 ] Slow typechecking on `Int` operation when `Data.Fin.fromInteger` is in scope

- src/Core/TT.idr
I set out to fix the display of implicitly bound values in goals but that seems a lot harder.
AFAIU for a definition `f` of type `f : a -> b -> a`, `f x y` is elaborated to `f {a = a@_} {b = b@_} x y`
and we should somehow find a way to ensure these `a` and `b` are marked as implicit.
In the meantime, may as well push this bug fix.
> [ fix ] isImplicit now works for all binders

- CHANGELOG.md
- src/Idris/Parser.idr
In response to #2178
I moved the doc-string up a few lines. Now it's right next to `module` which is close semantically to the command in question.
Also renamed the command to `package` to dispel confusion about its semantics (Assuming the word 'import' conveys the intention better than 'load').
> Rename `lp/loadpackage` to `package`

- docs/source/typedd/typedd.rst
- libs/base/Data/Bits.idr
- libs/contrib/Language/JSON/Data.idr
- src/Libraries/Utils/Hex.idr
- tests/base/data_bits001/BitOps.idr
- tests/chez/integers/TestIntegers.idr
- tests/node/integers/TestIntegers.idr
- tests/refc/integers/TestIntegers.idr
- tests/typedd-book/chapter11/Arith.idr
- tests/typedd-book/chapter11/ArithCmd.idr
- tests/typedd-book/chapter11/ArithCmdDo.idr
- tests/typedd-book/chapter11/ArithTotal.idr
- tests/typedd-book/chapter12/ArithState.idr
This was originally created during discussions at IDM but is was blocked by #2032. Since it's now fixed, we can consider this change.
Also, this PR contains a small cleanup as a separate commit.
> [ base ] Use `Fin n` as index in `Bits`

- libs/test/Test/Golden.idr
- support/c/idris_system.c
Manage the fact that `system()` can (and, actually, have to) use non-negative exit codes to mark an error, `127` in particular.
Also, manage the fact that some `libc` implementations (`glibc` in particular) do shift left the exit code by 8 bits for some reason:
- [how bad call is managed using `127` and `W_EXITCODE`](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/posix/system.c;h=48668fb392e67d1a84bb8ffef480e4237b7b4645;hb=HEAD#l180)
- [how good call is managed, using `__waitpid`](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/posix/system.c;h=48668fb392e67d1a84bb8ffef480e4237b7b4645;hb=HEAD#l171)
- [how `__waitpid` is implemented through `wait4`](https://sourceware.org/git/?p=glibc.git;a=blob;f=posix/waitpid.c;h=d46f57ea133454b5034473ba6a855494636f74cd;hb=HEAD#l38)
- …
> [ re #238 ] Fix program error condition of `git diff` call in `Golden`

- support/c/idris_system.c
I need to add this include on FreeBSD (probably also needed on other BSDs). I'm not sure why linux/macos build without it.
> idris_system: include sys wait

- .github/workflows/ci-idris2.yml
- .github/workflows/ci-super-linter.yml
The current super-linter v3 line is broken, they recommend to use the
v4 line: https://github.com/github/super-linter/issues/2253
Also pick a specific version, so that such transient linter bugs won't
camouflage as Idris CI failures.
> [ ci ] update previous version to v0.5.1, and super-linter to v4.8.5

- flake.lock
- flake.nix
https://github.com/NixOS/nixpkgs/pull/131833 has been merged.
> Use chez-racket from mainline Nixpkgs

- libs/base/System/Escape.idr
- libs/contrib/Search/Generator.idr
- libs/network/Network/Socket.idr
- libs/test/Test/Golden.idr
- src/Compiler/RefC/CC.idr
- src/Idris/IDEMode/Parser.idr
- src/Idris/IDEMode/SyntaxHighlight.idr
- src/Idris/ProcessIdr.idr
- src/Protocol/IDE.idr
- src/Protocol/IDE/Formatting.idr
- src/TTImp/Parser.idr
I am getting close to ready to put my unused import warning PR up for review. Here's another (small) round of unused import culling before I do.
Culling these imports as a separate PR helps keep the size of the warning PR down and removes noise as I troubleshoot actual problems with the warning PR as well. Separately, there is of course a code cleanliness gain to removing these imports.
> [cleanup] Small round of unused import culling.

- libs/contrib/System/Path.idr
Currently, the only function that `System.Path` provides to parse a `Path` from a `String` is `parse`, which silently fails by returning an empty path if the parsing fails. Often you want to know whether the parsing fails, so I've added a new function which returns a `Maybe` instead.
> Add 'tryParse' function to 'System.Path'

- nix/package.nix
- `idris2 --version` correctly displays hash again
- `idris2 --install <ipkg>` defaults to $HOME/idris2 instead of a
literal `~/.idris2`.
- allows building in Nix on latest MacOS
> [ nix ] fix bitrot

- CHANGELOG.md
Fix terminology spelling to adhere to the new super-linter rules
> Fix markdown linting

- CHANGELOG.md
Apparently, the older version of record syntax has now been deprectated.
This was not reflected in the CHANGELOG, and the CHANGELOG entry for an earlier version of Idris2 was erroneously updated to use the new syntax.
THis commit fixes the CHANGELOG.
> [ CHANGELOG ] Fix CHANGELOG.

- libs/base/Data/String.idr
- src/Core/Case/CaseBuilder.idr
- src/Core/Coverage.idr
- src/Core/Name.idr
- src/Core/Name/Namespace.idr
- src/Idris/Desugar.idr
- src/Idris/Doc/HTML.idr
- src/Idris/Doc/Keywords.idr
- src/Idris/Doc/String.idr
- src/Idris/Error.idr
- src/Idris/IDEMode/CaseSplit.idr
- src/Idris/IDEMode/Holes.idr
- src/Idris/ModTree.idr
- src/Idris/Package.idr
- src/Idris/Pretty.idr
- src/Idris/ProcessIdr.idr
- src/Idris/REPL.idr
- src/Idris/REPL/Common.idr
- src/Idris/REPL/Opts.idr
- src/Idris/SetOptions.idr
- src/Libraries/Data/String/Extra.idr
- src/Libraries/Text/Literate.idr
- src/Libraries/Text/PrettyPrint/Prettyprinter/Doc.idr
- src/Parser/Lexer/Source.idr
- src/Parser/Rule/Source.idr
- src/TTImp/ProcessDef.idr
When the effect of the `base` `String.lines` and `String.unlines` functions changed subtly a while back, a compatibility layer was added to the compiler and these `String` module functions were hidden.
This PR unhides and switches back to the `String` module versions of these functions. It also removes `replicate` from `Libraries.Data.String.Extra` because that function has since been ported to `base`.
> [cleanup] Unhide string module

- libs/contrib/System/Path.idr
- src/Libraries/Utils/Path.idr
Currently the operators for combining paths associate to the right, but it would be more convenient if they associated to the left instead. For example, currently you cannot write:
```idris
root /> "usr" /> "lib"
```
As this is parsed as:
```idris
root /> ("usr" /> "lib")
```
But `/>` takes a `Path` on the LHS and so this is invalid.
By making the operators associate to the left, you can write this example without any extra brackets.
> Change associativity for System.Path operators

- docs/source/backends/custom.rst
- tests/idris2/api001/LazyCodegen.idr
The example `lazy-idris2` was broken since PR https://github.com/idris-lang/Idris2/pull/1621. This PR fixes the example.
> Minor fix in documentation

- support/js/support.js
- tests/node/tailrec002/run
I was getting a stack overflow on the tailrec002 test, caused by this primitive being recursive. I've made it iterative. I'm no JS expert but I've tested its behaviour against the old version.
> Make prim_js2idris_array iterative

- docs/source/typedd/typedd.rst
The skeleton code in exercise 2 of Chapter 8.2.5 no longer type-checks with idris2.
From ohad in the Discord:
"Idris2 treats unbound implicits in a more sophisticated way than idris1, and the n that appears in your code is constrained to be the same n as the n that appears in the type of myReverse.
You want a helper function that's more general, where the length of the accumulator changes with each call"
> Update typedd.rst - Exercise 2 of 8.2.5

- libs/base/Data/String.idr
This looks like an oversight: `Data.String.words` is provably total, as all white space is dropped after each invocation of `break`. While it would be nice to actually have a proper proof of totality, this wasn't done for other functions like `Data.List.split` either, so I just went for the sledgehammer here.
> [ totality ] Data.String.words should be total

- src/Core/Binary.idr
- src/Idris/Desugar.idr
- src/Idris/Doc/String.idr
- src/Idris/Syntax.idr
This small change retains origin information for the fixity declaration for an operator.
I think this could be generally useful for various things, but it is specifically useful for the unused warning import feature I am working on -- modules like prelude's `Prelude.Ops` (declares nothing but fixities) can be imported and indeed required for an operator to be fully defined but without knowing that the operator's fixity came from that module it is not possible to determine the module has been "used."
> [ new ] Add fixities' FC to the syntax info.

- docs/source/backends/refc.rst
- src/Compiler/RefC/RefC.idr
Rename the functions stubs generated by RefC for RefC extensions.
This is a breaking change, but should only impact RefC extensions. To my knowledge, that is only the Python backend, which I already have a fix for.
This change reduces the chance of naming collisions. This is most obvious when two separate libraries bind the same foreign function, but can also occur between Idris functions and function stubs through a particularly poor choice of names.
This change also allows the use of special characters in the `%foreign` directive, that are not caught by `cName`. For example, `[` and `]`.
> Rename RefC extension function stubs

- libs/base/System/File/Buffer.idr
- tests/refc/buffer/TestBuffer.idr
This commits make `readBufferData` return the number of bytes that have been read. Without it, you cannot read the content of a file by chunks.
An example of how returning the number of read bytes can be used:
```haskell
||| Construct a `Stream` reading from a File
export
fromFile : HasIO m => File -> Stream (Of Bits8) m (Either FileError ())
fromFile file = (newBuffer 1024) >>= loop where
loop : Maybe Buffer -> Stream (Of Bits8) m (Either FileError ())
loop (Just buffer) = do
False <- liftIO $ fEOF file
| True => pure (Right ())
Right cap <- liftIO (rawSize buffer >>= Test.readBufferData file buffer 0)
| Left err => pure (Left err)
data' <- traverse (getBits8 buffer) [0..(cap-1)]
fromList_ data' *> loop (Just buffer)
```
> make readBufferData return the number of bytes that have been read

- support/js/support.js
This is a follow-up of #2267 . As noted correctly by @dunhamsteve, there should be a `let` in the `for` statement. While this is not strictly necessary, it can lead to nasty scoping bugs as described in [this stackoverflow reply](https://stackoverflow.com/questions/5717126/var-or-no-var-in-javascripts-for-in-loop).
Sorry, for not spotting this myself when I gave Edwin my OK on this.
> [ fix ] add let in JS array conversion

- CHANGELOG.md
- tests/refc/buffer/TestBuffer.idr
Just realized I missed this in #2274. This PR ensures that `readBufferData` returns the correct result.
> update refc/buffer to check how many bytes have been read

- src/Idris/Desugar.idr
- src/Idris/Parser.idr
- src/Idris/Pretty.idr
- src/Idris/Syntax.idr
- src/Parser/Lexer/Source.idr
- src/Parser/Rule/Source.idr
- tests/Main.idr
- tests/idris2/idiom001/Main.idr
- tests/idris2/idiom001/expected
- tests/idris2/idiom001/input
- tests/idris2/idiom001/run
- tests/idris2/perror007/expected
This PR adds new syntax for prefixing idiom brackets with namespaces: `Foo.Bar.[| x + y|]`. This will be desugared just like regular idiom brackets, but in the desugared version `pure` and `(<*>)` will be prefixed with the given namespace as well.
There are several reasons why I consider this to be useful:
- Symmetry: Just like do blocks can be disambiguated by prefixing `do` with a namespace, this should be possible for idiom brackets as well.
- Usefulness: Applicative functors compose, and it is quite common to apply a function over a nesting of applicatives. As shown in the example below, this is now possible with very little syntactic overhead.
Example (see also the new test case in `idris2/idiom001`):
```idris
namespace App2
public export
(<*>) : Applicative f => Applicative g =>
f …
```
> [ syntax ] Namespaced idiom brackets

- libs/contrib/contrib.ipkg
I get `Module Data.Seq.Internal not found` with `import Data.Seq.Unsized` if I do not have this change.
> [ fix ] expose Data.Seq.Internal

- libs/papers/Language/Tagless.idr
- libs/papers/papers.ipkg
This witnesses some of the current pain points:
1. I'd like to be able to make some interface parameters `auto`
2. Why are interface declarations leaking outside of their scope to the point where I need to hide them in `Section4`?
> [ new ] Dependent Tagless Final

- docs/source/typedd/typedd.rst
There is a difference between idris1 and idris2 which breaks backwards compatibility when trying to implement `(>>=)` to use `do` notation for a custom type. See https://github.com/idris-lang/Idris2/pull/1095 for details.
> Update TypeDD Chapter 11 for idris2

- src/Idris/Package/Init.idr
On Unix-like operating systems stdio.h is usually line-buffered. As
putStr uses fputs(3) from stdio.h internally, output will be written to
standard out after a newline character is written to the buffer. Since
the various prompts written by `idris2 --init` don't contain a newline
character they are buffered indefinitely. As such, the prompt strings
themselves are never presented to the user.
To fix this issue, this commit introduces a prompt utility procedure
which prints a prompt string and afterwards flushes standard output
before receiving input using getLine. This ensures that the prompt
string is always written before input is retrieved via getLine.
This is similar to c725b11c891b9f9f1e25ead66d9fc75a91b69836.
> [ fix ] Flush standard when prompting for package information

- libs/base/Language/Reflection/TTImp.idr
- src/Core/Binary.idr
- src/Core/Options/Log.idr
- src/Idris/Desugar.idr
- src/Idris/Elab/Implementation.idr
- src/Idris/Elab/Interface.idr
- src/Idris/Parser.idr
- src/Idris/Pretty.idr
- src/Idris/REPL.idr
- src/Idris/Resugar.idr
- src/Idris/Syntax.idr
- src/TTImp/Elab/App.idr
- src/TTImp/Elab/Case.idr
- src/TTImp/Elab/Quote.idr
- src/TTImp/Interactive/GenerateDef.idr
- src/TTImp/Parser.idr
- src/TTImp/ProcessDef.idr
- src/TTImp/Reflect.idr
- src/TTImp/TTImp.idr
- src/TTImp/TTImp/Functor.idr
- src/TTImp/Utils.idr
- tests/Main.idr
- tests/idris2/with007/With0.idr
- tests/idris2/with007/expected
- tests/idris2/with007/run
It's not solving the issue but it may be offering a workaround.
Example:
```idris
test : (0 n : Nat) -> Type -> Type
test n a with 0 (n + n)
_ | twon = a
```
> [ re #499 ] quantity-aware with-clauses

- libs/prelude/Prelude/Interfaces.idr
This enables us to do `map f @{Compose @{Compose}}` instead of `map f @{Compose @{(Compose, %search)}}` and `(>=>) a 
b @{Compose @{Compose}}` instead of `(>=>) a b @{Compose @{(Compose, %search, %search)}}` when the level is three.
> [ prelude ] Ease `Compose` compositions

- libs/prelude/Prelude/Interfaces.idr
The place is chosen to be near to the `Semigroup` and `Monoid` instances of `Alternative`.
> [ new ] Add a `Monoid` instance of the `f a` where `f` is `Applicative`

- libs/network/Network/FFI.idr
- libs/network/Network/Socket.idr
- support/c/idris_net.c
- support/c/idris_net.h
This add `recvAllBytes`, `recvBytes` and `sendBytes`, which are variants of `recvAll`, `recv`, and `send` but uses `List Bits8` instead of `String`.
This PR tackles #2211, #2307, and #2282
> [ network ] add binary support for socket + fix recvAll

- libs/base/Data/SnocList.idr
The scoping of the utility function meant that Idris treats `foldl f z (xs :< x)` and `f (foldl f z xs) x` as two different terms, making proving things about it difficult.
> Inline SnocList foldl utility function

- libs/base/Data/List.idr
- libs/base/Data/String.idr
I don't like `mergeReplicate` but it seems to be a bit faster than using `interleave (sep <$ xs) xs`.
> [ fix #2303 ] remove quadratic unwords

- CONTRIBUTING.md
- README.md
- docs/source/backends/index.rst
- docs/source/faq/faq.rst
- docs/source/libraries/index.rst
Hi, I'm new here. In fact I haven't yet even *read* the `CONTRIBUTING.md` file which I've edited :wink:
@andrevidela I believe *either* this PR should be merged, *or* your recent changes to https://github.com/idris-lang/Idris2/wiki should be reverted.
IMO using the GitHub wiki is usually a bad idea - it changes out of lockstep with the main repo, and often ends up being yet another place people put information. I'd rather see the info from the wiki included in the `docs/`. I understand that might require rethinking how it fits together with the rest of the documentation. Perhaps just merge my PR for the time being to fix the links? :smile:
> [doc] Fix wiki links

- src/TTImp/Elab/App.idr
This takes `Idris.Doc.String` from (crudely measured) 1m to 25s compile time.
Update: during a more classic build rather than my flawed measurement, it looks like it's nearly instantaneous.
> [ perf ] only normalise primitives on small strings on the RHS

- libs/contrib/Data/SortedMap.idr
- libs/contrib/Data/SortedSet.idr
Usual sorted maps have this, but existing code that uses `keySet` breaks when switching from a sorted map to a dependent one.
> [ contrib ] Add `keySet` function for dependent sorted maps too

- src/Core/Directory.idr
- tests/idris2/pkg011/expected
Following https://github.com/idris-lang/Idris2/pull/2134, I've lifted the `cleanPath` function and applied it to other functions in the `Core.Directory` module that output paths. Essentially this means that those functions do not output paths with interleaved `.` identifiers. This is visible from the updated test that is now consistent in the output both with and without the ipkg. Also some tools may have issues with those non-normalized paths, i.e. LSP uses the API and produced paths that were not recognized by some clients like neovim.
> Clean path in more `Core.Directory` functions

- libs/base/Control/Monad/Error/Either.idr
- libs/base/Control/Monad/Identity.idr
- libs/base/Control/Monad/Maybe.idr
- libs/base/Control/Monad/RWS/CPS.idr
- libs/base/Control/Monad/Reader/Reader.idr
- libs/base/Control/Monad/ST.idr
- libs/base/Control/Monad/State/Interface.idr
- libs/base/Control/Monad/State/State.idr
- libs/base/Control/Monad/Trans.idr
Some modules in `Control.Monad` are missing documentation and there is some inconsistency between documentation styles and wording in existing documentation. This pull request addresses those issues.
> Add documentation for Control.Monad.*

- libs/base/Control/WellFounded.idr
Control.WellFounded was completely lacking in documentation. This pull request fixes that, documenting all items and the module itself.
> [ doc ] for Control.WellFounded

- libs/base/Language/Reflection/TTImp.idr
This PR aligns the signature of `NoMangle` from `Language.Reflection.FnOpts` with the counterpart in `TTImp.TTImp.FnOpts'`.
It solves the following issue:
When entering the following in the repl:
```haskell
decl : List Decl
decl= `[export %nomangle myId : Int -> Int ; myId = id]
```
It outputs (I replaced the FCs for better readability):
```haskell
IClaim EmptyFC MW Export [NoMangle Nothing] (MkTy EmptyFC EmptyFC (UN (Basic "myId")) (IPi EmptyFC MW ExplicitArg Nothing (IPrimVal EmptyFC (PrT IntType)) (IPrimVal EmptyFC (PrT IntType)))),
IDef EmptyFC (UN (Basic "myId")) [PatClause EmptyFC (IVar EmptyFC (UN (Basic "myId"))) (IVar EmptyFC (UN (Basic "id")))]
```
When using the above to declare the function in `Elab` like this:
```haskell
declareMyId : Elab ()
declareMyId = declare [
IClaim …
```
> Signature of NoMangle from Language.Reflection.FnOpts

- src/Idris/Parser.idr
- tests/Main.idr
- tests/idris2/perror012/CaseParseError.idr
- tests/idris2/perror012/LamParseError.idr
- tests/idris2/perror012/expected
- tests/idris2/perror012/run
People often get confused by `->` vs. `=>`. This should hopefully make things nicer.
> [ parser ] better error messages for Haskellers

- src/Idris/Parser.idr
- remove unneeded totality assertions
- reformat `do`s to make changes to them a bit easier
- remove unneeded `the` type ascription
- (arguably) improve readability in couple of places
> [ cleanup ] Cleanup parser

- libs/base/Control/Function/FunExt.idr
OMG, only after merging I realised that I forgot to export the definition. Sorry
> [ re #2370 ] Add forgotten export clause

- idris2api.ipkg
- src/Core/Context.idr
- src/Core/Core.idr
- src/Idris/Desugar.idr
- src/Idris/Error.idr
- src/Idris/ProcessIdr.idr
- src/TTImp/ProcessDecls.idr
- src/TTImp/ProcessDecls/Totality.idr
- tests/Main.idr
- tests/idris2/failing003/FailingTotality.idr
- tests/idris2/failing003/expected
- tests/idris2/failing003/run
I had to program defensively against the fact that we usually check totality at the end of a file
but here do so in the middle and so may be finding out about partial definitions that have nothing
to do with the `failing` block.
> [ fix #2402 ] Check totality before exiting `failing` block

- CHANGELOG.md
- libs/contrib/Text/Parser/Core.idr
When writing parsers using the `contrib` library, it is often useful to be able to `show` the parse error (provided you can `show` your tokens).
> [ contrib ] Implement `Show ParsingError`

- src/Core/Context.idr
- src/Core/Core.idr
- src/Core/Unify.idr
- src/Idris/Error.idr
- Fix `Deprecated`, `PatternVariableUnifies`, `ParseFail`
- Added `fct` to `PatternVariableUnifies` so the second `fc` could be easily cleared
> Improve location killing

- src/Core/Binary.idr
- src/Core/Options/Log.idr
- src/Idris/Desugar.idr
- src/Idris/Doc/HTML.idr
- src/Idris/Doc/String.idr
- src/Idris/Package.idr
- src/Idris/Pretty.idr
- src/Idris/ProcessIdr.idr
- src/Idris/Syntax.idr
- support/docs/alternative.css
- support/docs/blackandwhite.css
- support/docs/default.css
- tests/ideMode/ideMode003/expected
Previously we were using namespaces as a poor approximation of
source file. We're now actually looking at the source file the
definition arose from in order to decide whether to keep it.
See e.g. base's Data.DPair for a drastic change.
Additionally, we sort definitions by definition location rather
than alphabetical order to respect the user's decision to introduce
some things before other.
> [ fix ] HTML doc contents

- libs/base/Debug/Trace.idr
I suggest to add such a function for simpler code when value should be traced and is not present with a name.
> [ base ] Add a `trace` variant easily embeddable to point-free expression

- libs/contrib/Data/List/Lazy.idr
Standard ones are not lazy for lazy lists
> [ contrib ] Add specialised `traverse_` and friends for lazy list

- docs/source/proofs/propositional.rst
``plusReducesR`` is introduced in "Theorem Proving / Propositions and Judgments" section [1] with the following signature:
``plusReducesR : (n:Nat) -> plus n Z = n``
But it seems that in "Proving Propositional Equality" [2]  ``n = plus n 0`` (mentioned in text after example) is proved instead.
This PR fixes ``plusReducesR`` implementation and proposition mentioned in text: ``plus n 0 = 0``
1. https://idris2.readthedocs.io/en/latest/proofs/definitional.html#propositions-and-judgments
2. https://idris2.readthedocs.io/en/latest/proofs/propositional.html#proving-propositional-equality
> [ doc ] Proving Propositional Equality: example fixed

- libs/base/Language/Reflection/TT.idr
- libs/base/Language/Reflection/TTImp.idr
This PR contains two significantly different commits. One removes unnecessary `partial` annotations and adds several totality assertions for recursive calls, mostly for lists of mutually-defined data. The second one adds two lacking clauses of recently added `Eq TTImp` and a bunch of `Eq` implementations that were required to implement those clauses.
> [ re #2423 ] Make `Eq` implementations in `Language.Reflection.TTImp` total

- docs/source/proofs/propositional.rst
Text above the code does not correspond to it (`x` and `y` are swapped). Since, it is an example starting in the previous section, I think it's better to fix arguments in the code and add some text clarifying why the argument's type in the code is different (comparing to the previous section) rather than having a discrepancy between code and text.
> [ doc ] Refine text about `rewrite` clause

- src/Core/AutoSearch.idr
- src/Core/TT.idr
- tests/Main.idr
- tests/idris2/interface029/FailedSearch.idr
- tests/idris2/interface029/expected
- tests/idris2/interface029/run
We currently try to solve the explicit arguments first (because they may force implicit ones)
and we don't distinguish between implicit & auto-implicit ones even though, because of
determining arguments, auto-implicit ones may also force implicit ones
> [ fix ] search should solve auto implicits before implicits

- Makefile
At the moment `make clean` on the main projects doesn't remove `.d` files from the `support` subdirectories.
It's problematic, as a classic `make clean install` would fail if we change dependencies in `c` backends.
> Remove .d files from c backends on make clean

- src/Idris/Parser.idr
- tests/Main.idr
- tests/idris2/perror015/ParseWith.idr
- tests/idris2/perror015/expected
- tests/idris2/perror015/run
A user on discourse was missing parens after `with` and couldn't figure out the issue from the compiler error message.
This PR changes the error message to:
```
1/1: Building ParseWith (ParseWith.idr)
Error: Expected '('.
ParseWith:2:12--2:13
1 | foo : Nat -> Nat
2 | foo a with a
^
```
> Better parse error for missing paren after with

- src/Compiler/RefC/RefC.idr
This causes issues whenever you have a FFI function taking `()` as an
argument. (Not that such a function is really useful, and I assume this
is the reason the issue hasn't been noticed so far.)
> [ fix ] Fix usage of `void` instead of `NULL` for Unit value in RefC

- libs/prelude/Prelude/Interfaces.idr
> [ doc ] Foldable's `all` is a conjunction

- libs/base/Control/Function/FunExt.idr
It is needed for more complex cases and better fits the type system ;-)
The type of existing function was changed (rather than a separate function added) because I didn't find any case where type inference didn't manage to work for old code with newer definition.
I also removed `0` for the function because it is inconvenient sometimes and anyway it does not matter for a fiction that is not meant to be implemented.
> [ base ] Change the `FunExt` interface to support dependent functions

- CHANGELOG.md
- libs/base/Decidable/Decidable.idr
`Given` with `Always` from Idris 1 library are completely overridden by `IsYes` and `ItIsYes` respectively in #950, and new ones have a more common naming. This, however, may break some very old code (which can be fixed by a trivial rename).
> [ re #950 ] Remove redunant legacy data definition

- libs/base/Data/Bits.idr
> Fix `FiniteBits` for `Bits64`

- libs/base/Language/Reflection/TTImp.idr
The current definition requires full reimplementation of all mutually recursive data types when we want a slightly alternative implementation of `TTImp` (real-world example: an equality up to renamings in `IPi` and `ILam`).
I propose a backward-compatible change that allows us to have a custom named `Eq TTImp` implementation while reusing implementations of all the other data types. For this, some of existing definitions were reordered and mutual block was replaced with a `parameters` block requiring `Eq TTImp` `auto`-implicit.
> [ refactor ] Support alternative `Eq` implementations for `TTImp`

- docs/source/cookbook/Calculator.idr
- docs/source/cookbook/LambdaCalculus.idr
- docs/source/cookbook/index.rst
- docs/source/cookbook/parsing.rst
- docs/source/index.rst
As part of the Idris Developer Meeting, I decided to scratch an itch by documenting the Text.Lexer/Text.Parser modules in a cookbook since I've had to figure out parsing using these modules around 3 times now.
I decided to include the original code for the lambda calculus parser and the calculator example in the docs so that folks could just include them rather than copying from the docs. If that isn't desirable, I can remove them.
> [ doc ] cookbook for parsing

- src/Idris/Doc/Keywords.idr
That way `:doc \` displays the code example correctly.
> Escape \ in the code example of lambdaAbstraction doc

- libs/base/Control/Function.idr
- libs/base/Data/Fin.idr
- libs/base/Data/List.idr
- libs/base/Data/List/Elem.idr
- libs/base/Data/List1.idr
- libs/base/Data/List1/Properties.idr
- libs/base/Data/SnocList/Elem.idr
- libs/base/Data/These.idr
- libs/base/Data/Vect.idr
- libs/base/Decidable/Equality.idr
- libs/base/Decidable/Equality/Core.idr
- libs/contrib/Data/List/Equalities.idr
- libs/contrib/Data/List/Palindrome.idr
- libs/contrib/Data/Validated.idr
I couldn't stop myself from doing this after recent additions ;-)
All commits contain different changes. The first commit is independent of the other two and I hope is not controversal, while invention of the new interface in the later commit may be. WDYT?
> [ cleanup ] Clean up `DecEq` implementations

- CHANGELOG.md
- src/Core/Options/Log.idr
- src/Idris/Package.idr
- src/Idris/Package/Types.idr
- src/Idris/SetOptions.idr
- tests/Main.idr
- tests/idris2/pkg006/depends/bar-baz/bar-baz.ipkg
- tests/idris2/pkg006/depends/quux/quux.ipkg
- tests/idris2/pkg010/expected.in
- tests/idris2/pkg010/run
- tests/idris2/pkg013/.gitignore
- tests/idris2/pkg013/depends/bar-0.7.2/bar.ipkg
- tests/idris2/pkg013/depends/foo-0.1.0/foo.ipkg
- tests/idris2/pkg013/expected
- tests/idris2/pkg013/expected.in
- tests/idris2/pkg013/gen_expected.sh
- tests/idris2/pkg013/run
- tests/idris2/pkg013/test.ipkg
This happens by installing the (modified) ipkg file along with ttc files
~~I can't think immediately of how to make a test for this, as in tests a custom version of idris is used with packages located in a non-standard place~~
added tests
fixes #2464
> make `depends` collect all transitive dependencies

- src/TTImp/Elab/Ambiguity.idr
- tests/Main.idr
- tests/idris2/reflection015/MacroRetFunc.idr
- tests/idris2/reflection015/expected
- tests/idris2/reflection015/run
This should be a fully backward-compatible change. In all previously working cases elaboration should produce expressions with the same meaning. But when it fails with `%runElab macroF arg1 arg2 arg3`, it successively tries `(%runElab macroF arg1 arg2) arg3`, `(%runElab macroF arg1) arg2 arg3`, etc. The longest argument lists inside `%runElab` are taken because of backward-compatibility **and** possible dependent types in a type of macro function (see tests).
Fixes #2493
> [ fix #2493 ] Put `%runElab` smartly in a call of `%macro`

- libs/contrib/Data/List/Equalities.idr
- libs/prelude/Prelude/Types.idr
Added following proofs to `contrib`:
- correspondence between bind and concatenation
- if x is an element of (xs ++ ys) it is an element of xs or ys
> List proofs

- src/Idris/REPL.idr
This PR adds showmachinenames  to the list of flags enumerated by the `:opts` command:
```
Welcome to Idris 2.  Enjoy yourself!
Main> :opts
showimplicits = False
showmachinenames = False
shownamespace = False
showtypes = False
eval = normalise
editor = vim
Main>
```
> Include "showmachinenames" in the output of :opts

- src/Core/Env.idr
- src/TTImp/Unelab.idr
- tests/Main.idr
- tests/idris2/debug001/expected
- tests/idris2/evaluator004/Issue1282.idr
- tests/idris2/evaluator004/expected
- tests/idris2/evaluator004/input
- tests/idris2/evaluator004/run
- tests/idris2/interactive017/expected
This improves the situation with #1282, but I wouldn't consider it a complete fix.
The general idea is to make `unelabCase` take TT instead of TTImp terms, because replacing variables in TT is much easier. The code still turned out a bit hacky IMO. (And also it's my first time looking deeper into the idris internals, so I may or may not know what I am doing.) But according to the tests it works fairly well (I only had to fix up 2 test cases).
> [ re #1282 ] Improve unelaboration of case expressions

- src/Core/Core.idr
`elimSemi` handles `Rig0` (= `plusNeutral`) first and `Rig1` second.
> Fix error message for LinearMisuse

- libs/base/Language/Reflection/TT.idr
- libs/base/Language/Reflection/TTImp.idr
- tests/idris2/reflection003/expected
* Decidable equality for names
* Prettier show instances (grouping similar Pi-arguments, prefix printing of infix names)
* `mapTTImp : (TTImp -> TTImp) -> (TTImp -> TTImp)` to easily modify all the TTImp nodes (e.g. apply `dropNS` to all the `IVar` ones)
> [ base ] Various `Language.Reflection` improvements

- libs/base/Language/Reflection/TTImp.idr
The only controversial thing I see in this change is the way I decided to print `LUknown` delayed type. But this type of expression rarely appears and I think it's important to show that this type is actually a some kind of lazy type when printing. I think, we don't have any adequate Idris syntax for this, so it's printed in the comment.
> [ re #2533 ] Fix printing of lazy types and values in `Show TTImp`

- libs/base/Data/String.idr
Small PR that removes the implicit argument from the documentation of `parseDouble`. I am guessing these examples were once copied `parseInteger`, which is polymorphic.
> Remove implicit argument in documentation for parseDouble

- CHANGELOG.md
- libs/base/Control/Monad/RWS/CPS.idr
- libs/base/Control/Monad/Writer/Interface.idr
Put the `RWST` argument to be the last one. This makes such functions to be easier used in point-free compositions and to be easily interchangeable with existing `runStateT`-like functions.
I ran into this when I wanted to replace `evalStateT s` by `evalRWST () s` to switch from `m a` to `m (a, w)`, but couldn't do it naturally because of different order conventions in `RWST` and the rest of transformers.
Pinging @stefan-hoeck as the person who added `RWST` into the `base` of Idris 2. Was the order intentional? I understand that this order is the original order of the Haskell implementation, but historically Idris had another (and subjectively, much better) order for `StateT` and `ReaderT` which allows partial point-free connections. I think, `RWST` should follow this convention.
> [ breaking ] Make arguments of `runRWST` be ordered like in other transformers

- libs/network/network.ipkg
I have no idea why `network.ipkg` lists its dependency on contrib in the `opts` field. I consider this to be really bad style, so I suggest we change this, which also will remove some manual dependency listing for *network* in pack's source code. In addition, this shows that actually the Idris compiler still transitively depends on contrib, although it doesn't make use of the `LIO` stuff. Therefore, an alternative to this would be to get rid of the `LIO` part altogether, and drop *network*'s dependency on contrib.
> [ cleanup ] add proper depends field to network.ipkg

- src/Idris/Package.idr
You can dump the intermediate code with `--dumpcases`, `--dumplifted`, and `--dumpvmcode`. But if you try to use `--dumpanf` you get the error:
```
Not all command line options can be used to override package options.
Overridable options are:
--quiet
--verbose
--timing
--log <log level>
--dumpcases <file>
--dumplifted <file>
--dumpvmcode <file>
--debug-elab-check
--codegen <cg>
--directive <directive>
--build-dir <dir>
--output-dir <dir>
```
This patch enables `--dumpanf`.
> Fix the --dumpanf command line switch.

- libs/base/System/Signal.idr
- support/js/support_system_signal.js
In support of #2207 
This attempts to add signal support to the node backend. This is my first attempt at any contributions to the Idris2 codebase, as such I'm going about this rather naively. You'll see that there are currently 3 stubbed out TODOs.
1. `defaultSignal`: This is tricky because it doesn't appear that node *has* default Signal handlers so we would have to decide on what the normal ones would be. and as best I can tell there isn't a way to "reset" the signal handler as best I can tell
2. `collectSignal`: Since this is stateful I wanted to check in here and see if creating a global variable in the `support_system_signal.js` file that maintains a data structure of currently pending signals is OK here or if there's a better approach
3. `handleNextCollectedSignal`: similar to …
> Support System.Signal for node backend

- tests/base/system_file_copyFile/run
- tests/contrib/system_directory_tree_copyDir/run
- tests/refc/buffer/run
Some of the tests fail on macos because the "base64" utility expects a `-i` switch in front of the input file.  The Linux version works both with and without the `-i`.  This PR updates the tests to add the `-i`.
> Update tests using base64 utility to also work on macos

- libs/base/Data/String.idr
- tests/base/data_string_parse_proof/StringParse.idr
- tests/base/data_string_parse_proof/expected
- tests/base/data_string_parse_proof/run
I recently wanted to jot down a little proof that a function was working but got caught on the last remaining private function in the way of the compiler evaluating natural number and integer string parsing.
> Allow for proofs involving parsing numbers from strings.

- src/TTImp/Elab/Binders.idr
- tests/idris2/reg051/expected
- tests/idris2/reg051/run
- tests/idris2/reg051/test.idr
On discord, @michaelmesser reported that this code:
```idris
Test : Type
Test = (case () of () => String) -> ()
```
gives this error message:
```
While processing right hand side of Test. Main.case block in Test is not accessible in this context.
```
The case is being turned into an erased top level function. which is then used in a non-erased context. To address the issue I changed `checkPi` in `Binders.idr` to keep the contextual quantity when processing the `argTy` of an `IPi` while in the `InExpr` elab mode (instead of forcing erased).
This passes tests and I believe it is correct, but I'd like someone more knowledgable to verify.
> Fix issue with case inside a Pi type.

- libs/base/System/Directory.idr
- libs/base/System/FFI.idr
- libs/base/System/File/ReadWrite.idr
This PR fixes the memory leak described in #2552 in addition to two other leaks.
The `fGetLine` function leaks 1kb for every line of text read by the compiler.  This happens because scheme is not freeing pointers returned from the C FFI.  (And, in the case of the getenv FFI, we don't want it to.)  This can be a problem with long running sessions like the REPL or idris2-lsp that reload lots of files.
The leaks and the fix were verified with the MacOS `leaks` utility and Linux `valgrind` utility (see #2552 for details).
> [ fix ] Fixes memory leaks in currentDir, fGetLine, and fGetChars

- src/Compiler/ES/Codegen.idr
Adds missing reserved keywords to JS backend so they are escaped properly in the output JavaScript.
Adds:
- all keywords that are always reserved (e.g. `this`...)
- all keywords that are reserved only in strict mode (e.g. `let`...)
- all keywords that are reserved only in modules or async functions (`await`)
- all future reserved keywords (`enum`)
- all future reserved keywords that are reserved only in strict mode (e.g. `public`...)
Reference list: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords
> [ fix ] Add missing reserved words to JS backend

- libs/base/Control/Monad/Error/Interface.idr
`Either e` and `EitherT e` have similar implementations for `MonadError e` and that's great. `Maybe` implements `MonadError ()` and this is great too. However, we don't have similar implementation for `MaybeT`.
I think, this should not clash with existing dropping-into implementation. Moreover, I think, one of the important reasons why one may use `MaybeT` in his stack is implementation for `MonadError ()`, that's why I think this implementation should be unnamed.
> [ base ] Implement `MonadError ()` for `MaybeT`

- INSTALL.md
Installing on Apple Silicon macs requires a special version of chez scheme. This PR adds instructions on how to do that and removes an outdated instruction that could cause users to build their support library for the wrong architecture.
I only updated the docs. If desired, we could also update the Makefile to set an appropriate CPATH when running on an Apple Silicon mac.  If libgmp is installed via homebrew, then you need to do:
```sh
export CPATH=/opt/homebrew/include/
```
to build Idris2.  
Further, if you want to build with the RefC backend, you need this environment when building your application:
```sh
export CPATH=/opt/homebrew/include/:/opt/homebrew/lib
export IDRIS2_LIBS=/opt/homebrew/lib
```
> [ doc ] Add instructions for installing chez scheme on M1 / M2 macs #2233

- CHANGELOG.md
- CONTRIBUTORS
- libs/network/Control/Linear/Network.idr
The `connect` function as defined by `Control.Linear.Network` currently only works if you obtained the raw socket object from `Network.Socket.socket` itself, leading to a possibly polluted namespace with both imported.
This changes the function to require a Socket in the `Ready` state.
As far as I understand sockets, this might *technically* be too constrained -- a client socket that `connect`s can also first `bind` itself (though it's not advised to do so?), but more importantly, according to the [connect(2)](https://man7.org/linux/man-pages/man2/connect.2.html) man page, certain protocol sockets may (disconnect and) reconnect multiple times. Tracking this however would probably need a more major change to the `Socket` data type to track its protocol, which I believe is probably out of …
> Fix typing of `connect` in network's Linear module, and add bytes-specific functions

- tests/idris2/interactive044/run
The test interactive044 randomly fails due to a timing issue.  I've seen this in CI and locally.
It copies a file and then runs an interactive session on it which generates a `.ttc` file and reloads.  Sometimes the `.ttc` file has the same timestamp as the source, causing it to be rebuilt on reload.  (Idris looks at the timestamps with a one second resolution and will rebuild if equal.) The rebuild emits an additional line of text causing the test to fail. 
I fixed the issue by adding a `sleep 1` after the file copy.
Below is a sample of two different outputs from running the test twice in a row locally:
```
dunham@peri interactive044 % ./run idris2
1/1: Building SplitShadowGen (SplitShadowGen.idr)
Main> colour (Emerald colour) = ?colour_rhs_6
Main> Loaded file SplitShadowGen.idr
Main> …
```
> [ test ] Fix timing issue in interactive044 test

- libs/contrib/Text/Parser/Core.idr
- src/Idris/Parser.idr
- src/Libraries/Text/Parser/Core.idr
- tests/Main.idr
- tests/idris2/perror016/ParseIf.idr
- tests/idris2/perror016/ParseIf2.idr
- tests/idris2/perror016/expected
- tests/idris2/perror016/run
- tests/idris2/with003/expected
I made an `if the else` typo the other day, and the error message pointed to the `if` saying that it expected an `if`.  This PR adds a `commit` after the `if` is accepted to improve error messages inside `if` statements.
Before:
```
1/1: Building perror016.ParseIf (perror016/ParseIf.idr)
Error: Couldn't parse any alternatives:
1: Expected 'case', 'if', 'do', application or operator expression.
perror016.ParseIf:3:10--3:12
1 |
2 | test : Int -> Int
3 | test a = if a < 10 the 0 else a
^^
```
After:
```
1/1: Building ParseIf (ParseIf.idr)
Error: Couldn't parse any alternatives:
1: Expected 'then'.
ParseIf:3:26--3:30
1 |
2 | test : Int -> Int
3 | test a = if a < 10 the 0 else a
^^^^
```
The second part is a bit more subtle. The PR also fixes an issue where an `Alt` will sometimes revert a …
> [ parser ] improvements to parser error messages

- CHANGELOG.md
- libs/base/Data/Fin.idr
This adds a theorem that's conceptually an inverse of `finToNatQuotient`.
I was a bit torn whether this should go to `base` or `contrib` (or anywhere at all), but since `finToNatQuotient` is already here, it feels natural to add its friend to this same module.
> [ base ] Add finToNatEqualityAsPointwise, an inverse of finToNatQuotient

- tests/idris2/interactive045/run
This is similar to #2644 - the test interactive045 randomly fails because the newly copied .idr file sometimes ends up with the same timestamp as its .ttc file.
> [ test ] Fix timing issue in interactive045 test

- support/js/support.js
This is a trivial fix of #2616, a potentially serious bug in the JS backends.
> [ fix ] issue 2616

- src/Idris/Parser.idr
- tests/idris2/perror016/ParseIf3.idr
- tests/idris2/perror016/expected
- tests/idris2/perror016/run
This PR adds a fatal error to `commitKeyword` to improve locality and accuracy of errors in the parser.
In Parser.idr, the description of `commitKeyword` is
```idris
-- Expect a keyword, but if we get anything else it's a fatal error
```
But it currently does not emit a fatal error (`commitSymbol` does emit an error). Because of this, missing keyword errors (for "in", "of", "then", and "else") can get swallowed and we just get a generic error at top level. 
With this change, instead of
```
Couldn't parse any alternatives:
1: Expected 'case', 'if', 'do', application or operator expression.
(Interactive):1:1--1:2
1 | (if True the 2 else 3)
^
... (90 others)
```
we get
```
Expected 'then'.
(Interactive):1:16--1:20
1 | (if True the 2 else 3)
^^^^
```
> [ parser ] Make commitKeyword fail fatally

- src/Idris/Elab/Implementation.idr
- tests/Main.idr
- tests/idris2/interface029/ForwardImpl1.idr
- tests/idris2/interface029/ForwardImpl2.idr
- tests/idris2/interface029/ForwardImpl3.idr
- tests/idris2/interface029/expected
- tests/idris2/interface029/run
Idris2 has syntax for forward declaring interface implementations by omitting the `where` at the end of the line. But it is not currently usable because the subsequent definition of the implementation will throw an `AlreadyDefined` error.  This PR fixes that by not emitting a second declaration, but checking that it converts to the first one.  This is the approach taken by forward declarations for `data`.
The patch should be double checked by someone more knowledgeable than me, but I believe it is correct, and it gets us closer to the goal of not requiring mutual.
Also note that, due to a parser bug that will be fixed by #2667, forward declarations of implementations must be followed by a declaration that begins with a keyword.
In the parser `implDecl` a missing `where` is indicated by a …
> [ new ] Handle forward declarations of implementations

- src/Idris/Parser.idr
- tests/Main.idr
- tests/idris2/perror017/ParseImpl.idr
- tests/idris2/perror017/expected
- tests/idris2/perror017/run
This change handles an error reported on discord.  The parser for an interface implementation was ignoring the column of the tokens when reading the arguments for an the interface's type constructor.
> [ parser ] Add indentation checks when parsing args in implDecl

- libs/base/System/Clock.idr
`showTime 4 12 $ makeDuration 312 123456` would previously give
`0312.123456000000` instead of `0312.000123456000`
Meaning the magnitude of nanoseconds were rarely accurate
> [ fix ] showTime pads nanoseconds properly

- support/gambit/support.scm
Patches the Racket bootstrap by adding `(require racket/unsafe/ops)` in `schHeader` (#2279).
Corrects a 🤦 mistake in Gambit support.scm (also from #2081).
I believe installing from a previous install works as is, so patching the bootstrap makes more sense than changing the support code.
> [ fix #2279 ] Racket bootstrap unsafe-fx

- src/Idris/Desugar.idr
- src/Idris/Resugar.idr
- src/TTImp/ProcessDecls.idr
- src/TTImp/Reflect.idr
- src/TTImp/TTImp.idr
- src/TTImp/TTImp/Functor.idr
- src/TTImp/TTImp/TTC.idr
- src/TTImp/TTImp/Traversals.idr
- src/TTImp/Utils.idr
- tests/Main.idr
- tests/idris2/perror019/ImplError.idr
- tests/idris2/perror019/expected
- tests/idris2/perror019/run
In the example below, you get an `Error: Implementation body can only contain definitions` located at `EmptyFC` (beginning of the file). So the user has no clue where the error is located. This patch changes the error to be located at the offending term.
```idris
data Foo = Bar
implementation Show Foo where
show Bar = "a Foo"
f
```
The root cause of this is that the `f` in the text below is interpreted as an interface implementation. That ends up as an `IPragma` which doesn't have an FC. I fixed it by adding an `FC` to `IPragma`.
Before change:
```
1/1: Building ImplError (ImplError.idr)
Error: Implementation body can only contain definitions
```
After change:
```
1/1: Building ImplError (ImplError.idr)
Error: Implementation body can only contain definitions
ImplError:5:3--5:4
1 | data …
```
> [ parse ] Add fc to IPragma for better error messages

- CHANGELOG.md
- libs/base/System.idr
- tests/node/args/TestArgs.idr
As discussed on discord: The node backend comes with an additional command line argument listing the path to the `node` executable. This is inconsistent with other backends, which only list the path to the running program as their first command line argument. For consistency, this PR removes said first argument from the list of command line args on the node backend.
> [ fix ] drop first command-line arg on node

- libs/test/Test/Golden.idr
I suggest to split the existing `runner` function to those which reads options from command-line arguments and those which performs all the rest, i.e. stuff about tuning the options, actual running and processing the results. This is needed to be able to run golden tests not only giving all the options through command line, while having the same printed result and exit code behaviour.
> [ golden ] Split runner to be able to run with custom options

- src/Compiler/Opts/ConstantFold.idr
- tests/chez/constfold/Check.idr
- tests/chez/constfold/Fold.idr
Literals for natural numbers are now constant folded by giving function `prim__integerToNat` some special treatment. In addition, the existing test case for constant folding was extended with this use case.
This enables constant folding for other arithmetic expressions involving natural numbers.
> [ performance ] constant fold prim__integerToNat

- libs/papers/Data/W.idr
Recently several modules were added to the `paper` lib, and one of them contains a postulate which leads to a warning each time one builds a compiler. The main reason for this PR is to remove this warning.
Since this is a postulate, one could just make it explicit, say with `believe_me`, and warning would be gone while postulate would stay a postulate. But I decided to suggest an implementation for this hole, since the standard library contains an interface which can be used as an external postulate. As far as I can see, this anyway does not break any idea inside this module, does it?
Unfortunately, for this trick a bunch of lines are indented, thus two-line change looks big in diff.
> [ papers ] Implement a postulate hole by requiring a special interface

- src/Idris/Desugar.idr
- src/Idris/Desugar/Mutual.idr
- src/Idris/Parser.idr
- src/Idris/Resugar.idr
- src/Idris/Syntax.idr
- src/Idris/Syntax/Traversals.idr
- tests/Main.idr
- tests/idris2/record018/expected
- tests/idris2/record018/mut.idr
- tests/idris2/record018/run
This change allows users to forward declare `record`, like they can for `data`, by omitting the `where` clause. The implementation follows the pattern of same functionality for `data`.  After the change you can do:
```idris
record B
record A where
b : B
record B where
a : A
```
instead of
```idris
mutual
record A where
b : B
record B where
a : A
```
> [ new ] Allow forward declarations of records

- docs/source/tutorial/multiplicities.rst
Idris will treat a number as an `Integer` by default, it's required to make the `Int` explicit to ouput 94.
> make the Int type explicit

- docs/source/tutorial/typesfuns.rst
`p` was used for both the filter predicate and the length of the filtered vector. This renames the latter to `n'`.
Thanks to ruchira for reporting this on the Discord.
> Reduce ambiguity in dependent types `filter` example

- src/Idris/Doc/String.idr
- tests/idris2/docs001/expected
- tests/idris2/interactive019/expected
I don't think there's a good solution at least until we start parsing these comments so let's just keep them as they were written by the library writer.
> [ fix #2721 ] Don't reflow doc lines

- libs/base/Control/Monad/Reader/Reader.idr
- tests/base/control_monad_instances/SearchReader.idr
- tests/base/control_monad_instances/SearchState.idr
- tests/base/control_monad_instances/SearchWriter.idr
- tests/base/control_monad_instances/expected
- tests/base/control_monad_instances/run
Instance of `MonadReader` cannot be automatically found for the current definition of `Reader`. This PR introduces a small change to `Reader` definition that fixes this along with the test checking that `MonadReader`, `MonadWriter` and `MonadState` could be found for `Reader`, `Writer` and `State` respectively.
> [ base ] Change `Reader` to fix search for `MonadReader` instance

- .github/workflows/ci-idris2.yml
- flake.nix
- nix/bootstrap.nix
This PR changes the nix build scripts to bootstrap idris and then use the bootstrapped compiler to build the final version. It also reenables CI for nix. This addresses #2087 for nix.
Previously, the nix scripts would test and install the copy of Idris built by the bootstrap compiler. The bootstrap compiler doesn't handle multiline strings properly, so the resulting compiler failed test `idris2/repl005`. 
To accomplish this, I duplicated `package.nix` as `bootstrap.nix` and changed `package.nix` to use the idris compiler in the result of `bootstrap.nix`.
I'm somewhat new to nix, so it would be good to have this reviewed by someone who knows idiomatic nix.
> Update nix build scripts to build Idris with the current version of Idris #2087

- Release/CHECKLIST
- libs/linear/linear.ipkg
- libs/papers/papers.ipkg
This might be an oversight. It leads to issues with pack, which uses the same version for all libraries from the Idris2 project. If this was left at 0.5.1 on purpose, feel free to close this and I'll fix pack instead.
> [ fix ] bump version of linear and papers packages

- src/Idris/Desugar.idr
- tests/Main.idr
- tests/idris2/error024/Error1.idr
- tests/idris2/error024/expected
- tests/idris2/error024/run
When there is a type mismatch on a bang expression, the error message doesn't point to the original source location.  This PR adds an appropriate virtual FC to the bang variable. (This issue was reported by @andorp on discord.)
For the test case:
```idris
foo : Int -> IO Int
foo x = pure x
main : IO ()
main = putStrLn !(foo 10)
```
Before this change, Idris would show:
```
1/1: Building tests.idris2.error024.Error1 (tests/idris2/error024/Error1.idr)
Error: While processing right hand side of main. When unifying:
Int
and:
String
Mismatch between: Int and String.
```
After the change, it shows:
```
1/1: Building Error1 (Error1.idr)
Error: While processing right hand side of main. When unifying:
Int
and:
String
Mismatch between: Int and String.
Error1:5:17--5:26
1 | foo : Int -> IO Int
2 | …
```
> [ parser ] Better error messages for type mismatch on bang expressions

- src/Idris/CommandLine.idr
- src/Idris/Driver.idr
This adds a new command for printing the current value of `Core.Binary.ttcVersion`. Tools like pack require this, because they need access to the `.ttc` files built by Idris, which are now hidden behind a directory consisting of this version number. For instance, pack is no longer able to use katla to generate semantically highlighted html docs, because it can no longer find the corresponding `.ttc` files.
It looks like this has been an issue for several days now, but it has only shown up because katla was adjusted to more often fail with a non-zero exit code.
> [ new ] add --ttc-version command

- CHANGELOG.md
- src/Idris/Doc/String.idr
Adds the ability to get help for unquotes through `:doc ~( )` at the REPL
> [ doc ] Add :doc for unquotes

- src/Core/Directory.idr
Prior to https://github.com/idris-lang/Idris2/pull/2684, any `lib` folder found in the `$(idris2 --libdir)/package-dir/` directory would be searched for `so` or `dylib` files that might need to be copied into the `_app` directory of an executable produced by the Chez Scheme backend.
After the TTC PR (2684), this stopped working because such directories were removed from the list of "extra" directories and added to the list of "package" directories. This move in isolation makes sense -- we are talking about a package directory, after all. So, this PR fixes the `lib` folder searching by adding these package directories to the list of searched paths in the `findLibraryFile` function that is ultimately responsible for locating the `so`/`dylib` files in question.
> [fix] look for lib folders in package directories.

- CHANGELOG.md
- support/c/idris_support.c
Seems there might be some oddities with what is reported when, e.g. reporting the maximum number of processors supported by the currently installed motherboard, regardless of which processor is socketed.
I hope this fixes things, but I'm waiting on confirmation.
> [ re #2742 ] Count no. processors online rather than configured

- libs/base/Data/Fin.idr
We don't need `n` at runtime to convert `x` from an `Integer` to a `Fin n`.
> Erase Fin fromInteger upper bound

- src/Idris/Elab/Interface.idr
- src/TTImp/ProcessRecord.idr
- tests/Main.idr
- tests/idris2/perror020/Issue2769.idr
- tests/idris2/perror020/Issue2769b.idr
- tests/idris2/perror020/expected
- tests/idris2/perror020/run
If a record constructor or interface constructor is given a name that is already defined, the error message ends up at EmptyFC. This was reported as #2769.
This PR places the error message on the entire record/interface expression to avoid having to change TTimp to add an FC for the constructor name.
For the code:
```idris
module Issue2769
record SomeRecord where
constructor SomeRecord
field : Int
```
The message before the patch is:
```
1/1: Building Issue2769 (Issue2769.idr)
Warning: No incremental compile data for Prelude
Error: Issue2769.SomeRecord is already defined.
```
and after the patch it is
```
1/1: Building Issue2769 (Issue2769.idr)
Error: Issue2769.SomeRecord is already defined.
Issue2769:3:1--5:14
3 | record SomeRecord where
4 |   constructor SomeRecord
5 |   field : Int
```
> [ error ] Improve error messages on record and interface constructors (#2769)

- docs/source/app/exceptionsstate.rst
Exception is no longer an interface but just a synonym of ``HasErr``. Updated docs to reflect this.
> Altered for ``Exception`` to reflect the code changes in Control.App

- CHANGELOG.md
- src/TTImp/Elab/Check.idr
- tests/Main.idr
- tests/idris2/error025/IAlternativePrints.idr
- tests/idris2/error025/expected
- tests/idris2/error025/run
At the moment if all alternatives of `IAlternative` with `FirstSuccess` rule are failing, only the last error is printed, which can be misleading.
> [ error ] Make failing `IAlternative` w/ `FirstSuccess` print all errors

- CHANGELOG.md
- libs/base/Data/Buffer.idr
- src/Core/Binary/Prims.idr
- tests/chez/chez004/Buffer.idr
- tests/refc/buffer/TestBuffer.idr
There is a comment preceding `setByte` saying we assume the value is in the range 0-255. This is enforced by the `Bits8` version, and so it should be preferred.
Deprecating for now, in order to not break external code which may rely on `setByte`.
> [ base ] Deprecate setByte in favour of setBits8

- src/Idris/IDEMode/REPL.idr
**Why:**
Makes the error message being displayed twice in Emacs. 
This change aligns IDEMode/REPL.idr with Idris/REPL.idr which works as expected.
See https://github.com/idris-lang/Idris2/blob/main/src/Idris/REPL.idr#L1241-L1242
Before change:
After change:
Relates to:
https://github.com/idris-hackers/idris-mode/pull/563
> [ ide-mode ] Do not include whole error message in building file display result message.

- src/Idris/Parser.idr
- tests/Main.idr
- tests/idris2/perror021/Implicit.idr
- tests/idris2/perror021/expected
- tests/idris2/perror021/run
Errors in an implicit argument bubble up to the top level, leaving the user to guess at the error location.  I fixed this issue by adding a `mustWork` after the `{` is parsed. Using `commit` is not sufficient because a parent `<|>` doesn't see it.
For this code:
```idris
import Data.Vect
myReverse : Vect n el -> Vect n el
myReverse [] = []
myReverse {n = S k} (x :: xs) =
replace {p=\n => Vect n el} (plusCommutative k 1) (myReverse xs ++ [x])
```
The current error message is:
```
1/1: Building Implicit (Implicit.idr)
Error: Couldn't parse declaration.
Implicit:5:1--5:10
1 | import Data.Vect
2 |
3 | myReverse : Vect n el -> Vect n el
4 | myReverse [] = []
5 | myReverse {n = S k} (x :: xs) =
^^^^^^^^^
```
And the message after this patch is:
```
1/1: Building Implicit (Implicit.idr)
Error: …
```
> [ error ] Improve parse errors in implicit arguments

- .github/workflows/ci-idris2.yml
- src/Compiler/RefC/CC.idr
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/ChezSep.idr
- src/Compiler/Scheme/Gambit.idr
- src/Compiler/Scheme/Racket.idr
- src/Idris/REPL.idr
Follow on from #2096. Use the new escaped version of `system` in the source of Idris itself.
This closes a couple of potential security holes, and makes the handling of these sorts of issues more uniform.
This PR will fail tests until the next version bump. I'm submitting the PR now, so that I don't forget about it.
> Use escaped version of `system` internally

- libs/base/Data/Vect.idr
I've found myself needing to prove something about the behavior of `Vect`'s `reverse`, and I wasn't able to do that since `go` is a `where`-local binding in `reverse`. Moving it out (along the lines of `Data.List` implementation) simplifies proving things about `reverse`.
> [ base ] Move the worker outside of the Vect's `reverse` definition

- src/Idris/Parser.idr
- tests/Main.idr
- tests/idris2/perror022/Indent.idr
- tests/idris2/perror022/expected
- tests/idris2/perror022/run
This issue was reported by "Oxy" on discord.  
When parsing record params on forward record declarations, the Idris parser is not checking indentation and may interpret a subsequent top level line as part of the record declaration.  
So this valid code:
```idris
record Rec (a : Type)
b : Int
```
yields the following error:
```
1/1: Building Indent (Indent.idr)
Error: Expected 'where'.
Indent:2:3--2:4
1 | record Rec (a : Type)
2 | b : Int
^
```
This patch fixes the issue by adding an indentation check in front of each parameter.
> [ parser ] fix issue where indentation is not checked in record params

- .github/workflows/ci-bootstrap.yml
- .github/workflows/ci-idris2.yml
According to [this](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), `set-output` feature will be deprecated. Now CI already prints warning during run. There is suggested change that does the same, but is not deprecated, thus let's use it.
> [ ci ] Replace deprecated feature with its functional equivalent

- src/Core/TT.idr
As remarked by Edwin, it's worth cherry picking as it makes a big difference.
Takes compilation of idris2+libs (after `make distclean`) from 6m25s to below 6m.
> [ perf ] cherrypick fast weakenNVar from yaffle

- src/Core/CompileExpr/Pretty.idr
- src/TTImp/Elab/Ambiguity.idr
The auto search in the pretty instances is just too damn expensive.
It still takes 4s so we should be able to squeeze some more perf out of this.
> [ perf ] compile Core.CompileExpr.Pretty faster

- src/Idris/Parser.idr
- src/Parser/Rule/Source.idr
- tests/Main.idr
- tests/idris2/perror023/ParseError.idr
- tests/idris2/perror023/expected
- tests/idris2/perror023/run
- tests/idris2/perror024/ParseError.idr
- tests/idris2/perror024/expected
- tests/idris2/perror024/run
Currently, using a reserved identifier or keyword on the LHS of a type claim gives a generic error message.
```idris
-- Fails with "Couldn't parse declaration"
String : Type
```
This might be confusing for new users.
I have updated the error messages:
```idris
Error: Cannot begin a declaration with a reserved identifier.
Test:4:1--4:7
1 | module Test
2 |
3 |
4 | String : Type
^^^^^^
```
```idris
Error: Keyword 'module' is not a valid start to a declaration.
Test:4:1--4:7
1 | module Test
2 |
3 |
4 | module : Type
^^^^^^
```
The error message is still poor when the reserved identifier is namespaced:
```idris
-- Fails with "Couldn't parse declaration"
X.String : Type
```
However I don't think this is a major problem as predeclaring names in other modules is an advanced use case, whereas this …
> Improve parser error messages when using reserved identifiers in decls

- src/Idris/Desugar.idr
- tests/Main.idr
- tests/idris2/namespace003/Test.idr
- tests/idris2/namespace003/expected
- tests/idris2/namespace003/run
This can come in handy when one deploys their own namespace with a subset of `pure`, `>>=`, `>>`, `<*>` overloaded in it and where one uses the qualified do-notation to disambiguate monad-style code.
> Let qualified do-notation apply to `pure` and to idiom brackets

- .github/workflows/ci-idris2.yml
- src/Idris/Package.idr
- tests/idris2/pkg010/expected.in
Paving the way for Katla to generate docs for all install modules.
> Install *.ttm on `idris2 --install`

- src/TTImp/Interactive/Completion.idr
Auto-complete logging topics in the emacs REPL via the IDE-mode.
> [ new ] logging topics autocompletion in the emacs REPL

- src/Idris/Parser.idr
- tests/Main.idr
- tests/idris2/perror025/DataWhere.idr
- tests/idris2/perror025/expected
- tests/idris2/perror025/run
This makes the error message ever so slightly more helpful if you forget the `where` keyword in a data declaration.
before:
```
1/1: Building test (test.idr)
Error: Expected end of input.
test:3:1--3:5
1 | module Main
2 | 
3 | data Foo : Type
^^^^
```
after
```
1/1: Building test (test.idr)
Error: Expected 'where'.
test:4:7--4:8
1 | module Main
2 | 
3 | data Foo : Type
4 |   Bar : String -> Foo
^
```
admittedly one might want to point in front of the `Bar` or underline it (I don't know yet how to do that, though)
> Add `mustWork` in GADT data declaration parser

- CHANGELOG.md
- idris2api.ipkg
- src/Compiler/Opts/CSE.idr
- src/Compiler/Opts/ToplevelConstants.idr
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/ChezSep.idr
- src/Compiler/Scheme/Common.idr
- src/Compiler/Scheme/Gambit.idr
- src/Compiler/Scheme/Racket.idr
This replaces #2807 : Non-recursive top-level constants are compiled to eagerly evaluated constants in Chez Scheme. In order to do this, they have to be added in the correct order. In addition, shared objects need to be loaded *before* the actual code, because they might already be needed when constants get eagerly evaluated.
This has a significant impact on performance: On my system, typechecking `idris2api.ipkg` goes from 3:40 minutes down to slightly below 3 minutes.
> [ performance ] Compile non-recursive top-level constants to constants in Chez

- support/chez/support.ss
Make `System.os` able to detect a "unix" system on AArch64 / ARM64
Testet on Linux/AArch64, but since Chez' `(machine-type)` follows a predictable pattern, I added the BSDs and Windows as well.
Not necessary, it's a minor fix.
> [chez] Detect AArch64 machine/OS combinations correctly

- libs/base/System/Clock.idr
- support/js/support_system_clock.js
`clockTimeProcess` and/or `clockTimeThread` may behave incorrectly when used with web workers
As idris doesn't currently have any control over js threads/WebWorkers, I think this is unavoidable
> add javascript support to `System.Clock`

- src/TTImp/WithClause.idr
- tests/Main.idr
- tests/idris2/with011/WithImplicits.idr
- tests/idris2/with011/expected
- tests/idris2/with011/run
Fix an issue where an @-pattern is leaked into the right side.  It occurs in a recursive call to a `with` clause if there are @ patterns and implicits. A typo in the function `getMatch` causes the left hand side to be used for the right hand side after an implicit is hit. 
**Should this change go in the CHANGELOG?**
This PR is just a bug fix, so it probably doesn't need a change log entry.  Let me know if it should have one.
> [ fix ] at-pattern leak in recursive with blocks (#2834)

- src/Idris/Package.idr
I propose that we allow library packages to ship "data" to a standard location within their install directory.
Although I am not familiar with the full breadth of uses of what Idris 2 calls "data directories" I do know that one established use is to include support JavaScript libraries into the build output when building an executable with the Node backend.
For example, if you have a foreign pragma such as:
```idris
%foreign "node:support:say_hello,util"
```
Then you should (a) create a file named `util.js`, (b) put it somewhere under a `js` subdirectory (e.g. `<your-project>/support/js/util.js`), and (c) add the parent folder (e.g. `<your-project>/support`) as a data directory when building your executable.
This is all fine when you are writing your support JS as part of the same project …
> [ new ] [ proposal ] Allow libraries to ship a data dir

- idris2api.ipkg
- src/Compiler/Common.idr
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/ChezSep.idr
- src/Compiler/Scheme/Common.idr
- src/Compiler/Scheme/Gambit.idr
- src/Compiler/Scheme/Racket.idr
- src/Libraries/Data/String/Builder.idr
this makes it about 50x faster at printing scheme code
I used this python script to generate a huge idris file:
```python
count = 100
out = "" 
out += "plus : Nat -> Nat = (+)\n"
out += "%noinline\n"
for i in range(count):
out += "f" + str(i)
if i < count - 1:
out += ", "
out += " : Nat -> Nat\n"
pluses = "x"
for i in range(500):
pluses = "plus x (" + pluses + ")"
for i in range(count):
out += "f" + str(i) + " x = " + pluses + "\n"
out += "main : IO ()\n"
out += "main = do\n"
for i in range(count):
out += "    printLn $ f" + str(i) + " 100\n"
print(out)
```
I added a call to `logTime` to this line: https://github.com/idris-lang/Idris2/blob/main/src/Compiler/Scheme/Chez.idr#L564
Previously it took 1.193s to pretty print the scheme code, with this change it takes 0.026s, a roughly 50x …
> [ performance ] String builder on all scheme backends

- CHANGELOG.md
- libs/prelude/Prelude/Types.idr
- tests/idris2/record019/expected
This improves performance for functions `isSpace`, `isNL`, and `isHexDigit`.
Using [idris2-profiler](https://github.com/stefan-hoeck/idris2-profiler), I ran a small micro benchmark on these (see next section on how to reproduce this):
```
char functions/isHexDigit/new                        2.497 μs   3.075 μs 0.998
char functions/isHexDigit/old                        31.64 μs   32.17 μs 0.999
char functions/isSpace/new                           1.785 μs   1.850 μs 0.999
char functions/isSpace/old                           2.784 μs   2.957 μs 0.997
char functions/isNL/new                              1.673 μs   1.792 μs 0.999
char functions/isNL/old                              1.728 μs   1.820 μs 0.999
```
In an empty dir, add file `bench.ipkg` with the following content
```
package …
```
> [ performance ] improve some Char functions

- support/js/support.js
This is approximately twice as fast on node (which uses V8), and over 4 times faster on firefox (SpiderMonkey)
here is the program used to benchmark it
```js
let perf
try {
perf = performance
} catch {
perf = require("perf_hooks").performance
}
const trunc_1_s = x => {
const res = x & 0xffffffffffffffffn;
return res >= 0x8000000000000000n ? res - 0x10000000000000000n : res;
}
const trunc_2_s = (x) => BigInt.asIntN(64, x)
const bench = (trunc) => {
const ITERS = 1000000;
const RUNS = 100;
let times = [];
for (let run = 0; run < RUNS; run++) {
const start = perf.now();
let res = new BigInt64Array(ITERS);
for (let i = 0; i < ITERS; i++) {
let x0 = res[i];
let x1 = trunc(x0 + 100n);
let x2 = trunc(x1 * 100n);
let x3 = trunc(x2 - 6n);
let x4 = trunc(x3 && 755n);
let x5 = trunc(x4 * 6n);
res[i] …
```
> Use built-in bigint truncation on js backend

- CHANGELOG.md
- libs/base/Data/Vect/Quantifiers.idr
I've included 3 separate small commits for QoL improvements on `Data.Vect.Quantifiers.All`. I am ok with these commits being individually approved/denied and will drop any commits that aren't deemed worthwhile.
1. Add a `Show` instance for `Data.Vect.Quantifiers.All`. Super minor, but definitely convenient. Precedent is set here by the `Show` instance for `Data.List.Quantifiers.All`.
2. Add an alias for `HVect` to `Data.Vect.Quantifiers.All`. There is a fully separate `HVect` type in the `contrib` library, but for 95% of operations I don't need the helpers defined against the contrib type (and if I do, they can be written against `All` anyway, so I just do that myself at that time). I've seen `All id` be recommended many times for an `HVect` type in various forums as well, so I believe …
> [new] Vect.Quantifiers.All QoL

- CHANGELOG.md
- libs/prelude/Prelude/Types.idr
- tests/base/deriving_foldable/DeriveFoldable.idr
- tests/base/deriving_traversable/DeriveTraversable.idr
- tests/base/deriving_traversable/expected
- tests/idris2/record019/expected
`Either` is bitravesable, right-biased functor and right-biased traversable. `Pair` is bitravesable, right-biased functor, but is not a traversable. This PR fixes this surprising irregularity.
> [ prelude ] Add lacking implementation of `Traversable` for `Pair`

- config.mk
gmp is located in `/usr/local/{include,lib}`.
With this patch, to build on FreeBSD:
```
$ sudo pkg ins chez-scheme gmp
$ cd Idris2 && gmake bootstrap SCHEME=chez-scheme && gmake install
```
> Fix build on FreeBSD

- .github/workflows/ci-bootstrap.yml
- .github/workflows/ci-idris2.yml
- .github/workflows/ci-lint.yml
- .github/workflows/ci-sphinx.yml
- .github/workflows/ci-super-linter.yml
- Update GitHub Action versions.
- Fix logic around `needs.initialise` (the newer version of GitHub's linter actually caught this problem).
- Re-enable a fixed Nix CI stage.
- Rename an ENV var and add clarity to the inline documentation.
> CI Maintenance

- CHANGELOG.md
- libs/base/System.idr
We should not print error messages to stdout
> [ base ] fix the definition of die

- libs/test/Test/Golden.idr
- src/Idris/Driver.idr
- src/Idris/Env.idr
- src/Idris/Pretty/Render.idr
- tests/idris2/pkg006/expected
- tests/idris2/pkg006/run
Closes https://github.com/idris-lang/Idris2/issues/1917.
I know that this works well in my testing of various Idris 2 CLI options and the REPL.
Would someone be willing to sanity check this works for IDE mode / emacs? It absolutely ought to, but seeing as how that was the express reason for checking `TERM` for "dumb" I'd like to be more confident than I am as a non-emacs user.
> [ fix ] make color output toggling simpler and also more robust.

- libs/prelude/Prelude/Basics.idr
- tests/Main.idr
- tests/idris2/total014/FunCompTC.idr
- tests/idris2/total014/expected
- tests/idris2/total014/run
This change enables equivalent changes like between `f_expl` and `f_impl` below to typecheck.
```idris
%default total
data X : Type where
B : X
T : r -> (r -> X) -> X
f_expl : (X -> X) -> X -> X
f_expl f B       = f B
f_expl f (T k g) = T k $ \n => f_expl f $ g n
f_impl : (X -> X) -> X -> X
f_impl f B       = f B
f_impl f (T k g) = T k $ f_impl f . g
```
In status quo `f_impl` fails to totality check.
> [ prelude ] Make some higher-kinded functions be tc-inlined

- nix/text-editor.nix
I've fixed the emacs nix expression by using `emacsPackages.trivialBuild` instead of `emacsPackages.elpaBuild`. This fixes #2859
> fix nix/text-editor.nix

- CHANGELOG.md
- libs/base/System/File/Process.idr
- libs/base/System/File/ReadWrite.idr
- support/js/support_system_file.js
- tests/Main.idr
- tests/node/node020/Popen.idr
- tests/node/node020/expected
- tests/node/node020/run
I've added support for `popen` and `pclose` to the NodeJS backend. I could not find a way to use the asynchronous `spawn` function for `popen` because there is no way (without using `await`) to block until the child process is done in `pclose`. This means the functionality is slightly different for NodeJS than for C/Chez, but I think it's still better to have `popen` than not -- especially with some really nice base library functions like `run` built on top of `popen`.
My seemingly random changes to CHANGELOG are in response to Super Linter becoming more opinionated in a recent release and this being the first PR that changed the CHANGELOG since then. It literally says to use "filename" instead of "file name" and "built-in" instead of "built in."
`CHANGELOG.md` (and potentially also …
> [ new ] `popen`/`pclose` for the NodeJS backend.

- CHANGELOG.md
- libs/prelude/Prelude/Interpolation.idr
- tests/idris2/record019/expected
This adds a constructor to `Interpolation` to be consistent with other interfaces in the standard libs (and because it's useful). A trivial implementation for `Interpolation Void` is also added.
> [ new ] constructor plus trivial impl for Interpolation

- src/Idris/Desugar.idr
- tests/Main.idr
- tests/idris2/error026/DoBlockFC.idr
- tests/idris2/error026/expected
- tests/idris2/error026/run
When a type error occurs in a pattern matching bind in a do block, it ends up at the top of the file (EmptyFC), making it hard to locate the issue.  This PR adds the FC of the principal pattern in the assignment to the scrutinee of the generated case statement, which is where the type error ends up occurring.
For example, before this change we have:
```
1/1: Building tests.idris2.error026.DoBlockFC (tests/idris2/error026/DoBlockFC.idr)
Error: While processing right hand side of foo. When unifying:
Maybe Int
and:
Either ?_ ?_
Mismatch between: Maybe Int and Either ?_ ?_.
```
After the fix, we get:
```
1/1: Building DoBlockFC (DoBlockFC.idr)
LOG elab:1: pat' (Right n) bpat (Right $n) DoBlockFC:7:3--7:10
Error: While processing right hand side of foo. When unifying:
Maybe Int
and:
Either ?_ …
```
> [ error ] Fix location of type errors in do block pattern matching

- CHANGELOG.md
- src/Idris/Desugar.idr
- src/Idris/Doc/String.idr
- src/Idris/Parser.idr
- src/Idris/Pretty.idr
- src/Idris/Syntax.idr
- src/Idris/Syntax/Traversals.idr
- src/Parser/Lexer/Source.idr
- src/Parser/Rule/Source.idr
- src/Parser/Support.idr
- src/Protocol/SExp/Parser.idr
This patch resolves issue #2087 and enhances the handling of multiline string literals:
1. Recognize `\r\n` at the end of a line, which was recognized as `\n\n` for two lines.
2. Dectect padding error before unescaping the literal, therefore this case becomes invalid:
```idirs
"""
A line
\n
Another line
"""
```
Closes https://github.com/idris-lang/Idris2/issues/2087
> [ fix #2087 ] Fix multiline string with CRLF

- .github/pull_request_template.md
There has been some stuff inconsistently slipping through the cracks, so it is probably best to explicitly include it.
(I'm being pedantic, I know, but I'd rather avoid having to re-crawl the git log à la #2703 :sweat_smile: )
> [ admin ] Update what should go in the changelog

- src/Core/Context.idr
- src/Core/LinearCheck.idr
- src/Core/TT.idr
- tests/Main.idr
- tests/idris2/linear016/Issue2895.idr
- tests/idris2/linear016/Issue2895_2.idr
- tests/idris2/linear016/expected
- tests/idris2/linear016/run
A much better solution would be to separate linearity checking and erasure of function arguments entirely.
Fortunately, this is no longer an issue in Yaffle since we are caching quantities on the application itself, making the type lookup redundant.
(This PR builds on #2896.)
> [ fix #2895 ] don't erase argument when type is erased

- CHANGELOG.md
- src/Compiler/ES/Doc.idr
This definition conflicts with one in `Data.String.Parser`
> Remove unused fixity definition

- src/Compiler/Opts/ConstantFold.idr
- src/Core/Context/Log.idr
- src/Core/LinearCheck.idr
- src/Core/Termination.idr
- src/Core/Termination/CallGraph.idr
- src/Core/Termination/Positivity.idr
- src/Core/Termination/References.idr
- src/Core/Termination/SizeChange.idr
- src/Core/Unify.idr
- src/TTImp/Elab/Delayed.idr
- src/TTImp/Interactive/ExprSearch.idr
- src/TTImp/PartialEval.idr
- src/TTImp/ProcessDef.idr
- src/TTImp/ProcessType.idr
- tests/Main.idr
- tests/idris2/reg051/BigFins.idr
- tests/idris2/reg051/expected
- tests/idris2/reg051/run
- tests/idris2/reg051/test.ipkg
This is a fix of a regression appeared in #2900, that (how I knew it) caused tests of [random-pure](https://github.com/buzden/idris2-random-pure) library to run (compile) hours instead of minutes.
As far as I found, the cause is too early call for `toFullNames` when logging: that call happened even if no logging was present. This is because proper `logC` was not used when it should. So, this PR in one commit changes the particular cause of a regression, and the other commit tries to find out similar cases and to fix them.
> [ regression ] Call to `toFullNames` in `log` properly

- CHANGELOG.md
- libs/base/System.idr
- src/Compiler/Common.idr
- support/c/idris_support.c
Currently `getChar` doesn't return a character until the user presses return, because stdin defaults to "cooked" mode.  This PR adds `enableRawMode` and `disableRawMode` primitive functions to allow reading stdin character by character with `getChar`. 
This works on Linux and MacOS, but I was unable to find an acceptable solution for windows.
> [ base ] Support unbuffered reading of stdin

- CHANGELOG.md
- src/Compiler/Inline.idr
- tests/codegen/con001/expected
- tests/idris2/casetree003/expected
- tests/idris2/debug001/expected
When collecting names referred to at runtime (after optimising) constructors on the left hand side of case alts should be collected too.
(see the somehow almost 2 year old #1378)
Note: you may need to rebuild libs to see all effects of this
> Collect constructors on the left hand side of case alternatives

- src/Core/Core.idr
`cond` is not Lazy in its second argument, which cause evaluation of default case all the time.
This can be a potential issue in https://github.com/idris-lang/Idris2/blob/main/src/Compiler/Scheme/Common.idr#L568-L572
```haskell
schExp i (NmConCase fc sc alts def)
= cond [(recordCase alts, schRecordCase i sc alts def),
(maybeCase alts, schMaybeCase i sc alts def),
(listCase alts, schListCase i sc alts def)]
-- probably more to come here...
(schCaseTree i sc alts def)
```
Here the default case tree builder is executed, which can be time consuming for a complex, nested case tree.
> make cond's default argument lazy

- libs/base/Data/List/Elem.idr
- libs/base/Data/SnocList/Elem.idr
- libs/base/Data/Vect/Elem.idr
Adds `get` and `lookup` functions to dereference `Elem`s without/with proof that the value is correct.
Also brings `List.Elem`, `SnocList.Elem`, and `Vect.Elem` closer to parity with one another.
> Add Elem get and lookup functions

- CHANGELOG.md
- libs/base/Data/Singleton.idr
Without them it's not convenient to use `Singleton` in tacit expressions
> [ base ] Add extraction functions to `Data.Singleton`

- CHANGELOG.md
- libs/contrib/Data/Fin/Extra.idr
These were two functions that I found useful when working with vectors of different sizes, but whose indices were related. I know `contrib` should ideally be its own thing, but when that happens I would really like these to be part of `Data.Fin.Extra` ^^
> [ contrib ] Add modFin and strengthenMod

- src/Idris/Parser.idr
- tests/Main.idr
- tests/idris2/perror026/Micro.idr
- tests/idris2/perror026/expected
- tests/idris2/perror026/run
This PR addresses the confusing parser error message reported in #2940, which occurs when a user forgets the comma between identifiers in a `forall` statement.
We now get the error message:
```
1/1: Building Forall (Forall.idr)
Error: Expected ',' or '.'.
Forall:3:14--3:15
1 | module Micro
2 |
3 | f : forall a b. (Unit -> Unit) -> Unit -> Unit
^
```
instead of
```
1/1: Building Forall (Forall.idr)
Error: Cannot return a forall quantifier.
Forall:3:5--3:13
1 | module Micro
2 | 
3 | f : forall a b. (Unit -> Unit) -> Unit -> Unit
^^^^^^^^
```
I'm not sure why the original error message was worded that way, is there a case I missed where that wording was appropriate?
I had to do a `bounds peek` to get the `mustUseBecause` to point at the right spot - there might be a more elegant way to do …
> [ parser ] Improve error message for missing comma or period in forall. #2940

- CHANGELOG.md
- libs/base/System/File/Process.idr
- support/c/idris_file.c
- support/c/idris_file.h
- tests/Main.idr
- tests/allbackends/popen2/Test.idr
- tests/allbackends/popen2/expected
- tests/allbackends/popen2/run
Adds a `popen2` function to `System.File.Process` which allows Idris to run subprocesses with access to both the input and output file streams.  It currently doesn't support windows, but updates are welcome if it's possible and somebody knows how to do it (and can verify that it works). This feature was requested by @jfdm in #2935, and I think @ohad was asking about it last year.
With this change you can do:
```idris
import System.File
main : IO ()
main = do
Right (inFile, outFile) <- popen2 "idris2"
| Left err => printLn err
_ <- fPutStrLn outFile ":h\n"
closeFile outFile
Right result <- fRead inFile
| Left err => printLn err
putStrLn result
putStrLn "done"
```
But I'd recommend writing be done on a separate thread from reading to avoid deadlocking if the subprocess is waiting for a …
> [ new ] Add support for bi-directional pipes on POSIX systems (resolves #2935)

- docs/source/typedd/typedd.rst
In chapters 1 and 2, added a note that `:exec` needs to be passed `main`.
No.
> Added notes: :exec needs to be passed main

- src/TTImp/ProcessDef.idr
- tests/Main.idr
- tests/idris2/error027/Issue2950.idr
- tests/idris2/error027/expected
- tests/idris2/error027/run
This pull request resolves #2950 and #2865 (which are the same issue).  There is a code generation problem in `Prelude.Num.mod` that causes it to pass an erased value to `idris_crash`.  
This error appears to happen because `Builtin` is not imported into `Prelude.Num` so `Builtin.idris_crash` is not in scope, but the code in `ProcessDef` is injecting a fallback case alt that references it.  I initially decided to detect this and report an error, but @Z-snails suggested we just call `prim__crash` directly. 
This problem affected all back-ends, but I'll discuss scheme below.
Previously the generated code looked like:
```scheme
(define PreludeC-45Num-u--mod_Integral_Int 
(lambda (arg-0 arg-1) 
(let ((sc0 (PreludeC-45EqOrd-u--C-61C-61_Eq_Int arg-1 (blodwen-toSignedInt 0 63)))) 
(cond ((equal? …
```
> [ fix ] codegen issue when using partial case statements in prelude.

- src/Core/Termination/SizeChange.idr
- tests/Main.idr
- tests/idris2/total019/Check.idr
- tests/idris2/total019/expected
- tests/idris2/total019/run
The following function is accepted by Idris as total, but it diverges if the first argument is non-empty:
```idris
total
foo : List Char -> List Char -> ()
foo (c :: cs) _ = foo (c :: cs) cs
foo _ _ = ()
```
(This is a reduction of an issue reported by Monadic Cat on Discord.)
The size change info for the function is:
```
Size change: Main.foo: [Just (0, Same), Just (0, Smaller)]
```
The totality checker is correctly assessing that the second argument is a smaller copy of the first, but I believe we need an argument to be smaller than itself. That is the number in the tuple needs to be the same as the index in the array. 
I updated the code based on this assumption, and it resolved this issue and still passes all of the existing test cases.
> [ totality ] divergent function accepted as total

- CHANGELOG.md
- libs/base/Data/List/Quantifiers.idr
- libs/base/Data/Vect/Quantifiers.idr
This adds a couple of missing implementations to `Data.List.Quantifiers` and `Data.Vect.Quantifiers`. In addition, it generalizes functions `imapProperty` to be used not only with functions of type `Type -> Type` ~~and uses these new versions to cleanup the implementation of `Show`~~. Finally, function `zipWithProperty` is also added to `Data.Vect.Quantifiers`.
> [ new ] Eq, Ord, Semigroup, and Monoid for All

- CHANGELOG.md
- src/Compiler/Opts/ConstantFold.idr
- tests/Main.idr
- tests/chez/constfold2/Check.idr
- tests/chez/constfold2/Fold.idr
- tests/chez/constfold2/expected
- tests/chez/constfold2/input
- tests/chez/constfold2/run
Idris sometimes introduces trivial and unnecessary let expressions which prevent the identity optimizer from performing its task. Consider the following example:
```idris
module Id
import Data.Nat
%default total
record Small where
constructor S
value : Nat
{auto 0 prf : LTE value 20}
Show Small where show = show . value
record Smaller where
constructor XS
value : Nat
{auto 0 prf : LTE value 10}
-- This is the identity function
toSmall : Smaller -> Small
toSmall (XS v @{prf}) = S v @{transitive prf %search}
-- This is again the identity function
manyToSmall : List Smaller -> List Small
manyToSmall [] = []
manyToSmall (x::xs) = toSmall x :: manyToSmall xs
main : IO ()
main = printLn $ manyToSmall [XS 1, XS 2, XS 3]
```
`toSmall` is the identity function as is `manyToSmall`. However, as can …
> [ codegen ] get rid of trivial let statements

- CHANGELOG.md
- src/Compiler/Opts/ConstantFold.idr
- tests/Main.idr
- tests/chez/constfold3/Check.idr
- tests/chez/constfold3/Fold.idr
- tests/chez/constfold3/expected
- tests/chez/constfold3/input
- tests/chez/constfold3/run
As discussed in #2961 , this gets rid of `believe_me` during constant folding. I added the `unsafeMkSingleton` example from @gallais as a test case.
> [ codegen ] constant fold believe_me

- libs/base/Control/Relation.idr
- libs/base/Data/List.idr
- tests/idris2/basic044/expected
- tests/idris2/with003/expected
Add `SymClosure` and `TransClosure` relations, which take the symmetric and transitive closures of a given relation.
> Add symmetric and transitive closure relations

- src/Core/Normalise/Eval.idr
It seems that the original version of evalDef was not optimized due to the call to evalTree, in which it fully evaluated the case tree, including calling evalDef in itself:
https://github.com/idris-lang/Idris2/blob/3f7cd84ccb38df7d6ccc02b9e6a4ff425640b814/src/Core/Normalise/Eval.idr#L510
Because of this, evalDef was not a tail recursion.
This can be solved without doing a full evaluation, but by returning the term from the matched case, and only then evaluate.
Thanks to this, the call to the repl (Normalise everything mode) `facTail 100000`
```idris
facAux : Integer -> Integer -> Integer
facAux 0 r = r
facAux n r = facAux (n - 1) (r * n)
facTail : Integer -> Integer
facTail n = facAux n 1
```
almost does not consume memory, whereas before, the process started to take up a lot of memory.
> [ perf ] Make Core.Normalise.Eval.evalDef stack safety

- src/Idris/Parser.idr
- tests/Main.idr
- tests/idris2/perror027/Outdent.idr
- tests/idris2/perror027/expected
- tests/idris2/perror027/run
A user on discord reported a difficult to understand parse error for the following code:
```idris
countdown : (secs: Nat) -> IO ()
countdown Z = putStrLn "Lift off!"
countdown (S secs) = do putStrLn (show (S secs))
usleep 1000000
countdown secs
```
The current version of Idris gives a "Error: Couldn't parse declaration", pointing at the LHS of the declaration:
```
Welcome to Idris 2.  Enjoy yourself!
1/1: Building src.Indent (src/Indent.idr)
Error: Couldn't parse declaration.
src.Indent:3:1--3:10
1 | countdown : (secs: Nat) -> IO ()
2 | countdown Z = putStrLn "Lift off!"
3 | countdown (S secs) = do putStrLn (show (S secs))
^^^^^^^^^
```
This PR surfaces the underlying error with a hint that it is an indentation issue and points the error at the faulty code:
```
1/1: Building Outdent …
```
> [ error ] Improve error messages for indentation issues

- src/Idris/Parser.idr
- tests/idris2/basic069/DebugInfo.idr
- tests/idris2/basic069/expected
Fixes issue #2967.  DebugInfo strings like `__LOC__` and `__FILE__` would cause a parse error if they were an argument to an application.   I moved the `debugString fname` from `appExpr` to `simpleExpr` and updated the test case `basic069` to also include the case below.
Previously, this code:
```idris
main : IO ()
main = putStrLn __LOC__
```
reported an error:
```
1/1: Building src.Loc (src/Loc.idr)
Error: Couldn't parse declaration.
src.Loc:2:1--2:5
1 | main : IO ()
2 | main = putStrLn __LOC__
^^^^
```
and now that code is accepted by the compiler.
> [ fix #2967 ] Fix issue parsing __LOC__ arguments 

- CHANGELOG.md
- src/Compiler/ES/Codegen.idr
- tests/Main.idr
- tests/node/integer_array/array.idr
- tests/node/integer_array/expected
- tests/node/integer_array/input
- tests/node/integer_array/run
I'm working on a library for immutable and mutable (linear) arrays indexed by their size (using `Nat`). From a usability and theoretical correctness point of view it makes sense to use `Integer` for indexing (instead of the slower truncated `Int` being used in `Data.IOArray.Prim`) in the primitive calls and then `Nat` in the user-facing API. The scheme codegens are written in such a way that this is supported without modifications, because all integral primitives are `Integer`s at the backends anyway. The JS backends, however, use a different representation for `Integer` (`BigInt`) than for `Int` (`Number`).
This PR adjust the JS backends in such a way, that all integral types are supported for primitive indexing into arrays. This is a minimal adjustment that does not break any existing …
> [ codegen ] more flexible array implementation on JS backends

- docs/source/typedd/typedd.rst
readNumber_v2 should be readNumbers_v2.  I also added a remark pointing to the corresponding function definition in the book, for people who prefer to type  in the definitions themselves (like me) rather than using the source files in the repo.  Not sure if that addition is OK.  I can take it out if so.
There's another issue with the chapter 5 tips, but I'm not sure what the right fix is, so I'll submit an issue separately.
Fixed typo in function name in tip for chapter 5 of TDDI.  Also added remark pointing to the relevant page number of the function definition in the text, since it's slightly different from the one in the source file (although  the correspondence is easy to guess).
No.
> Update typedd.rst: fixed typo in function name, added page ref

- CHANGELOG.md
- libs/base/Language/Reflection/TT.idr
Currently, there is an implementation of `Ord Name` in the compiler source files, but no corresponding implementation in `Language.Reflection.TT`. This pull request aims to port the implementation to `Language.Reflection.TT`. Having this implementation is useful for metaprogramming purposes, as it allows to use `Name` in `SortedMap`.
> [ base ] Implemented `Ord` for `Name`, `Namespace` and `UserName` 

- src/Idris/Parser.idr
- tests/idris2/perror016/ParseIf4.idr
- tests/idris2/perror016/expected
- tests/idris2/perror016/run
A discord user reported a confusing error message pointing at `=>` and saying `=>` was expected. The error was a missing `do` which caused `atEnd` to fail further down the AST.  I put a `mustWork` on the `atEnd` to surface that error and point at a more appropriate location.
Test case:
```idris
import System.File
foo : File -> IO ()
foo file = do
stuff <- fgetLine file
case stuff of
(Left err) => printLn err
(Right content) => if content == ""
then println "Empty"
else blah <- doSomething
putStrLn content
```
Previous error message:
```
1/1: Building Foo (Foo.idr)
Error: Expected '=>' or 'impossible'.
Foo:7:23--7:25
3 | foo file = do
4 |     stuff <- fgetLine file
5 |     case stuff of
6 |       (Left err) => printLn err
7 |       (Right content) => if content == ""
^^
```
New error …
> [ fix ] Improve error messages at end of if statements

- docs/source/typedd/typedd.rst
The instructions for the exercises at the end of section 5.3.4 list several file-handling functions needed for the exercises.  They were in the Prelude, but now are in `System.File.Handle` and `System.File.ReadWrite`, and I added a note about that.  (`import System.File` would work for the exercise code, but the docs aren't there, so I didn't mention that.  I also didn't mention there a few other definitions, in other modules, that one needs to look up to understand the functions that the book lists.  I think that figuring out that one needs to find those additional docs is supposed to be part of the exercise.)
> Update typedd.rst: Chapter 5: new imports for exercises in 5.3.4

- docs/source/typedd/typedd.rst
Re `cast` vs. `stringToNatOrZ` in the chapter 5 tip:
`cast` from `String` to `Nat` *does* work in Idris 2, version 0.6.0-a75161cb2, so the first sentence is not currently correct.  There is no change needed to code in the book or the associated source file to make the code work correctly.
In the Discord documentation channel, z_snail suggested changing the text to merely recommend changing `cast` to `stringToNatOrZ`, without requiring it.   This PR proposes that change.  I tried to modify the text as little as possible, but I made some additional, strictly speaking unnecessary revisions where I thought they would make the wording clearer given the essential changes.  I added a missing period as well.
An alternative is to simply delete the two paragraphs concerning `cast` and …
> In "Updates Required", modify comments about stringToNatOrZ to reflect working cast

- docs/source/typedd/typedd.rst
Adds note to `typedd.rst` correcting the syntax for forward declarations of `data` in Listing 6.9 of the book.
> [ doc ] Add correction to listing 6.9 in typedd.rst

- src/TTImp/ProcessDef.idr
- tests/Main.idr
- tests/idris2/linear017/As.idr
- tests/idris2/linear017/expected
- tests/idris2/linear017/run
This should hopefully unblock PR #2977.
> Ignore `UseSide` annotation in non-linear as-patterns

- docs/source/backends/javascript.rst
- docs/source/backends/libraries.rst
- docs/source/reference/builtins.rst
- docs/source/reference/packages.rst
- docs/source/reference/strings.rst
- docs/source/tutorial/typesfuns.rst
- docs/source/typedd/typedd.rst
- docs/source/updates/updates.rst
- libs/papers/Language/IntrinsicScoping/TypeTheory.idr
- libs/papers/Language/TypeTheory.idr
```
commit 38b854be04b95e01005c1eb2185ec23307d337d9
Author: Walter Smuts <smuts.walter@gmail.com>
Date:   Sun May 14 13:06:29 2023 +0200
Typos: Run 'typos -w' command over docs/
Only running over "docs/" directory since it will likely have the
largest postivie impact and cause fewest issues.
Typos will do simple find-and-replace when it detects a word not in it's
dictionary. It does not have any regard for formatting based on
surrounding context. Care must be taken not no merge variable names in
same scope etc.
Typos can be driven by Github Actions:
https://github.com/crate-ci/typos/blob/master/docs/github-action.md
Tool: https://github.com/crate-ci/typos
```
and
```
commit 0c29a13c02a0186acd7c1078586d576cb86794c7
Author: Walter Smuts <smuts.walter@gmail.com>
Date:   Sun May 14 13:21:22 …
```
> Typos: Run 'typos -w' command over docs/

- CHANGELOG.md
- libs/base/Control/Order.idr
We have a generalised order in `Control.Order`, but do not have appropriate generalised `min` and `max`, let's add it.
> [ new ] Add generalisations of `min` and `max` for `StronglyConnex`

- libs/base/Data/Bool.idr
Add a proof that if `x || y = False`, then `x = False`, and `y = False`.
> Add orBothFalse proof

- docs/source/conf.py
The pages at https://idris2.readthedocs.io/ show "© Copyright 2020, The Idris Community". This actually made me think that the project is dead. It turns out that the year is hardcoded in a file and should be updated.
> Update docs copyright notice from 2020 to 2023

- CHANGELOG.md
- libs/base/Data/List/Quantifiers.idr
- libs/papers/Control/DivideAndConquer.idr
- libs/papers/Data/ProofDelay.idr
- libs/papers/Language/Trip.idr
- libs/papers/papers.ipkg
This ports the proof delay part of the paper as `papers/Data/ProofDelay.idr`.
I did start an implementation of Trip, but it's quite a bit more work than I anticipated, so I'm putting that on ice for now. If anyone else thinks it would be fun to do, by all means go for it!  : )
> [ papers ] Port the first part of "Deferring the details [...]" by Liam O'Connor

- CHANGELOG.md
- src/Core/Binary.idr
- src/TTImp/Elab/Utils.idr
- src/TTImp/ProcessData.idr
Credit to @andrevidela for the suggestion
This doesn't pass tests on my PC, maybe somehow it will in CI?
> Treat unit types as erased in constructors

- libs/base/Data/List.idr
https://github.com/idris-lang/Idris2/blob/6729fa8c89792c8d75b58daa86ad2e70c438120f/libs/base/Data/List.idr#L273-L287
A trivial typo fix for `\\` in `Data.List` where the example had a typo showing it as `//`
I guess probably not.
> docs: typo in list difference documentation

- src/TTImp/Elab/Local.idr
- src/TTImp/TTImp.idr
- tests/Main.idr
- tests/idris2/basic070/Issue2592.idr
- tests/idris2/basic070/Issue2593.idr
- tests/idris2/basic070/Issue2782.idr
- tests/idris2/basic070/Issue3016.idr
- tests/idris2/basic070/expected
- tests/idris2/basic070/run
PR #1952 introduced top level aliases - definitions without a type declaration.  This had a number of side effects, including local function names being exposed at top level and strange type errors for local function definitions without type declarations.
It turns out that the root cause was the function names not being added to `nested`.  This PR addresses that by looking at `IDef` in addition to `IClaim` when determining the list of locally defined names.  It fixes #2782, #2592, and #2593, which are included in the test case. It also addresses a case raised on discord.
I believe it addresses #3016, but note that, as with top level declarations, the definitions have to have simple bind variables on the LHS. (A constraint imposed by the #1952 code.)
> [ fix ] Ensure local defs with no claim are local 

- docs/source/tutorial/typesfuns.rst
Hi, I'm learning Idris right now, and was going through the documentation. I noticed that one code example has `x` shadowed in the pattern matching of the `case` expression by the function parameter `x` of `splitAt`. I thought it would be clearer to use different names.
Let me know if this is correct (still learning Idris so perhaps I've made incorrect assumptions!)
> Remove shadowed names in documentation

- CHANGELOG.md
- src/Core/Binary.idr
- src/Core/Context.idr
- src/Core/Options.idr
- src/Core/TTC.idr
- src/Idris/Desugar.idr
- src/Idris/Parser.idr
- src/Idris/Syntax.idr
- src/TTImp/Elab/Ambiguity.idr
- tests/Main.idr
- tests/idris2/reflection020/FromDecls.idr
- tests/idris2/reflection020/FromName.idr
- tests/idris2/reflection020/FromTTImp.idr
- tests/idris2/reflection020/expected
- tests/idris2/reflection020/run
Adds `fromTTImp`, `fromName`, and `fromDecls`, analagously to `fromString`, `fromInteger`, etc. This allows overloading of `TTImp`, `Name` and `Decl` literals.
Example usage:
```idris
import Language.Reflection
%language ElabReflection
data NatExpr : Type where
Plus : NatExpr -> NatExpr -> NatExpr
Mult : NatExpr -> NatExpr -> NatExpr
Val : Nat -> NatExpr
Var : String -> NatExpr
natExpr : TTImp -> Elab NatExpr
natExpr `(~(l) + ~(r)) = [| Plus (natExpr l) (natExpr r) |]
natExpr `(~(l) * ~(r)) = [| Mult (natExpr l) (natExpr r) |]
natExpr `(fromInteger ~(IPrimVal _ (BI n))) = pure $ Val $ fromInteger n
natExpr (IVar _ (UN (Basic nm))) = pure $ Var nm
natExpr s = failAt (getFC s) "Invalid NatExpr"
%macro
fromTTImp : TTImp -> Elab NatExpr
fromTTImp = natExpr
eg : NatExpr
eg = `(1 + 2 * x)
``` …
> Add fromTTImp, fromName, and fromDecls for custom TTImp, Name, and Decls literals

- CHANGELOG.md
- Makefile
- docs/source/reference/envvars.rst
Discovered by scarf005 in #3022, if the `IDRIS2_PREFIX` envvar is set, bootstrapping fails. This happens regardless of `PREFIX` being set or not, and _only_ happens if `IDRIS2_PREFIX` is set.
Changing the syntax in the `Makefile` to use `?=` (assign-if-unset) instead of `:=` (assign) seems to fix the issue.
I also updated the `envvars.rst` docs, because they were outdated and didn't mention `PREFIX` being a thing (something which could've avoided the issue, but also would've left it buried for someone else to unearth). There were several changes, e.g. #2649, which weren't included.
> [ fix ] Only set `IDRIS2_PREFIX` if it is unset (fixes Issue 3022)

- docs/source/reference/envvars.rst
This warning appears in all PRs and is annoying. Anyway, it's better to not to fool the formatter, since plain `*` is a markup syntax
> [ docs ] Fix the formatting warning in the docs

- support/c/idris_term.c
This PR fixes the failing windows CI test `scheme002` by checking the return value of `GetConsoleScreenBufferInfo`.  Windows was lacking error handling in the code for the getting the terminal size.  The fix is also included in #3027, so this PR be closed if that PR is merged.
> [ fix ] Fix error handling in windows getTermLines

- libs/base/Syntax/PreorderReasoning.idr
This reduces the need for excess `irrelevantEq`s.
> Erase additional PreorderReasoning arguments

- src/Idris/Parser.idr
- src/Libraries/Text/Parser/Core.idr
- tests/Main.idr
- tests/idris2/perror029/DelayParse.idr
- tests/idris2/perror029/expected
- tests/idris2/perror029/run
This PR improves error messages in `Delay` statements to address #3036. It adds a check for an additional `simpleExpr` after the statement. It also introduces a `mustFailBecause` helper function that will fail with a message if a given parser succeeds at the current point.
Prior to this change, the following code:
```idris
module DelayParse
public export
data MyStream : Type where
(::) :  (anA : a)
-> (nextA : a -> a)
-> Inf MyStream
-> MyStream
public export
go : a -> (a -> a) -> MyStream
go initA fn =
MyStream.(::) initA fn (Delay (fn initA) fn)
```
would fail with:
```
1/1: Building tests.idris2.perror029.DelayParse (tests/idris2/perror029/DelayParse.idr)
Error: Not the end of a block entry, check indentation.
tests.idris2.perror029.DelayParse:13:26--13:27
09 |
10 | public export
11 | …
```
> [ error ] Improve error messages for Delay &co

- .github/workflows/ci-idris2.yml
To try to stabilize the windows CI, this PR pins the windows chez to the latest release (9.5.8a) instead of pulling the latest dev version. This appears to fix the issue with the `chez/futures001` test.
> [ fix ] Pin chez v9.5.8a in windows CI

- CHANGELOG.md
- libs/base/Data/List1.idr
Changes `foldr1` and `foldr1By` to be `public export`.  This change unblocks computation in idris-tparsec.
> [ base ] Make foldr1 and foldr1By public

- libs/prelude/Prelude/Basics.idr
Add documentation for Not.  Based on a suggestion by Andre in discord.
Yes, I think so.
> Add documentation for Not.

- CHANGELOG.md
- CONTRIBUTORS
- Makefile
- src/Idris/Package.idr
- support/Makefile
- support/c/Makefile
- support/chez/Makefile
- support/refc/Makefile
Prefix `${PREFIX}` with `${DESTDIR}` allowing installation into a staging directory for packaging Idris2.
Also take DESTDIR into account with `idris2 --install` etc.
I tested this a little on Fedora Linux.
When DESTDIR is not set, installation should behave exactly as now.
> implement DESTDIR support for distros

- src/TTImp/Unelab.idr
- tests/Main.idr
- tests/idris2/reflection021/QuoteSearch.idr
- tests/idris2/reflection021/expected
- tests/idris2/reflection021/run
Thanks to @madman-bob for discovering this issue. 
Consider the following code snippet that checks the value of `%search` and immediately quotes the checked value, logs it and runs an elaboration script that defines `y : Nat` to be the sum of the quoted value with itself.
```idris
import Language.Reflection
%language ElabReflection
x : Elab Nat
x = check `(%search)
defy : Elab ()
defy = do
let fc = EmptyFC
val <- quote !x
logTerm "" 0 "Quoted term:" val
declare [
IClaim fc MW Private [] (MkTy fc fc (UN (Basic "y")) (IVar fc (UN (Basic "Nat")))),
IDef fc (UN (Basic "y")) [PatClause fc (IVar fc (UN (Basic "y"))) (IApp fc (IApp fc (IVar fc (UN (Basic "+"))) val) val)]
]
%runElab defy
```
When checking the value, `%search` gets elaborated into a metavariable. Currently, when unelaboration …
> [ unelab ] Properly unelaborate metavariables originating from `%search`

- CHANGELOG.md
- src/Compiler/Scheme/Racket.idr
- tests/Main.idr
- tests/racket/ffi001/RacketLib.idr
- tests/racket/ffi001/expected
- tests/racket/ffi001/run
This adds an optional ",library" suffix to Racket FFI definitions. Replaces #3048.
Before this PR, FFI definitions that use bindings from parent scopes are always unreliable since a user can't know which libraries are `require`d as part of code generation:
https://github.com/idris-lang/Idris2/blob/86c53e6071ee83008dc77e4572e20be195d5b137/src/Compiler/Scheme/Racket.idr#L48-L56
Suppose a user's library Foo, which uses any of the functions `require`d there. If a future Idris version removed this code the Foo library would stop working.
To make this more robust, this PR gives users the *option* of specifying which Racket library they are defining FFI for. Now, the require is inserted when that code is generated, meaning that Foo would still work on this future hypothetical version of Idris …
> Add library loading for Racket

- libs/prelude/Prelude/Interfaces.idr
- tests/Main.idr
- tests/idris2/total020/Check.idr
- tests/idris2/total020/expected
- tests/idris2/total020/run
- tests/idris2/total020/test.ipkg
Without this you may get weird wrong totality checker errors when using simple functions like `<$>`, you can see an example in the added test.
> [ prelude ] Add some lacking `%tcinline`s

- CHANGELOG.md
- libs/base/Data/List.idr
In `Data.List` we have
- `prefixOfBy`, `isPrefixOfBy`, `isPrefixOf`;
- `suffixOfBy`, `isSuffixOfBy`, `isSuffixOf`;
- but only `isInfixOf`,
which is a shame sometimes. I suggest adding those two lacking complementary functions.
> [ base ] Add lists' infix-by functions, complementary to existing ones

- Makefile
- idris2api.ipkg
- libs/base/System/File/Meta.idr
- src/Core/Binary/Prims.idr
- src/Libraries/System/File/Meta.idr
- support/c/idris_file.c
- support/c/idris_file.h
- support/c/windows/win_utils.c
- support/c/windows/win_utils.h
- support/js/support_system_file.js
- tests/Main.idr
- tests/idris2/basic071/A.idr
- tests/idris2/basic071/B.idr
- tests/idris2/basic071/expected
- tests/idris2/basic071/run
This PR changes TTC modification time comparison to use nanosecond-precision timestamps. It addresses the issue described in #3042, but, unlike the original PR, it does not break safety guarantees and does not risk missed rebuilds of source files. Since getting high-precision timestamps is platform-dependent and might not be supported everywhere, it reverts to current behaviour whenever there is no proper way to get nanosecond part of file's mtime.
This PR depends on #3044 to pass CI and avoid bootstrapping the compiler when upgrading.
> [ ttc ] Compare modification time with nanosecond precision

- .github/workflows/ci-idris2-and-libs.yml
The extra CI jobs introduced in #3067 work fine as long as 'main' is not the checked out branch. This is due to the fetch to a new branch, which git does (reasonably) not allow when you're trying to fetch 'main' into a new branch that's also called 'main'. In this case, we should just `git pull origin main`, which is what the script now (hopefully) does. (source: https://stackoverflow.com/questions/2236743/git-refusing-to-fetch-into-current-branch)
> [ ci ] re #3067: fix CI on main branch

- CHANGELOG.md
- libs/contrib/Data/List/Lazy.idr
- tests/Main.idr
- tests/idris2/misc/lazy004/LazyFor.idr
- tests/idris2/misc/lazy004/expected
- tests/idris2/misc/lazy004/input
- tests/idris2/misc/lazy004/run
This change is like #2412, but for old long-existing functions. Since `Applicative` interface is inherently not lazy, the current implementation was not lazy by the effect, even if the underlying monad's effect could be short-cutting. One can see an example in the added test.
Since, `LazyList` is still `Foldable`, old behaviour is reachable by converting the `LazyList` to `List`.
It may seem that this change relies on some exploiting of the breakage of monadic laws, but it is fundamental for an eager language since monad interface is inherently lazy anyway.
> [ fix ] Make `traverse` and friends lazy for `LazyList`

- README.md
Workflow was renamed, while the badge was forgotten about.
> [ re #3067, readme ] Fix the build badge in the readme

- .gitignore
- tests/idris2/basic/basic071/run
- tests/idris2/basic/case001/run
- tests/idris2/basic/case002/run
- tests/idris2/basic/literals001/run
- tests/idris2/literate/literate018/run
- tests/idris2/pkg/pkg010/run
- tests/idris2/pkg/pkg016/run
- tests/idris2/total/total021/run
- tests/testutils.sh
I decided to be constructive in critics of #3085. This is an alternative, a more universal fix for the package tests hygiene problem. Fixes #3084, closes #3085. I also cleaned up old or became incorrect hygiene workarounds in existing tests.
Also, some tests' `run` scripts were changed due to the new style (I suppose, they were forgotten to be changed). To ease the review, I did it in a separate commit.
> [ test ] Fix package tests hygiene

- CHANGELOG.md
- libs/base/Data/Vect/Quantifiers.idr
This generalizes `Data.Vect.Elem.elemToFin`.
> [ base ] Add `anyToFin` converting a Vect's `Any` to its index

- CHANGELOG.md
- src/Core/Binary.idr
- src/Idris/Desugar.idr
- src/Idris/Resugar.idr
- src/TTImp/Elab/Ambiguity.idr
- src/TTImp/Elab/RunElab.idr
- src/TTImp/Elab/Term.idr
- src/TTImp/Reflect.idr
- src/TTImp/TTImp.idr
- src/TTImp/TTImp/Functor.idr
- src/TTImp/TTImp/TTC.idr
- src/TTImp/TTImp/Traversals.idr
- src/TTImp/Utils.idr
- tests/idris2/reflection/reflection023/DeclMacro.idr
- tests/idris2/reflection/reflection023/UseMacroWithoutExtension.idr
- tests/idris2/reflection/reflection023/expected
- tests/idris2/reflection/reflection023/run
- tests/idris2/reflection/reflection023/test.ipkg
Macro-functions are a great way of hiding some complex thing in a library without showing this to a user. A pretty example was shown as a motivating example in PR #2930.
But since currently call to a macro function, generally, is just a `%runElab` of an appropriate expression, each use of such function means to users that they need to turn on the language extension flag `ElabReflection`, despite they may not feel why.
I mean, imagine a library that does some hard stuff in a macro function (like enabling some syntax in PR mentioned above, or some DSL-y thing), and user just imports this library and uses its functions and gets "`%language ElabReflection not enabled`" all the time. I understand this requirement in explicit `%runElab` expressions and declarations -- here a user explicitly has …
> [ elab ] Make `%macro`-function be callable without the `ElabReflection` extension

- CHANGELOG.md
- libs/base/Language/Reflection.idr
- src/Core/Name/Namespace.idr
- src/TTImp/Elab/RunElab.idr
- tests/idris2/reflection/reflection024/.gitignore
- tests/idris2/reflection/reflection024/expected
- tests/idris2/reflection/reflection024/run
- tests/idris2/reflection/reflection024/src/Inside/PrintDirs.idr
- tests/idris2/reflection/reflection024/src/LessSimpleRW.idr
- tests/idris2/reflection/reflection024/src/SimpleRW.idr
- tests/idris2/reflection/reflection024/src/TypeProviders.idr
- tests/idris2/reflection/reflection024/src/existentToRead
- tests/idris2/reflection/reflection024/src/existentToWrite
- tests/idris2/reflection/reflection024/src/fancy-record.txt
- tests/idris2/reflection/reflection024/test.ipkg
Idris 1 used to have type providers, facilities that allowed pretty arbitrary code to be additionally executed at the compile time allowing to provide particular values based on whatever stuff. But this approach is very fragile and unsafe, since arbitrary effects can break a lot and generally seems to be undesired.
Seemingly, most important feature was a file access. This allowed to implement the principle of a single source of truth in a higher level and typesafe manner. Say, your code interacts with some other code with some well-defined typed interface and if you can generate a type declaration from this description automatically during compile time, you've solved a problem of synchronisation: each time the common description updates, your types update too. If the change was …
> [ elab ] Support limited file operations in elab scripts, e.g. enable type providers

- CHANGELOG.md
- libs/base/Data/Ref.idr
- tests/base/data_ref_monadstate/RefMonadState.idr
- tests/base/data_ref_monadstate/a-test.ipkg
- tests/base/data_ref_monadstate/expected
- tests/base/data_ref_monadstate/run
Allows to use some existing code with `MonadState` requirement in a `Ref`-based environment, and anyway have the common code for both of the worlds, when applicable.
> [ base ] Add a bridge between `MonadState` and `Ref`

- CHANGELOG.md
- libs/base/Data/List.idr
This adds a new function to `Data.List` for grouping a list into equal sized sub lists. For instance, `group 3 [1..10]` will return `[[1,2,3],[4,5,6],[7,8,9],[10]]`. I took the function's name from a similar function in Scala ([see here](https://www.scala-lang.org/api/current/scala/collection/immutable/List.html#grouped(size:Int):Iterator[C])).
The implementation is tail-recursive and runs in O(n).
> [ new ] add Data.List.grouped function

- CHANGELOG.md
- libs/base/Data/Vect.idr
- libs/base/Data/Vect/Quantifiers.idr
This seems to come in useful, and since the implementation might be non-obvious (as been discussed in Discord), it's probably worth having the function in the library.
Note that proving `rememberForgetId` (that is, the identity in the other direction of `remember . forget`) is more complicated, since it only holds modulo the `xs` that the `All` is indexed by, and I'm not sure we want to go that route, especially given that there currently seems to be no machinery for doing `All (const p) xs -> All (const p) ys` (although I'd be happy to add that if you think it might be worth it!)
> [ base ] Add `Data.Vect.Quantifiers.All.remember`, the inverse to `forget`

- CHANGELOG.md
- src/Idris/Desugar.idr
- src/Idris/Elab/Implementation.idr
- src/Idris/Parser.idr
- src/Idris/Syntax.idr
- src/Idris/Syntax/Traversals.idr
- tests/idris2/interface/interface030/DefaultImplicitsInImpls.idr
- tests/idris2/interface/interface030/expected
- tests/idris2/interface/interface030/run
There is no principle why named implementation cannot have a `default` implicit argument. You always could model it with
```idris
%hint
NamedImpl : {default V tuning : _} -> Interface ...
NamedImpl = N where
[N] Interface ... where
...
```
but why not to support it directly? This PR enables the code from above be written as
```idris
[NamedImpl] {default V tuning : _} -> Interface ... where
...
```
i.e. to write default implicit arguments exactly where usual implicit arguments are written in implementations.
P.S. And now I understand why Edwin complains about the way how the interfaces and implementations are elaborated: sometimes code looks horrifying.
> [ impl ] Support `default` implicits in named implementations

- src/Idris/Desugar.idr
- src/Idris/Parser.idr
- src/Idris/Syntax.idr
- src/Idris/Syntax/Traversals.idr
- tests/idris2/error/perror030/LoggingParse.idr
- tests/idris2/error/perror030/expected
- tests/idris2/error/perror030/run
In issue #3097, a `%logging` pragma followed by a named implementation will produce an odd parse error.  The root cause for this is a second, inline parser for `%logging` inside `simplerExpr` that is being hit while `implDecl` attempts to parse the `%logging` line.  I addressed the issue by moving the `directiveDecl` parser before the `impDecl` parser in the alt.
But this change broke `%runElab` statements. It turns out that there is an old parser for `%runElab` inside `directiveDecl` that was no longer being used because `runElabDecl` occurred first.  It parsed `%runElab` to `PReflect`, which desugars to a "Reflection not implemented yet" error. So I removed that.
Since `PReflect` is not used (the real parser for `%runElab` produces a `PRunElabDecl`), I also removed `PReflect`. …
> [ parser ] Fix issues parsing %logging followed by named impls - fix #3097

- src/TTImp/Elab/RunElab.idr
- tests/idris2/reflection/reflection024/src/LessSimpleRW.idr
Compile-time file operations introduced in #3099 attempt to check file paths and prevent exiting the directory specified by `LookupDir`. This safeguard, however, can be easily fooled by the use of `./` as part of the path. For instance, the following call would result in the creation or  modification of a file outside the project directory:
```idris
%runElab writeFile ProjectDir "./../outerFile" "uh oh"
```
This occurs because the introduced function `pathDoesNotEscape` performs the check by tracking how deep the provided relative path goes down in the directory tree, making sure it doesn't go up more than it goes down. It, however, treats "." like a regular directory, allowing the user to increase the depth perceived by the function "for free". This PR adds special handling of the "." …
> [ fix ] Prevent relative path traversal in elaborator scripts

- CHANGELOG.md
- libs/base/Data/Vect/Quantifiers.idr
Implement an analog of `Prelude.Traversable.traverse` for `All`s.
There are actually two traversals, one mirroring the current `mapProperty` and friends where the argument corresponding to the elements of `xs` in `All p xs` is irrelevant, and the other takes them as relevant, which seems to be useful in some real-world use cases. The first one results in a better code generation though, so having both looks like the most optimal decision.
> [ base ] Relevant and irrelevant traversals for `Data.Vect.Quantifiers.All`

- CHANGELOG.md
- libs/base/Data/Colist.idr
- libs/base/Data/Colist1.idr
- libs/base/Data/Either.idr
- libs/base/Data/Maybe.idr
- libs/base/Data/SortedMap.idr
- libs/base/Data/Zippable.idr
- libs/contrib/Data/IMaybe.idr
Some very standard types lacked this interface implementations. Also, couple existing implementations were generalised, and this generalised implementation is also applicable to, say, monad transformers of those standard types. Also, a `Compose` implementation is added.
> [ base ] Implement `Zippable` for several standard types + small cleanup

- libs/base/Deriving/Common.idr
- tests/base/deriving_traversable/expected
Two things are done:
- unsafe operations were commented to be marked as `%unsafe` as soon as released compiler supports them, and
- errors of the `isType` function were made to point to the expression that caused the failure, if there is one.
> [ derive ] Small improvements in `Deriving.Common`

- libs/contrib/Data/String/Parser.idr
This fixes #2099, which causes an infinite loop upon using the `some` function. These would be equivalent if the function was total, but it isn't.
I don't think so, but I'm not sure.
> Use `do` notation in `some`

- docs/source/reference/failing.rst
- docs/source/reference/index.rst
This adds documentation for `failing` along with some (hopefully) helpful examples.
Fixes #3073
Closes #3077
No
> [ doc ] Document `failing` blocks

- libs/contrib/Text/Distance/Levenshtein.idr
- libs/contrib/Text/Lexer/Core.idr
- libs/contrib/Text/Lexer/Tokenizer.idr
- libs/contrib/Text/Literate.idr
- libs/contrib/Text/PrettyPrint/Prettyprinter/Render/HTML.idr
This switches the string functions used in the Lexer and Parser libraries from their `fast` variants to the normal variants. This allows them to be used at compile-time, but doesn't introduce performance regression, as they're translated to their faster versions at compile-time anyways. This should fix #791
I don't think so
> Switch from 'fast' string functions to normal string functions

- .github/workflows/ci-idris2-and-libs.yml
Previous version of JamesIves/github-pages-deploy-action uses [deprecated GH Actions functionality](https://github.com/idris-lang/Idris2/actions/runs/6612307397/job/17958920185#step:15:61). It'll break eventually, better safe than sorry.
> [ ci ] Update deploy-action in ci-idris2-and-libs.yml

- CHANGELOG.md
- libs/base/Data/These.idr
Sometimes `These` data type is really handy, but it lacks a bunch of implementations and couple of functions for convenient use
> [ base ] Implement a bunch of standard interfaces for `Data.These`

- CHANGELOG.md
- libs/base/Language/Reflection.idr
- src/Core/Context.idr
- src/Core/Reflect.idr
- src/TTImp/Elab/RunElab.idr
- src/TTImp/ProcessDef.idr
- tests/idris2/reflection/reflection025/CurrFn.idr
- tests/idris2/reflection/reflection025/InspectRec.idr
- tests/idris2/reflection/reflection025/RefDefs.idr
- tests/idris2/reflection/reflection025/RefDefsDeep.idr
- tests/idris2/reflection/reflection025/expected
- tests/idris2/reflection/reflection025/run
- tests/idris2/reflection/reflection025/test.ipkg
I wanted to be able to implement recursion-aware DSLs using elaborator scripts and macroses for a very long time. Very nice example for this would be a `MonadRec` interface, which allows to define stack-safe monads. Problem of this interface is that instead of nicely supported `>>=`, it uses its own function, which is really painful to be used by a human. So, I wanted to adapt a DSL which encodes nice `do`-syntax with appropriate functions from the `MonadRec` interface. The same goes for `Arrow`s too, BTW, and I believe, in more cases.
My initial idea was to define a script which takes the whole declaration, say
```idris
%runElab AsMonadRec `[
f : Monad m => ... -> m a
f ... = do
someCode ...
x <- someRecursiveCall <$> f ...
...
]
```
Then, I realised that this badly works for mutual …
> [ elab ] Implement abilities for recursion check in elab scripts

- .github/workflows/ci-idris2-and-libs.yml
PR #3122 failed during build because `macos-bootstrap-chez` used chez scheme 9.6.4 and `macos-self-host-chez` used 9.6.2, which is incompatible. It looks like chez was updated in homebrew last week and `macos-self-host-chez` got a machine with an older homebrew install.
I'm proposing we address the issue by doing a `brew update` before installing chez scheme.  This is consistent with the `apt-get update` being run on the linux side, but homebrew is more aggressive about updating dependencies.
Between the two jobs, this ends up adding about 10 minutes to the mac build path, because homebrew insists on upgrading a bunch of packages, but mac still finished slightly before windows, so it may not effect overall time.
> [ ci ] Run a brew update during ci

- src/Idris/Parser.idr
This PR removes a duplicate copy of the header parser. (This was discussed in  #3068)
There are two copies of the parser code for the file header in `Parser.idr`.  One is in `progHdr`, which is used to parse the header for building the module tree and deciding whether to rebuild a file or not.  The other is in `prog` which is used to parse the entire `.idr` file.  Because there are two copies, they could accidentally diverge from each other.  This has already happened, but currently the only difference is a `Module` decoration.
Here I keep the copy in `progHdr`, adding the decoration, and have `prog` call `progHdr` and then add the declarations.
> [ cleanup ] remove duplicate copy of header parsing

- libs/base/Deriving/Show.idr
- tests/base/deriving_show/DeriveShow.idr
- tests/base/deriving_show/expected
Sometimes data type definitions contain type aliases, including non-trivial ones. The current derivation mechanism tries to count them as proper types without an attempt to treat them. The example of such a type can be found in the added test case.
What I suggest is to try to reduce a type before analysis using quotation. Since, we do not restore the whole context of a type expression being reduced, we only `try` it and fallback to the original behaviour if we didn't manage.
Notice that this mechanism cannot be applied directly to `Type -> Type` derivations like `Functor`, since in this case we *have to* restore the context, at least the parameter type has to be there. I do this type of stuff in some of my elaboration scripts, but this change is far beyond a simple fix, which this PR …
> [ deriving ] Try to reduce a type before searching it's showable

- docs/source/ffi/ffi.rst
I didn't realize that structs needed to be fully defined in Idris and I don't see any indication of that in the docs yet. This adds an important note.
> Add FFI note about something that just tripped me up

- CHANGELOG.md
- docs/source/reference/envvars.rst
Some envvars are only used at build-time, some only at runtime, and lots are used at both. This clearly cagetorises them accordingly in the docs. Having these headings was suggested [a long time ago](https://github.com/idris-lang/Idris2/pull/3024#issuecomment-1644572572) by dunham; I finally got around to doing it... (Side-note: the original discussion suggests that this indexing used to be in the Idris docs. However, I have been unable to find this and so have just gone based on testing and grep­-ing the makefile.)
> [ doc ] Headings for envvars based on use

- CHANGELOG.md
- Makefile
There are two cases where `make -j` fails: `make bootstrap -j` and `make all -j`. I fixed them both in two separate commits. 
> Support "make -j"

- src/Core/Termination/CallGraph.idr
Two improvements of `sizeEq` discussed on Monday:
- work up to `CompatibleVars`
- dotted terms are terms, not patterns: apply `(==)` straight away
I will document the other two proposed improvements
- equality of terms up to `CompatibleVars`
- recording function call arguments as part of `SCCall`
as issue reports separately.
> Cleanup of `sizeEq`

- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/Gambit.idr
- src/Compiler/Scheme/Racket.idr
- tests/allschemes/ffi001/Struct.idr
- tests/allschemes/ffi001/run
When a FFI call contains a function type as argument whose domain is a `Struct` the definition for the struct type is not emitted by codegen, causing an error at compile time.  This issue was reported and diagnosed by slayerofthebad on discord. It occurs in chez, racket, and gambit.
The root cause was that the `Builder` returned by `mkStruct a` was being dropped. It represents the string for the structure definition, and needed to be concatenated with the one for the domain before returning. (These expressions end up at the top level.)
Before the change, the test case would fail to compile with:
```
Exception: unrecognized foreign-callable argument ftype name AST at line 616, char 162 of /Users/dunham/build/i2/Idris2/build/exec/out_app/out.ss
```
And after the change it compiles.
I tested …
> [ ffi ] Fix missing structure declarations in scheme ffi

- CHANGELOG.md
- libs/base/Language/Reflection/TTImp.idr
- tests/idris2/reflection/reflection025/expected
- tests/idris2/reflection/reflection025/run
I propose to allow a bit more applicable, applicative mapping of `TTImp`s, which generalises existing `mapMTTImp` way.
Proposed way allows you to do, for example, the following. Since traversal goes bottom up, from leaves up to the root, there might be not enough information of whether some transformation should be done, or not. Consider you want some transformation happen, but want to cancel it if some condition happens. You may need an original value at this point. The proposed addition of `mapMMTTImp` (along with existing `mapMTTImp`) allows this:
```idris
record WithOrig a where
constructor W
orig : a
main : Lazy a
Functor WithOrig where
map f = {orig $= f, main $= f}
Applicative WithOrig where
pure x = W x x
W fo fm <*> W xo xm = W (fo xo) (fm xm)
whateverTransformation : TTImp -> …
```
> [ elab ] Support more applicative traversals of `TTImp`

- src/Idris/Package.idr
- tests/idris2/pkg/pkg018/bad.ipkg
- tests/idris2/pkg/pkg018/bad2.ipkg
- tests/idris2/pkg/pkg018/expected
- tests/idris2/pkg/pkg018/run
The parser for `.ipkg` files reports any error as "Expected end of input". The root cause was a "many" and an "alt" that eat the error messages. Here I've added `mustWork` where appropriate, a better error message for when it hits an unknown keyword, and added the original source to the error message.
Previously:
```
Uncaught error: Parse errors ([("bad.ipkg":3:1--3:7, "Expected end of input.")])
```
Now it says:
```
Uncaught error: Error: Unrecognised property "depend".
"bad.ipkg":3:1--3:7
1 | package idris2app
2 |
3 | depend = network
^^^^^^
```
The other test case reports this instead of "Expected end of input":
```
Uncaught error: Error: Expected string.
"bad2.ipkg":2:13--2:16
1 | package bad
2 | sourcedir = src
^^^
```
Probably not significant enough to warrant a change log entry.
> [ error ] Improve error messages when reading ipkg files

- INSTALL.md
- README.md
- docs/source/backends/javascript.rst
I've been looking at doing a good overhaul of the docs, to
* make it easier for newcomers
* reduce duplication
and wanted to get early feedback. Do be completely honest. Is this helpful? I have an idea to work on the docs much more widely, so the approach here (short, to the point) is as important as the content.
Remaining tasks
> refactor README and installation instructions

- src/Core/Unify.idr
- src/Core/UnifyState.idr
This constraint is never actually used so one fewer thing to maintain.
> [ cleanup ] remove dead code MkSeqConstraint

- src/TTImp/ProcessFnOpt.idr
If `%deaulthint` is used in a local definition, Idris complains "%globalhint is not valid in local definitions`.  This PR changes it to say "%defaulthint is not valid in local definitions" in that case.
```idris
foo : Nat -> Nat
foo x = x
where
%defaulthint
bar : Show String
```
gives the error message:
```
Error: While processing right hand side of foo. %globalhint is not valid in local definitions
```
With the fix, it now says:
```
Error: While processing right hand side of foo. %defaulthint is not valid in local definitions
```
> [ error ] Fix error message for %defaulthint on a local function

- support/gambit/support.scm
This PR fixes a segfault involving `unpack` in gambit and syntax errors in `support.scm` when using the latest gambit. 
The following code segfaults when compiled with the gambit backend:
```idris
main : IO ()
main = printLn "hello, world"
```
The root cause was that `pack` / `unpack` expect a different list representation than Idris currently uses. I suspect it was written before Idris mapped lists to native scheme lists. 
I also discovered that gambit 4.9.5 reports syntax errors for `support.scm`. It doesn't like the use of `[]` instead of `()`.  Gambit 4.9.3 on a different platform is happy with the brackets. I couldn't track down when this changed, but did find that R7RS reserves `[]` and `{}` for future use.
I've addressed both of these issues in this PR.  The code has been tested …
> [ gambit ] fix pack / unpack segfault with gambit scheme

- tests/Main.idr
- tests/racket/conditions006/Main.idr
- tests/racket/conditions007/Main.idr
Racket does not have FFI bindings for these primitives.
> [ fix #3103, #3104 ] Disable broken tests

- CHANGELOG.md
- libs/base/Data/Vect/Quantifiers.idr
Adding some more functions that are useful in practice and might be not exactly trivial to implement (like `tabulate`'s erased `xs` but unerased `n` to allow for pattern-matching on the shape of `xs`).
> [ base ] Add `mapPropertyRelevant`, `tabulate` and `(++)` for `Vect`'s `All`

- src/TTImp/Elab/Record.idr
- tests/idris2/data/record020/RecordImplicit.idr
- tests/idris2/data/record020/expected
- tests/idris2/data/record020/run
This PR fix #3083.
Now update of record leaves a hole only for implicit type variable.
Moreover, would it be correct to have a different behavior for auto arguments to make the following code correct?
```idris
record WithShow (ty : Type) where
constructor MkWS
{auto hasShow : Show ty}
name : ty
foo : WithShow ty -> WithShow String
foo ws = { name := "meh" } ws
```
> [ fix #3083 ] Fix record update with implicit args

- CHANGELOG.md
- libs/base/System/File/Process.idr
- support/c/idris_file.c
- support/c/idris_file.h
- tests/allbackends/popen2/Test.idr
- tests/allbackends/popen2/expected
- tests/allbackends/popen2/run
Current implementation of `popen2` function introduces in #2944 has slightly different behaviour for POSIX and Windows systems, and, more importantly, it leaves zombie processes on POSIX systems, which, when being run regularly, leads to exhaustiveness of PIDs in a system.
Anyway, leaky and unstable behaviour is not to nice, so I propose the simplest solution I came with. I suggest to make behaviour similar in POSIX and WIndows AND requiring a cleanup call `popen2Wait`. Roughtly speaking, this is not a much stretch, because for usual `popen` we already have a pair function `pclose` with the similar meaning. We can't have direct "closing" analogue for `popen2`, because moment and order of closing of the file handlers depends on a particular use (unlike `popen`), so, full cleanup has to be …
> [ re #2944, fix ] Make `popen2` be able to not to leak system resources

- libs/prelude/Prelude/Show.idr
- tests/idris2/total/total020/Check.idr
Currently once cannot implement provably total `showPrec` using recommended `showCon` and `showArg`, which is annoying. But this can be solved by `public` exporting and `%tcinline`'ing those auxiliary functions. So, lets do this.
> [ prelude ] Make able to implement provably total `showPrec` recursively

- Makefile
- bootstrap-stage1-chez.sh
- bootstrap-stage2.sh
- flake.nix
- nix/package.nix
- nix/support.nix
- tests/Makefile
- tests/testutils.sh
I aimed to not make any drastic or unneeded changes with this PR. Hopefully others agree that the small Makefile changes are all net positive in any context even if they were motivated in this case by a Nix refactor.
I tried to tell the story with the commit messages, but to enumerate the changes briefly:
1. Instead of each of the two Chez bootstrap stages reading the `SCHEME` env var separately, take advantage of the fact that this variable is known in stage 1 and carry it forward to stage 2 automatically.
2. Export needed library paths at the top of bootstrap stage 2 instead of inlining the environment variables. This reduces repetition which is even more significant given that I added two additional variables (one of them, `DYLD_LIBRARY_PATH`, just for good measure).
3. Retain test …
> Separate support derivation (and small related tweaks to the Makefile)

- CHANGELOG.md
Unfortunately, I wasn't fast enough to notice this, and this is an examplary case for future (and the only reason why I do this as a separate PR, not as a part of some future bigger one): after an addition to the PR template which mentions the appropriate changelog update, lots of PRs indeed update it, but they update the place relevant to the point of PR creation, which not has changed after the recent release. A lot of PRs need updates in precisely this part.
> [ re #3171 ] Correct mistakenly forgotten to be updated changelog

- CHANGELOG.md
- libs/contrib/System/Console/GetOpt.idr
- tests/contrib/getOpt001/UseGetOpt.idr
- tests/contrib/getOpt001/expected
- tests/contrib/getOpt001/run
- tests/contrib/getOpt001/test.ipkg
**TLDR**: This PR adds a backward-compatible ability to parse particular option's bodies in the current `getOpt` with errors being recorded into the current `Result` type, rather than external aftermath errors parsing.
Existing simple options parsing facility is really nice, but since usually not every "body" of an option is acceptable, it is common to have the result of the option parsing to be `Either <error-type> <desired-result-type>`, and after the parsing to analyse those `Either`s. I've seen this pattern somewhere (i.e. in `pack`) and even implemented it in my code. After a while I thought of a helper function that would help with this pattern (and I implemented it in the first commit of this PR).
But this attempt showed that different errors of options parsing are present …
> [ contrib ] Support options parsing errors in `getOpt`

- CHANGELOG.md
- CONTRIBUTORS
- libs/base/Data/List/Quantifiers.idr
- src/Libraries/Data/List/Quantifiers/Extra.idr
This exists in `Data` for `SnocList` and `Vect` but not for `List` for some reason. I copied it verbatim from [src](https://github.com/idris-lang/Idris2/blob/2f2102c4134c8579a0406894b0beb563673255f0/src/Libraries/Data/List/Quantifiers/Extra.idr#L17-L20)
> Add `(++)` for `List` variation of `All`

- .github/pull_request_template.md
- CHANGELOG.md
- CHANGELOG_NEXT.md
- CONTRIBUTING.md
- Release/CHECKLIST
We have a small problem that when releasing a new version, all existing PRs with entries in the CHANGELOG need to be updated so they do not mistakenly add entries to the already-released version. This PR adopts a strategy that was [suggested twice](https://github.com/idris-lang/Idris2/pull/3178) (as in use by other projects). It won't always make post-release management of open PRs effortless, but it should make it so that we have no risk of accidentally modifying the CHANGELOG for an already-released version.
> Add a new CHANGELOG_NEXT.md file and update documentation around CHANGELOG entries.

- support/js/support_system_file.js
In JS switch cases with shared code should look like this:
```js
switch(smth) {
case 'w':
case 'a':
// shared code
break;
}
```
In case of original code, first case always ignored:
```js
switch(smth) {
case 'w', 'a':   // Case 'w' always ignored
// 'a'-only code
break;
}
```
No, because currently NodeJS backend supports only 'r' mode, so this switch-case ignored anyway
> Fix static JS code: open process mode in support_system_file_popen

- CHANGELOG.md
- flake.nix
- nix/buildIdris.nix
- nix/package.nix
- nix/templates/pkg/flake.nix
- nix/templates/pkgWithDeps/flake.nix
- nix/test.nix
- Switch from deprecated `defaultPackage.${system}` to newer `package.${system}.default` flake structure.
- Rename `build` property of `buildIdris` result to `executable` (keep old property name around but deprecated).
- Rename `installLibrary` property of `buildIdris` result to `library` and turn it into a function that supports "install with source" (keep the old property name around but deprecated).
- Add the `idris2-api` package to the flake outputs.
> Improve `buildIdris` and expose the `idris2-api` via the Nix flake.

- CHANGELOG_NEXT.md
- src/Compiler/ES/Node.idr
- tests/node/executable/TestExecutable.idr
- tests/node/executable/expected
- tests/node/executable/run
The output file from compiling with the NodeJS backend is now executable which complements the already existing shebang at the top of that file nicely.
> Make NodeJS backend's output file executable

- CHANGELOG_NEXT.md
- flake.nix
- nix/buildIdris.nix
The last Nix PR I merged got the `buildIdris` function working much better for library installation. This PR makes executable builds much more useful. Where before they copied every build artifact blindly, now build artifacts are treated differently depending on whether its an _app folder for a scheme build where we want to re-wrap the binary or the single file for a NodeJS build where we want to set the executable bit.
These changes have been tested with several downstream projects including the `idris2-lsp` flake addition that I have in-progress and one of my more substantial Idris2 CLI tools.
> Fix executable output of buildIdris nix helper

- docs/source/faq/faq.rst
YouTube removed the original singing dragon video that was linked in the FAQs.
Added the archive.org version.
> fix: singing dragon link

- src/Compiler/RefC/RefC.idr
- support/refc/prim.c
- support/refc/prim.h
- tests/refc/prims/Test.idr
- tests/refc/prims/expected
- tests/refc/prims/run
- [RefC] delete unnecessary conversion to keep code simply.
- [RefC] rename some C functions to confliction safe.
- [RefC] make some C function inline for speed.
- [RefC] reuse some objects to reduce allocation cost.
-
Just for cleanup and safety.
no. I think this is transparent.
> - [RefC] delete unnecessary conversion to keep code simply.

- src/Compiler/Scheme/Chez.idr
Since incremental compilation currently has no way to know about constants in other modules, this commit sets the list of constants to `empty` (as is done in the `ChezSep` backend) which allows successful compilation.
The optimisation for non-recursive top-level constants introduced in #2817 accidentally breaks incremental compilation when an optimised top-level constant is referenced in another module (noticeable in larger, non-trivial programs, e.g. when building Idris itself in incremental mode).
The resulting error message (during execution) can look like this:
```
Exception: variable PrimIO-unsafePerformIO is not bound
```
The above error is caused due to the order of the different `(load "xyz.so")` statements. But even when correcting the `(load)` order by hand, the following error …
> [ fix ] Disable top-level constants optimisation during incremental compilation

- CHANGELOG_NEXT.md
- libs/base/Data/Buffer.idr
- libs/contrib/Debug/Buffer.idr
- src/Libraries/Utils/Binary.idr
- tests/chez/chez004/Buffer.idr
- tests/node/node004/Buffer.idr
- tests/refc/buffer/TestBuffer.idr
In pursuit of being able to eventually remove the deprecated `getByte` function, remove its use in the `bufferData` function and all other locations aside from the one test case that specifically exists to test the `getByte` function.
Then, realizing that the `bufferData` function has the same problem as `getByte`, deprecate `bufferData` in favor of `bufferData'` with a similar change in the range as to `getByte` -> `getBits8`. Along with deprecating `bufferData` and introducing `bufferData'`, the compiler source gains a duplicate definition of `bufferData'` so that it both avoids using a deprecated function and also continues to build using the previous version of the `base` library; that duplicated function can be removed once we release the next version of the compiler.
implementation, …
> Remove use of deprecated `getByte` function

- nix/buildIdris.nix
We build the support library as its own derivation for Nix builds so we do not want to copy it as part of the `buildIdris` install phase and we certainly don't want to wrap it as if it were an executable.
> Fix `buildIdris` on non-macos machines

- CHANGELOG_NEXT.md
- flake.lock
- flake.nix
- nix/buildIdris.nix
- nix/package.nix
- nix/support.nix
- nix/templates/pkg/flake.nix
- nix/templates/pkgWithDeps/flake.nix
The changes look more drastic than they are. The meat and potatoes of `buildIdris` are not changing, just some naming, some code organization (implementation details), and relatively small details of the output (like `name` being versioned now).
- align buildIdris function with direction of nixpkgs version.
- rename `idris2-api` flake output to `idris2Api` to follow nixpkgs.
- rename `projectName` buildIdris argument to `ipkgName` to better self-document its purpose.
- tangentially, update naming of local variables to follow nixpkgs.
- use pname/version instead of name for buildIdris derivations.
------
This is next on my list before considering merging:
> Hopefully final refactor of `buildIdris` for some time

- CHANGELOG_NEXT.md
- src/Compiler/RefC/RefC.idr
- support/refc/_datatypes.h
- support/refc/cBackend.h
- support/refc/memoryManagement.c
- support/refc/prim.c
- support/refc/prim.h
- support/refc/stringOps.c
- tests/refc/args/run
- tests/refc/buffer/run
- tests/refc/ccompilerArgs/run
- tests/refc/doubles/run
- tests/refc/garbageCollect/run
- tests/refc/integers/run
- tests/refc/issue1778/run
- tests/refc/issue2424/run
- tests/refc/issue2452/run
- tests/refc/prims/run
- tests/refc/refc001/run
- tests/refc/refc002/run
- tests/refc/refc003/run
- tests/refc/reg001/run
- tests/refc/strings/TestStrings.idr
- tests/refc/strings/expected
- tests/refc/strings/run
- tests/testutils.sh
* Bug fix
- Invalid memory read of strSubStr. (String overrun)
- Memory leaks of IORef.
* Perform memory leak analysis, if valgrind is installed.(Only for RefC)
* Keeping error messages at compile time of tests in the output to make debug easy.
> [RefC] [Test] Valgrind support & Fix invalid memory read of strSubstr

- libs/base/Language/Reflection.idr
- src/TTImp/Elab/RunElab.idr
- tests/idris2/reflection/reflection008/Interp.idr
- tests/idris2/reflection/reflection008/expected
- tests/idris2/reflection/reflection008/input
It's been noticed for a long time that memory consumption of the compiler executing elaborator scripts somewhat exponential on the reached depth of monadic bindings in the `Elab` monad. At the same time, it's been noticed that code like `act1 *> act2 <* act3` uses much more memory comparing to the code `do {act1; r <- act2; act3; pure r}` when it is somewhere deep inside the script. My guess is that this is because of a closures preserving problem, similar to runtime problems of closure allocation.
Since both `map` and `<*>` were implemented through `Bind` in the `Elab` monad, I thought that running them in `Core` is much more efficient (because `Core` is effectively a glamourous `IO`, which is run optimised, with no cost for bindings). I tried this, but I didn't suspect how efficient …
> [ fix ] Exponentially reduce memory consumption for elab scripts running

- src/Compiler/ES/Codegen.idr
- tests/node/node028/HelloWorld.idr
- tests/node/node028/LazyIsStillThere.idr
- tests/node/node028/expected
- tests/node/node028/run
This seems to be unnecessary, and, as was discussed [in the Discord](https://discord.com/channels/827106007712661524/827109161857712128/1199083661769838685), is as safe as the original code. This allows the tree-shaked code to not to contain unneeded definition of `__lazy` when it is indeed is not needed.
I added a test that checks that `mainExpression` is indeed compiled without `__lazy`, and that `__lazy` indeed was inserted when it was inserted before this PR.
> [ cleanup ] Do not wrap the `mainExpression` into `lazy` in ES backends

- flake.nix
This allows you to `make` Idris2 from a dev shell (`nix develop`).
> [new] Nix dev shell to the flake

- src/Compiler/RefC/RefC.idr
- tests/refc/callingConvention/expected
- tests/refc/garbageCollect/expected
- tests/refc/garbageCollect/run
- tests/refc/reuse/expected
- tests/testutils.sh
ReturnStatement has no role and is just noise that adds extra work.
Unless there is no other use for it, it should be removed.
> [RefC] [Cleanup] erase ReturnStatement

- CHANGELOG_NEXT.md
- libs/base/Language/Reflection/TTImp.idr
- tests/idris2/reflection/reflection027/TraverseWithConst.idr
- tests/idris2/reflection/reflection027/expected
- tests/idris2/reflection/reflection027/run
- tests/idris2/reflection/reflection027/test.ipkg
Current applicative traversals introduced at #3130 can be used for analysis of an expression, e.g. for collecting some data. But since currently the only way to analyse expression is to analyse the result of `pure`, used `Applicative` must contain at least on level of expressions, disallowing simple stuff like `Const` functor for applicative traversals for collecting the data.
But once we pass the original expression along with the current data to the user function, we gain the ability to traverse the data with simple applicatives, like `Const`. You can see an example of such collecting traversal in the newly added test.
This is a backward-compatible change in terms of main existing functions `mapATTImp` and `mapMTTImp`. However, intermediate functions for `mapM<WhateveElse>` changed …
> [ elab ] Support easy collection of information during `TTImp` traverse

- INSTALL.md
- src/Idris/CommandLine.idr
- src/Idris/SetOptions.idr
This is a pretty small benefit, but ever since I saw another project offer ZSH completion more directly by wrapping the init stuff up in the script I have wanted to add it everywhere.
> [new] zsh completion script

- nix/package.nix
Nix offers a standard way to expose auto-completion scripts in derivation outputs. Since Idris has auto-completion scripts for bash/zsh, install those into the output.
> [new] add autocompletion scripts to Nix output

- nix/buildIdris.nix
This makes specifying dependencies is much more intuitive.
This is backwards compatible (if you're specifying the whole dependency tree in the `buildIdris` `idrisPackages` input) but it will make specifying packages more intuitive and convenient; the list of packages needing to be specified will be the same list needing to be specified in the `ipkg` file.
> propagate dependencies for the buildIdris nix function

- CHANGELOG_NEXT.md
- libs/base/Data/Nat.idr
- tests/idris2/basic/basic044/expected
This re-implements `succNotLTEpred` such that the implicit argument of `succNotLTEpred` no longer needs to be available at runtime. It also adds `succNotLTEpred` as a `Uninhabited` instance, which parallels how `succNotLTEzero` is available as an `Uninhabited` instance.
It is technically user-facing so I've added it to the `CHANGELOG_NEXT` file. However, I'm happy to remove the addition to the change-log if it's superfluous.
> Generalize `succNotLTEpred` 

- tests/codegen/builtin001/expected
- tests/idris2/basic/basic044/expected
- tests/idris2/evaluator/spec001/expected
- tests/testutils.sh
This PR fixes an off by one error in `clean_names` awk script in `testutils.sh`.  The last digit of a name was ignored, causing some names to be merged that shouldn't be.  The issue was noted by @buzden here: https://github.com/idris-lang/Idris2/pull/3156#issuecomment-1983175868
> [ test ] fix clean_names function in testutils.sh

- CHANGELOG_NEXT.md
- src/Core/Context.idr
- src/Core/Options.idr
- src/Idris/Driver.idr
- src/Idris/REPL.idr
- src/Idris/SetOptions.idr
- tests/testutils.sh
For a number of versions now it has been the case that two different concepts share the same name in the Idris2 build process:
1. Locations where packages are searched for (e.g. `~/.idris2/idris2-0.7.0`)
2. Directories containing packages at the required versions for the current build (e.g. `~/.idris2/idris2-0.7.0/base-0.7.0`)
The build context has stored both of these things as `package_dirs` until now. This mixed-use can be quite confusing. If you print `idris2 --paths`, you will see a mix of `(1)` and `(2)` in the output for "Package Directories." Despite this output, the two really are used differently. Adding a path to `IDRIS2_PACKAGE_PATH` will add it to that shared list, but it will only work (i.e. a package will only be discoverable due to the additional path) if you are …
> [fix] Package Search Paths

- CHANGELOG_NEXT.md
- libs/base/Data/Nat.idr
- tests/base/data_nat/Properties.idr
- tests/base/data_nat/expected
- tests/base/data_nat/run
closes https://github.com/idris-lang/Idris2/issues/3230
This PR reverts the addition of a new Uninhabited implementation found in https://github.com/idris-lang/Idris2/pull/3225.
That addition looked good at face value, but with small Nats it causes ambiguity with another pre-existing implementation of the same interface. I think the most reasonable solution is to remove the new interface implementation because it is in essence already a named implementation of Uninhabited (`absurd x` can be spelled `succNotLTEpred x`).
I've added a test that failed with the following ambiguity prior to reverting the interface imoplementation:
```
Error: While processing right hand side of lteZeroSuccAbsurd. Multiple solutions found in search of:
Uninhabited (LTE 1 0)
Properties:4:23--4:31
1 | import …
```
> [fix] ambiguity error with Uninhabited interface implementations.

- .github/workflows/ci-idris2-and-libs.yml
> Use overwrite install to fix glib installation

- docs/source/reference/pragmas.rst
Add documentation for the `%cg` pragma. I missed this one when documenting the pragmas because it is hiding in the lexer.
> [ doc ] document %cg pragma

- CHANGELOG_NEXT.md
- CONTRIBUTORS
- libs/base/Language/Reflection.idr
- src/TTImp/Elab/RunElab.idr
- tests/idris2/reflection/reflection028/GetVis.idr
- tests/idris2/reflection/reflection028/expected
- tests/idris2/reflection/reflection028/input
- tests/idris2/reflection/reflection028/run
- tests/idris2/reflection/reflection028/test.ipkg
This is a small extension to the elaborator that allows an elab script to query the visibility of a declaration.
As a quick example, given the following file:
```idris
private foo : Bar
export baz : Quux
namespace A
public export foo : Bar
```
We can get do the following in the REPL:
```idris
> :let %language ElabReflection
> %runElab getVis `{foo}
[(NS (MkNS ["A", "Main"]) (UN (Basic "foo")), Public),
(NS (MkNS ["Main"]) (UN (Basic "foo")), Private)]
> %runElab getVis `{baz}
[(NS (MkNS ["Main"]) (UN (Basic "baz")), Export)]
```
The visibilities of all declarations matching the given `Name` are returned.
> [ elab ] Let elab scripts access visibility modifiers

- tests/idris2/total/total024/Issue1988.idr
- tests/idris2/total/total024/expected
- tests/idris2/total/total024/run
Issue #1988 appears to be fixed now, presumably thanks to PR #3108 or similar. This came up when I was looking through the `proof of false` tagged things, thanks to a question in the Discord. Thought it best to add the issue case to the test suite, just for good measure  : )
Closes #1988
Don't think so
> [ test ] Add issue#1988 to the test suite

- nix/package.nix
- nix/support.nix
Recent changes to the Refc support files require a newer version of the macOS stdenv than Nixpkgs defaults to. This PR builds the Support derivation against the newer stdenv and patches a spot where the support derivation would have otherwise been rebuilt as part of the bootstrapping process.
This has no impact on non-nix builds for non-macos platforms.
> [fix] macos-nix build: refc support files don't build under default environment anymore

- src/Compiler/RefC/RefC.idr
- support/refc/casts.h
- support/refc/memoryManagement.c
- support/refc/memoryManagement.h
- support/refc/prim.c
- support/refc/prim.h
- support/refc/runtime.c
- support/refc/runtime.h
- support/refc/stringOps.c
- tests/refc/callingConvention/expected
- tests/refc/reuse/expected
To really isolate the contribution in #3177 (removal of the arglist wrapper),
let us start by having a separate commit dealing with the primitives' renaming.
> [ re #3177 ] Separate the renaming from the rest

- docs/source/tutorial/typesfuns.rst
Doc: fixed one third-person form + one comma in "Types and Functions".
> doc: typos in "Types and Functions"

- src/Idris/Desugar.idr
- tests/idris2/operators/operators009/expected
Warning message for unexported fixities suggested the wrong fix.
> fix error message for unexported fixities

- docs/source/tutorial/modules.rst
The Crash Course material on naming modules is apparently out of date. It does not mention that identifiers in module names must be capitalized (I used UK spelling in my revision), or that they must match the filename path.
> Doc: module naming constraints

- Makefile
- config.mk
- tests/refc/ccompilerArgs/run
On ARM macs, homebrew stashes libgmp in `/opt/homebrew`.  The compiler build fails unless you set CPATH or CPPFLAGS.   It looks like github is now using ARM macs and the CI is failing.  Pack updates also fail for this reason (stefan-hoeck/idris2-pack#283).
The PR changes `config.mk` to look for `/opt/homebrew/include/gmp.h` and update `CPPFLAGS` and `LDFLAGS` if it is there.
> [ fix ] fix macos ci

- CHANGELOG_NEXT.md
- src/Idris/Parser.idr
- tests/idris2/error/perror031/Issue3251.idr
- tests/idris2/error/perror031/expected
- tests/idris2/error/perror031/run
This PR addresses #3251 - where unquote was picking up postfix expressions where it wasn't expected. 
Previously, `(g ~(f 5).fun)` would unquote all of `(f 5).fun` and now it only unquotes `(f 5)`.  Similarly `~x.fun` would unquote `x.fun` and now it only unquotes `x`.
The code from #3251 is used as a test case.
I've added it to CHANGELOG_NEXT since it may break existing code.
> [ parser ] Fix issue parsing unquote

- CHANGELOG_NEXT.md
- libs/test/Test/Golden.idr
- src/Idris/Parser.idr
- tests/idris2/error/perror032/LambdaImpossible.idr
- tests/idris2/error/perror032/expected
- tests/idris2/error/perror032/run
A user on the Discord was having trouble figuring out the syntax for creating a lambda whose cases are impossible.  It is currently supported via a case lambda: `\case Refl impossible`, but not with a bare lambda. The error message is unclear on what to do.
With this change we can now write expressions like `\Refl impossible` for impossible lambdas.
> [ parser ] Add support for impossible lambdas

- support/refc/memoryManagement.c
The support code calls `aligned_alloc` which does not appear to be supported on windows, and is not defined in the `stdlib.h` header file. The latest GitHub windows image has turned the warning about this into an error, causing ci to fail.
I’ve updated the condition in `memoryManagement.c` to use the fallback branch which calls `malloc` when building on windows.
> [ fix ] fix windows CI, aligned_alloc not supported on win32

- CHANGELOG_NEXT.md
- libs/base/Control/Function/FunExt.idr
We have a `FunExt` interface containing general enough proposition, for omega-quantitied functions. But this property is also useful for functions taking arguments with the other quantities as well. Thankfully, these properties are derivable from the existing one, so I propose to add them with their proofs to the library.
> [ funext ] Add a proof for funext variants with the other quantities

- CHANGELOG_NEXT.md
- src/Compiler/Opts/CSE.idr
- src/Compiler/Scheme/Common.idr
- src/Compiler/Scheme/Racket.idr
- tests/Main.idr
- tests/idris2/misc/lazy005/LiftedBot.idr
- tests/idris2/misc/lazy005/LiftedTrace.idr
- tests/idris2/misc/lazy005/expected
- tests/idris2/misc/lazy005/run
This PR fixes #2927.
Thanks to @stefan-hoeck for his assistance in Discord. He suggested fixing the issue by using Scheme's `delay` and `force` to memoize constants, as in #2807 instead of #2817 that is currently used. However, this solution comes with a performance overhead.
To reduce the overhead, I modified CSE to track whether an expression occurs inside a `%delay` block. If that is the case, the expression is lifted as memoized lazy value using Scheme's `delay` and `force`. Otherwise, it becomes an eagerly evaluated top-level constant. Benchmarking the bootstrapped compiler on `idris2api.ipkg` showed 5% slowdown on my machine, which is an improvement compared to the 8.5% slowdown in #2807.  
> [ fix #2927 ] Do not eagerly evaluate expressions occurring inside `%delay` block

- libs/contrib/System/Future.idr
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/Racket.idr
- tests/chez/futures002/Futures.idr
- tests/chez/futures002/expected
- tests/chez/futures002/run
- tests/racket/barrier001/run
- tests/racket/futures002/Futures.idr
- tests/racket/futures002/expected
- tests/racket/futures002/run
Fix in #2939 accidentally broke one (actually, inconsistent) assumption about how the lazy values are managed. This may lead to a crash, you can see an example in the newly added test. Incidentally, this does not crash on chez (yet) because of undocumented coindicence of two runtime representations in the current particular implementation (dynamically-typed languages, omg), but this can change in the future at any time. Racket fails properly.
I changed the way the primitive `prim__makeFuture` is called: now it reuses the way the forcing is actually implemented instead of trying to assume particular implementation. We should be more stable on potential future changes of the way lazy values are treated after this PR.
Pinging @mjustus as the merger of #2939.
UPD: Oh, and I found that one …
> [ fixup #2939 ] Make futures not interfere with optimisations

- docs/source/reference/pragmas.rst
This fixes a typo.
Discussed with @buzden over the Discord channel.
> fix: typos in "Expressions"

- docs/source/reference/pragmas.rst
Hi,
I'm was not sure what elaborator reflection was and I saw references to it in the main docs but couldn't find any information introducing it. 
This PR links introductory material by @stefan-hoeck as discussed with @buzden over Discord.
> [ doc ] reference intro info on elab

- docs/source/tutorial/views.rst
- src/Idris/Doc/Keywords.idr
The documentation in `:doc with` mentions that `with` rewrites the target type. This doesn't seem to be mentioned in the html documentation, so I'm copying it here.  This came up in the discussion in #3271. 
I've also added documentation for multi-`with` and removed the warning about the documentation not being updated for Idris 2.  The documentation appears to be accurate and all of the code snippets run in Idris 2.
#3271 also asks when to use `with` vs `case`.  I'm not sure what to say or where to say it, so I haven't addressed that.
> [ doc ] Update documentation for `with`

- libs/base/Control/Monad/Maybe.idr
I was surprised at first to find that `toMaybeT` executes its effect regardless of the condition. Does my docstring edit clarify that?
> clarify `toMaybeT` docstring

- docs/source/tutorial/interfaces.rst
This fixes a typo in the docs.
> fix: typos in "Named Implementations"

- INSTALL.md
The previous command does not work in any shell I am aware of. The new one directly opens the library documentation in `$BROWSER` if it is set and otherwise just echos the path to index.html.
> Doc: Use executable command for opening lib docs

- CHANGELOG_NEXT.md
- libs/base/Data/Vect/Elem.idr
This makes it possible to call the function in more situations. It also brings its signature in line with the overloads on `List`, `List1` and `SnocList`.
The previous implementation of `Data.Vect.Elem.dropElem` required the length of the `Vect` to be available at runtime. This was used in order to recurse in the case that the `Elem` is not `Here`. However, it turns out that this is not actually necessary. Idris can deduce that the tail must be non-empty if it contains an `Elem`.
> fix(base): runtime-erase implicit length argument to Vect's `dropElem`.

- CHANGELOG_NEXT.md
- libs/prelude/Prelude/Basics.idr
- libs/prelude/Prelude/Ops.idr
- src/Libraries/Data/PosMap.idr
- tests/idris2/misc/import009/Import.idr
- tests/idris2/misc/import009/expected
- tests/idris2/operators/operators001/Test.idr
- tests/prelude/operators001/Test.idr
- tests/prelude/operators001/expected
- tests/prelude/operators001/run
Adds the pipeline operators `|>` and `<|` known from other functional languages like F# and Elixir.
> Add pipeline operators

- CHANGELOG_NEXT.md
- flake.nix
- src/Idris/SetOptions.idr
This makes some improvements to the output of the `--list-packages` Idris2 option. Mostly, my aim was to make it more apparent when different "advanced" installs of Idris and libraries has created a problem because libraries aren't installed with the same TTC version as Idris2. The improvements also make it clear when you have multiple installs of a library in your package path and where these libraries are -- useful because Idris only "sees" the first one it encounters.
Before, an example of output for a complex install might be:
```
base (Just 0.7.0)
base (Just 0.7.0)
contrib (Just 0.7.0)
contrib (Just 0.7.0)
linear (Just 0.7.0)
linear (Just 0.7.0)
network (Just 0.7.0)
network (Just 0.7.0)
prelude (Just 0.7.0)
prelude (Just 0.7.0)
test (Just 0.7.0)
test (Just 0.7.0)
```
After (I've …
> List packages improvements

- src/Core/AutoSearch.idr
- tests/idris2/error/error028/Issue3313.idr
- tests/idris2/error/error028/expected
- tests/idris2/error/error028/run
This fixes #3313, where auto search reports no solution instead of an ambiguous solution. 
The root cause it that the `AmbiguousSearch` error is caught and then re-emitted as `CantSolveGoal`.
Prior to this change the code:
```idris
data Expr : Type -> Type where
Add : (Integral n) => n -> n -> Expr n
eval : (Integral n) => Expr n -> n
eval (Add x y) = x + y
```
reports
```
1/1: Building src.Issue3313 (src/Issue3313.idr)
Error: While processing right hand side of eval. Can't find an implementation for Num n.
src.Issue3313:5:18--5:23
1 | data Expr : Type -> Type where
2 |     Add : (Integral n) => n -> n -> Expr n
3 | 
4 | eval : (Integral n) => Expr n -> n
5 | eval (Add x y) = x + y
^^^^^
```
and after the change it reports
```
1/1: Building Issue3313 (src/Issue3313.idr)
Error: While …
```
> [ fix ] auto search returns no solution instead of ambiguous solution #3313

- src/TTImp/Elab/App.idr
- src/TTImp/Elab/Check.idr
- src/TTImp/Elab/ImplicitBind.idr
- src/TTImp/Elab/Term.idr
- tests/idris2/error/error028/expected
- tests/idris2/error/error029/Issue34.idr
- tests/idris2/error/error029/expected
- tests/idris2/error/error029/run
- tests/idris2/interactive/interactive042/expected
- tests/idris2/interface/interface016/expected
When implicitly binding a variable, use the location of the head function/constructor that expects it. This way we can differentiate multiple implicits bound on the same LHS.
Note that this does not resolve the issue 34: there the location is then further muddled by the fact that where-bound functions are lifted to the toplevel.
> [ re #3314, #34 ] Tighten the location information for implicits

- src/Core/AutoSearch.idr
- tests/idris2/interface/interface031/DefaulthintWithDep.idr
- tests/idris2/interface/interface031/expected
- tests/idris2/interface/interface031/run
- tests/idris2/interface/interface032/DefaulthintInterfaceBug.idr
- tests/idris2/interface/interface032/expected
- tests/idris2/interface/interface032/run
Fixes #2850, fixes #2932.
The root cause of both fixed problems was errorneous proparation of the `defaults` flag down to search of *dependencies* of found hint candidates. Default hint may require non-default implementation as an `auto`-argument and vice versa. You can see cases in reported issues being fixed.
Some special error treatement was added to make sure we leave adequate error messages in case of the whole search went bad.
This PR is split to several commits to make review easier.
> [ fix ] Fix search around `%defaulthints`

- src/Core/Termination/CallGraph.idr
The changes in #3108 remove the `arity` argument from `findSCcall`, but left some code that was doing a type lookup to compute the arity. This PR removes that vestigial code.
> [ cleanup ] remove unused code left in #3108

- CHANGELOG_NEXT.md
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/ChezSep.idr
At least @edwinb and I are using this `collect-request-handler` for at least more than half of a year and we were discussing at the last weekly Idris chat that it's time to make all users happy being able to use this.
In case you doubt, you can try this GC handler and play with [this patcher](https://github.com/buzden/deptycheck/blob/master/.patch-chez-gc-handler) which replaces only the handler in the given `*.ss` file (recompiling the `*.so` one) or installed app name (using `pack`).
> [ perf ] Use alternative better GC on chez

- CHANGELOG_NEXT.md
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/ChezSep.idr
- support/chez/support.ss
> idris2.ss: support powerpc

- support/c/idris_signal.c
`static_assert` may not be defined in `assert.h`, use `_Static_assert` as a fallback.
This fix is borrowed from Python.
> idris_signal: fix static_assert

- nix/buildIdris.nix
- nix/package.nix
- nix/support.nix
- The Nix `buildIdris` function now precisely targets the executable and also any C libraries built alongside the executable so less work needs to be done to package an application that ships its own shared library.
- The Nix derivations for the `support` libraries and compiler don't rebuild when only the `buildIdris` function changes anymore.
> Nix `buildIdris` improvement: precisely target executable

- CHANGELOG_NEXT.md
- libs/base/Decidable/Decidable.idr
`decision` is not used in this file, so I assume it is intended to be exported.
> Public export Decidable.Decidable.decision

- flake.lock
- nix/buildIdris.nix
Following in the footsteps of a recent change to the Nixpkgs variant of `buildIdris`, this PR just makes it a bit easier to work with the output of the `buildIdris` function as an input to another Idris package. The changes are backwards compatible so they just provide more flexibility and better ergonomics going forward.
Before:
```nix
let myLib = buildIdris { ... };
in buildIdris {
...
idrisLibraries = [ (myLib.library {}) ];
}
```
After:
```nix
let myLib = buildIdris { ... };
in buildIdris {
...
idrisLibraries = [ myLib ];
}
```
> [nix] allow `buildIdris` output to be used as a dependency in other `buildIdris` calls more directly

- CHANGELOG_NEXT.md
- src/Idris/Desugar.idr
- src/Idris/Parser.idr
- src/Idris/Pretty.idr
- src/Idris/Syntax.idr
- src/Idris/Syntax/Traversals.idr
- tests/idris2/basic/basic072/Issue3327.idr
- tests/idris2/basic/basic072/expected
- tests/idris2/basic/basic072/run
This PR implements most of the proposal in #3327. With this change we can optionally provide a type annotation in a monadic bind, following the syntax of the same in a `let` statement:
```idris
test1 = do
x : Nat <- foo
printLn x
```
and with pattern matching
```idris
test6 = do
Just x : Maybe Nat <- bar
| Nothing => pure ()
printLn x
```
The discussion in #3327 (and on discord) mentions support for declaring multiplicities on the binds like in `let` statements.  This is implemented when binding a variable name, but not for a pattern matching bind.  The syntax for pattern quantities would have broken existing code and would not function correctly because of issues related to #2513 (`ICase` does not have a quantity).
implementation, I have updated …
> Add type annotations to monadic bind #3327

- CHANGELOG_NEXT.md
- libs/base/Language/Reflection/TT.idr
> [ elab, minor ] Implement `Functor` for `PiInfo`

- CHANGELOG_NEXT.md
- libs/base/Language/Reflection.idr
- tests/idris2/reflection/reflection030/SearchZero.idr
- tests/idris2/reflection/reflection030/expected
- tests/idris2/reflection/reflection030/run
Or else we are unable to work with types that contain zeroin inside
> [ elab ] Change quantity of the `search` function's argument to `0`

- CHANGELOG_NEXT.md
- libs/contrib/System/Future.idr
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/Common.idr
- src/Compiler/Scheme/Racket.idr
- support/chez/support.ss
- support/racket/support.rkt
`System.Future` in `contrib` is strange, especially because it relies on two backend-specific functions, `prim__makeFuture` and `prim__awaitFuture` which are very different: the first one is a special primitive function that compiler is aware of, when the second one is a normal `%foreign` function. The main reason for this was the desire to pass `Lazy` value into the foreign function, which is not supported (for good reason, I think), so it was made a primitive.
But I think that this was, basically, the XY-problem -- we actually wanted to pass not a `Lazy` value of type `a`, but a function that returns `a` when demanded -- in general case, semantics of `Lazy` values may differ, but semantics of this call does not. Also, it is pretty disgusting that we have a compiler primitive that is …
> [ cleanup ] Make `makeFuture` to be `%foreign`, not `%extern`

- tests/testutils.sh
Sets the locale in the `testutils.sh`. I think, this is right place do to this, since no other test wants to observe the same problem in the future.
> [ fix #3339 ] Set the global test locale

- src/Core/Normalise/Eval.idr
- tests/idris2/evaluator/evaluator005/TypeCase.idr
- tests/idris2/evaluator/evaluator005/expected
- tests/idris2/evaluator/evaluator005/input
- tests/idris2/evaluator/evaluator005/run
Compile time typecase gets stuck when comparing a type constructor case alt to either a Pi type or `Type`.  This is happening because the code path for the happy case is present:
```idris
tryAlt {more}
env loc opts fc stk (NBind pfc x (Pi fc' r e aty) scty) (ConCase (UN (Basic "->")) tag [s,t] sc)
```
but the non-matching case falls back to `GotStuck`. I've added cases for `NoMatch` for both Pi types and `Type`.
This issue was reported in the idrus-help-forum on discord.
Previously, given the code from the discord discussion:
```idris
data The : (a : Type) -> a -> Type where
Is : (x : a) -> The a x
tcase : Type -> Type
tcase (The a _) = a
tcase a = a
```
the REPL would evaluate `tcase (Int -> Int)` to `tcase (Int -> Int)`. Getting stuck at:
```
LOG eval.casetree.stuck:5: Got stuck …
```
> [ fix ] compile time typecase for functions

- .github/workflows/ci-idris2-and-libs.yml
- tests/testutils.sh
On my machine when I run the test suite, every single test case complains with:
```
../../testutils.sh: line 113: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
```
This seems to be a common issue with macOS, though I can't explain why we don't see that warning in CI. Nevertheless, I found a solution that feels reasonable enough and certainly cleans up the warnings on my machine.
I also bumped the version of the racket setup action being used in response to GitHub's warning about the version of NodeJS that action was using.
> Fix annoying warning when running tests on some macOS machines

- CHANGELOG_NEXT.md
- libs/base/Data/Either.idr
I'm using this to provide more informative proofs on function arguments than `IsJust`.
> Add `fromRight` and `fromLeft` for extracting values out of `Either`

- libs/base/System/Clock.idr
- src/Idris/Parser.idr
- src/Idris/Pretty.idr
- tests/idris2/error/perror033/DeclIndent.idr
- tests/idris2/error/perror033/expected
- tests/idris2/error/perror033/run
This PR improves the checking of indentation in function declarations.  The issue was brought up by @Russoul on discord.  The current parser accepts the following code, despite an outdent past the beginning of the function declaration:
```idris
namespace A
test : (x : Type -> Type) -> Type
test x =
x Type
```
After the change, this gives:
```
1: Unexpected end of expression.
DeclIndent:4:2--4:3
1 | namespace A
2 |   test : (x : Type -> Type) -> Type
3 |   test x =
4 |  x Type
^
... (2 others)
```
I addressed this by adding an indentation check after the `=`.  My initial fix was to add the check to `typeExpr`, but this broke parsing at the repl, which runs `typeExpr` with an indentation of 0.  Fixing this issue required two indentation fixes in the Idris source, and it may affect user code …
> [ fix ] check indentation after = in declarations

- CHANGELOG_NEXT.md
- libs/test/README.md
- libs/test/Test/Golden.idr
- tests/Main.idr
This change to how Golden tests handle requirements for a pool of tests makes the test framework much more versatile. It is a breaking change but most code using the test lib (including the compiler test suite) won't need to change in response to it.
I've introduced a new `Requirement` record type to allow projects using this library to define their own types of requirements. Existing constructors of the old `Requirement` type have been rewritten as same-named functions returning values of the new record type.
> Support more flexible requirements for Golden tests

- CHANGELOG_NEXT.md
- src/Core/Termination/CallGraph.idr
- tests/idris2/total/total004/expected
- tests/idris2/total/total025/Issue3317.idr
- tests/idris2/total/total025/Totality.idr
- tests/idris2/total/total025/expected
- tests/idris2/total/total025/run
- tests/ttimp/total002/expected
The PR enhances totality checking to see size changes underneath matching constructors, addressing issue #3317. With this change Idris recognizes:
- `Just xs` is smaller than `Just (x :: xs)`
- `x :: zs` is smaller than `x :: y :: zs`
and similar changes.  The new additional rule is that an argument is smaller than a parameter if the data constructors match on both sides, each of the corresponding arguments of the constructor are either `Same` or `Smaller` (not `Unknown`), and at least one argument is `Smaller`. This is applied recursively, so `a :: c :: es` is smaller than `a :: b :: c :: d :: es`.
We can't allow `Unknown`, because that could be used to introduce a structurally larger child that could later be used in recursion.
That change is in `sizeCompareCon`.
The `pfoom` function in …
> [ new ] totality checking can look under constructors

- .github/linters/.stylelintrc.json
- .github/workflows/ci-super-linter.yml
- CHANGELOG_NEXT.md
- CONTRIBUTORS
- src/Idris/Doc/HTML.idr
- src/Idris/Package.idr
- support/docs/alternative.css
- support/docs/blackandwhite.css
- support/docs/default.css
This PR addresses [3014](https://github.com/idris-lang/Idris2/issues/3014) and adds functionality for adding docstrings for each applicable module when created via `--mkdoc`.
Closes #3014.
> Show module docstring for namespace indexes

- libs/linear/System/Concurrency/Session.idr
Can't push straight to `main`  as it's protected :(
> [ linear ] typo in the docstring

- libs/base/Language/Reflection/TT.idr
- libs/base/Language/Reflection/TTImp.idr
- tests/idris2/reflection/reflection020/FromDecls.idr
- tests/idris2/reflection/reflection020/FromName.idr
- tests/idris2/reflection/reflection020/FromTTImp.idr
This follows on from #2930. Now that we've had a version bump, we can bind `fromTTImp`, `fromName`, and `fromDecls` in base.
> Add fromTTImp, fromName, and fromDecls

- CHANGELOG_NEXT.md
- src/Idris/Package.idr
- src/Idris/Package/Init.idr
This PR closes #3232.
This issue stemmed from the lack of parsing in `interactive` found in `src/Idris/Package/Init.idr`.
> `idris2 --init` doesnt check the name of a package

- src/Compiler/Scheme/Chez.idr
- tests/chez/chez037/Hello.idr
- tests/chez/chez037/expected
- tests/chez/chez037/run
If chez exits with a status code other than 0 during compilation, Idris ignores the error and completes successfully, leaving a non-working executable. For example, this occurs when an out of memory error occurs during compilation.  I've changed `Chez.idr` to check the return code and throw an `InternalError` reporting the code if it is not zero.
Before this change, `CHEZ=false idris2 -c Hello.idr -o hello` would complete successfully, but `./build/exec/hello` would report:
```
./build/exec/hello: line 15: /Users/dunham/code/i2/Idris2/build/exec/hello_app/hello.so: No such file or directory
```
after the change, the compilation step fails with:
```
Error: INTERNAL ERROR: Chez exited with return code 1
```
> [ fix ] Report chez failures

- CHANGELOG_NEXT.md
- src/Idris/Package.idr
This PR enables `--clean` to remove documentation generated via `--mkdoc`.
This addresses one of the tasks in #1918.
> Clean removes generated docs

- CHANGELOG_NEXT.md
- libs/base/System/Signal.idr
In this small but potentially breaking change, `System.Signa.signalCode` and `toSignal` are `export`ed, since these conversions are useful when one wants to define different signal handling routines while sticking to the already existing `Signal` type.
> [ refactor ] export signal to code conversions

- CHANGELOG_NEXT.md
- libs/base/Control/Monad/Identity.idr
This allows us to simply reuse more general code, e.g. for any `Foldable`, for single items without creation of intermediate singleton lists or anything.
> [ base ] Implement `Foldable` and `Traversable` for `Identity`

- src/Compiler/Opts/ConstantFold.idr
- tests/codegen/fix3375/Prog.idr
- tests/codegen/fix3375/run
- tests/idris2/total/total022/expected
This fixes #3375 by adding two additional rules to constant folding.
> [ codegen ] get rid of artifacts introduced when optimizing `IO`

- samples/FFI-readline/readline_glue/idris_readline.c
Closes #1179.
On some systems this sample already builds fine, on others it hits the error that `FILE` is not defined. Including `stdio` fixes the problem and even aligns with the example code given in the readline manpages.
> [fix] include stdio header in readline C code in example so it builds on all systems

- .github/workflows/ci-idris2-and-libs.yml
This fixes recent CI failures after GitHub stopped including hidden files in artifact uploads by default. The Idris2 compiler gets installed into one such hidden folder, so we need to include them.
> include hidden files in artifact

- nix/buildIdris.nix
Up until now I've never seen an app with more than one `_app` directory in the build output of Idris2, but I saw one today. This small change makes the Nix `buildIdris` function handle the multi-app-directory build artifacts without issue.
> [ fix ] make buildIdris nix function still work when there are more than one app directories in the build output

- docs/source/backends/gambit.rst
This PR makes a few changes to the gambit documentation to try to fix some confusion in #3387
It wasn't clear what version was needed to use `GAMBIT_GSC_BACKEND`, it wasn't clear that `--directive C` does not create an executable, and it stated that you needed to build gambit yourself to use `GAMBIT_GSC_BACKEND`.
> [ doc ] Update gambit docs

- CHANGELOG_NEXT.md
- CONTRIBUTORS
- src/Parser/Lexer/Common.idr
- src/Parser/Lexer/Package.idr
- src/Parser/Lexer/Source.idr
- tests/idris2/pkg/multiline-comments/Main.idr
- tests/idris2/pkg/multiline-comments/expected
- tests/idris2/pkg/multiline-comments/run
- tests/idris2/pkg/multiline-comments/test.ipkg
Alternative to #3384.
Implements multiline comments in ipkg to fulfill the promises of the existing documentation.
Added to _NEXT.
> Handle multiline comments in Package (ipkg)

- CHANGELOG.md
- src/Core/CompileExpr/Pretty.idr
- tests/idris2/basic/basic039/expected
- tests/idris2/repl/repl007/expected
- tests/idris2/repl/repl007/input
- tests/idris2/repl/repl007/run
The `:di` command at the REPL confuses data and type constructors. Example:
```repl
CaseTree> :di Bool
Prelude.Basics.Bool
Type constructor:
tag: 100
arity: 0
parameter positions: []
constructors: Prelude.Basics.False, Prelude.Basics.True
Compiled: Data Constructor:
arity: 0
```
As can be seen, `Bool` is listed as a "Data Constructor" in its compiled form. Likewise, `True` or `False` will be listed as type constructors. The fix is trivial.
> [ fix ] Data and Type Constructor tags for :di

- src/Idris/Desugar.idr
- tests/idris2/operators/operators012/Y.idr
- tests/idris2/operators/operators012/expected
- tests/idris2/operators/operators012/run
Fixity declarations are instructions to parsers, thus they can appear in a lot of places in code, e.g. in `let`s, `where`s, etc., and they work till the end of the module or hiding/redefinition, like pragmas. This indeed may be useful, say, we are definiting local function which uses some context in its closure, and we want to declare it as an infix operator: it's logical that you can declare a fixity of this function near the definition of a function, and it indeed works:
```idris
f : Nat
f =
let (%^%) : Nat -> Nat -> Nat
(%^%) = (+)
private infixl 1 %^%
in 1 %^% 2
```
But as soon as you try this in `do`-notation, it suddenly does not work:
```idris
g : Nat
g = do
let (%^%%) : Nat -> Nat -> Nat
(%^%%) = (+)
private infixl 1 %^%%
1 %^%% 2
```
```console
Error: Unknown operator '%^%%' …
```
> [ fix ] Fix ability to declare fixities in `do`

- src/Core/Case/Util.idr
- src/Core/Coverage.idr
- src/TTImp/Impossible.idr
- src/TTImp/ProcessDef.idr
- tests/idris2/coverage/coverage021/Head.idr
- tests/idris2/coverage/coverage021/Issue2250a.idr
- tests/idris2/coverage/coverage021/Issue2250b.idr
- tests/idris2/coverage/coverage021/Issue2250c.idr
- tests/idris2/coverage/coverage021/Issue3276.idr
- tests/idris2/coverage/coverage021/Visibility.idr
- tests/idris2/coverage/coverage021/expected
- tests/idris2/coverage/coverage021/run
This PR addresses a few issues in #2250 and issue #3276.  They are caused by an issue with `IAlternative` in impossible clauses, a type confusion issue in impossible clauses, and treatment of out of hidden constructors as impossible. An additional issue was brought up in #2250 that is not addressed here.  I'll first discuss the issues and how I resolved them and then discuss a frex issue that should be patched before merging.
The `IAlternative` issue is illustrated at the top of #2550:
```idris
%default total
g : Not Bool
g () impossible
f : Void
f = g True
```
Here the `impossible` clause is accepted because the type doesn't match at all, but when it is converted by `mkTerm` to a term for coverage checking, the ambiguous `()` is converted to a pattern variable which is then considered to …
> [ fix ] Address some proofs of void via impossible from issues #2250 and #3276

- CHANGELOG_NEXT.md
- CONTRIBUTORS
- src/Idris/Parser.idr
- tests/idris2/repl/repl001/expected
Remove reference to column number parameter in the help menu for the `refine` command.
> fix: help menu for `refine` command

- CHANGELOG_NEXT.md
- libs/base/Data/Nat.idr
- libs/contrib/Data/Nat/Factor.idr
- libs/contrib/Data/Vect/Properties/Fin.idr
- libs/papers/Search/Auto.idr
Historically for some strange reason in `Data.Nat` we have two equivalent definitions: `IsSucc` and `NonZero`. Other standard types have standard pattern of `Is<Constructor>` type, `ItIs<Constructor>` constructor of proof and `isIt<Constructor>` for `Dec Is<Consturctor>`. `IsSucc` follows this pattern, when `NonZero` does not. However, `NonZero` is a handy name for this.
But the fact that there are two different types for this and the fact that some standard and non-standard functions use one of them, and others use the other, triggers a lot of people (I personally know around five of them).
What I suggest is to make `NonZero` to be an alias for `IsSucc` and to declare a deprecated alias for original constructor of `NonZero` to be backward compatible at least on usages at RHS. …
> [ cleanup ] Make `Nat`'s `NonZero` to be an alias for `IsSucc`

- CHANGELOG_NEXT.md
- libs/base/Data/SortedMap.idr
- libs/base/Data/SortedMap/Dependent.idr
- libs/base/Data/SortedSet.idr
- src/Compiler/Opts/ToplevelConstants.idr
- src/Compiler/RefC/RefC.idr
- src/Compiler/Scheme/ChezSep.idr
- src/Compiler/Separate.idr
- src/Core/Case/CaseBuilder.idr
- src/Core/Termination/SizeChange.idr
- src/Libraries/Data/Graph.idr
- src/Libraries/Data/SortedMap.idr
- src/Libraries/Data/SortedSet.idr
- src/TTImp/Elab/Record.idr
- src/TTImp/TTImp.idr
- tests/idris2/reflection/reflection027/TraverseWithConst.idr
This is mainly the less controversial part of #3392, reimplementing and deprecating completely useless specialised `toList` function from `SortedSet`.
Additionally, this PR contains some preparation to future removing the redundant `Libraries.Data.Sorted{Set|Map}` from the compiler's internal lib, the fact coming from times when `Sorted{Set|Map}` were in `contrib`. But currently, they cannot be replaced, because implementations in the compiler's lib have several functions that are missing in the implementation at `base`, so I suggest adding them there, while also doing the same thing with deprecating specialised `toList`, so that we just could remove those redundant modules once we've released new version of the compiler.
I made all changed in different commits in order to make review …
> [ base ] Better set's `toList` implementation + preparation for cleanup

- src/Idris/CommandLine.idr
- tests/Main.idr
- tests/cli/optional001/run
- tests/cli/optional001/test.ipkg
If an optional argument is expected and the following option comes instead, it is skipped. For example, in the command
```shell
idris2 --build --quiet
```
`--quiet` will be missed. And the command
```shell
idris2 --clean --log 0
```
will be processed as
```shell
idris2 0 --clean
```
> [ fix ] Fix option loss when an optional argument is missed

- libs/base/System.idr
`system` returns `Int`, and `exitWith` takes `ExitCode`. So it is useful to have casts between the two. In particular this is needed for #3427, because most code generators use `system` for `executeExpr`.
> [ base ] Add casts between `Int` and `ExitCode`

- CHANGELOG_NEXT.md
- src/Idris/CommandLine.idr
- src/Idris/Driver.idr
- src/Idris/Error.idr
- src/Idris/Package.idr
- src/Idris/REPL.idr
- src/Protocol/SExp.idr
- tests/idris2/error/error008/expected
- tests/idris2/error/error012/expected
- tests/idris2/error/error032/expected
- tests/idris2/error/error032/run
- tests/idris2/error/perror008/expected
- tests/idris2/error/perror008/run
- tests/idris2/error/perror011/expected
- tests/idris2/error/perror011/run
- tests/idris2/misc/import004/expected
- tests/idris2/misc/import004/run
I tried to keep the following isolated in their own commits so we can just ditch anything folks don't like.
----
Whereas the CLI for the REPL currently only pays attention to one argument as an input file but quietly ignores the rest, I've made it an error to specify multiple input files:
```
Uncaught error: Error: Expected at most one input file but was given: file1.idr, file2.idr
```
This is further improved (described in the last section below) by using `die` instead of an uncaught `throw` so the error doesn't look so unexpected.
----
Whereas the REPL previously printed an error about a file loaded with `:l` in monochrome without fanfare, I've indented the error message, given it room to stand out, and written the context of the error in the standard `IdrisAnn` color for error …
> Error Message Potpourri

- .github/workflows/ci-idris2-and-libs.yml
This would allow us to break the tie when we need green CI for the breaking compiler change AND simultaneously correct pack collection building with the previous compiler version, like it happened in #3415.
> [ ci ] Make pack-dependent jobs to use bleeding edge

- src/Idris/Driver.idr
- src/Idris/Package.idr
- src/Idris/SetOptions.idr
- tests/idris2/error/perror011/expected
- tests/idris2/error/perror011/run
- tests/idris2/misc/import006/expected
- tests/idris2/misc/import006/run
- tests/idris2/misc/import008/Exe/depends/lib-0
- tests/idris2/misc/import008/run
- tests/idris2/pkg/pkg003/expected
- tests/idris2/pkg/pkg003/run
- tests/idris2/pkg/pkg006/expected
- tests/idris2/pkg/pkg006/run
- tests/idris2/pkg/pkg013/run
- tests/idris2/pkg/pkg014/run
- tests/idris2/pkg/pkg015/expected
- tests/idris2/pkg/pkg015/run
- tests/idris2/pkg/pkg018/expected
- tests/idris2/pkg/pkg018/run
- tests/idris2/pkg/pkg021/expected
- tests/idris2/pkg/pkg021/input
- tests/idris2/pkg/pkg021/run
- tests/idris2/pkg/pkg021/src/Stuff.idr
- tests/idris2/pkg/pkg021/test.ipkg
- tests/testutils.sh
Prior to this change, the first package matching version requirements would be used by the compiler -- if that package was only installed with an incompatible TTC version, it simply cannot be used. After this change, we skip package directories with only incompatible TTC versions which allows the compiler to find a farther down option (if one exists) in some other directory that does have a compatible TTC vesrion.
For example, if you've got an incompatible package named `foo` at `~/.idris2/idris2-0.7.0/foo-0/12345` and a compatible package at `~/extra/idris2/foo-0/56789` this PR allows the compiler to succeed given `~/extra/idris2` is in `IDRIS2_PACKAGE_PATH`. Prior to this PR, that would not have worked.
When a package is passed over due to incompatible TTC version, you see the following …
> When searching for packages, rule out incompatible TTC versions

- src/Core/Context.idr
- src/Core/Options.idr
- src/Idris/Package.idr
- src/Idris/SetOptions.idr
- tests/idris2/pkg/pkg006/expected
- tests/idris2/pkg/pkg006/run
- tests/idris2/pkg/pkg015/expected
- tests/idris2/pkg/pkg015/run
- tests/idris2/pkg/pkg020/run
- tests/testutils.sh
The error when a package dependency cannot be resolved is updated from e.g.
```
Error: Failed to resolve the dependencies for my-pkg:
pg-idris-0.0.8; indexed-0.0.10; parser-json-0.1.0; parser-0.1.0; elab-util-0.6.0; base-0.7.0; required indexed > 0.0.10 but assigned version 0.0.10 which is out of bounds
```
To
```
Error: Failed to resolve the dependencies for my-pkg:
Required indexed > 0.0.10 but only found version 0.0.10 which is out of bounds. Resolved transitive dependencies: pg-idris-0.0.8; indexed-0.0.10; parser-json-0.1.0; parser-0.1.0; elab-util-0.6.0; base-0.7.0.
Searched for packages in:
/home/matt/staging/tmp/depends
/home/matt/.idris2/idris2-0.7.0
For more details on what packages Idris2 can locate, run `idris2 --list-packages`
```
Tangentially, the output for `--list-packages` …
> Improve package dependency error

- src/Core/FC.idr
- src/Idris/Desugar.idr
- src/Idris/Desugar/Mutual.idr
- src/Idris/Parser.idr
- src/Idris/Pretty.idr
- src/Idris/ProcessIdr.idr
- src/Idris/Resugar.idr
- src/Idris/Syntax.idr
- src/Idris/Syntax/Traversals.idr
- src/Idris/Syntax/Views.idr
- tests/idris2/misc/import009/expected
- tests/idris2/misc/namespace005/expected
- tests/idris2/warning/warning004/expected
Only the FC changes from #3450
Fixes location tracking on errors involving operators.
> FC Changes from #3450

- libs/linear/System/Concurrency/Linear.idr
Run a computation concurrently to the current thread.
This returns a receiver for the value. A typical usage
pattern is showcased by the implementation of `par1`:
in a do block start executing a series of actions
concurrently and then collect the results with a series
receiving steps.
```idris
do recva <- concurrently1 ioa
recvb <- concurrently1 iob
a <- recva
b <- recvb
pure1 (a # b)
```
> [ linear ] fork1, concurrently1

- CHANGELOG_NEXT.md
- libs/base/Language/Reflection/TTImp.idr
PR #3423 introduces a new data structure which added several top-level declarations with names `rig`, `vis`, `opts` and `type` which leads a lot of existing code to warnings of shadowing these top-level names with local variables. These names are pretty popular, especially for parameter names in certain contexts (even precisely this module has already several parameters named in this way).
I believe that this was not the intended behaviour, to I suggest to declare `IClaimData` not as a `record`, like it's done with the type `Record` in the same module.
Pinging @andrevidela as the original PR author.
> [ re #3423 ] Make `IClaimData` to be a `data`, not `record`

- CHANGELOG_NEXT.md
- docs/source/tutorial/modules.rst
- src/Compiler/Scheme/Common.idr
- src/Core/Normalise/Eval.idr
- src/Idris/Parser.idr
> deprecate old parameter-block syntax

- nix/buildIdris.nix
This updates the existing `buildIdris` Nix function so that its outputs (both library and executable) support a `withSource` passthru attribute that can be used to get the given derivation and all of its dependencies built with sourcecode included after-the-fact. This means you don't need to decide up front -- a library can easily be built without source by default and then asked for its withSource variant specifically for a developer shell environment.
I've PRed similar changes to nixpkgs and I've been testing these changes in `nix-idris2-packages` for a while now.
> [ enhancement ] update `buildIdris` Nix function to support withSource retroactively

- libs/contrib/Control/Category.idr
Adding constructors to category interface
We should probably also move this outside contrib, maybe have other things that are categories to go along with it
> add a constructor to the Category interface

- libs/linear/System/Concurrency/Linear.idr
Just like concurrently1 but its output is not restricted so we actually have a safe implementation
> [ linear ] add concurrently

- src/Compiler/Scheme/Chez.idr
check if a linux implementation uses glibc to decide whether to load "glibc.so.6" or "glibc.so"
> Support for non-glibc versions of linux (musl, android)

- libs/papers/Language/IntrinsicTyping/Krivine.idr
- src/Core/Coverage.idr
- src/TTImp/ProcessDef.idr
- tests/idris2/coverage/coverage022/Issue3477.idr
- tests/idris2/coverage/coverage022/expected
- tests/idris2/coverage/coverage022/run
This fixes #3477.  Idris considers `2 = length xs` as empty while checking missing cases in coverage checking, and it incorrectly accepts this as covering:
```idris
test : (xs : List Int) ->  2 = length xs -> (Int, Int)
test (x1 :: x2 :: x3 :: []) pf = (x1, x2)
```
There are two changes here:
I removed the `clearDefs` in `conflictNF` to allow the `length xs` to expand when `xs` is known.  _Let me know if there is a reason we don't allow expansions here._ It passes tests and it seems to be necessary to enable Idris to automatically use the `2 = length xs`. 
Without this change, the following `impossible` clauses are required:
```idris
test : (xs : List Int) ->  2 = length xs -> (Int, Int)
test (x1 :: x2 :: []) pf = (x1, x2)
test (x1 :: Nil) Refl impossible
test (x1 :: x2 :: x3 :: _) Refl …
```
> [ fix ] False positives checking for conflicts in coverage checking

- src/Core/Binary.idr
- src/Core/Case/Util.idr
- src/Core/Context.idr
- src/Core/Context/Context.idr
- src/Core/Context/Data.idr
- src/Core/Context/Pretty.idr
- src/Core/Coverage.idr
- src/Core/TTC.idr
- src/Core/Termination/Positivity.idr
- src/Idris/Doc/String.idr
- src/TTImp/Elab/App.idr
- src/TTImp/Elab/Record.idr
- src/TTImp/Elab/RunElab.idr
- src/TTImp/Interactive/CaseSplit.idr
- src/TTImp/Interactive/ExprSearch.idr
- src/TTImp/Interactive/Intro.idr
- src/TTImp/ProcessBuiltin.idr
- src/TTImp/ProcessData.idr
- src/TTImp/ProcessRecord.idr
- tests/idris2/data/data003/Issue3457.idr
- tests/idris2/data/data003/OopsDef.idr
- tests/idris2/data/data003/OopsRef.idr
- tests/idris2/data/data003/Positivity.idr
- tests/idris2/data/data003/Test.idr
- tests/idris2/data/data003/Test2.idr
- tests/idris2/data/data003/expected
- tests/idris2/data/data003/run
This addresses two issues related to confusing empty `data` declarations with forward `data` declarations.  
The following is accepted by Idris and I believe it should be rejected with an error that `Bar` is already defined.
```idris
data Bar : Type where
data Bar : Type where
MkBar : Bar
```
The second issue is that this forward declaration is allowed to be used in an impossible clause and later is defined to not be empty:
```idris
data Bar : Type
total
foo : Bar -> a
foo x impossible
data Bar : Type where
MkBar : Bar
```
Since forward declarations and empty data appear to be indistinguishable in the data, I added a type flag for `forwardDecl`.  There is an existing flag `external` that is used in similar cases. This affects serialization, so I updated the TTC version.
The test for …
> Empty data declarations are confused with forward data declarations

- libs/base/Language/Reflection/TTImp.idr
- src/Core/Binary.idr
- src/Core/Context.idr
- src/Idris/Elab/Interface.idr
- src/Idris/Parser.idr
- src/Idris/Syntax.idr
- src/TTImp/Parser.idr
- src/TTImp/TTImp.idr
- tests/base/deriving_functor/DeriveFunctor.idr
- tests/base/deriving_functor/expected
- tests/base/deriving_show/DeriveShow.idr
- tests/base/deriving_traversable/expected
- tests/idris2/data/data004/EmptySearch.idr
- tests/idris2/data/data004/expected
- tests/idris2/data/data004/run
- tests/idris2/data/record022/EmptySearch.idr
- tests/idris2/data/record022/expected
- tests/idris2/data/record022/run
- tests/idris2/interface/interface034/Main.idr
- tests/idris2/interface/interface034/expected
- tests/idris2/interface/interface034/run
- tests/idris2/reflection/reflection003/expected
- tests/idris2/reflection/reflection032/DeterminingData.idr
- tests/idris2/reflection/reflection032/DeterminingRecord.idr
- tests/idris2/reflection/reflection032/expected
- tests/idris2/reflection/reflection032/run
The determining parameters are stored in `List`, but an empty list is never used. I suggest reflecting this in the signature with `List1`.
Also, the parser allows an empty list of determining parameters in interfaces, which is simply ignored during elaboration. I suggest making this a parser error:
```idris
interface Iface | where
```
> [ refactor ] Use `List1` for determining parameters

- tests/chez/channels008/Main.idr
This PR bumps the timeout for the new `channelGetWithTimeout` function from `5000` to `15000`  in the `channels008` test.
This should help `channels008` pass consistently as it occasionally fails when this test is run non-locally via the merge pipelines/jobs.
> [ fix ] Increasing timeout for channelGetWithTimeout test

- CHANGELOG_NEXT.md
- CONTRIBUTORS
- docs/source/reference/literate.rst
- src/Parser/Unlit.idr
- tests/idris2/literate/literate020/IEdit.dj
- tests/idris2/literate/literate020/expected
- tests/idris2/literate/literate020/input
- tests/idris2/literate/literate020/run
[Djot](https://djot.net/) is a markup format that is derived from CommonMark, it's code block syntax is identical to CommonMark's, so we can support it as a CommonMark style literate formate by just adding the file extension.
> [new] Support literate Djot files

- CHANGELOG_NEXT.md
- libs/network/Control/Linear/Network.idr
I reckon `newSocket` is unnecessarily restrictive. I was unable to use it to create a pair (`LPair`) of sockets, as the closures that produce them aren't themselves linear. To make them linear, I merged them and used `LEither`.
> Use single, linear callback in `newSocket`

- src/TTImp/Unelab.idr
- tests/idris2/data/record021/Issue3501.idr
- tests/idris2/data/record021/expected
- tests/idris2/data/record021/run
- tests/idris2/reflection/reflection033/QuotingShadowed.idr
- tests/idris2/reflection/reflection033/expected
- tests/idris2/reflection/reflection033/run
Fixes an issue brought up in #3501.  The change in #3468 causes a regression in record elaboration where the outer name is used when shadowing.  The following fails to compile:
```idris
import Data.Vect
record Foo (th : Vect n a) where
nIsZero     : n === 0
vectIsEmpty : (th ===)
$ replace {p = \ n => Vect n a} (sym nIsZero)
$ Nil
```
If the `n` in the lambda is replaced by `z`, it succeeds.
The root cause is that record elaboration is calling unelaboration with `NoSugar True`, which tries to make the names unique. It changes `n` to `{n:0}`, but neglects to update the instances of `n` under the binder. This is the same issue as #2084 filed by @buzden.
I was initially going to address this by switching to `NoSugar False`, but I figured I would fix #2084 instead and make unelaboration work …
> [ fix ] fix shadowing issue in record elaboration and reflection

- src/Compiler/Scheme/Chez.idr
- src/Core/Context/Log.idr
- src/Core/Normalise.idr
- src/Core/Options/Log.idr
- src/Core/UnifyState.idr
- src/TTImp/TTImp.idr
1. Added `LogTopic` type to avoid passing `KnownTopic` separately
2. `KnownTopic` made data to improve error output.
Before: `Can't find an implementation for IsJust Nothing`.
After: `Can't find an implementation for KnownTopic "invalid.topic"`.
> [ refactor ] Refactoring types for log topic validation

- .github/workflows/ci-idris2-and-libs.yml
We're having some CI runs freezing up during tests and being killed after five hours. This has occurred a few times in `macos-self-host-chez` and in `windows-bootstrap-chez`.  I don't have a root cause, but suspect a bug in chez or possibly the test runner is causing a deadlock. I see that there is some history of deadlocks on these platforms in the chez bug tracker.
As a workaround, I've added a 45 minute timeout to the jobs that run tests. The typically run in about half that time.  They will still fail when there is a deadlock, but will fail in 45 minutes instead of 5 hours.
> [ ci ] add 45 minute timeout to jobs running tests

- CHANGELOG_NEXT.md
- libs/base/System/Concurrency.idr
- support/chez/support.ss
- tests/chez/chez038/ThreadId.idr
- tests/chez/chez038/expected
- tests/chez/chez038/run
This PR adds the `getThreadId` function to `System.Concurrency` (chez backend).
> [ base ] Add getThreadId

- CHANGELOG_NEXT.md
- libs/base/Language/Reflection.idr
- src/Idris/Pretty/Render.idr
- src/TTImp/Elab/RunElab.idr
- tests/idris2/reflection/reflection034/ResugarTerm.idr
- tests/idris2/reflection/reflection034/expected
- tests/idris2/reflection/reflection034/run
I suggest to make elaborator scripts to be able to access existing resugaring+pretty-printing mechanism
> [ elab ] Implement resugaring primitive for elaborator scripts

- .gitignore
- CHANGELOG_NEXT.md
- libs/linear/Data/Linear/Notation.idr
It seems only natural for `unrestricted` to be linear in  `(!*)` .
> Make `unrestricted` linear in the `(!*)`

- .github/workflows/ci-idris2-and-libs.yml
PR #3504 missed the `nix-bootstrap-chez` that runs the tests
> [ ci ] Add 45 minute timeout to `nix-bootstrap-chez`

- libs/base/Data/Either.idr
I forgot to export these when I added them
No need - it's already in CHANGELOG_NEXT from before
> Export `fromRight` and `fromLeft`

- support/refc/_datatypes.h
- support/refc/runtime.c
The `runtime.c` file in the refc backend calls closure functions without a prototype.  clang warns that this is deprecated, and newer version of GCC (implementing the C23 standard) fail to work with the RefC backend (see #3538).
The clang warning is:
```
runtime.c:17:16: warning: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
17 |     return (*f)(xs);
|          
```
and gcc 15 says:
```
runtime.c: In function ‘idris2_dispatch_closure’:
runtime.c:17:13: error: too many arguments to function ‘(Value * (*)(void))f’; expected 0, have 1
17 |     return (*f)(xs);
|            ~^~~ ~~
```
This PR adds a declaration of appropriate arity to each switch branch.
> [ fix ] Declare function types in idris2_dispatch_closure fixes #3538

- CHANGELOG_NEXT.md
- libs/network/Control/Linear/Network.idr
It's currently not possible to use a value produced by a socket, outside of `newSocket`. This fixes that.
I think I've got the linearity right - `L io` implies we can't return the `Socket` itself.
> Allow `newSocket` to produce a value

- CHANGELOG_NEXT.md
- libs/contrib/Data/Validated.idr
While I was using ValidatedL, I was confused for a few minutes about why it wouldn't work with a List and why List1 was being pulled in. That is, until I looked at the definition of ValidatedL. Hopefully this saves others a bit of their future time.
> Change List to List1 in ValidatedL doc comment

- src/Compiler/Common.idr
- src/Core/Binary.idr
- src/Core/Binary/Prims.idr
- src/Core/Context/TTC.idr
- src/Core/Metadata.idr
- src/Core/TTC.idr
- src/Idris/Syntax/TTC.idr
- src/TTImp/TTImp/TTC.idr
In Yaffle, `Ref Bin Binary` is passed implicitly, reducing boilerplate slightly. I suggest adopting the same approach in Idris.
> [ refactor ] Make `Binary` argument auto in `TTC`

- CHANGELOG_NEXT.md
- CONTRIBUTORS
- support/refc/prim.c
- support/refc/prim.h
- tests/node/node004/.gitignore
- tests/node/node017/.gitignore
- tests/node/node018/.gitignore
- tests/refc/piTypecase001/Test.idr
- tests/refc/piTypecase001/expected
- tests/refc/piTypecase001/run
This pull request introduces changes to fix support for Pi type constructors in the RefC runtime and includes updates to tests and supporting files. The most notable changes include defining a constant string for Pi type representation, adding test cases to verify this functionality, and updating `.gitignore` files for some of the Node backend tests.
* Added a constant string `idris2_constr____gt` (`"->"`) in the RefC support library to represent Pi type constructors. This ensures that code involving Pi types can now compile successfully. (`support/refc/prim.c`, `support/refc/prim.h`) [[1]](diffhunk://#diff-2423aedfcc69b49c9088332a7302217f6bee57d5708269249a8134ec1563f9f0R236) [[2]](diffhunk://#diff-e31bd75810a67651c461e5fc744c3c4e3bfeeb4992552308f445f427ebb7af2bR68)
* Documented the …
> Get pattern matching on pi types to compile with refc

- CHANGELOG_NEXT.md
- src/Core/Normalise/Convert.idr
- src/Core/Unify.idr
- src/TTImp/ProcessData.idr
- tests/idris2/basic/basic073/DefaultHole.idr
- tests/idris2/basic/basic073/expected
- tests/idris2/basic/basic073/run
- tests/idris2/data/data006/ConvertPiInfo.idr
- tests/idris2/data/data006/expected
- tests/idris2/data/data006/run
- tests/idris2/error/error033/Examples.idr
- tests/idris2/error/error033/UnifyPiInfo.idr
- tests/idris2/error/error033/expected
- tests/idris2/error/error033/run
Now `convert` and `unify` do not compare `PiInfo`. As a result, the following code compiles successfully:
```idris
data X : Type -> Type
data X : Type => Type where
```
```idris
plus : Int -> {n : Int} -> Int
plus = (+)
```
This PR adds `PiInfo` processing to both functions. Also, due to unification, it allows resolve metavariables in default values (see [DefaultHole.idr](https://github.com/idris-lang/Idris2/pull/3541/files#diff-77829a94397b1b4f0ba98e4da1584596dc448465f9873fdde00fef1dc43b4401)). 
In additional to this, I changed `AlreadyDefined` to `CantConvert` when data is declared and defined with different types.
> [ fix ] Process `PiInfo` in `convert` and `unify`

- CHANGELOG_NEXT.md
- libs/base/Data/Zippable.idr
> [ base ] Add default definitions for `zipWith3` and `unzipWith3`

- src/Core/WithData.idr
- src/Libraries/Data/Record.idr
- src/Libraries/Data/WithData.idr
This is the first step towards #3570 it adds three modules:
- `Libraries.Data.Record` a generic labelled record with runtime nat-indexing for performance
- `Libraries.Data.WithData` A datastructure to attach metadata to a type by means of a record
- `Core.WithData` A series of helpers for existing known metadata that the compiler already uses
This design addresses the goals set out by #3570 by allowing us to refactor a number of existing records into either `Record` or `WithData`. This refactoring, in turn, allows us to make changes to the metadata without changing the fundamental structure of the surrounding program, since most tree operations are metadata agnostic. 
Once we add the Reify and Reflect instances for those types, they will also remove the need to write bespoke versions for …
> Add `WithData` to generalise over `WithName` and `WithFC`

- docs/source/tutorial/typesfuns.rst
The example data constructors `SOddIsEven` and `SEvenIsOdd` had the wrong `Nat` identifier in the output type. Since this didn't match the identifier in the input type, there wasn't actually any relationship between the two. Changing `k` to `n` here makes sure that we can only construct `Even n` when `n` is even, and likewise for `Odd n`.
> Typo in typesfuns.rst

- .github/workflows/ci-idris2-and-libs.yml
- idris2api.ipkg
- src/Core/Binary.idr
- src/Core/Context.idr
- src/Core/Core.idr
- src/Core/FC.idr
- src/Core/Reflect.idr
- src/Core/TTC.idr
- src/Idris/Desugar.idr
- src/Idris/Desugar/Mutual.idr
- src/Idris/Elab/Interface.idr
- src/Idris/Parser.idr
- src/Idris/Pretty.idr
- src/Idris/ProcessIdr.idr
- src/Idris/Resugar.idr
- src/Idris/Syntax.idr
- src/Idris/Syntax/Traversals.idr
- src/Libraries/Data/WithData.idr
- src/TTImp/Elab/Local.idr
- src/TTImp/Elab/Quote.idr
- src/TTImp/Parser.idr
- src/TTImp/ProcessDecls.idr
- src/TTImp/TTImp.idr
- src/TTImp/TTImp/Functor.idr
- src/TTImp/TTImp/Traversals.idr
- src/TTImp/Utils.idr
This change is part of #3570 
The goal is to gradually replace all constructor that tie meta-data to nodes with uses of `WithData` such that one can easily add metadata without changing the trees
> Replace WithFC by alias for WithData

- Release/CHECKLIST
Now that the website can be managed by the community, the release process can finally be completed. For that, please see:
idris-lang/idris-lang.github.io#11
Fixes #3173
There remains an open question as to what to do with the documentation. My understanding is that this is currently built (automatically?) via the `www` directory? In any case, the penultimate `CHECKLIST` point likely needs updating now that the community can manage the website. I'll open an issue to track this tomorrow.
implementation, I have updated [`CHANGELOG_NEXT.md`](https://github.com/idris-lang/Idris2/blob/main/CHANGELOG_NEXT.md)~~ N/A (Not Applicable)
> [ admin ] Finish releasing 0.7.0, clear the release checklist

- src/Compiler/Opts/CSE.idr
The first commit cleans up the code by introducing a generic type
for the transformation, replacing `pre` by its size, and using the
more efficient `locateIsVar` function.
The second commit fixes a bug identified during the cleanup.
> [ fix ] the dropConAlt case was dropping the protected inner

- .github/workflows/ci-idris2-and-libs.yml
- idris2api.ipkg
- src/Compiler/CompileExpr.idr
- src/Compiler/LambdaLift.idr
- src/Compiler/Opts/ConstantFold.idr
- src/Compiler/Opts/Identity.idr
- src/Core/Env.idr
- src/Core/LinearCheck.idr
- src/Core/Normalise/Convert.idr
- src/Core/Normalise/Quote.idr
- src/Core/SchemeEval/Quote.idr
- src/Core/TT/Var.idr
- src/Core/Unify.idr
- src/Libraries/Data/NatSet.idr
- src/Libraries/Data/VarSet.idr
- src/Libraries/Data/VarSet/Core.idr
- src/TTImp/Elab/App.idr
- src/TTImp/Elab/Case.idr
- src/TTImp/Elab/Check.idr
- src/TTImp/Elab/ImplicitBind.idr
- src/TTImp/Elab/Utils.idr
- src/TTImp/PartialEval.idr
- src/TTImp/Unelab.idr
We may as well define the well-scoped structure.
Note that it's all unsafe and so we have some (useless) checks
in `toList` when extracting the list. But then again there should
almost never be any use case for extracting a list.
I have also made a couple of quadratic functions linear and
removed redundant code.
> [ re #3603 ] Actually bother introducing VarSet

- src/Core/Core.idr
- src/Core/Reflect.idr
- src/Core/TT/Binder.idr
- src/Core/TTC.idr
- src/Core/WithData.idr
- src/Idris/Desugar.idr
- src/Idris/Desugar/Mutual.idr
- src/Idris/Elab/Implementation.idr
- src/Idris/Parser.idr
- src/Idris/Resugar.idr
- src/Idris/Syntax.idr
- src/Idris/Syntax/Traversals.idr
- src/Libraries/Data/WithData.idr
- src/TTImp/Elab/Local.idr
- src/TTImp/Elab/Quote.idr
- src/TTImp/Parser.idr
- src/TTImp/ProcessParams.idr
- src/TTImp/ProcessRecord.idr
- src/TTImp/Reflect.idr
- src/TTImp/TTImp.idr
- src/TTImp/TTImp/Functor.idr
- src/TTImp/TTImp/TTC.idr
- src/TTImp/TTImp/Traversals.idr
- src/TTImp/Utils.idr
This addresses a number of points from #3570 and #3409 namely:
- track location of names in binder with multiple names #3409
- Replace ImpParameter by its own data type using WithData #3570
- replace WithName by WithData #3570
- unify binder datatypes between syntax and TTImp via `PiBindData` (overdue)
We are starting to enjoy the benefits of `WithData` since we can now remove redundant TTC instances and have them properly behave using the default `WithData` instance. There is still some work to do around Reflect/reify instance but that should be resolved once we don't need to maintain backward compatibility with elab reflection.
> Unify binder data types using WithData

- src/Core/Binary.idr
- src/Core/WithData.idr
- src/Idris/Desugar.idr
- src/Idris/Doc/String.idr
- src/Idris/Elab/Implementation.idr
- src/Idris/Elab/Interface.idr
- src/Idris/Parser.idr
- src/Idris/Resugar.idr
- src/Idris/Syntax.idr
- src/Idris/Syntax/TTC.idr
Prerequisite for #3615
- replace `Method`
- harmonise and merge `Signature` and `Declaration`
- replace `(String, Name)` by `WithData [Doc', FC'] Name`
> Method refactor

- flake.lock
- flake.nix
- nix/support.nix
This addressed deprecation warnings and then later errors coming from Nixpkgs owing to use of an old helper that is no longer needed.
and I've updated [`CONTRIBUTORS.md`](https://github.com/idris-lang/Idris2/blob/main/CONTRIBUTORS.md) with my name.
implementation, I have updated [`CHANGELOG_NEXT.md`](https://github.com/idris-lang/Idris2/blob/main/CHANGELOG_NEXT.md)
> remove now-unneeded and no longer supported overrideSDK calls from Nix files

- CITATION.cff
GitHuB supports the
[CFF](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) format for displaying how the software *should* be cited.
Let us add a note on how Idris2 should be cited.
We add a preference for the Idris2 paper as the preferred citation
GitHub also [supports pointing to a BibTex
file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#other-citation-files).
> [ feature ] Add `CITATION.cff`

- docs/source/reference/operators.rst
- src/Idris/Error.idr
- src/Idris/Parser.idr
- src/Idris/Pretty.idr
- tests/idris2/operators/operators001/Test.idr
- tests/idris2/operators/operators002/Errors.idr
- tests/idris2/operators/operators002/Errors5.idr
- tests/idris2/operators/operators002/LinImport.idr
- tests/idris2/operators/operators002/expected
- tests/idris2/operators/operators005/Test.idr
- tests/idris2/operators/operators006/Test.idr
- tests/idris2/operators/operators007/Test.idr
- tests/idris2/operators/operators007/Test2.idr
- tests/idris2/operators/operators007/expected
fine print of #3582 
implementation, I have updated [`CHANGELOG_NEXT.md`](https://github.com/idris-lang/Idris2/blob/main/CHANGELOG_NEXT.md)
(There is actually no changelog changes to make since there has not been a release since the previous implementation of binding operators)
> replace binding symbol for autobind

- nix/text-editor.nix
This addresses the following error when building emacs tooling via Nix:
```
error: 'emacsWithPackages' has been renamed to/replaced by 'emacs.pkgs.withPackages'
```
and I've updated [`CONTRIBUTORS.md`](https://github.com/idris-lang/Idris2/blob/main/CONTRIBUTORS.md) with my name.
implementation, I have updated [`CHANGELOG_NEXT.md`](https://github.com/idris-lang/Idris2/blob/main/CHANGELOG_NEXT.md)
> [ fix ] address an exception in building emacs related packages for Idris2 via Nix
