idris-lang/Idris2

- libs/network/Makefile
- support/c/Makefile
- support/c/idris_support.c
- support/c/windows/win_utils.c
- support/c/windows/win_utils.h
There's some nonsense when trying to install it yet. But this as far as I got during lunch, the bootstrap works and the libraries build at least.
> Windows fixes

- .gitignore
- libs/network/test.c
> Make network test build on windows

- tests/Main.idr
- tests/chez/chez016/run
> Fix chez016 test

- src/Idris/IDEMode/Parser.idr
- src/Parser/Support.idr
- src/Utils/Either.idr
This corresponds with edwinb/Idris2#387
> Create new mapError utility function and refactor some parser code

- libs/base/Data/Maybe.idr
- fromJust : (v : Maybe a) -> IsJust v => a
> Add a total version of the fromMaybe

- idris2.ipkg
- idris2api.ipkg
- idris2rkt.ipkg
- src/Idris/Desugar.idr
- src/Idris/IDEMode/CaseSplit.idr
- src/Idris/IDEMode/MakeClause.idr
- src/Idris/IDEMode/Parser.idr
- src/Idris/IDEMode/TokenLine.idr
- src/Idris/Package.idr
- src/Idris/Parser.idr
- src/Idris/REPL.idr
- src/Parser/Lexer/Common.idr
- src/Parser/Lexer/Source.idr
- src/Parser/Rule.idr
- src/Parser/Rule/Common.idr
- src/Parser/Rule/Source.idr
- src/Parser/Source.idr
- src/Parser/Support.idr
- src/TTImp/Interactive/GenerateDef.idr
- src/TTImp/Parser.idr
> Split Parser into Source(.idr) and Package (.ipkg) (Part 1)

- Makefile
- bootstrap-win.sh
- bootstrap/idris2-boot
- src/Compiler/Scheme/Chez.idr
- src/Core/Options.idr
- support/c/Makefile
- support/c/windows/win_hack.c
- tests/Main.idr
- tests/tests.ipkg
213 of 218 tests passes, which is pretty good for now.
This needs a new bootstrap image to run to the end. But one can just pick the one from `build/exec` on the first run and copy it to the bootstrap folder. So I don't add that noise to this commit.
> Windows support

- Makefile
- libs/contrib/System/Path.idr
- src/Compiler/Scheme/Chez.idr
- src/Core/Directory.idr
- tests/Main.idr
- tests/chez/chez014/Echo.idr
- tests/chez/chez017/expected.in
- tests/chez/chez017/gen_expected.sh
This makes all the tests pass on Windows.
There is one real oddity in the test runner that I will note in a comment.
> Fix windows tests

- src/Core/Context.idr
- src/TTImp/ProcessData.idr
- src/TTImp/ProcessDef.idr
- src/TTImp/ProcessType.idr
Fixes #101 but there's more left to address and it has no effect in practice yet. I'm marking this as a draft until it's done.
> Convert to full names before computing hashes

- libs/base/Data/Nat.idr
It's just a copy / paste from Idris 1 source code adding the "minus" proofs on Nats
> minus proofs on Nats from Idris1

- src/Compiler/Common.idr
- src/Compiler/CompileExpr.idr
- src/Core/CaseBuilder.idr
- src/Core/CaseTree.idr
- src/Core/Context.idr
- src/Core/Core.idr
- src/Core/Coverage.idr
- src/Core/Hash.idr
- src/Core/LinearCheck.idr
- src/Core/Normalise.idr
- src/Core/TTC.idr
- src/Core/Unify.idr
- src/Idris/Error.idr
- src/Idris/ModTree.idr
- src/Idris/REPL.idr
- src/Idris/REPLCommon.idr
- src/TTImp/Elab/Delayed.idr
- src/TTImp/ProcessDef.idr
- tests/Main.idr
- tests/idris2/coverage009/expected
- tests/idris2/coverage009/run
- tests/idris2/coverage009/unreachable.idr
Report a warning if detecting overlapping patterns, rather than a mysterious error in some cases. I don't know how complete this is, but it certainly catches some common things that are likely to be errors.
> Some improvements on case trees

- src/TTImp/ProcessDef.idr
This removes an annoying warning that I missed
> Remove unreachable case

- src/Utils/String.idr
Wasn't available when I made the #8 PR
> Use library version of substr

- src/Idris/ProcessIdr.idr
public imports need to change the present modules hash, but we were
updating before initialising the hash, so they never got included. Oops!
> Fix hash generation of public imports

- src/Core/Binary.idr
- src/Core/LinearCheck.idr
- src/Core/TTC.idr
- src/Idris/Elab/Implementation.idr
Related to linear errors and totality checking
> Various fixes

- libs/base/System/File.idr
- support/c/idris_file.c
- tests/Main.idr
- tests/chez/chez020/Popen.idr
- tests/chez/chez020/expected
- tests/chez/chez020/input
- tests/chez/chez020/run
Mostly copied from Idris 1. I have only tested it on Ubuntu though.
Is this the right place for the test case?
> Add popen and pclose from Idris 1

- libs/contrib/System/Path.idr
- src/Idris/ModTree.idr
- src/Utils/Path.idr
> Allow parsing multiple separators in Path

- libs/base/Control/App/Console.idr
Now all common console IO functions available from the
prelude are available through the `Control.App.Console`
interface.
Added:
- putChar
- getChar
- getCharLn
- print
- printLn
Renamed:
- getStr to getLine
> added more functions to Control.App.Console

- libs/base/Data/List.idr
- libs/contrib/Data/List/Equalities.idr
- libs/contrib/Data/List/Palindrome.idr
- libs/contrib/Data/List/Reverse.idr
- libs/contrib/Data/List/Views/Extra.idr
- libs/contrib/contrib.ipkg
- src/Idris/Main.idr
Added a few views and and proofs. In some cases, the code was borrowed from Idris1.
> some proofs and views around lists

- src/Compiler/Scheme/Gambit.idr
This resolves https://github.com/idris-lang/Idris2/issues/76
> Fix "Can't pass argument of type %World to foreign function" issue in gambit ffi

- libs/base/Language/Reflection.idr
- src/TTImp/Elab/RunElab.idr
- tests/Main.idr
- tests/idris2/reflection008/Interp.idr
- tests/idris2/reflection008/expected
- tests/idris2/reflection008/input
- tests/idris2/reflection008/run
This allows writing a staged well typed interpreter, for example (see
reflection008 test)
> Add reflection under (explicit) binders

- libs/base/Language/Reflection.idr
- src/TTImp/Elab/RunElab.idr
Also remove forall, since I haven't tested it and its type was wrong
anyway. It can go back when we have a use for it...
> Make lambda elaborator dependent

- docs/source/tutorial/packages.rst
- docs/source/updates/updates.rst
Just some of the differences I stumbled upon while trying to compile lightyear. There might be others!
> Update docs to reflect changes to ipkg format

- .github/workflows/ci-full-bootstrap.yml
This depends on https://github.com/edwinb/Idris2-boot/pull/393 and https://github.com/idris-lang/Idris2/pull/272 to work.
It will not run on every PR, just pushes to master
> Add a bootstrap from Idris 1 CI script

- libs/base/Data/Buffer.idr
- libs/base/System/File.idr
- src/Compiler/CompileExpr.idr
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/Racket.idr
- src/Core/Binary.idr
- src/Core/CompileExpr.idr
- src/Core/TTC.idr
- src/Utils/Binary.idr
- support/c/idris_buffer.c
- support/c/idris_buffer.h
- support/c/idris_directory.c
- support/chez/support.ss
- support/racket/support.rkt
Meaning that the FFI is aware of it, so you can send arbitrary byte data to foreign calls. Fixes #209
This means that we no longer need the hacky way of reading and writing binary data via scheme, so can have a more general interface for reading and writing buffer data in files.
It will also enable more interesting high level interfaces to binary data, with C calls being used where necessary.
Note that the Buffer primitive are unsafe! They always have been, of course... so perhaps (later) they should have 'unsafe' as part of their name and better high level safe interfaces on top.
This requires updating the scheme to support Buffer as an FFI primitive, but shouldn't affect Idris2-boot which loads buffers its own way.
> Make buffers more primitive

- tests/idris2/reflection003/expected
- tests/idris2/reflection003/refprims.idr
> Fix overly nitpicky reflection test

- libs/contrib/Debug/Buffer.idr
- libs/contrib/contrib.ipkg
I'm working on making network use buffers, while doing that I added this little lib to dump buffers to strings.
> Debug printing for buffers

- INSTALL.md
- Makefile
- bootstrap-rkt.sh
- bootstrap.sh
- bootstrap/idris2-boot
- bootstrap/idris2-rktboot
- config.mk
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/Racket.idr
- tests/chez/chez010/run
- tests/chez/chez013/run
- tests/chez/chez022/run
and probably for other *BSD operating systems with minor tweaks
> Add support for OpenBSD

- src/Compiler/Scheme/Chez.idr
Cut a little too much :-(
Should run the selfhosting part on the windows CI too.
> Fix windows script

- .gitignore
Add `.vscode` folder to `.gitignore`.
> Add VS Code settings to gitignore

- INSTALL.md
- docs/source/tutorial/starting.rst
This adds Homebrew installation instructions to `INSTALL.md` and Getting Started guide.
Closes #317
> Add Homebrew installation instructions

- docs/source/tutorial/modules.rst
> Updated documentation for export

- docs/source/tutorial/starting.rst
Forgot to add that extra colon... :shrug:
> Format Homebrew install code block

- CHANGELOG.md
- Makefile
- libs/contrib/Control/Linear/LIO.idr
- libs/contrib/contrib.ipkg
- src/Core/AutoSearch.idr
- tests/Main.idr
- tests/idris2/linear010/Door.idr
- tests/idris2/linear010/expected
- tests/idris2/linear010/run
An experimental library for wrapping computations in a type which describes the multiplicity of the return value of the computation. The goal is to, as generically as is reasonable, support programming with linear resources.
> Add Control.Linear.LIO

- Makefile
- libs/contrib/Control/Linear/LIO.idr
- libs/network/Control/Linear/Network.idr
- libs/network/network.ipkg
This is at least partly as a test for tracking linear state in types via LIO, but I think it's useful in its own right.
> Add linear network library

- src/Idris/REPL.idr
This fixes a thing that's been annoying me in the vim mode. It's usually something that's left to the editor, but we do all the work for the vim mode! (This is hard to test conveniently, sorry...)
> Add new clause at next blank line

- src/TTImp/Impossible.idr
- src/TTImp/ProcessDef.idr
- tests/Main.idr
- tests/idris2/reg027/expected
- tests/idris2/reg027/pwhere.idr
- tests/idris2/reg027/run
> Pay attention to nested names in coverage check

- libs/contrib/Data/List/Equalities.idr
A suggestion of additions to the `contrib`'s `Data.List.Equalities` module. Not only "cons" and "snoc" are injective but also `(zs ++)` and `(++ zs)` too. Also, connected _inequality_ is suggested.
> Injectivity and similar properties were added for lists'a append

- docs/source/tutorial/multiplicities.rst
I hit a roadblock trying to understand linear types, because I couldn't figure out what is meant to "use" a variable. I eventually think I figured it out, by reading "Linear types can change the world!", but it was not easy to do so. I think a better description of what "use" means would be very helpful for those unfamiliar with linear types, so I took a stab at it. Hope it helps.
> Describe what is meant by "use" in the context of linear types

- src/Core/Termination.idr
- src/TTImp/Elab/App.idr
- src/TTImp/Elab/Term.idr
- src/TTImp/WithClause.idr
- tests/Main.idr
- tests/idris2/reg030/A.idr
- tests/idris2/reg030/B.idr
- tests/idris2/reg030/C.idr
- tests/idris2/reg030/expected
- tests/idris2/reg030/run
- tests/idris2/reg031/dpair.idr
- tests/idris2/reg031/expected
- tests/idris2/reg031/run
- tests/idris2/total009/expected
- tests/idris2/total009/run
- tests/idris2/total009/tree.idr
Just working though a few small fixes.
> Resolving some issues

- libs/base/Data/Strings.idr
- libs/contrib/Data/String/Parser.idr
- libs/contrib/contrib.ipkg
- samples/StringParser.idr
- tests/Main.idr
- tests/chez/chez027/StringParser.idr
- tests/chez/chez027/expected
- tests/chez/chez027/input
- tests/chez/chez027/run
I plan to use for making parsers for URIs and HTTP headers and such things.
It doesn't have all that many combinators yet. I'll fill it out when I get around to making the parsers, if not sooner.
> Add a simple parser combinator library for strings

- libs/prelude/PrimIO.idr
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/Common.idr
- src/Compiler/Scheme/Gambit.idr
- src/Compiler/Scheme/Racket.idr
It's not used anymore and %foreign is preferred.
> Remove prim__cCall

- CHANGELOG.md
- idris2.ipkg
- idris2api.ipkg
- src/Core/Binary.idr
- src/Core/Context.idr
- src/Idris/Desugar.idr
- src/Idris/DocString.idr
- src/Idris/Elab/Interface.idr
- src/Idris/IDEMode/REPL.idr
- src/Idris/Parser.idr
- src/Idris/REPL.idr
- src/Idris/Resugar.idr
- src/Idris/Syntax.idr
- tests/Main.idr
- tests/idris2/docs001/expected
- tests/idris2/docs001/input
- tests/idris2/docs001/run
- tests/idris2/docs002/Doc.idr
- tests/idris2/docs002/expected
- tests/idris2/docs002/input
- tests/idris2/docs002/run
They're not especially pretty, but at least they exist now.
> Initial implementation of :doc and :browse

- .github/workflows/ci-full-bootstrap.yml
- src/Compiler/ES/Imperative.idr
Replace if-expression with a function
> Fix bootstrap

- docs/source/implementation/index.rst
- docs/source/implementation/overview.rst
- docs/source/index.rst
These were lying around in Idris2-boot, but it's better to put them somewhere people might find them
> Add some implementation notes to the docs

- docs/source/implementation/index.rst
- docs/source/implementation/overview.rst
Couple of mistakes and several formatting things were fixed.
> Recently added implementation docs were slightly fixed and nicened

- libs/base/Data/Vect.idr
The non-linear version might be easier to reason about 'in practice', since client code may already have proved
stuff about zipWith that they want to reuse
> Include a (non-linear) definition for transpose that uses zipWith

- libs/base/Data/Vect.idr
- libs/prelude/Builtin.idr
Some minor things to add that I have seen so far this past week.
> Some things to add.

- libs/base/Data/List.idr
- libs/base/Data/List/Elem.idr
- libs/base/Data/Vect.idr
- libs/base/Data/Vect/Elem.idr
- libs/base/System.idr
- libs/contrib/Data/List/TailRec.idr
- libs/network/Control/Linear/Network.idr
- libs/prelude/Prelude/Types.idr
- samples/FFI-readline/src/Text/Readline.idr
- src/Core/Binary.idr
- src/Core/CaseBuilder.idr
- src/Core/CompileExpr.idr
- src/Core/Coverage.idr
- src/Core/LinearCheck.idr
- src/Core/Termination.idr
- src/Core/Unify.idr
- src/Idris/Error.idr
- src/TTImp/Elab/Ambiguity.idr
- src/TTImp/Elab/App.idr
- src/TTImp/Elab/Utils.idr
- src/TTImp/Interactive/ExprSearch.idr
- src/TTImp/Utils.idr
- tests/idris2/basic019/expected
- tests/idris2/real002/StoreL.idr
No changes to behavior here, just a reduction in code.
> Minor simplifications

- src/Idris/IDEMode/Commands.idr
- src/Idris/IDEMode/REPL.idr
- src/Idris/Parser.idr
- src/Idris/REPL.idr
- src/Idris/Syntax.idr
- tests/idris2/interactive015/expected
- tests/idris2/interactive015/input
I forgot to update the IDE mode REPL. Also, added a counter to :gd which means the vim mode will be able to keep generating new definitions. I have that working, but the interface is terrible - I'll update idris2-vim once it's a bit less terrible.
> More search stuff

- src/TTImp/Elab/App.idr
Fixes #499 
When an erased pattern argument in a non-erased context is of a
datatype that has 0 or 1 constructors, there is no need to dot it
(i.e., require that the canonical term is inferred by other
dependencies): it has to be the unique constructor that appears in the
source.
> Take into account syntactic sub-singletons when dotting in patterns

- libs/base/Data/List.idr
- libs/base/Data/List/Elem.idr
- libs/base/Data/List/Quantifiers.idr
Some generic list lemmas that were useful in formalizing some explicit substitution & modal calcull.
> Add list lemmas

- libs/base/Data/List.idr
> Add irrelevance annotations to Data.List functions taking NonEmpty

- README.md
Also, rearrange videos in reverse chronological order to show the most recent videos first
> Add another recent video talk on Idris 2

- CHANGELOG.md
> Fix the code generator name for JavaScript CG

- INSTALL.md
This adds a section about installing from nix to INSTALL.md
> Add installation instructions for nix

- docs/source/backends/javascript.rst
It ain't much but it's honest work.
> javascript codegen minimal doc

- src/Core/Context.idr
- src/Core/Unify.idr
- src/TTImp/Interactive/ExprSearch.idr
- tests/Main.idr
- tests/idris2/interactive015/expected
- tests/idris2/interactive018/PlusPrf.idr
- tests/idris2/interactive018/expected
- tests/idris2/interactive018/input
- tests/idris2/interactive018/run
Just some small things - rejecting more invalid recursive calls, and a fix for a bug caused by a typo in unification.
> More search improvements

- docs/source/app/exceptionsstate.rst
- docs/source/app/interfaces.rst
- docs/source/app/introapp.rst
- docs/source/app/linear.rst
- libs/base/Control/App.idr
App renamed the Environment to a List of Errors. This updates the docs to not confuse readers.
> Update app docs

- src/Core/CompileExpr.idr
> Add implicit arity arg to NmOp

- libs/contrib/Syntax/PreorderReasoning.idr
- libs/prelude/Prelude/Basics.idr
following review by @gallais in PR#559.
> Insert linearity annotations for cong2 and move it to prelude

- libs/base/Control/Monad/Reader.idr
- libs/base/base.ipkg
This includes:
- ReaderT transformer
- Instances for Functor, Applicative, Monad, MonadTrans, HasIO,
Alternative
- asks helper function
- Reader alias
> Implement MonadReader and related types/instances

- libs/base/Control/Monad/Either.idr
- libs/base/base.ipkg
- libs/prelude/Prelude/Types.idr
add EitherT transformer
add Foldable/Traversable implementations for Either
Filling in the missing zoo as needed.
> add EitherT transformer

- CHANGELOG.md
- libs/contrib/Data/HVect.idr
- libs/contrib/contrib.ipkg
mostly copied from the HVect from idris1.
I had a hard time getting deleteAt and the Shows interface working. But I got help in the #idris channel on slack. Thanks to arnaud and ionathanch.
> implement HVect

- libs/contrib/Data/String/Parser.idr
Relaxed constraints, added `optionMap` and `succeeds` combinators.
> additional refactor of Data.String.Parser

- libs/contrib/contrib.ipkg
> Add missing `Data.Stream.Extra` module to contrib.ipkg

- libs/prelude/Prelude/Interfaces.idr
- src/Idris/Package.idr
quite useful to have for more complex libraries and types
> add semigroup/monoid instances for Unit/()

- src/Idris/Parser.idr
- tests/idris2/perf005/Lambda.idr
- tests/idris2/perf005/NoRegression.idr
- tests/idris2/perf005/expected
> Fix DPair parsing

- src/Core/Termination.idr
This will hopefully make debugging of the totality/termination checker that little bit easier, especially given #645.
I need someone to check the levels, as I think I have sett them to high...
> Added some logging information to the totality checker.

- libs/contrib/Data/Bool/Decidable.idr
- libs/contrib/contrib.ipkg
> [contrib] Add a `Reflects` datatype

- CONTRIBUTING.md
After all, Agda has one ;) https://github.com/jupyter/jupyter/wiki/Jupyter-kernels
> Suggest adding a Jupyter kernel for Idris

- libs/prelude/Prelude/Uninhabited.idr
- src/Compiler/ES/ES.idr
- src/Compiler/RefC/RefC.idr
- src/Compiler/Scheme/Common.idr
avoid the error below on the javascript codegen
Error: INTERNAL ERROR: prim not implemented: Prelude.Uninhabited.void
> prim void to js codegen

- src/Compiler/ANF.idr
Introduces parenthesis around parts of let expressions and closes
parenthesis for the case expression.
> Resolves #804

- docs/source/backends/javascript.rst
I summarized the basic tools I used in my JS experiment.
> [doc] JS FFI examples.

- src/Idris/Package.idr
I want to parse an ipkg file in some tooling I am working on
> export a function to parse ipkg files

- CONTRIBUTORS
- docs/source/updates/updates.rst
I have set up automatic deletion of trailing whitespace on my Vim, that's why you see quite a few changes in CONTRIBUTORS.
Hopefully, that's okay.
> [ doc ] new application syntax

- idris2api.ipkg
- src/Compiler/RefC/RefC.idr
- src/Core/Core.idr
- src/Data/DList.idr
I tried to make the commits semantic so that it is easy to revert part of this
without reverting everything.
The more contentious one is probably: 62bcc28adc1d89263c58c4e7edfdff35477cba0c
> Finally got around to having a look at RefC

- libs/base/Data/List1.idr
I've been needing this a lot lately so I thought I'd add it.
> Add Traversable to List1

- libs/prelude/Prelude/Interfaces.idr
Credit to @gallais and @michaelmesser in #868 .
> Adding default implementation of `Foldable.null`

- libs/contrib/System/Path.idr
- src/Core/Directory.idr
- src/Utils/Path.idr
* Rename `startWith` to `isBaseOf`
* Rename `stripPrefix` to `dropBase`
* Add `dropExtension`
* Add `splitPath`
* Improve document
> Refactor System.Path and Utils.Path

- libs/contrib/Data/List/Lazy.idr
Addes Eq, Ord, and Show implementations for LazyList based on the ones for List.
> Eq, Ord, and Show instances for LazyList

- libs/contrib/Data/String/Iterator.idr
- src/Compiler/ES/ES.idr
- support/chez/support.ss
- support/gambit/support.scm
- support/racket/support.rkt
The proposed function allows for more effective backend-dependent iterator-to-string conversions.
Pinging #894
> Add withIteratorString

- libs/base/Control/Monad/Maybe.idr
- libs/prelude/Prelude/Basics.idr
- tests/idris2/interactive019/expected
This was changed due to the recent multiplicity update.
> Update test output

- result
Introduced as:
```
7a7504c95 (Guilherme Silva 2021-01-15 14:20:52 -0300 1) /nix/store/nw0mm1z2afpxv5rgf6w3apxc8pxwgd6h-idris2-0.3.0
```
> Remove leaked result file

- Makefile
Trying to untangle idris2 bootstrap build, this will make it a
little simpler.
> Simpler idris2-boot.ss generation

- .editorconfig
> Specify tab size in .editorconfig

- libs/base/Decidable/Decidable.idr
Added several functions for `Dec`. The set of functions and names
are picked consistently with `Maybe`:
* `isNothing` -> `isNo`
* `isJust` -> `isYes`
* `IsJust` -> `IsYes`
* `isItJust` -> `isItYes`
This is follow-up to #942
> Add isYes function and friends

- libs/contrib/Data/String/Iterator.idr
A non-invasive way to revert to linear iterator signatures in `Data.String.Iterator`.
We need to do this because internally backends can freely mutate iterator representations.
> Revert back to linear iterators

- CONTRIBUTORS
- libs/base/Language/Reflection/TTImp.idr
> Fix `Language.Reflection` definition of `INamespace

- libs/base/Data/List.idr
- libs/base/Data/List1.idr
- libs/base/Data/Stream.idr
- libs/base/Data/Vect.idr
- libs/base/Data/Zippable.idr
- libs/base/base.ipkg
- src/Compiler/ES/TailRec.idr
Following the suggestion from #972
> [ new ] Zippable interface

- libs/contrib/Data/List/Lazy.idr
This is the weaker (and actually, the original) version of #867. Suggestion of addition of lazy `foldr` to the `Foldable` interface seems to be accepted not as enthusiastic as I anticipated, but I think we need at least to fix existing `LazyList` implementation.
The current implementation of `LazyList`'s functions `<*>` from `Applicative` and `>>=` from `Monad` are not lazy, thus resulting to too eager and costly computation when there are potentially big lazy lists being combined with `<*>` or `>>=`.
This PR fixes this and seems to not to add anything controversial, unlike the #867.
> Fix of laziness of applicative and monad operations of `LazyList`

- .github/workflows/ci-nix.yml
> Update Nix version in CI

- .github/workflows/ci-ubuntu-combined.yml
> [ ci ] Switch to nightly chez builds when testing API

- libs/contrib/contrib.ipkg
Seems like this got forgotten.
> Add Data.Int.Order to contrib.ipkg

- libs/contrib/Control/Category.idr
Thanks to Russoul for telling me to add `| cat`.
> Generalize Category

- src/Core/FC.idr
> Fix typo in FC.idr.

- CHANGELOG.md
As introduced in https://github.com/idris-lang/Idris2/commit/891b2d667ab9ef2f12aaaf372494ad680a494be5
> Document new :l behaviour

- libs/base/Data/Nat.idr
- libs/base/Data/So.idr
- src/Core/CaseBuilder.idr
- src/Core/Context.idr
- src/Core/Coverage.idr
- src/Core/Normalise.idr
- src/TTImp/Impossible.idr
- src/TTImp/ProcessDef.idr
- tests/Main.idr
- tests/idris2/coverage012/Issue899.idr
- tests/idris2/coverage012/expected
- tests/idris2/coverage012/run
- tests/idris2/reflection004/refdecl.idr
It currently seems to break reflection004. Let's see if it builds the compiler itself first.
> [ fix #899 ] Be careful when generating an impossible LHS

- docs/source/updates/updates.rst
- libs/prelude/Prelude.idr
https://github.com/idris-lang/Idris2/blob/master/libs/prelude/Prelude/Types.idr#L685
> [ typo ] Enum -> Range

- README.md
Some slight changes to README to add #978 and satisfy the actions linter.
> [ fix #978 ] Mention Editor Plugins in README

- libs/contrib/contrib.ipkg
Added the missing module path in contrib.ipkg.
> [ fix ] added Data.Elem.Extra to contrib.ipkg

- libs/base/Data/Colist.idr
This implements inBounds and InBounds for Colists (hopefully the correct approach to defining InBounds). Currently these exist only for Lists. I'm not sure if there is a better way to refer to 'current file' than Data.Colist .
> Colist Inbounds

- libs/base/Data/Vect.idr
Making `range` linear instead of quadratic.
> [ refactor ] more efficient implementation of range

- src/Compiler/RefC/RefC.idr
- support/refc/mathFunctions.c
- support/refc/mathFunctions.h
* fix doublequoting in constArray
* substitute tildes in names
* Add negate functions
* Add string comparisons
Several things remain, notably missing _argList functions.
> Fixes from trying to compile idris with the refc backend

- docs/source/backends/backend-cookbook.rst
- docs/source/backends/index.rst
During the preparation of my Bob2021 talk I wrote this document. It summarizes the thing I encountered with during the design/experiment/implementation of the STG backend. I hope this information could be useful for the community.
I encourage everyone to suggest improvements or just add extra commits to this PR as English is not my native language and I suspect there are many grammatical mistakes or possible Hunglish can be found in the text.
@edwinb I mentioned your SPLV20 talk at the beginning of the doc. I hope it's not a problem, I am also happy to remove that part if needed.
> [ doc ] Custom backend cookbook

- docs/source/updates/updates.rst
It is now possible to write your own code generation.
I copied this from [here](https://idris2.readthedocs.io/en/latest/faq/faq.html#can-idris-2-generate-javascript-what-about-plug-in-code-generators)
> Update section on custom code gens in updates.rst

- libs/base/System.idr
- support/chez/support.ss
- support/gambit/support.scm
- support/racket/support.rkt
This spares us from having to build Idris data structures in the foreign
code.
> Replace prim__getArgs with prim__getArgsCount and prim__getArg

- src/Idris/Parser.idr
While digging into nuances of parser around interface parameters, I found that something in the code could be expressed more elegantly, which I suppose to do. No suggested changes are meant to change the behaviour.
> [ refactoring ] Some equivalent changes, mostly code styling nicened

- .github/workflows/ci-windows.yml
- libs/base/System/Directory.idr
- libs/base/System/File.idr
- libs/test/Test/Golden.idr
- src/Compiler/ES/Node.idr
- support/js/support_system_directory.js
- support/js/support_system_file.js
- tests/chez/chez016/run
> add tests to Windows CI

- libs/contrib/System/Directory/Tree.idr
I was writing up a little something about `System.Directory.Tree` and came up with these
while trying to think of good examples.
> [ new ] depthFirst, findFile

- INSTALL.md
- config.mk
- docs/source/backends/custom.rst
Improve documentation around installation / self-hosting.
> [doc] Minor tweaks to installation instructions

- libs/base/Data/Primitives/Views.idr
This way it is similar to the `S n` view of natural numbers
> [base] Minor: change the order of terms in the IntegerView

- README.md
- src/Core/Name.idr
- src/Idris/Pretty.idr
- src/Idris/Syntax.idr
- src/Parser/Lexer/Source.idr
- tests/Main.idr
- tests/idris2/pretty001/Issue1328A.idr
- tests/idris2/pretty001/expected
- tests/idris2/pretty001/input
- tests/idris2/pretty001/run
> [ fix #1328 ] print infix functions enclosed in grave accents

- src/Idris/Pretty/Render.idr
emacs sets the TERM variable to "dumb" and expects not to have to
handle any ANSI escape codes as a consequence. We need to patch the
renderer to unannotate the Doc in this situation.
> [ fix ] emacs' terminal is "dumb"

- libs/base/Data/Fin.idr
- libs/contrib/Data/Fin/Extra.idr
Some zeroes in signatures, one simpler implementation and formatting.
> [ refactoring ] Tiny changes following up the idris-lang/Idris2#830

- libs/contrib/Control/Arrow.idr
I am confused with the `make test` results though...
> [ contrib ] Add `liftA2`.

- src/Core/Unify.idr
- tests/Main.idr
- tests/idris2/basic016/expected
- tests/idris2/eta001/Issue1370.idr
- tests/idris2/eta001/expected
- tests/idris2/eta001/run
- tests/ttimp/eta002/expected
Not sure why we were not doing this from the very beginning so pinging @edwinb for a review.
> [ fix #1370 ] use the lambda's type for eta-expansion

- libs/base/Data/List.idr
- src/Compiler/ES/ES.idr
- src/Compiler/ES/Imperative.idr
- src/Compiler/ES/ImperativeAst.idr
- src/Compiler/ES/Javascript.idr
- src/Compiler/ES/Node.idr
- src/Compiler/ES/RemoveUnused.idr
- src/Compiler/ES/TailRec.idr
- src/Libraries/Data/List/Extra.idr
- src/Libraries/Data/SortedSet.idr
As part of #1416, I went through the JS backend code, cleaned it up where possible and added a lot of annotations and docstrings. Some of them are rather detailed, but I would have found this kind of code documentation helpful when trying to understand the details of the JS backend implementation.
> [ cleanup ] Annotate JS backend sources

- CHANGELOG.md
I went through my PRs since the last Idris2 release and updated the changelog accordingly.
> [ doc ] Updated changelog

- libs/contrib/System/Path.idr
- src/Compiler/Common.idr
- src/Core/Binary.idr
- src/Core/CaseTree.idr
- src/Core/Context.idr
- src/Core/TT.idr
- src/Core/TTC.idr
- src/Core/Unify.idr
- src/Idris/Main.idr
- src/Libraries/Utils/Path.idr
- tests/idris2/basic044/expected
Fix one situation where ttcs were reloaded unnecessarily, and do a bit more metavariable inlining so there's fewer definitions we need to save out. Overall this took about 8s off building Idris, for me.
> Some TTC loading improvements

- .github/workflows/ci-lint.yml
- .github/workflows/ci-macos-combined.yml
- .github/workflows/ci-ubuntu-combined.yml
- .github/workflows/ci-windows.yml
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Remove unsecure commands

- src/Core/Binary.idr
- src/Libraries/Utils/Binary.idr
- tests/idris2/import001/expected
This is a fix for https://github.com/idris-lang/Idris2/pull/1438#issuecomment-845276317
> [ fix ] Version encoding should be stable

- libs/contrib/Data/Vect/Extra.idr
- libs/contrib/Data/Vect/Properties.idr
- libs/contrib/Data/Vect/Properties/Fin.idr
- libs/contrib/Data/Vect/Properties/Foldr.idr
- libs/contrib/Data/Vect/Properties/Map.idr
- libs/contrib/contrib.ipkg
A few more functions/lemmata from Frex
> [contrib] More properties of vectors

- libs/test/Test/Golden.idr
Put the dependency checks in the banner, e.g.:
```
------------------------------------------------------------------------
Base library
✓ Found Chez at /usr/bin/chezscheme9.5
✓ Found node at /usr/bin/node
------------------------------------------------------------------------
```
> [ test ] cosmetic improvements

- .github/workflows/ci-macos-combined.yml
- .github/workflows/ci-ubuntu-combined.yml
- Makefile
- src/Idris/ModTree.idr
- src/Idris/REPL/Common.idr
And turn it on in the CI. I'd have done it in the PR if it was not
so annoying to update.
> [ re #1466 ] Actually error out with `-Werror`

- src/Core/Normalise.idr
This is an approximate check of arguments - if we can find an argument
that differs at the head, there's no point in checking further. This can
be a significant shortcut when conversion checking two large terms that
only differ very slightly, as it saves checking big arguments
unnecessarily.
> Add a 'shortcut' to conversion check

- support/refc/runtime.c
- tests/refc/strings/TestStrings.idr
- tests/refc/strings/expected
Add support for pattern matching on the `Char` type in the RefC backend.
> Add RefC Char pattern matching support

- src/Core/CaseBuilder.idr
- src/Core/Coverage.idr
- src/Core/Normalise.idr
- src/Core/Unify.idr
- src/Core/UnifyState.idr
- src/Idris/Error.idr
- src/TTImp/Elab.idr
- src/TTImp/Elab/Ambiguity.idr
- src/TTImp/Elab/App.idr
- src/TTImp/Elab/Check.idr
- src/TTImp/Elab/Delayed.idr
- src/TTImp/Elab/ImplicitBind.idr
- src/TTImp/Elab/Term.idr
- src/TTImp/ProcessDef.idr
- tests/Main.idr
- tests/idris2/coverage003/expected
- tests/idris2/coverage004/expected
- tests/idris2/error018/expected
- tests/idris2/interactive002/expected
- tests/idris2/literate001/expected
- tests/idris2/literate012/expected
- tests/idris2/literate016/expected
- tests/idris2/real002/Control/App.idr
- tests/idris2/reg041/expected
- tests/idris2/reg041/run
- tests/idris2/reg041/tuple.idr
- tests/ttimp/coverage001/expected
- tests/ttimp/coverage002/expected
- tests/ttimp/eta001/expected
- tests/ttimp/eta002/expected
One to improve elaboration of `fromInteger` so we only fully normalise on the LHS.
Another to fix #1510 and properly check whether LHS patterns are polymorphic enough.
> A couple of fixes

- libs/test/Test/Golden.idr
- libs/test/test.ipkg
> Add color to tests

- libs/test/Test/Golden.idr
Add filenames to Golden Test missing file error reporting.
> Add filenames to Golden Test missing file error reporting

- .github/workflows/ci-ubuntu-combined.yml
- idris2api.ipkg
- libs/network/Network/FFI.idr
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/ChezSep.idr
- src/Compiler/Scheme/Gambit.idr
- src/Compiler/Scheme/Racket.idr
- src/Core/Core.idr
- src/Idris/CommandLine.idr
- src/Idris/Error.idr
- src/Idris/Version.idr
- src/Libraries/Data/Version.idr
- tests/chez/chez031/expected
This is a rebase + squashes of @Russoul and @abailly work to fix deadlocks.
Supersedes #1298
> Fix deadlocks [Rebased, Squashed]

- docs/source/tutorial/typesfuns.rst
> [docs] ind-ind ind-rec rec-rec in style of fwddecl

- libs/prelude/Prelude/Types.idr
- src/Compiler/CompileExpr.idr
- src/Idris/Package.idr
- tests/Main.idr
- tests/idris2/reg042/NatSpeedBug.idr
- tests/idris2/reg042/expected
- tests/idris2/reg042/nsb.ipkg
- tests/idris2/reg042/run
This should fix #1577, also I added a regression test speed check for optimizations. Let me know if it's in the wrong place.
> [ Fix #1577 ] Actually use natMinus hack

- libs/test/Test/Golden.idr
* Do not pass a codegen choice when the test pool specifies it does
not require a codegen to be specified.
* padding shouldn't be affected by ANSI escape codes
> [ fix ] Various Test.Golden fixes

- libs/base/Data/Stream.idr
- libs/prelude/Prelude/Types.idr
Fixes #1581
There is however a performance issue:
```
~/D/O/Idris2   fix-1581 $+…  time idris2 --check test.idr                                            Wed 23 Jun 2021 11:02:59 PM CDT
1/1: Building test (test.idr)
________________________________________________________
Executed in    8.45 secs    fish           external
usr time    8.32 secs    0.00 micros    8.32 secs
sys time    0.12 secs  335.00 micros    0.11 secs
```
> [ fix #1581 ] public export Range functions and implementations

- .github/workflows/ci-super-linter.yml
> Ignore @generated in super-linter

- CHANGELOG.md
- src/Compiler/Scheme/Chez.idr
- tests/Main.idr
- tests/chez/chez033/Main.idr
- tests/chez/chez033/Mod.idr
- tests/chez/chez033/expected
- tests/chez/chez033/input
- tests/chez/chez033/run
Otherwise it doesn't load the compiled modules and can't find the compiled definitions!
> Need --script for incrementally compiled apps

- libs/base/System/Signal.idr
- support/c/idris_signal.c
It is not safe to call `malloc` or `pthread_mutex_lock` from signal
handler.
CC @mattpolzin
> Make System.Signal async-signal-safe

- libs/base/System/FFI.idr
- libs/network/Network/FFI.idr
- libs/network/Network/Socket/Raw.idr
- support/c/idris_memory.c
- support/c/idris_memory.h
- support/c/idris_net.c
- support/c/idris_net.h
* Move `malloc`/`free` from `Network.FFI` to `System.FFI`
* Might be useful by other code
> Expose malloc and free from System.FFI

- Makefile
- support/chez/support.ss
- support/gambit/support.scm
- support/racket/support.rkt
- tests/Main.idr
- tests/chez/chez034/ThreadData.idr
- tests/chez/chez034/expected
- tests/chez/chez034/input
- tests/chez/chez034/run
This is an update of PR #540, thanks to @lodi
> fix arity for blodwen-set-thread-data

- src/Idris/Parser.idr
- src/Idris/Syntax.idr
- src/Parser/Lexer/Source.idr
- tests/idris2/reflection001/quote.idr
- tests/idris2/reflection003/refprims.idr
- tests/idris2/reflection004/refdecl.idr
- tests/idris2/reg033/DerivingEq.idr
- tests/idris2/reg033/test.idr
This is an update of @buzden's PR #916 fixing the conflicts
> Name quotes are suggested to use single brace instead of double

- libs/base/Data/IOArray.idr
- libs/contrib/Data/Linear/Array.idr
- tests/chez/chez012/array.idr
- tests/node/node012/array.idr
As suggested in #1677.
Crashing on out-of-bounds might be more practical, but we can
reconsider it later.
> Return Bool from IOArray.writeArray

- libs/base/Data/Buffer.idr
Also rename `loc` -> `offset`.
> Add parameter names to Buffer builtins parameter names

- libs/base/Control/App.idr
> Export throw and catch again in App

- docs/source/faq/faq.rst
I saw an unclosed bracket in the FAQ and while I was at it made some other tiny changes.
> Minor FAQ edits

- libs/contrib/Data/Nat/Factor.idr
A few proofs have been rewritten, a few unnecessary cases cut, and
lots of unnecessary "explicit implicits" have been cut. Probably these
implicits were required when the code was initially written, and
inference has improved since then.
> Simplify a few Factor proofs

- libs/base/System/Directory.idr
- support/c/idris_directory.c
- tests/Main.idr
- tests/base/system_directory/ReadDir.idr
- tests/base/system_directory/expected
- tests/base/system_directory/input
- tests/base/system_directory/run
This function is what users want 99.9% of time.
This in on top of #1732.
> System.Directory.listDir

- .github/workflows/ci-idris2.yml
A new environment seems to have solved our issue.
Cf. actions/virtual-environments#3774
> [ ci ] bring racket builds back

- support/chez/support.ss
- support/racket/support.rkt
We need these things in the next version so that the next-but-one version can have a scheme evaluator!
I'll probably release an intermediate version reasonably soon - current evidence playing around with the new evaluator is that there are a few places where it can massively improve performance. I'll also probably open a draft PR with it fairly soon, although it'll fail CI until the next release.
> More Scheme readback machinery

- docs/source/tutorial/windows.rst
Each pull request shows this problem even it's unrelated
> [ doc ] Hopefully fix the linting problem in the docs

- docs/source/backends/chez.rst
- docs/source/reference/builtins.rst
- docs/source/tutorial/starting.rst
> [ doc ] Remove trailing spaces from doc files

- libs/base/System.idr
- tests/base/system_time001/Time.idr
- tests/base/system_time001/expected
- tests/base/system_time001/input
- tests/base/system_time001/run
Add support for getting the unix timestamp from code compiled with any javascript backend.
> Add javascript support for getting system time as integer.

- src/Core/Metadata.idr
- src/Core/Name.idr
- src/Idris/Parser.idr
- src/TTImp/Elab/App.idr
- tests/ideMode/ideMode005/expected5
- tests/ideMode/ideMode005/expectedH
Companion PR to https://github.com/idris-community/idris2-mode/pull/6 using the `Postulate` decoration
for `Builtin.assert_` functions & other unsafe primitives.
> [ highlighting ] Builtin.assert_ functions using postulate face

- src/TTImp/ProcessDef.idr
- tests/Main.idr
- tests/idris2/coverage001/expected
- tests/idris2/coverage019/Issue1632.idr
- tests/idris2/coverage019/expected
- tests/idris2/coverage019/run
This solves the second problem reported in the issue, not the first one.
> [ re #1632 ] (->) does not unify with any of TCon/Type/PrimVal

- src/Idris/REPL.idr
- src/Idris/REPL/Common.idr
I haven't been able to test it on idris2-vim yet...
Edit: tested basic commands: it works
> Retain the --client mode behaviour (defect introduced in #1919)

- libs/base/Decidable/Equality.idr
This adds `DecEq` for the `IntX` and `BitsX` types. I just copy-pasted what was already there, which was quite verbose. I was not sure whether it is safe to factor out the common parts.
> [ new ] DecEq for Int types

- src/Core/Name.idr
- src/Core/Name/Namespace.idr
- src/Idris/REPL.idr
- src/TTImp/WithClause.idr
- tests/idris2/interactive021/expected
- tests/idris2/interactive026/expected
- tests/idris2/interactive027/expected
This works in conjunction with https://github.com/idris-community/idris2-mode/pull/8
> [ fix #1744 ] Compare names by root rather than UserName

- libs/base/Data/Fin.idr
- tests/idris2/basic042/expected
> [ re #2032 ] faster version of fromInteger

- src/Idris/Doc/Keywords.idr
Small fix of code example to let binding.
> [ doc ] fix example in doc letbinding

- libs/base/Language/Reflection.idr
- libs/base/Language/Reflection/TT.idr
- src/Core/Normalise.idr
- src/TTImp/Elab/App.idr
- src/TTImp/Elab/RunElab.idr
- tests/Main.idr
- tests/idris2/reflection012/expected
- tests/idris2/reflection012/input
- tests/idris2/reflection012/nameinfo.idr
- tests/idris2/reflection012/run
Currently this is only whether it's a function, or data or type constructor. I expect more may be useful/possible.
> Get information about names in reflection

- src/Compiler/ES/Javascript.idr
- src/Compiler/RefC/RefC.idr
- src/Compiler/Scheme/Chez.idr
- src/Compiler/Scheme/ChezSep.idr
- src/Compiler/Scheme/Gambit.idr
- src/Compiler/Scheme/Racket.idr
- src/Core/Metadata.idr
- src/Core/Options.idr
- src/Idris/CommandLine.idr
- src/Idris/Driver.idr
- src/Idris/Package.idr
- src/Idris/SetOptions.idr
This PR is a follow-up to #1142 as I couldn't reopen it.
> [refactor] Use multiline strings for better readability

- libs/contrib/Data/String/Parser.idr
- tests/chez/chez027/expected
This also updates the error message of some common combinators
> Show the line and column in diagnostic message in String.Parser

- libs/base/Data/List1.idr
I noticed that this wasn't implemented yet so figured I might as well add it.
> implement Data.List1.length

- Makefile
Signed-off-by: Maciej Barć <xgqt@riseup.net>
> Makefile: bootstrap - check for chez threading support

- tests/Main.idr
- tests/idris2/basic065/Issue215.idr
- tests/idris2/basic065/expected
- tests/idris2/basic065/run
I'm too wise to push straight to `main`, even for something this trivial.
> [ re #215 ] test case

- libs/base/Control/Relation.idr
- libs/base/Control/WellFounded.idr
- libs/base/Data/Fin/Order.idr
- libs/base/Data/Nat.idr
- libs/contrib/Data/Nat/Division.idr
- libs/contrib/Data/Nat/Exponentiation.idr
- libs/contrib/Data/Nat/Factor.idr
- libs/contrib/Data/Nat/Order/Properties.idr
- libs/contrib/Data/Nat/Order/Strict.idr
- libs/contrib/Data/Tree/Perfect.idr
- libs/contrib/Decidable/Order/Strict.idr
- libs/contrib/Syntax/PreorderReasoning/Generic.idr
This follows from https://github.com/idris-lang/Idris2/pull/2140.
I have no idea why it works, but it does!
> Cut relation implicit args

- libs/prelude/Prelude/Interfaces.idr
This is a tiny cleanup, but I thought it's worth it since it is a `prelude`
> [ cleanup ] Remove piece of dead code from `prelude`

- src/Compiler/Inline.idr
When we're inlining, since we only have the current module, we might
encounter names we don't have definitions for. In this case, we need to
leave the arity alone, since the module it originates from will have set
it correctly.
This is tricky to test in isolation, and ideally needs something in CI
for a full incremental build (which would have caught the problem!). I
don't have time right now, but let's at least see if this breaks
anything else for now.
> Fix for incremental builds

- src/Idris/Parser.idr
> [ fix ] highlighting 'as' & 'off' keywords

- src/Idris/Driver.idr
Spotted while reading some unrelated code.
> [ cleanup ] using whenJust in Driver

- CHANGELOG.md
- libs/base/Control/Function.idr
- libs/contrib/Data/Nat/Factor.idr
A few additions and changes related to the new `Injective` interface.
> Injective follow-up

- CHANGELOG.md
- docs/source/implementation/ide-protocol.rst
- idris2api.ipkg
- idris2protocols.ipkg.hide
- src/Idris/IDEMode/Parser.idr
- src/Protocol/SExp/Parser.idr
Include the changes in the CHANGELOG
> [ refactor ] More IDE protocol

- src/Compiler/ES/TailRec.idr
The tail recursion optimizer used in the JS backends generates n copies of the same optimized functions for n mutually tail recursive functions as discussed on [discord](https://discord.com/channels/827106007712661524/827109190266257409/926986207366361138). This fix makes sure each function is only generated once.
Thanks @dunhamsteve, for finding this and suggesting the fix.
> [ fix ] mutual tail recursion

- libs/base/System.idr
- support/js/support.js
- support/js/support_system.js
- tests/base/system_env/Test.idr
- tests/base/system_env/expected
- tests/base/system_env/run
- tests/base/system_system/expected
- tests/base/system_system/input
- tests/base/system_system/run
Specifically, `setEnv`, `unsetEnv`, and `system`.
> Add a few missing NodeJS FFI functions to `System`

- libs/prelude/Prelude/Show.idr
- tests/idris2/docs001/expected
Got missed somehow all this time :>
> [ base ] add Show for Ordering

- src/Idris/Parser.idr
- src/Idris/REPL.idr
fixes [2208](https://github.com/idris-lang/Idris2/issues/2208)
> [ fix #2208 ] Add interactive commands to help message

- libs/prelude/Prelude/Types.idr
- tests/prelude/bind001/bind.idr
- tests/prelude/bind001/expected
- tests/prelude/bind001/input
- tests/prelude/bind001/run
New implementation of `(>>=)` and `(<*>)` for `List` with linear runtime complexity.
> [ fix ] issue #2288

- libs/base/Data/List.idr
- libs/base/Data/String.idr
- tests/base/data_string/StringReduce.idr
- tests/base/data_string/expected
- tests/base/data_string/run
Allow `String` operations to reduce at the Type-level, with test.
> Allow Type-level String operations

- libs/base/Data/List.idr
- libs/base/Data/List1.idr
Not totally sure on the names I used for these functions. Open to different spellings.
> [ new ] A couple of nearly trivial proofs about list length.

- .github/workflows/ci-idris2.yml
~~currently commented out to check CI is actually broken~~ not any more
> [ ci ] install mingw64 gcc for windows

- libs/base/Data/List.idr
- libs/base/Data/List1.idr
- libs/base/Data/SnocList.idr
...or else it is hard to write even simple properties involving blend of `List1`, `SnocList` and `List`.
> [ base ] Some properties of `List` and `SnocList`

- CHANGELOG.md
I realised that recently there were some pretty significant changes (not only induces by me) that worth to be depicted in the changelog.
> [ doc ] Add some recent lib changes to the changelog

- CHANGELOG.md
- libs/base/Data/List/Quantifiers.idr
- libs/base/Data/SnocList/Quantifiers.idr
- libs/base/Data/Vect/Quantifiers.idr
- tests/Main.idr
- tests/idris2/quantifiers001/TestQuantifiers.idr
- tests/idris2/quantifiers001/expected
- tests/idris2/quantifiers001/input
- tests/idris2/quantifiers001/run
This allows them to be used with auto-implicits
> [ base ] `public export` the various proof quantifiers

- libs/base/System/Directory.idr
- libs/base/System/File/Buffer.idr
- libs/base/System/File/Error.idr
- libs/base/System/File/Handle.idr
- libs/base/System/File/Meta.idr
- libs/base/System/File/Permissions.idr
- libs/base/System/File/Process.idr
- libs/base/System/File/ReadWrite.idr
- libs/base/System/File/Support.idr
- libs/base/System/File/Virtual.idr
- libs/base/System/Info.idr
- src/Libraries/System/File/Buffer.idr
- support/js/support_system_directory.js
- support/js/support_system_file.js
- tests/base/system_file_remove/Test.idr
- tests/base/system_file_remove/expected
- tests/base/system_file_remove/run
NodeJS support for:
- `getNProcessors`
-  `removeDir`
- `removeFile`
Partially addresses https://github.com/idris-lang/Idris2/issues/2207.
> System NodeJS additions

- docs/source/reference/builtins.rst
These docs got out of date, I have updated them and made them clearer
> [doc] Rewrite docs for `%builtin` and nat optimisations

- src/Libraries/Text/Literate.idr
> [ fix ] missing Show implementation

- .github/linters/.markdown-lint.yml
- .github/workflows/ci-idris2.yml
- libs/prelude/PrimIO.idr
- www/README.md
- www/katla.sh
- www/source/index.md
You can see it rendered here: https://gallais.github.io/Idris2/
> [ new ] Katla-powered landing page

- CHANGELOG.md
- src/Core/Options/Log.idr
- src/Idris/Package.idr
- src/Idris/Package/Types.idr
- src/Idris/SetOptions.idr
- tests/Main.idr
- tests/idris2/pkg006/depends/bar-baz/bar-baz.ipkg
- tests/idris2/pkg006/depends/quux/quux.ipkg
- tests/idris2/pkg010/expected.in
- tests/idris2/pkg010/run
- tests/idris2/pkg013/.gitignore
- tests/idris2/pkg013/depends/bar-0.7.2/bar.ipkg
- tests/idris2/pkg013/depends/foo-0.1.0/foo.ipkg
- tests/idris2/pkg013/expected.in
- tests/idris2/pkg013/gen_expected.sh
- tests/idris2/pkg013/run
- tests/idris2/pkg013/test.ipkg
Reverts idris-lang/Idris2#2469
this had some problems, I will try and fix them later but for now go back to a working version
> Revert "make `depends` collect all transitive dependencies"

- libs/prelude/Prelude/Types.idr
- tests/prelude/char001/chars.idr
- tests/prelude/char001/expected
- tests/prelude/char001/run
Hey there! This is my first time fiddling around with Idris, so I apologize if the PR is not up to expectations or requirements. Please request any necessary changes, and feel free to e.g. ask for an RFC or a rewrite if so needed.
This implementation of `Range Char` merely takes care of converting to `Int` in order to use the existing `Range Nat` implementation, then mapping back the results to `List Char`.
> [ prelude ] Add Range implementation for Char

- CHANGELOG.md
- src/Core/Options/Log.idr
- src/Idris/Package.idr
- src/Idris/Package/Types.idr
- src/Idris/SetOptions.idr
- tests/Main.idr
- tests/idris2/pkg006/depends/bar-baz/bar-baz.ipkg
- tests/idris2/pkg006/depends/quux/quux.ipkg
- tests/idris2/pkg010/expected.in
- tests/idris2/pkg010/run
- tests/idris2/pkg013/.gitignore
- tests/idris2/pkg013/depends/bar-0.7.2/bar.ipkg
- tests/idris2/pkg013/depends/foo-0.1.0/foo.ipkg
- tests/idris2/pkg013/expected
- tests/idris2/pkg013/expected.in
- tests/idris2/pkg013/gen_expected.sh
- tests/idris2/pkg013/run
- tests/idris2/pkg013/test.ipkg
See #2469 for initial idea
Hopefully actually installing the version will make pack work properly (pinging @stefan-hoeck)
> Transitive dependencies v2

- CHANGELOG.md
- src/Core/Options/Log.idr
- src/Idris/Package.idr
- src/Idris/Package/Types.idr
- src/Idris/SetOptions.idr
- tests/Main.idr
- tests/idris2/pkg006/depends/bar-baz/bar-baz.ipkg
- tests/idris2/pkg006/depends/quux/quux.ipkg
- tests/idris2/pkg010/expected.in
- tests/idris2/pkg010/run
- tests/idris2/pkg013/.gitignore
- tests/idris2/pkg013/depends/bar-0.7.2/bar.ipkg
- tests/idris2/pkg013/depends/foo-0.1.0/foo.ipkg
- tests/idris2/pkg013/expected.in
- tests/idris2/pkg013/gen_expected.sh
- tests/idris2/pkg013/run
- tests/idris2/pkg013/test.ipkg
Reverts idris-lang/Idris2#2496
see #2528
> Revert "Transitive dependencies v2"

- libs/base/Data/Nat.idr
- libs/base/Language/Reflection/TT.idr
- libs/base/Language/Reflection/TTImp.idr
- libs/prelude/Builtin.idr
- src/TTImp/Utils.idr
- tests/idris2/interactive039/expected
Continuing my streak of upstreaming local changes
> Various small improvements

- libs/base/Deriving/Functor.idr
- libs/base/Language/Reflection.idr
- libs/base/Language/Reflection/TTImp.idr
- libs/base/base.ipkg
- src/TTImp/Elab/RunElab.idr
- tests/Main.idr
- tests/idris2/reflection017/DeriveFunctor.idr
- tests/idris2/reflection017/Search.idr
- tests/idris2/reflection017/expected
- tests/idris2/reflection017/run
TODO
```idris
namespace Free
data Free : (Type -> Type) -> Type -> Type where
Pure : a -> Free f a
Bind : f a -> (a -> Free f b) -> Free f b
free : Functor (Free f)
free = %runElab derive
```
```idris
namespace MaybeT
record MaybeT (m : Type -> Type) (a : Type) where
constructor MkMaybeT
runMaybeT : m (Maybe a)
maybeT : Functor m => Functor (MaybeT m)
maybeT = %runElab derive
```
> [ new ] deriving Functor

- src/Compiler/CompileExpr.idr
- src/Compiler/Interpreter/VMCode.idr
- tests/Main.idr
- tests/codegen/builtin001/expected
- tests/idris2/primloop/PrimLoop.idr
- tests/idris2/primloop/expected
- tests/idris2/primloop/input
- tests/idris2/primloop/run
- tests/refc/garbageCollect/expected
So, I tried fixing #2537, and it actually seems to work (see the new test), but I get three other test failures I'm not sure how to deal with. Pinging @Z-snails , because we've discussed this on discord.
> [ fix ] issue 2537

- docs/source/backends/custom.rst
The type Codegen was changed in #2594.
> [ fix ] custom backend doc

- CHANGELOG.md
- libs/base/Language/Reflection/TTImp.idr
- src/Compiler/Common.idr
- src/Compiler/ES/Codegen.idr
- src/Compiler/NoMangle.idr
- src/Core/Context/Context.idr
- src/Core/Context/TTC.idr
- src/Core/Options/Log.idr
- src/Core/TTC.idr
- src/Idris/Parser.idr
- src/TTImp/ProcessType.idr
- src/TTImp/Reflect.idr
- src/TTImp/TTImp.idr
- src/TTImp/TTImp/Functor.idr
- src/TTImp/TTImp/TTC.idr
- src/TTImp/TTImp/Traversals.idr
- tests/node/nomangle001/nomangle.idr
- tests/node/nomangle002/expected
- tests/node/nomangle002/nomangle1.idr
- tests/node/nomangle002/nomangle2.idr
> Reimplement %nomangle in terms of %export

- libs/base/Deriving/Common.idr
- libs/base/Deriving/Functor.idr
- libs/base/Language/Reflection/TTImp.idr
- tests/idris2/reflection017/DeriveFunctor.idr
- tests/idris2/reflection017/expected
A lot of refactoring to bring these. That's hopefully the last
feature that was needed...
> [ fix ] support for implicits in Deriving.Functor

- src/Compiler/LambdaLift.idr
- src/Core/Context.idr
- src/Core/Core.idr
- src/Idris/Error.idr
- src/TTImp/ProcessType.idr
- tests/idris2/basic049/Fld.idr
- tests/idris2/basic049/expected
Related to #2607 (doesn't solve it due to warnings not being emitted when errors are)
> Warning for shadowed local bindings

- libs/papers/Data/W.idr
- libs/papers/papers.ipkg
> [ papers ] Computing with Generic Trees

- src/Idris/Parser.idr
- tests/Main.idr
- tests/idris2/perror018/ParseRecord.idr
- tests/idris2/perror018/ParseRecord2.idr
- tests/idris2/perror018/ParseRecord3.idr
- tests/idris2/perror018/expected
- tests/idris2/perror018/run
> [ parse ] better error messages for records

- libs/base/System.idr
We have function `system` that runs a command and its output would be just printed as an output of the caller program, and we have `run` function that allows to process the whole output of the command. But sometimes commands either have too big output or simply are long running, while there is a demand of processing their output. I suggest to have a function that allows to process program output line by line along with the execution of the command, without obligatory storage of the whole output in the memory. Also, this allows to already react appropriately on some output during the execution of long-running command.
> [ base ] Add a variant of `System.run` allowing processing on the fly

- libs/test/Test/Golden.idr
Why is it important?
1) This allows alternative runners (available after #2687) to use alternative approaches to CLI options
2) This allows in the future `golden` itself to support more flexible `only` patterns, say, wildcards.
> [ golden ] Make options to store more flexible tests filter

- .github/workflows/ci-idris2.yml
- Makefile
- libs/test/Test/Golden.idr
> [ fix ] parsing of test lib's options

- README.md
Fixes a couple of links broken by the wiki refactoring.
> [ doc ] Fix broken links from README to wiki

- libs/papers/Data/Description/Indexed.idr
- libs/papers/Data/Description/Regular.idr
- libs/papers/Data/Enumerate.idr
- libs/papers/Data/Enumerate/Common.idr
- libs/papers/Data/Enumerate/Indexed.idr
- libs/papers/papers.ipkg
> [ papers ] A Completely Unique Account of Enumeration

- Release/CHECKLIST
- src/Idris/Package.idr
- tests/Main.idr
- tests/idris2/pkg016/bar.ipkg
- tests/idris2/pkg016/bar/Bar.idr
- tests/idris2/pkg016/baz.ipkg
- tests/idris2/pkg016/baz/Baz.idr
- tests/idris2/pkg016/expected
- tests/idris2/pkg016/foo.ipkg
- tests/idris2/pkg016/foo/Foo.idr
- tests/idris2/pkg016/run
- tests/idris2/pkg016/src/Test.idr
- tests/idris2/pkg016/test.ipkg
As discussed in #2746, this is a more straightforward fix for #2745. I added also a new test to make sure Idris can find the `.ipkg` files it installed.
> [ fix ] isue 2745

- libs/contrib/Data/Late.idr
- libs/papers/Control/SECD.idr
- libs/papers/Language/IntrinsicTyping/SECD.idr
- libs/papers/Language/IntrinsicTyping/STLCR.idr
- libs/papers/papers.ipkg
So it's all pretty straightforward to formalise and we even get fun little programs
running. The main issue (already highlighted in the MSc thesis) is that the run
function is not an accurate description of the SECD's supposed behaviour (it's not
tail recursive, cf. `APP`).
> [ new ] typed SECD

- CHANGELOG.md
> [ re #2649 ] Update CHANGELOG

- src/Idris/IDEMode/REPL.idr
...except now packageDirs keeps getting added to. So rather than just saving and replacing extraDirs, I'm replacing the whole dirs directory within defs.options
> :load-file in ide-mode goes slower and slower. Similar to pull request #2136, commit 8ffad8878fc

- libs/papers/Language/IntrinsicScoping/TypeTheory.idr
- libs/papers/Language/IntrinsicScoping/Variables.idr
Somehow did not notice earlier.
> [ papers ] fill last hole in lambda pi formalisation

- .github/ISSUE_TEMPLATE/installation-problem.md
- libs/base/Data/Nat.idr
- libs/contrib/Control/Arrow.idr
- libs/test/Test/Golden.idr
Several cleanups and minor changes each not worth a separate PR. Different changes are in different commit to ease the review.
> [ cleanup ] Several cleanups and minor changes

- src/Core/Binary/Prims.idr
- src/Libraries/Utils/Binary.idr
Just building idris2.ipkg:
4m flat, down from 4m13s-4m23s
> [ perf ] use integers in the buffer state

- .github/workflows/ci-idris2.yml
> Various ci improvements

- CHANGELOG.md
- src/Idris/Parser.idr
- src/Parser/Lexer/Source.idr
- src/Parser/Rule/Source.idr
- tests/Main.idr
- tests/idris2/basic069/DebugInfo.idr
- tests/idris2/basic069/expected
- tests/idris2/basic069/run
- tests/idris2/interactive028/expected
- tests/idris2/perror007/expected
- tests/idris2/perror014/expected
I grabbed the syntax from https://v2.ocaml.org/api/Stdlib.html#1_Debugging
> [ new ] __LOC__, __FILE__, __LINE__, __COL__ magic debug strings

- libs/base/System/Clock.idr
also rename some arguments and add docs
No need, this is a very minor change
> export `{to,from}Nano` in `System.Clock`

- CHANGELOG.md
- src/Compiler/ES/Node.idr
> Js shebang

- CHANGELOG.md
- docs/source/ffi/ffi.rst
- docs/source/reference/packages.rst
See https://github.com/idris-lang/Idris2/pull/2836 for context.
> [docs] javascript FFIs and packaging of JS or C support files

- src/Compiler/CaseOpts.idr
The inner case can now have a default alternative. This means `Prelude.Types.prim__integerToNat` is better optimised
before
```js
/* Prelude.Types.prim__integerToNat : Integer -> Nat */
function Prelude_Types_prim__integerToNat($0) {
let $1;
switch(((0n<=$0)?1:0)) {
case 0: {
$1 = 0;
break;
}
default: $1 = 1;
}
switch($1) {
case 1: return $0;
case 0: return 0n;
}
}
```
after
```js
/* Prelude.Types.prim__integerToNat : Integer -> Nat */
function Prelude_Types_prim__integerToNat($0) {
switch(((0n<=$0)?1:0)) {
case 0: return 0n;
default: return $0;
}
}
```
ps
if you want to try this out, make sure you rebuild all libraries (ie delete `build`)
> Allow case-of-case to work on cases with defaults

- .github/workflows/ci-bootstrap.yml
@gallais Pointed me to this fix that had already been applied to the Idris2 CI workflow. Applying it to the Bootstrap workflow now is looking promising.
> [ ci ] [ fix ] Apply a fix from the other workflow that uses commit message.

- libs/prelude/Prelude/Types.idr
- tests/idris2/docs001/expected
> [ doc ] Remove typo from `Prelude.plus` doc string and reformat doc string for `Prelude.minus`

- libs/contrib/Data/Nat/Division.idr
- libs/contrib/Data/Nat/Order/Properties.idr
Adding three new properties to Data.Nat.Order.Properties and carried out a small refactoring in Data.Nat.Division.
> Adding new properties to Data.Nat.Order.Properties

- CHANGELOG.md
- src/Core/Termination.idr
- tests/Main.idr
- tests/idris2/total016/AssertPositivity.idr
- tests/idris2/total016/LazyPositivityCheck.idr
- tests/idris2/total016/expected
- tests/idris2/total016/run
> [ fix ] positivity checker: assert_total & Lazy

- src/TTImp/ProcessData.idr
- tests/Main.idr
- tests/idris2/namespace004/Export.idr
- tests/idris2/namespace004/expected
- tests/idris2/namespace004/run
> [ fix ] respect visibility in forward data declarations

- src/Idris/Parser.idr
- tests/ideMode/ideMode005/expected1
- tests/ideMode/ideMode005/expected2
- tests/ideMode/ideMode005/expectedE
- tests/ideMode/ideMode005/expectedG
Something I spotted last week and only just got around to pushing
> [ fix ] highlight record constructor

- CHANGELOG.md
- libs/prelude/Prelude/IO.idr
- support/js/support_system_file.js
Partially fixes #2875 
Yes done
> Js char io

- CHANGELOG.md
- libs/contrib/Data/Telescope/Telescope.idr
- libs/papers/Search/Tychonoff/PartI.idr
- src/Compiler/CompileExpr.idr
- src/Compiler/ES/Doc.idr
- src/Core/Context.idr
- src/Core/Core.idr
- src/Core/Name/Namespace.idr
- src/Core/Options/Log.idr
- src/Idris/Desugar.idr
- src/Idris/Error.idr
- src/Idris/Package.idr
- src/Idris/REPL/Common.idr
- src/Idris/Syntax.idr
- src/Libraries/Data/StringMap.idr
- src/TTImp/Elab/App.idr
- tests/Main.idr
- tests/idris2/warning004/Lib1.idr
- tests/idris2/warning004/Lib2.idr
- tests/idris2/warning004/Main0.idr
- tests/idris2/warning004/Main1.idr
- tests/idris2/warning004/expected
- tests/idris2/warning004/run
> [ re #2832 ] warn about conflicting fixity declarations

- CHANGELOG.md
- CONTRIBUTORS
- libs/contrib/Text/Lexer/Tokenizer.idr
> add Functor impl for Tokenizer

- CONTRIBUTING.md
* Don't link to discord. Write a summary instead.
* Move around the intro and the main disclaimer.
> [ docs ] Update contributing guidelines

- libs/base/Data/Nat/Order.idr
Found this while learning Idris
> Remove `decideLTE`

- libs/prelude/Prelude/Interfaces.idr
^^^ I haven't updated the changelog, looks like this is a new feature anyway so is mentioned here
https://github.com/idris-lang/Idris2/blob/dc79c6dd059e06ed24ab9c7041bec5267b71bb90/CHANGELOG.md?plain=1#L130
> Fix typo in namespace for [bi]traversable composition

- CHANGELOG.md
- libs/base/Data/SortedMap.idr
- libs/base/Data/SortedMap/Dependent.idr
> [ base ] Add update functions to sorted maps

- .readthedocs.yaml
Cf.
1. https://readthedocs.org/projects/idris2/builds/22027851/
2. https://docs.readthedocs.io/en/stable/config-file/index.html
> [ docs ] fix build by adding config file

- .github/workflows/ci-sphinx.yml
It looks like `sphinx-ci.yml` is just running sphinx to see if it succeeds.  It doesn't seem to do anything with the results.  On this assumption, I've replaced the `ammaraskar/sphinx-action` action with a direct invocation of sphinx in the ubuntu container.
> [ fix ] Fix docs build

- src/Core/Reflect.idr
- tests/idris2/reflection/reflection026/Issue3168.idr
- tests/idris2/reflection/reflection026/expected
- tests/idris2/reflection/reflection026/run
- tests/idris2/reflection/reflection026/test.ipkg
> [ fix #3168, re #3063 ] Fix forgotten reflection values

- tests/refc/callingConvention/Main.idr
- tests/refc/callingConvention/expected
- tests/refc/callingConvention/run
This should allow us to see the changes brought forth by PR #3177.
> [ re #3177 ] Test to see the change in calling conventions

- src/Compiler/RefC/RefC.idr
- support/refc/_datatypes.h
- support/refc/memoryManagement.c
- support/refc/memoryManagement.h
Removal of vestigial organs that are never used.
(organs? what? I don't think this translation is correct, but I will believe DeepL)
No. This was never used in the first place.
> [RefC] [Cleanup] Erase the World (not a fantasy things)

- docs/source/faq/faq.rst
> Update website FAQ on package managers

- libs/contrib/Data/Vect/Properties/Fin.idr
> Typo fix in  Data/Vect/Properties/Fin.idr

- libs/contrib/Data/Telescope.idr
> Typo fix in docs for  /contrib/Data/Telescope.idr

- nix/buildIdris.nix
A much less substantial refactor than the git diff would suggest. I am mostly just moving the derivation creation up to where the shared attributes were created; this allows using the newer function form of derivation argument and accessing `finalAttrs` to populate a `shellHook` in the shared derivation. The shell hook exposes the `IDRIS2_PACKAGE_PATH` in dev shells which is necessary for a functional dev environment.
This is not a breaking change.
> better nix-shell support via shellHook

- libs/base/Data/Fin.idr
- tests/base/data_fin/fromInteger.idr
> [ fix ] issue 3266

- src/Core/Context.idr
- src/Core/Core.idr
- src/Core/Name.idr
- src/Idris/Desugar.idr
- src/Idris/Error.idr
- src/Idris/Syntax.idr
- src/Libraries/Utils/Shunting.idr
- tests/idris2/operators/operators011/Module.idr
- tests/idris2/operators/operators011/Test.idr
- tests/idris2/operators/operators011/Test1.idr
- tests/idris2/operators/operators011/Test2.idr
- tests/idris2/operators/operators011/Test3.idr
- tests/idris2/operators/operators011/Test4.idr
- tests/idris2/operators/operators011/expected
- tests/idris2/operators/operators011/run
> Emit error when unbound fixity is hidden

- libs/contrib/Language/JSON/Data.idr
- tests/contrib/json_004/JSON.idr
- tests/contrib/json_004/expected
- tests/contrib/json_004/run
Add JSON `Eq` interface, and lookup, update, and traversal functions.
> Add JSON manipulation functions

- libs/contrib/Data/String/Parser.idr
between - an additional parser combinator in Data.String.Parser (contrib).
> Add between parser combinator to Data.String.Parser

- Makefile
> refactor: makefile -> reduce duplications

- libs/base/Data/Buffer.idr
- libs/contrib/Text/Distance/Levenshtein.idr
- libs/network/Network/Socket.idr
- libs/papers/Language/IntrinsicScoping/TypeTheory.idr
- libs/papers/Language/TypeTheory.idr
- src/Libraries/Text/Distance/Levenshtein.idr
- tests/node/node027/PID.idr
> refactor: errors -> more descriptive

- libs/base/Makefile
- libs/contrib/Makefile
- libs/linear/Makefile
- libs/network/Makefile
- libs/papers/Makefile
- libs/prelude/Makefile
- libs/test/Makefile
> refactor: makefile -> use PHONY

- CHANGELOG_NEXT.md
- libs/base/Data/List/Quantifiers.idr
- libs/base/Data/List1/Quantifiers.idr
- libs/base/Data/SnocList/Quantifiers.idr
- libs/base/Data/Vect/Quantifiers.idr
> [ base ] Add a function connecting `All` and `Any` through `Alternative`

- README.md
Move content from the wiki directly into the readme for greater visibility. Part of this issue: https://github.com/andrevidela/idris-documentation-tracking/issues/1
> Update README with resources to learn and use Idris

- docs/source/reference/packages.rst
- docs/source/tutorial/conclusions.rst
- docs/source/tutorial/packages.rst
fix https://github.com/andrevidela/idris-documentation-tracking/issues/6
> Update old links in documentation

- docs/source/tutorial/interfaces.rst
- docs/source/tutorial/starting.rst
- docs/source/tutorial/typesfuns.rst
- docs/source/tutorial/windows.rst
I went over
1. starting.rst
2. windows.rst
3. typesfuns.rst
4. interfaces.rst
> Grammar improvements to the beginning of the tutorial

- src/Idris/Syntax.idr
- src/Idris/Syntax/Traversals.idr
I think it's pretty self explanatory
> remove dead code
